### ISSUE TITLE
clear search and tag with escape 

### ISSUE THREAD

**Issue by Chrysanthemum536** [adirh3/Fluent-Search#1001]
**Describe the solution you'd like**
If the "clear search with escape" option is enabled, then pressing escape after the search bar is already empty should clear any tags as well.

**Describe alternatives you've considered**
clearing the tag with backspace press. but pressing escape twice would be faster

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 1.0.0.40 . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
