### ISSUE TITLE
Home screen is not shown

### ISSUE THREAD

**Issue by xuwei152** [adirh3/Fluent-Search#1011]
**Describe the bug**

I have updated the fluence search to the latest version. However, the home screen is not shown.
![Clip_2024-05-18_18-03-34](https://github.com/adirh3/Fluent-Search/assets/51861161/f58c4701-8e24-41c5-864b-54832a1f61be)

**To Reproduce**

1. Update to the latest version;
![Clip_2024-05-18_18-08-24](https://github.com/adirh3/Fluent-Search/assets/51861161/0dbf560c-6616-45b1-ac58-5f820106104d)

2, Start up the fluence search with empty input.

**Expected behavior**

Show the home screen

![Clip_2024-05-18_18-11-06](https://github.com/adirh3/Fluent-Search/assets/51861161/1fa0e099-0473-4d58-980c-8f5836b67672)

**Desktop (please complete the following information):**
 - Window 10/11 Version: 23H2(0S: 22635.3575)
 - Fluent Search Version: 1.0.0.42
 - Installation source:  Appx

**Comment by ninopiamonte** [comment]
I think you need to disable Always open the search bar

Fluent Search settings → Personalization → Window Style → Always open the search bar (turn off)

**Comment by xuwei152** [comment]
Thanks a lot. As you mentioned, it works after turning on the option "Always open the search bar".
