### ISSUE TITLE
Just Start Using it and LOVE IT

### ISSUE THREAD

**Issue by Galthariel** [adirh3/Fluent-Search#1012]
First of all Thanks a lot for this Amazing App. I LOVE IT

I have only a single request and since I'm not a developer I don't know how hard it will be to implement in case it's possible.

Besides all of the amazing features I'm using, the Home Screen Pinned Apps is the one I use most and I would like to make it possible to increase the icons independently without changing the font size. Creating a slider to change the icons and Font separately in the Home Screen will do the job. I know I can hide the font but then when I mouse over it shows the path of the program instead of the name of the App.

Thanks in Advance :-)

**Comment by adirh3** [comment]
Glad to hear you liked it :)

Will add this in the next nightly version.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 1.0.0.43                                          . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
