### ISSUE TITLE
Inability to lose focus while in edit mode in a text box.

### ISSUE THREAD

**Issue by elo-marciello** [adirh3/Fluent-Search#1013]
**Describe the bug**
Inability to lose focus while in edit mode in a text box.

**To Reproduce**
1. Go to 'Apps>Web>Web Search Tags'
2. Click on 'URL'
3. When in the "Suggestion URL" or "URL" edit mode, clicking off the editable part should deselect the text and exit the editable part and save the content. Same when clicking enter.

**Expected behavior**
When in the "Suggestion URL" or "URL" edit mode, clicking off the editable part should deselect the text and exit the editable part and save the content. Currently, the text box stays in focus and there is no way to lose focus but to click on another setting or button. Although there is a lose focus feature bound to the "ESC" key, it is not intuitive for a simple user to guess they need to press ESC before trying to click off the window or hit enter.

**Desktop (please complete the following information):**
- Windows 11 Version: 22H2
- Fluent Search Version: 1.0.0.42
- Installation source: Installer (nightly)

**Additional context**
N/A

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 1.0.0.43                                          . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
