### ISSUE TITLE
Open the "Customize Search Tag" Menu when adding a New Search tag 

### ISSUE THREAD

**Issue by elo-marciello** [adirh3/Fluent-Search#1014]
**Is your feature request related to a problem? Please describe.**
When adding a new item to web search tags by clicking on '+', nothing happens, resulting in a blank spot in the search tag section. This feels unintuitive and incomplete.

**Describe the solution you'd like**
When adding a new item to web search tags, it should either open the menu "Customize Search Tag" or trigger some action to indicate that an item is being added, providing a more seamless user experience.

**Describe alternatives you've considered**
Considered showing a default template for the new search tag or a prompt guiding the user to customize the new tag immediately.

**Additional context**
The section In which it happens is in Apps>Web>Web Search Tags>+

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 1.0.0.43                                          . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
