### ISSUE TITLE
### Adjustability of "Show search results when opened recently" Feature

### ISSUE THREAD

**Issue by elo-marciello** [adirh3/Fluent-Search#1016]
**Is your feature request related to a problem? Please describe.**
The feature "Show search results when opened recently" is currently fixed at 10 seconds and cannot be adjusted. This limitation can be frustrating for users who need a different duration.

**Describe the solution you'd like**
Allow the "Show search results when opened recently" feature to be adjustable, enabling users to set their preferred duration.

**Describe alternatives you've considered**
Considered having preset options such as 5 seconds, 10 seconds, 20 seconds, etc., or a customizable input field for users to specify the exact duration they prefer.

**Additional context**
N/A

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 1.0.0.43                                          . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
