### ISSUE TITLE
### Audio Continues Playing After Exiting Video Preview

### ISSUE THREAD

**Issue by elo-marciello** [adirh3/Fluent-Search#1017]
**Describe the bug**
When playing a video file with the preview function (shift + return), pressing the ESC key stops the video feed but the audio continues playing. There is no way to stop the audio except by restarting the app.

**To Reproduce**
1. Play a video file using the preview function (shift + return).
2. Press the ESC key to exit the video preview.

**Expected behavior**
Pressing the ESC key should stop both the video feed and the audio.

**Desktop (please complete the following information):**
- Windows 11 Version: 22H2
- Fluent Search Version: 1.0.0.42
- Installation source: Installer (nightly)

**Additional context**
N/A

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 1.0.0.43                                          . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
