### ISSUE TITLE
Web Search Icon table should show preview of image instead of local link

### ISSUE THREAD

**Issue by Metroid-Prime** [adirh3/Fluent-Search#102]
This is a no-brainer in terms of user-interface

Instead of this:
![image](https://user-images.githubusercontent.com/1836362/121796742-43704780-cbd0-11eb-91be-b55b9214ae46.png)

Fluent Search should have a generic picture icon there, that when clicked opens a dialogue box to select the image and then show a small preview of the image, like this:

![image](https://user-images.githubusercontent.com/1836362/121796882-50da0180-cbd1-11eb-846c-6fd0910674c3.png)

Once the icons are added, this is what it should look like:
![image](https://user-images.githubusercontent.com/1836362/121796836-de692180-cbd0-11eb-9326-c4f91f3e7aae.png)

**Comment by adirh3** [comment]
@Metroid-Prime closing this,

**Comment by Metroid-Prime** [comment]
This was done absolutely brilliantly.  What a beautiful surprise it was when I saw it.
THANK YOU for listening so intently to your users.  This design was the right decision.
