### ISSUE TITLE
### User-Configured File Indexing Settings Not Visible After Reopening Settings

### ISSUE THREAD

**Issue by elo-marciello** [adirh3/Fluent-Search#1021]
**Describe the bug**
When in the Apps>Files>File indexing settings menu, closing the window and relaunching it by typing 'settings' in the search and clicking on it sends you to the last used setting menu. However, the "Ignored paths and files" and "Indexed paths" configured by the user are not visible; only the default paths and ignored paths that come with Fluent Search are shown. To view the user-configured paths, you must exit out of the file indexing window to 'Files' and come back without closing the settings window.

**To Reproduce**
1. Go to 'Apps>Files>File indexing settings'.
2. Close the window.
3. Relaunch the settings by typing 'settings' in the search and clicking on it.
4. Observe that user-configured "Ignored paths and files" and "Indexed paths" are not visible.

**Expected behavior**
User-configured "Ignored paths and files" and "Indexed paths" should be visible when reopening the file indexing settings.

**Desktop (please complete the following information):**
- Windows 11 Version: 22H2
- Fluent Search Version: 1.0.0.42
- Installation source: Installer (nightly)

**Additional context**
Before reopening:
N/
![FluentSearch_mVAMrG3CTv](https://github.com/adirh3/Fluent-Search/assets/109159272/a380cf50-8abb-48d1-bec6-af6d0c9aad9b)
A
After reopening:
![FluentSearch_FMvM9BFNbl](https://github.com/adirh3/Fluent-Search/assets/109159272/3b419260-5b2c-4977-a591-2a8dde6d697e)

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 1.0.0.43                                          . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
