### ISSUE TITLE
### Error When Searching Through Web Search Tags While Editing URL or Suggestion URL

### ISSUE THREAD

**Issue by elo-marciello** [adirh3/Fluent-Search#1022]
**Describe the bug**
When editing a URL or suggestion URL in the Apps>Web>Web Search Tags section, if the user doesn't exit the editable box and hits the magnifying glass to search through web search tags, a red text error message appears.

**To Reproduce**
1. Go to 'Apps>Web>Web Search Tags'.
2. Edit a URL or suggestion URL.
3. Without exiting the editable box, click the magnifying glass to search through web search tags.
4. Observe the red text error message that appears.

**Expected behavior**
No error should occur, and the search should proceed normally even if the user is editing a URL or suggestion URL.

**Desktop (please complete the following information):**
- Windows 11 Version: 22H2
- Fluent Search Version: 1.0.0.42
- Installation source: Installer (nightly)

**Additional context**
A picture of the issue is attached to this report, showing the red text error message.
![wWtXZwcU5c](https://github.com/adirh3/Fluent-Search/assets/109159272/a8387781-ebc7-4bf1-92c8-e0ab4fe3597c)

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 1.0.0.43                                          . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
