### ISSUE TITLE
All history showing when using YouTube tag

### ISSUE THREAD

**Issue by Mr-Frankenstein** [adirh3/Fluent-Search#103]
**Describe the bug**
When searching on YouTube with YouTube tag using web search, FS is showing all my history.

**To Reproduce**
(You must have a YouTube web search to see this error)
1. Use YouTube tag
2. search for something you have searched on google.

**Expected behavior**
Only YouTube history should be shown when using the YouTube tag.

**Screenshots**
![image](https://user-images.githubusercontent.com/85425543/121800402-275fbb00-cc4f-11eb-8583-b42bb445843e.png)

**Desktop (please complete the following information):**
 - Windows 10 Version: 21H1
 - Fluent Search Version 0.9.85.45

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.85.50

**Comment by Metroid-Prime** [comment]
@Mr-Frankenstein  can you validate at your earliest convenience?

**Comment by Mr-Frankenstein** [comment]
It's fixed
