### ISSUE TITLE
Add option to copy filename from right panel context menu

### ISSUE THREAD

**Issue by christubuntu** [adirh3/Fluent-Search#1031]
https://github.com/adirh3/Fluent-Search/assets/55885756/d28a8592-dfed-4337-85e9-93a5adaf6df1

Currently, FS only has hotkey to copy filepath, not filename. You could either add a hotkey for filename or allow copying the filename from that panel.

**Comment by adirh3** [comment]
[Copy file name.zip](https://github.com/user-attachments/files/15525301/Copy.file.name.zip)
Here extract and import the task it should do that

**Comment by christubuntu** [comment]
Thanks. Is there a way to assign a hotkey to the plugin? It's not showing up in the main Hotkey page.

**Comment by adirh3** [comment]
> Thanks. Is there a way to assign a hotkey to the plugin? It's not showing up in the main Hotkey page.

Yes in Tasks click on the `Custom operation` block and add key gesture -
![image](https://github.com/adirh3/Fluent-Search/assets/27368554/9371dfbb-3a03-406e-ae77-5bb6c4ea4d1d)

**Comment by adirh3** [comment]
Closing this as I do not intend to have this built it, might add it as plugin
