### ISSUE TITLE
how do i switch this off

### ISSUE THREAD

**Issue by temginson** [adirh3/Fluent-Search#1032]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. I'm always frustrated when im in my painting program and wanna merge layers i press CTRL+M

**Describe the solution you'd like**
A clear and concise description of what you want to happen. i wanna atleast change this shortcut so that it dosent trigger atleast in my painting program
**Describe alternatives you've considered** i have tried to find where i can edit this shortcut 

**Additional context**

![image](https://github.com/adirh3/Fluent-Search/assets/132342905/f5129340-a373-4485-9efd-7d20fbfb712f)

**Comment by adirh3** [comment]
Got to Settings -> Screen -> Screen hotkey, click on it and press `Escape` and then `Stop listening`
