### ISSUE TITLE
folders appear twice

### ISSUE THREAD

**Issue by Chrysanthemum536** [adirh3/Fluent-Search#1035]
**Describe the bug**
folder appears twice in the search results. once with the ending \ and once without. also, the one without the \ has both the folders and files tag for some reason

**To Reproduce**
search in folders i guess 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
window 10 
version 1.0.0.42

**Additional context**

**Comment by adirh3** [comment]
@Chrysanthemum536 which indexer do you use?

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 1.0.0.43                                          . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
