### ISSUE TITLE
The File search doesn't seem to include google drive

### ISSUE THREAD

**Issue by prowhiz** [adirh3/Fluent-Search#104]
**Describe the bug**
The file search doesn't seem to include my Google drive folder even though I have the drive indexed in the Files settings

**To Reproduce**
1. Go to Settings > Files
2. Under Indexed Paths, I click the + icon and add G:\My Drive
3. Click Rebuild Index. 

**Expected behavior**
It should list the file/folder in the search results when I search for a folder or file stored in Google drive. But It doesn't find regardless of which File Indexer is used

**Desktop (please complete the following information):**
 - Windows 10 Version: [e.g. 20H2]
 - Fluent Search Version [e.g. 0.9.85.45]

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.85.50

**Comment by prowhiz** [comment]
That was quick. I've updated and it works now. Thank you
