### ISSUE TITLE
升级1.0.0.43版本后，文字显示乱码，搜索框显示乱码，设置中的标题显示乱码

### ISSUE THREAD

**Issue by LeoZYChai** [adirh3/Fluent-Search#1045]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Window 10/11 Version: [e.g. 20H1]
 - Fluent Search Version: [e.g. 0.9.80.0]
 - Installation source: Installer / Microsoft Store / Portable / Appx

**Additional context**

![image](https://github.com/adirh3/Fluent-Search/assets/33129407/9292e176-db84-4408-8ac5-ce0de23bf957)
![image](https://github.com/adirh3/Fluent-Search/assets/33129407/d55b3521-292b-4e8f-96d5-02844a885ecb)

**Comment by ccddos** [comment]
it may have something to do with font setting, you may change font to one that support CN,  like notocjk https://github.com/notofonts/noto-cjk

**Comment by baixiang-main** [comment]
> it may have something to do with font setting, you may change font to one that support CN, like notocjk https://github.com/notofonts/noto-cjk

Not only is it a font problem, but after changing the fonts that can be displayed, the same problem will still occur the next time it is started. It seems that this is a BUG that will be triggered stably in this version.

**Comment by ccddos** [comment]
> > it may have something to do with font setting, you may change font to one that support CN, like notocjk https://github.com/notofonts/noto-cjk它可能与字体设置有关，您可以将字体更改为支持 CN 的字体，例如 notocjk https://github.com/notofonts/noto-cjk
> 
> Not only is it a font problem, but after changing the fonts that can be displayed, the same problem will still occur the next time it is started. It seems that this is a BUG that will be triggered stably in this version.不仅是字体问题，而且在更改了可以显示的字体后，下次启动时仍然会出现同样的问题。看来这是一个BUG，在这个版本中会稳定触发。

Yes, I also noticed it. This is definitely a software bug. 

I just switched to English, and now my input of Chinese characters is correct.

**Comment by bxd** [comment]
> > it may have something to do with font setting, you may change font to one that support CN, like notocjk https://github.com/notofonts/noto-cjk
> 
> Not only is it a font problem, but after changing the fonts that can be displayed, the same problem will still occur the next time it is started. It seems that this is a BUG that will be triggered stably in this version.

same problem.

**Comment by YangHanlin** [comment]
Same problem here. I also noticed that only some of the text is garbled (with the wrong font used, e.g. the input box in the following screenshot), while others are not (with the correct font used).

![image](https://github.com/adirh3/Fluent-Search/assets/8692892/addb7a2b-3271-48cd-971a-b0273b61b03b)

**Comment by syshlang** [comment]
same problem.
![image](https://github.com/adirh3/Fluent-Search/assets/8163995/b6e472ed-89d9-41d3-8cbd-ed73262f1951)

**Comment by Lyrikp** [comment]
Here are something wrong with English fonts too.
I try to switch font to default, it seems that the font is forcibly set to bold, with wrong display of part of Chinese.
![image](https://github.com/user-attachments/assets/81ad7764-8164-49eb-baa5-8ae09632fcc6)
![image](https://github.com/user-attachments/assets/22893934-99ac-4806-8e49-f94e4606df5e)
On v1.0.0.44

**Comment by Lyrikp** [comment]
It's weird that chage theme can fix it temporarily. This bug may be a problem with custom theme setting.

**Comment by invisprints** [comment]
+1

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 1.0.0.45                                          . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
