### ISSUE TITLE
Copy Calculation Results with a Click

### ISSUE THREAD

**Issue by DhananjayPorwal** [adirh3/Fluent-Search#1048]
**Is your feature request related to a problem? Please describe.**
No, it isn't related to a problem.

**Describe the solution you'd like**
There are times when I need to copy a calculation result. For example:

![image](https://github.com/adirh3/Fluent-Search/assets/51775507/fee08e59-406b-4a47-a1de-50ae5e60648e)
Currently, I cannot copy this result. It would be beneficial to have a feature that allows us to copy the calculation result simply by clicking on it.

**Describe alternatives you've considered**
At the moment, I memorize the value and use it.

**Additional context**
Please add any other context or screenshots relevant to the feature request here.

**Comment by adirh3** [comment]
You can copy the result by pressing Ctrl+C or pressing `Copy text`
![image](https://github.com/user-attachments/assets/9537b68a-504e-4aee-93a4-72c214db48c4)
