### ISSUE TITLE
Website is down[Error 403]

### ISSUE THREAD

**Issue by CatsArmy** [adirh3/Fluent-Search#1057]
I have tested this on multiple devices and networks and that same issue appears
unsure why the website is down though. @adirh3 
![image](https://github.com/user-attachments/assets/757f1500-fee3-4374-8c85-c0c2b73fc475)

**Comment by jasonbrown1965** [comment]
App still available through window store. Just downloaded it after looking up a simpler option to Everything, which I could never figure out how to configure reliably.

**Comment by CatsArmy** [comment]
Yeah it probably still works but I'm using the beta version and also I'm just worried about the fact the site suddenly stops working

**Comment by adirh3** [comment]
Thank you very much! I will fix it

**Comment by adirh3** [comment]
Fixed, thanks again!
