### ISSUE TITLE
search does not get cleared after time limit sometimes

### ISSUE THREAD

**Issue by Chrysanthemum536** [adirh3/Fluent-Search#1061]
**Describe the bug**

sometimes, after opening a result, and then opening fluent search again after several minutes, the search field has not gotten cleared, even though in the settings reset search after opening is set to `text and tags` and the time limit is set to 10 seconds.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Window 10/11 Version: [e.g. 20H1]
 - Fluent Search Version: [e.g. 0.9.80.0]
 - Installation source: Installer / Microsoft Store / Portable / Appx

**Additional context**

**Comment by kwanice** [comment]
using newr version on ARM, and this is still happening
i try to click on FS icon and it remember my last request written 30 min before
@adirh3
