### ISSUE TITLE
Tags not showing in the search window

### ISSUE THREAD

**Issue by WilliamK7** [adirh3/Fluent-Search#1063]
**Describe the bug**
The new version loses the ability to show the type of the search result

**To Reproduce**
1. Search an app name
2. See error

**Expected behavior**
The first screenshot comes from 1.0.0.44 and the second one comes from the previous portable version.
There should be a category indicator as the previous version before the search result.
For example, there should be "App" before the first search result and "File" before the second result.

**Screenshots**
![image](https://github.com/user-attachments/assets/4eeb55a3-ef59-4fa4-8dae-06509e16f1b1)
![image](https://github.com/user-attachments/assets/7561276f-72aa-43e4-b3a3-3f4a4f4837b2)

**Desktop (please complete the following information):**
 - Window 10 Version: 22H2
 - Fluent Search Version: 1.0.0.44
 - Installation source: Installer

**Additional context**
![image](https://github.com/user-attachments/assets/0ef2388d-5de1-4d13-bbe6-8b8ef6f2a878)
However, some categories can be shown, as in the picture above "System setting" and "Setting"

**Comment by adirh3** [comment]
This is the result type, I changed it so it appears only for some results. FYI the tags are still showing on the right side panel.
I will add a setting to enable it back.

**Comment by WilliamK7** [comment]
> I will add a setting to enable it back.

Glad to hear that.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 1.0.0.45                                          . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by WilliamK7** [comment]
Great, just go personalization-text and select always show result type.
I'll close this issue.
