### ISSUE TITLE
Scrolling Glitch After Media Playback with Shift+Enter

### ISSUE THREAD

**Issue by elo-marciello** [adirh3/Fluent-Search#1064]
**Describe the bug**
After playing a media file such as an MP3 or MP4 using Shift+Enter in Fluent Search, pressing the Escape key causes the scrolling function using the up and down arrow keys to glitch. This behavior is similar to what was described in issue #1041, where the file preview provider is "Fluent Search."

**To Reproduce**
1. Play a media file (e.g., MP3 or MP4) by selecting it and pressing Shift+Enter.
2. After playback, press the Escape key.
3. Attempt to scroll using the up and down arrow keys.
4. Notice the glitch in the scrolling behavior.

**Expected behavior**
The up and down arrow keys should allow smooth scrolling after media playback and exiting with the Escape key, without any glitches.

**Desktop (please complete the following information):**
- Windows 11 Version: 22H2, OS build 22621.3880
- Fluent Search Version: 1.0.0.45
- Installation source: [Nightly]

**Additional context**
This issue is similar to the behavior described in issue #1041, where the file preview provider used is "Fluent Search."

**Comment by adirh3** [comment]
@elo-marciello does this still happen in .47? I can't reproduce it

**Comment by elo-marciello** [comment]
issue seems to be fixed but i need further testing

**Comment by adirh3** [comment]
reopen please if this issue still happens, still can't repro
