### ISSUE TITLE
Drag-and-Drop File Action for Machine Learning Prioritization

### ISSUE THREAD

**Issue by elo-marciello** [adirh3/Fluent-Search#1065]
**Is your feature request related to a problem? Please describe.**
Currently, Fluent Search does not seem to account for files being dragged from the search interface to other locations when it comes to machine learning-based file prioritization. As a result, even if a file is frequently dragged, it may not appear at the top of the search results over time.

**Describe the solution you'd like**
I would like the drag-and-drop action within Fluent Search to be integrated into the machine learning algorithm that prioritizes files. This means that if a file is dragged multiple times, it should gradually move up in the search results list, reflecting its frequent use.

**Describe alternatives you've considered**
An alternative would be manually pinning frequently used files to the top of the search results, but this requires more user intervention and does not leverage the automated learning capabilities of the software.

**Additional context**
This feature would enhance the usability of Fluent Search by making it more adaptive to user behavior, ensuring that frequently used files are more easily accessible.

**Comment by adirh3** [comment]
Good idea, will do thanks :)

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 1.0.0.49                                          . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
