### ISSUE TITLE
Add an option to clear last input

### ISSUE THREAD

**Issue by xuwei152** [adirh3/Fluent-Search#1068]
**Is your feature request related to a problem? Please describe.**
When I start a new search, the last input remains. I have to clear it before starting a new search.
![image](https://github.com/user-attachments/assets/5878bf7a-0c82-43bf-a18c-0bdb178a2eee)

**Describe the solution you'd like**
Is it possible to add an option to clear last research?

**Comment by adirh3** [comment]
Settings -> Search -> Interactions -> Reset search when opening -> Set it to `Search and tags` and change the time to your liking
