### ISSUE TITLE
Clipboard - Impossible to add a TAG

### ISSUE THREAD

**Issue by kwanice** [adirh3/Fluent-Search#107]
**Describe the bug**
when i select an item on my clipboard list, and add a tag, i cant see the tag added

**To Reproduce**
1. select the item
2. click on the + to add the tag

**Expected behavior**
we should see the list of tag on this item when its selected.

**Desktop (please complete the following information):**
 - Windows 10 Version: 21390.1000
 - Fluent Search Version: 0.9.85.35

**Comment by Nomad-0** [comment]
Can you please explain in detail what do you mean by tag? (with screenshots if possible).

**Comment by adirh3** [comment]
@Nomad-0 Its a known issue for all plugins, can't add custom search tags

**Comment by Nomad-0** [comment]
oh, understood

**Comment by Metroid-Prime** [comment]
The way I interpreted this it's a limitation or a known issue so I removed the bug label.
