### ISSUE TITLE
 Improve Search Functionality with Image Recognition and Specific Click Positions

### ISSUE THREAD

**Issue by jiangyun-fun** [adirh3/Fluent-Search#1071]
**Is your feature request related to a problem? Please describe.**
The screen/window search works fine most of the time, but for some apps, it misses a lot of places, which can be frustrating.

**Describe the solution you'd like**
1. Allow users to upload an image that they want to be recognized, such as an icon or a text box.
2. Enable users to set a specific position to click on the focused window, even if the position is not clickable. This is useful when OCR is difficult to use or when the user simply wants to move the mouse to a specific position.

**Additional context**
I am currently using AutoHotkey to click specific positions, but I am not familiar with visualization. After setting many keys, I often forget which key to hit. I believe this feature would work well with Fluent Search.

**Comment by adirh3** [comment]
Thanks for the feedback! I will think about adding these in future version.

Have you tried one of the following features in Screen Search?

1. You can move the hints to any direction using arrow keys - this can allow you to click on something that was not correctly recognized.

2. Change screen search engine to use UI recognition instead of image recognition (in Settings -> Screen search -> Screen search engine).
This can be triggered manually by pressing TAB while screen search is running.

**Comment by jiangyun-fun** [comment]
Thank you for your prompt reply and suggestions.

I found your first piece of advice very useful as I hadn't discovered that option before. Is it possible to adjust the speed for moving hints with the arrow keys?

Regarding the search engines, I have tried both UI recognition and image recognition. However, they seem to perform identically in my experience. Additionally, when I adjust the rectangle density level in image recognition mode from high to low, the number of hints displayed within the window decreases. Could I be configuring something incorrectly?

Thank you once again for your assistance.
![2024-09-14-08-17-39](https://github.com/user-attachments/assets/143c9a76-39ef-4693-ae24-00fdc98b3e31)

**Comment by adirh3** [comment]
@jiangyun-fun can you please share your screen resolution and.DPI (monitor scaling)?

**Comment by jiangyun-fun** [comment]
The GIF above looks small because I minimized the window while presenting.

**System and Screen Information:**
- **Windows Version:** Windows 11 Enterprise 23H2
- **Screen Resolution:** 1920 x 1080 (two screens)
- **Screen Size:** 24 inches
- **Scaling:** 100%
- **Refresh Rate:** 60Hz

If you need additional information, please let me know. Some settings that might be helpful:
(I actually use `Caps & F/G` to launch.)
```json
{
  "Screen.json": [
    {"SettingName": "HintsCharacters", "Value": "ASDWJKLIFHQERNOUMCXVZGBTYP"},
    {"SettingName": "KeepMousePosition", "Value": true},
    {"SettingName": "ScreenRectangleSize", "Value": 14},
    {"SettingName": "ShowRectBorders", "Value": true},
    {"SettingName": "UseCustomRectangleBackground", "Value": false},
    {"SettingName": "CustomRectangleBackground", "Value": {"ColorValue": 0}},
    {"SettingName": "OcrDefaultLanguage", "Value": "zh-hans-cn"},
    {"SettingName": "AddOcrLanguageTags", "Value": true},
    {"SettingName": "ForceUiSearchEngine", "Value": 1},
    {"SettingName": "RectangleDensityLevel", "Value": 0},
    {"SettingName": "EnableApplication", "Value": true},
    {
      "SettingName": "Search hotkey",
      "Value": {
        "Name": "Keyboard shortcut to start searching using Screen",
        "HotKeys": [164, 162, 160, 71]
      }
    },
    {
      "SettingName": "Search foreground process hotkey",
      "Value": {
        "Name": "SearchProcessScreen",
        "HotKeys": [162, 164, 160, 70]
      }
    },
    {"SettingName": "Single Click key gesture", "Value": "D1"},
    {"SettingName": "Double Click key gesture", "Value": "D2"},
    {"SettingName": "Select Click key gesture", "Value": "D3"},
    {"SettingName": "Right Click key gesture", "Value": "D4"},
    {"SettingName": "Move mouse key gesture", "Value": "D5"}
  ]
}
```

**Comment by adirh3** [comment]
@jiangyun-fun which browser do you use? Using `in-window` screen search engine I am able to have everything covered in the website you showed in the gif

**Comment by jiangyun-fun** [comment]
I'm using Edge. I'm curious as to why both engines produce the same hints. 

Another more representative example: the screen search engine cannot find a clickable button in the left widget bar in the application named **Feishu**. Even when I press `Tab` to switch the engine, the hints count and positions do not change.

For reference, here are the screenshots:

**In-Window Mode:**
[Imgur](https://imgur.com/SuO4Og7)

**Full Screen Mode:**
[Imgur](https://imgur.com/3jpgHbt)

**Comment by jiangyun-fun** [comment]
> 1. You can move the hints to any direction using arrow keys - this can allow you to click on something that was not correctly recognized.

I wonder if the movement speed of the arrow keys can be adjusted?

**Comment by adirh3** [comment]
@jiangyun-fun can you check if you have the setting "Search in window content" enabled?
It's in Settings -> Apps -> Window(s)

![image](https://github.com/user-attachments/assets/d6aeebb4-920f-463c-9e0c-44f245636086)

**Comment by jiangyun-fun** [comment]
Thank you for pointing that out. I wasn't aware that I needed to enable the "Search in window content" setting. After turning it on, the function works perfectly.

Thanks again for your assistance!
