### ISSUE TITLE
Modify the preview hotkey, Alt

### ISSUE THREAD

**Issue by ligq** [adirh3/Fluent-Search#1079]
Hi, could you please change the preview hotkey from Alt to Alt+P, or let users customize the hotkey?
In windows file explorer, the preview hotkey is Alt+P. I hope the operation in Fluent Search could be consistent with file explorer. 
And the standalone Alt key can accidently be pressed. I hope it could be a two keys combination. 
Thank you very much.

**Comment by ligq** [comment]
Dear Adirh, I beg you to consider this option. Thank you.

**Comment by fatsen** [comment]
especially when using autohotkey (key-remapping program), all ALT-started key combinations can't be used.

**Comment by adirh3** [comment]
I am considering this.
Alt+P is used by pinning results, maybe I will change it.

**Comment by H5820121** [comment]
@adirh3
I also join to this request.

‫בתאריך שבת, 26 באוק׳ 2024 ב-6:37 מאת ‪Guoqiang LI‬‏ <‪
***@***.***‬‏>:‬

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 1.0.0.64. Changelog - https://github.com/adirh3/Fluent-Search/releases/tag/1.0.0.64

**Comment by ligq** [comment]
> This issue has been potentially fixed in version 1.0.0.64. Changelog - https://github.com/adirh3/Fluent-Search/releases/tag/1.0.0.64

Great! Thank you so much.
