### ISSUE TITLE
please update keywords in tolgee

### ISSUE THREAD

**Issue by u-Sir** [adirh3/Fluent-Search#1081]
![图片](https://github.com/user-attachments/assets/b2009529-0764-4cdc-bf24-a1d133a511f2)
![图片](https://github.com/user-attachments/assets/6ae876c4-acbf-412a-8fc5-c8fac4cbab53)
![图片](https://github.com/user-attachments/assets/74cbafe3-06d8-42bf-8f53-be6c2620020a)
![图片](https://github.com/user-attachments/assets/2bfa62ee-7117-4c1b-a4c2-93483ddc4570)
![图片](https://github.com/user-attachments/assets/02b4b7c8-f981-4dd9-9a24-0b96c0a8da34)
![图片](https://github.com/user-attachments/assets/63407d77-c082-40c5-ab59-1024b85136d7)
![图片](https://github.com/user-attachments/assets/cb0983cf-0564-42ea-830b-41e603e324a5)
![图片](https://github.com/user-attachments/assets/2dc5b7c8-9220-4d27-8409-e7f79feafdfe)
![图片](https://github.com/user-attachments/assets/51fa21e9-f594-4b53-a443-9a77f6dddd63)
![图片](https://github.com/user-attachments/assets/21b1953b-046a-4305-bb40-c95055bfdcce)
![图片](https://github.com/user-attachments/assets/51e65e10-0b71-4076-9a1e-8082339a36fe)
![图片](https://github.com/user-attachments/assets/d1dcca68-e8bb-4760-87fb-5485d674bbfc)
![图片](https://github.com/user-attachments/assets/fbc693fc-dc37-4fc9-8833-77f765bafcec)
![图片](https://github.com/user-attachments/assets/a3dde118-d28b-4269-81d0-4cfc31694385)
![图片](https://github.com/user-attachments/assets/9cc4cf2c-051d-4591-ad85-ae3ba7f7dda4)

**Comment by adirh3** [comment]
Will do, thank you very much!

**Comment by adirh3** [comment]
@u-Sir Updated Tolgee, thanks again!

**Comment by u-Sir** [comment]
OK, And part of updated words is empty.

**Comment by u-Sir** [comment]
![图片](https://github.com/user-attachments/assets/ef1d7041-5102-4241-a30b-06882830f2dc)
![图片](https://github.com/user-attachments/assets/bc76bc2d-958d-4706-afda-628e5aed472f)
![图片](https://github.com/user-attachments/assets/626a3d56-7d9e-41a5-a914-600e34ba4d2c)
![图片](https://github.com/user-attachments/assets/c6dda5b5-7915-4523-b1dc-b96861b55a93)
![图片](https://github.com/user-attachments/assets/dda033fd-fd1f-40a3-a244-feffcc6e097b)
![图片](https://github.com/user-attachments/assets/bd514d4b-fb9f-4a19-bc40-0b48e4b2b8a8)
![图片](https://github.com/user-attachments/assets/0fe7494d-fd4b-4c3e-9ab0-b17e8d73e887)
![图片](https://github.com/user-attachments/assets/641bd510-c2a9-4ec9-9819-f89818c48bff)
![图片](https://github.com/user-attachments/assets/ea14dba7-16f6-4693-8224-0c28719e5aee)
![图片](https://github.com/user-attachments/assets/14dc24b9-3057-4297-af34-9116248ea77c)
![图片](https://github.com/user-attachments/assets/153d190e-0da6-4f1c-aab0-10ff4b9b9a89)


@adirh3 these still missing/ didn't apply

**Comment by adirh3** [comment]
@u-Sir thanks a lot!
Some of these were not translated in Tolgee -
![image](https://github.com/user-attachments/assets/4118ebd4-3392-4bb7-a58d-ad84d6506d48)

I will add the rest that are missing.

**Comment by u-Sir** [comment]
thanks, i checked it again. `is chromium` still not added in tolgee
![图片](https://github.com/user-attachments/assets/6e04b30c-801d-42b5-8d6b-41fb04d8fed8)


and maybe you should set it `outdated` when has the English line as default. Now filter it out by searching one at a time.😂
![图片](https://github.com/user-attachments/assets/90d6ecf6-6d9f-4ea4-b733-5ab77acfd755)

**Comment by adirh3** [comment]
> thanks, i checked it again. `is chromium` still not added in tolgee ![图片](https://private-user-images.githubusercontent.com/93647031/385269506-6e04b30c-801d-42b5-8d6b-41fb04d8fed8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MTM1ODQsIm5iZiI6MTczMTQxMzI4NCwicGF0aCI6Ii85MzY0NzAzMS8zODUyNjk1MDYtNmUwNGIzMGMtODAxZC00MmI1LThkNmItNDFmYjA0ZDhmZWQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDEyMDgwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlNDU3MGMzZThjMDAzMjVmZjRmZGQ3YzUwNGE3YThjZjQ5YTgxYjdlMzhjODJmNDg4ZTIxN2ZkOTAwNDBmM2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Ri9MUT3dehRFDosoqIPxRjikp-QvKC9LGvQpaWjoRZ8)
> 
I removed it from the UI, it was there by mistake :)

**Comment by u-Sir** [comment]
some missing translations in latest nightly version. @adirh3 
<img width="1659" height="995" alt="Image" src="https://github.com/user-attachments/assets/2aebd251-6b86-44a1-9858-5ac9f991d755" />


<img width="2175" height="1352" alt="Image" src="https://github.com/user-attachments/assets/7ca3d48e-db3c-453b-962f-8f1644ed3837" />

<img width="3200" height="2000" alt="Image" src="https://github.com/user-attachments/assets/0aa80d24-9100-4920-a5fb-0cdf9d09ab5f" />

<img width="3200" height="2000" alt="Image" src="https://github.com/user-attachments/assets/d02850a5-f951-4d58-a96a-7377b0ed89cf" />

<img width="3200" height="2000" alt="Image" src="https://github.com/user-attachments/assets/91bf82d5-faad-41a4-8232-0ab232a04f4c" />

<img width="3200" height="2000" alt="Image" src="https://github.com/user-attachments/assets/d00471f6-6b41-46de-8f50-f635a5bbcb19" />
