### ISSUE TITLE
FS crashed when add any block in task in 1.0.0.50

### ISSUE THREAD

**Issue by u-Sir** [adirh3/Fluent-Search#1082]
**Describe the bug**
FS crashed when add any block in task

**To Reproduce**
add any block in task

**Screenshots**
![图片](https://github.com/user-attachments/assets/0612bfb7-69db-4e87-a4ba-6b56b05a6f8c)

**Desktop (please complete the following information):**
 - Window 11 Version: 24h2
 - Fluent Search Version: 1.0.0.50 beta
 - Installation source: Installer

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 1.0.0.51                                          . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
