### ISSUE TITLE
Disable file service indexer if Everything is used

### ISSUE THREAD

**Issue by wada3n** [adirh3/Fluent-Search#1084]
Hi,

First off, thank you for the amazing work on Fluent Search! It's been a game-changer for my workflow.
it would be great if there was an option to disable the built-in indexer when using Everything.

Thanks again for your hard work and dedication!

Best regards,

**Comment by adirh3** [comment]
Hey in this is already the case, when using any external indexer Fluent Search will stop the indexer and not start it again anymore.
Note - the indexer service will still be up for other tasks, but it will not index your drives anymore and you should see only 1 `FluentSearch.exe` process.
Did you experience something differently?

**Comment by wada3n** [comment]
hi @adirh3 
Actually, I did not experience anything differently.
I will close this.

Thank you!
