### ISSUE TITLE
[0.9.85.45] `Settings>Files` issues

### ISSUE THREAD

**Issue by cannibalox** [adirh3/Fluent-Search#109]
in 0.9.85.45 (portable) : some sections are not displayed in `Settings>Files`:
- `file indexer` chooser section is not displayed at all (I can search in the inpute box, a result comus up but doesn't lead anywhere)
-`Indexed paths` section is not displayed at all
- I can see the `ignored paths` section though
- the `Settings>Files` heading is not displayed (see gif below), it's working for other `search applications` but not for the `files`
![20210613_NUC8_OasztWOd7c](https://user-images.githubusercontent.com/4605693/121816110-f21c9280-cc79-11eb-8cc6-d6010dc29651.gif)

**Comment by adirh3** [comment]
@cannibalox is it fixed in 0.9.85.50?

**Comment by cannibalox** [comment]
fixed, thank you !
