### ISSUE TITLE
Instant search in file dialogs isn't working

### ISSUE THREAD

**Issue by flamingjupiter** [adirh3/Fluent-Search#1091]
**Describe the bug**
When a save/open file dialog appears, Fluent Search simply doesn't activate/pops up, even with instant searching in file dialogs option/setting activated. W11 23H2, latest FS version, tested with both installer and portable versions.

**Comment by adirh3** [comment]
Using the nightly version?

**Comment by flamingjupiter** [comment]
> Using the nightly version?

No, the version on https://fluentsearch.net/, which I guess it must be the last stable version. Will try the nightly version.

**Comment by flamingjupiter** [comment]
> Using the nightly version?

Just tested the nightly version (portable), and the same happens. Just to clear any misunderstandings, the instant search in file dialog feature/option/setting is to automatically pop up a fluent search popup (normal or specifically for files, not sure on this) whenever a file dialog (open; save as; etc) so you can search for the file/folder/path, enter it, and then the file dialog will navigate to that path, correct? You don't have to do or press anything, correct?

**Comment by adirh3** [comment]
> > Using the nightly version?
> 
> Just tested the nightly version (portable), and the same thing happens. Just to clear any misunderstandings, the instant search in file dialog feature/option/setting is to automatically pop up a fluent search popup (normal or specifically for files, not sure on this) whenever a file dialog appears (open; save as; etc), so you can search for the file/folder/path, enter it, and then the file dialog will navigate to that path, correct? You don't have to do or press anything, correct?

You need to start typing your search when the file dialog is focused and keyboard is not focused in a text box.
Then Fluent Search should appear with your search and let you pick a file from the folder in the dialog.

**Comment by flamingjupiter** [comment]
> > > Using the nightly version?
> > 
> > 
> > Just tested the nightly version (portable), and the same thing happens. Just to clear any misunderstandings, the instant search in file dialog feature/option/setting is to automatically pop up a fluent search popup (normal or specifically for files, not sure on this) whenever a file dialog appears (open; save as; etc), so you can search for the file/folder/path, enter it, and then the file dialog will navigate to that path, correct? You don't have to do or press anything, correct?
> 
> You need to start typing your search when the file dialog is focused and keyboard is not focused in a text box. Then Fluent Search should appear with your search and let you pick a file from the folder in the dialog.

Oh, so that's how it works, my bad. It is working as expected. On that, though, could automatic popup and focus on fluent search be made into a feature/settings option? On my computer (I don't know if this is the default behavior, but I guess so), whenever a file dialog opens (Save As; Open), the text box is automatically focused, so one needs to tab a few times to land on something that is not a text box, then start typing to activate Fluent Search. Is this the intended behavior? Tabbing until you get out of any text box is a kinda cumbersome way to then activate Fluent Search.

**Comment by adirh3** [comment]
@flamingjupiter thanks for the feedback, I will consider it for future version (Currently I am focusing on bugs). If you can create a separate feature request to make things organized I will appreciate it.
Also, I suggest you check out using the Quick Menu feature if you're using dialogs a lot.

**Comment by flamingjupiter** [comment]
> @flamingjupiter thanks for the feedback, I will consider it for future version (Currently I am focusing on bugs). If you can create a separate feature request to make things organized I will appreciate it. Also, I suggest you check out using the Quick Menu feature if you're using dialogs a lot.

I will create a feature request for that and check the quick menu feature, thank you for the attention.
