### ISSUE TITLE
Just seeking answer: How to rebuild index manually?

### ISSUE THREAD

**Issue by bxd** [adirh3/Fluent-Search#1094]
I changed my SSD and a lot of files changed their location.
Now FS has so many old invalid index. 
How can I rebuild the index?
thx in advance.

Using fluent search 1.0.0.63 under Windows 11

**Comment by adirh3** [comment]
1. Open settings by right clicking the system tray menu.
2. Go to -> Apps -> Files -> File indexer, or simply search `File indexer`
3. Click `Rebuild index`
![image](https://github.com/user-attachments/assets/e1259014-b67c-4166-af71-313463d06d6e)

**Comment by bxd** [comment]
> 1. Open settings by right clicking the system tray menu.
> 2. Go to -> Apps -> Files -> File indexer, or simply search `File indexer`
> 3. Click `Rebuild index`
>    ![image](https://private-user-images.githubusercontent.com/27368554/393529733-e1259014-b67c-4166-af71-313463d06d6e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2MjgyNjAsIm5iZiI6MTczMzYyNzk2MCwicGF0aCI6Ii8yNzM2ODU1NC8zOTM1Mjk3MzMtZTEyNTkwMTQtYjY3Yy00MTY2LWFmNzEtMzEzNDYzZDA2ZDZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA4VDAzMTkyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExM2YwMzQ4NThmMmZlZGQzOTdiMzU3Yjk5NDNiNGZkZTVlZjI2NjJlYWRiMzg2YThmOTc4MjBkZDU3M2JkN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.u_YOLlQrrY88u0OhRaDbu43ldOIiC2daUlouluBrQKA)

Thanks a lot! Finnaly i got it!
