### ISSUE TITLE
Icons in result section for files are not aligned (folders OK)

### ISSUE THREAD

**Issue by Metroid-Prime** [adirh3/Fluent-Search#111]
@MakeshVineeth noticed this and I volunteered to submit the bug report

The text on the files results are not aligned:

![image](https://user-images.githubusercontent.com/1836362/121993532-7a716500-cd58-11eb-8fc3-f8ee5f0abab0.png)

Request is to re-align them.

**Comment by adirh3** [comment]
This is duplicate with #74 @Metroid-Prime ?

**Comment by Metroid-Prime** [comment]
> This is duplicate with #74 @Metroid-Prime ?

Unless I am missing something (@Nomad-0 ) it's a completely different issue?  
#74  is referring to the ? showing up on all icons.   This issue (#111) is referring to the misaligned text to the icons.   Perhaps they're _technically_ related; in other words, if issue 74 is fixed, it would fix this?

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.85.75

**Comment by Metroid-Prime** [comment]
@adirh3  It looks better to be sure, but may I ask for a slightly more alignment?  I know this is a nitpick but just like Apple design spec, the little details really matter to users' subconscious.

 See this pic:
![image](https://user-images.githubusercontent.com/1836362/122630443-8a4eb900-d078-11eb-9e7b-67080e9d4ce2.png)

**Comment by adirh3** [comment]
> @adirh3 It looks better to be sure, but may I ask for a slightly more alignment? I know this is a nitpick but just like Apple design spec, the little details really matter to users' subconscious. The folder entries look more aligned than the ? Files
> 
> See this pic:
> ![image](https://user-images.githubusercontent.com/1836362/122630443-8a4eb900-d078-11eb-9e7b-67080e9d4ce2.png)

It is aligned, there is just differences in sizes between icons that I can't overcome. 
Try looking at them with the selection line on them, that way you will see they're all aligned at the middle
