### ISSUE TITLE
Add "options" and "preferences" and "settings" option to open main settings page

### ISSUE THREAD

**Issue by Metroid-Prime** [adirh3/Fluent-Search#112]
Request is to add a way to launch the main settings page through the word "preferences" and "options" and .... (Adir you're going to hate me... Lol)  "settings".

Alfred & Listary have done this and I found it's the fastest/best way to launch the main settings page.
![image](https://user-images.githubusercontent.com/1836362/121995462-cd005080-cd5b-11eb-9bb2-5b654ac92531.png)
![image](https://user-images.githubusercontent.com/1836362/121995488-d8ec1280-cd5b-11eb-9308-e4561603ac6c.png)

**Comment by adirh3** [comment]
Isn't this the same as #13 ? @Metroid-Prime

**Comment by Metroid-Prime** [comment]
Darn it. I'm sorry @adirh3  Yes it is.  I _knew_ I had posted it but for some reason I couldn't find that specific post.
Thanks, I'll close this one.
