### ISSUE TITLE
Moving files from FS onto Windows File Explorer not working

### ISSUE THREAD

**Issue by christubuntu** [adirh3/Fluent-Search#113]
**Describe the bug**
Moving files/folders out of FS to Windows Explorer etc. is not working. 

**To Reproduce**
1. Open FS, search for a file/folder
2. Hold Alt keyboard key, drag and drop the file/folder from FS to Windows File explorer
3. There's a crossed circle indicating error

**Expected behavior**
The file/folder should be moved to the destination software/process

**Desktop (please complete the following information):**
 - Windows 10 Version: [e.g. 20H1]
 - Fluent Search Version [e.g. 0.9.85.50]

**Additional context**
Issue seems related to issue #77 (https://github.com/adirh3/Fluent-Search/issues/77) where a bug (that was fixed) affected drag and drop to COPY files.

**Comment by kwanice** [comment]
@christubuntu agree, we can copy but not MOVE file :)

**Comment by Metroid-Prime** [comment]
@christubuntu I usually use the copy /paste function

will defer to @adirh3  if it's supposed to be working with drag and drop to desktop.

**Comment by christubuntu** [comment]
> will defer to @adirh3 if it's supposed to be working with drag and drop to desktop. 
It's in the changelog for version 0.9.80.0

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.85.65
