### ISSUE TITLE
Every letter changes to lowercase

### ISSUE THREAD

**Issue by Mr-Frankenstein** [adirh3/Fluent-Search#114]
**Describe the bug**
If I create a task in Microsoft To Do or search for something on Google, FS makes every letter lowercase.

**To Reproduce**
1. Search something on google with uppercase
2. See all letters change to lowercase

**Expected behavior**
FS shouldn't change uppercase letters to lowercase.

**Screenshots**
![image](https://user-images.githubusercontent.com/85425543/122089198-259b2080-ce24-11eb-85c8-3dbdbbb65413.png)

**Desktop (please complete the following information):**
 - Windows 10 Version: 21H1
 - Fluent Search Version 0.9.85.55

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.85.65

**Comment by Metroid-Prime** [comment]
@Mr-Frankenstein  can you validate?

**Comment by Mr-Frankenstein** [comment]
> @Mr-Frankenstein can you validate?

This issue is fixed. You can close this issue now.
