### ISSUE TITLE
CLIPBOARD - be able to edit an item

### ISSUE THREAD

**Issue by kwanice** [adirh3/Fluent-Search#116]
**Is your feature request related to a problem? Please describe.**
We can have a long list of item saved, and adding the possibility to edit will be great :)

**Describe the solution you'd like**
Add another menu to edit

**Additional context**
![image](https://user-images.githubusercontent.com/14847187/122160811-e0511000-ce70-11eb-92c4-16de14f0f1a3.png)

**Comment by adirh3** [comment]
Not going to change that, as I plan to add a notes plugin which will be make more sense for this
