### ISSUE TITLE
TAG - the UI indicator for TAG give the wrong information

### ISSUE THREAD

**Issue by kwanice** [adirh3/Fluent-Search#117]
**Describe the bug**
It happen when the feature `suggest tags from result` is not enabled
see the 2 images to see what happen

**To Reproduce**
1. Open FS
2. type clip
3. press enter
4. Instead of clipboard history (as the ui indicator mentioned, we have the search clip:)

**Expected behavior**
the Ui indicator should show the clip tag instead of clipboard history

**Screenshots**
![image](https://user-images.githubusercontent.com/14847187/122161246-a9c7c500-ce71-11eb-841d-d1df2b927357.png)
then press TAB
![image](https://user-images.githubusercontent.com/14847187/122161266-b2200000-ce71-11eb-99d6-a4c060f4d8cb.png)

**Desktop (please complete the following information):**
 - Windows 10 Version: 21390.1000
 - Fluent Search Version: 0.9.85.60

remarks :
If i enable the settings `suggest tags from result` i dont have this problem :)

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.85.65
