### ISSUE TITLE
When Open FS, the scroll bar is not always on the top

### ISSUE THREAD

**Issue by kwanice** [adirh3/Fluent-Search#119]
**Describe the bug**
when we make a new search on FS, the scroll bar should be on the top, but now, if for example you search on your clipboard history, and scrolling down , and after u open again FS, and start to search something, the scroll bar is not at top but maybe the 3 or 4 th line, and on the FS screen result you cant see the top lines

** to reproduce **
1. scroll in your clipboard history
2. open again FS
3. search
4. the scroll bar is not at the top

**Expected behavior**
The highlighted and focused line should always be the first one

**Screenshots**
![image](https://user-images.githubusercontent.com/14847187/122163734-ee555f80-ce75-11eb-81b7-a239acb5ebeb.png)

**Desktop (please complete the following information):**
 - Windows 10 Version: 21390
 - Fluent Search Version: 0.9.85.60

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.76                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
