### ISSUE TITLE
Prioritization not sorting result properly

### ISSUE THREAD

**Issue by kwanice** [adirh3/Fluent-Search#120]
**Describe the bug**
i set the prioritization with app first and after clipboard
when i make a search the clipboard came first and after app
if i set the clipboard at a lower place less than 20 in my example, i cant see the clipboard result in the FS result

**Screenshots**
the result
![image](https://user-images.githubusercontent.com/14847187/122164577-4ccf0d80-ce77-11eb-9cd8-00c1e35deb58.png)

my settings
![image](https://user-images.githubusercontent.com/14847187/122164613-59ebfc80-ce77-11eb-9b95-11dfa819f218.png)

**Desktop (please complete the following information):**
 - Windows 10 Version: 21390
 - Fluent Search Version: 0.9.85.60

**Comment by adirh3** [comment]
Should be fixed, closing
