### ISSUE TITLE
Move Plugins setting to bottom of settings left pane.

### ISSUE THREAD

**Issue by Metroid-Prime** [adirh3/Fluent-Search#122]
Prepare for a nitpick.

![image](https://user-images.githubusercontent.com/1836362/122174063-415bf200-ce37-11eb-8bf6-cdc6e65869eb.png)

Of course this plugins should sit above the "About" pane in #31

**Comment by adirh3** [comment]
@Metroid-Prime I believe you say it because your settings window is stretched (not default size), if I move it to bottom people will not know it's there.

**Comment by Metroid-Prime** [comment]
Wouldn't that be the case for the other search tags too then?  Could be wrong, but I feel like plugins are a lower priority than the core stuff? What do you think?

**Comment by adirh3** [comment]
Both settings section are now collapsed by default, closing this
