### ISSUE TITLE
Highlighted clicking jumps over plugins and Advanced Sections

### ISSUE THREAD

**Issue by Metroid-Prime** [adirh3/Fluent-Search#123]
**Describe the bug**
![image](https://user-images.githubusercontent.com/1836362/122174488-a0216b80-ce37-11eb-993c-36b8123f09fa.png)

![image](https://user-images.githubusercontent.com/1836362/122174843-f1c9f600-ce37-11eb-9d8f-8e11d656c88f.png)
 - Windows 10 Version: LTSC 1809
 - Fluent Search Version 0.9.85.60

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.76                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
