### ISSUE TITLE
FS Twitter Outdated

### ISSUE THREAD

**Issue by Metroid-Prime** [adirh3/Fluent-Search#124]
The FS Twitter page is outdated for ~2 months (since May).
https://twitter.com/FluentSearch

I would say cleanse the old announcement posts to avoid making the app look outdated 
_or_
If there's a way to automate announcements of new versions via Twitter (like what we did with Discord) that would be an option too.

**Comment by adirh3** [comment]
@Metroid-Prime I don't think people want to see changelogs in twitter, although I might be wrong.
I will try to post more updates there with screenshots, let me know if you got any specific suggestion.

**Comment by Metroid-Prime** [comment]
I agree with you. Changelogs in twitter are absolutely not necessary but I saw a few them of there.  From a user's  perspective, seeing 'old'  (relatively speaking for FS of course, lol)

**Comment by Metroid-Prime** [comment]
I'll leave it up to you if you want to delete the twitter changelogs from past so there's no confusion to users.
