### ISSUE TITLE
The hotkeys for navigation in ms edge browser (ctrl+m) are called very slowly

### ISSUE THREAD

**Issue by haosmos** [adirh3/Fluent-Search#126]
**Description of the problem:**

For some unknown reason, the hotkeys for navigation in ms edge browser (ctrl+m) are called very slowly. The browser even hangs up)

I assume it has to do with some extension of my browser (of which I have many) because in chrome the shortcuts are called very fast. 

How can I check which of my extensions is causing the problem?   

Or maybe the problem is something else?

**My work environment:**
 - Windows 10 Version: insider dev build 21382.1
 - Fluent Search Version 0.9.85.60 (beta)
 - ms edge canary - build 93.0.923.0

**Comment by adirh3** [comment]
@haosmos Can you check if you have "Force using UI search engine" enabled in Settings -> Screen?

**Comment by haosmos** [comment]
> @haosmos Can you check if you have "Force using UI search engine" enabled in Settings -> Screen?

This seems to be the problem. I disabled this feature and now hotkeys are called quickly! Thank you! 👍

Would you please tell me if you need any other clarifying information? 

Or can I close the issue?

**Comment by Nomad-0** [comment]
@haosmos you may close the issue now

**Comment by Metroid-Prime** [comment]
Closing for @haosmos
