### ISSUE TITLE
Long text in info box are not well cut

### ISSUE THREAD

**Issue by kwanice** [adirh3/Fluent-Search#127]
**Describe the bug**
on some info box, when the text is on several lines, at the end of the line, the word is not well splited

**Screenshots**
![image](https://user-images.githubusercontent.com/14847187/122341996-61c5a280-cf44-11eb-9569-050b51d5c277.png)
the word "remove" should be "re-move" or "remove" at the beginning of the second line
and the word "search" should be written on the 3rd line

**Desktop (please complete the following information):**
 - Windows 10 Version: 21390.1000
 - Fluent Search Version: 0.9.85.65

**Comment by kwanice** [comment]
![image](https://user-images.githubusercontent.com/14847187/122343178-b61d5200-cf45-11eb-8242-ebd908351878.png)

**Comment by adirh3** [comment]
Should be fixed on latest stable/nightly, closing. Feel free to reopen if it's not fixed on your side
