### ISSUE TITLE
KillAll plugin's search tag does not clear on tab

### ISSUE THREAD

**Issue by ScarletKing-001** [adirh3/Fluent-Search#128]
On pressing `Tab` to activate the `killall` tag:
 if the tag is pressed before typing killall fully, the letters typed appear in the argument of the tag.
For eg.,
if 'killa' `Tab` is typed, the killall tag searches for a process called 'killa'
![image](https://user-images.githubusercontent.com/71964994/122345008-e5789280-cf36-11eb-9c99-f023b2f80291.png)

But if 'killall' is typed fully, `Tab` is blank, waiting for process name.
![image](https://user-images.githubusercontent.com/71964994/122345255-2ffa0f00-cf37-11eb-8fa6-0995c8f4b9d7.png)

Fluent Search version: 0.9.85.65
OS version: Windows 10 21H1(19043.985)

**Comment by adirh3** [comment]
@ScarletKing-001 I believe this is fixed in the latest version

**Comment by Nomad-0** [comment]
fixed on my end, @ScarletKing-001, please validate

**Comment by ScarletKing-001** [comment]
Yes, has been fixed.
