### ISSUE TITLE
About window is too small

### ISSUE THREAD

**Issue by ScarletKing-001** [adirh3/Fluent-Search#129]
The about window is too small & must be resized to view version details

**To Reproduce**
1. Right-click systray icon
2. Click on 'About'
3. The window is too small to see the version number, and needs resizing ; needs to become larger by default

**Screenshots**
![image](https://user-images.githubusercontent.com/71964994/122347630-c7606180-cf39-11eb-941c-31084a1ca1eb.png)

**Specs**
 - Windows 10 21H1 
 - Fluent Search Version 0.9.85.65

**Comment by Metroid-Prime** [comment]
@ScarletKing-001   Mine doesn't do this.  Do you have Windows scaling turned on above 100%? 
@Nomad-0   Do  you mind if I change this to bug?  It shouldn't be working this way as my window fits the version window

**Comment by Nomad-0** [comment]
oh sorry, I thought he asked adding the changelog to the about window.

**Comment by ScarletKing-001** [comment]
@Metroid-Prime My windows scaling is at 125%, but as it turns out, even on setting my default zoom to 100%, the window is scaled down in size, and the version number's still hidden.

**Comment by adirh3** [comment]
@ScarletKing-001 I believe this is fixed, if not reopen this
