### ISSUE TITLE
Setting Quick Launch via  “options” or “settings” or "preferences"  

### ISSUE THREAD

**Issue by Metroid-Prime** [adirh3/Fluent-Search#13]
Allow FS to launch settings by typing in “options” or “settings” or "preferences" in the FS's main search window

All of the top launchers have this.  FS should have it too.

![image](https://user-images.githubusercontent.com/1836362/120909206-9de53300-c627-11eb-90e8-ef8887618f1d.png)

**Comment by mochigithub** [comment]
![image](https://user-images.githubusercontent.com/1836362/120909206-9de53300-c627-11eb-90e8-ef8887618f1d.png)

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.85.75

**Comment by Metroid-Prime** [comment]
> This issue has been potentially fixed in version 0.9.85.75

@Nomad-0  @MakeshVineeth  Can either of you get this working?  I tried "settings" as suggested in the changelog but it didn't work.

**Comment by Nomad-0** [comment]
I can open particular _settings_ from FS like, appearances, search. but can't find any option for settings only

**Comment by MakeshVineeth** [comment]
It is like this from my side, is this what you were expecting?

![2021-06-19](https://user-images.githubusercontent.com/19371684/122630641-e4846400-d0e2-11eb-925a-a417608b5179.png)

**Comment by Metroid-Prime** [comment]
I just redownloaded a portable version of FS and don't see that.  I thought for sure it was related to my settings.

@adirh3  any idea why I wouldn't see it?  It looks like it's implemented so I'll close it for good measure but hopefully you can let me know if it's settings based

**Comment by Metroid-Prime** [comment]
Sorry Adir. Going to reopen this as it sounds like there's difficulty for others getting it to launch

**Comment by adirh3** [comment]
@Metroid-Prime did you search for "settings"?

**Comment by Nomad-0** [comment]
@Metroid-Prime I'm being able to find it now, it was way below the result that I couldn't find it previously I think

![image](https://user-images.githubusercontent.com/76395594/122646223-ea5c6280-d13f-11eb-91b6-ff1ecfcd6ba9.png)

**Comment by Metroid-Prime** [comment]
> @Metroid-Prime did you search for "settings"?

Yes. See screenshot. I'm suspecting this has got to do with my settings. Is it dependent on any specific settings.
![image](https://user-images.githubusercontent.com/1836362/122663337-842b0c00-d14e-11eb-8a43-8e3ab9c3e53c.png)

**Comment by adirh3** [comment]
> > @Metroid-Prime did you search for "settings"?
> 
> Yes. See screenshot. I'm suspecting this has got to do with my settings. Is it dependent on any specific settings?
> ![image](https://user-images.githubusercontent.com/1836362/122663337-842b0c00-d14e-11eb-8a43-8e3ab9c3e53c.png)

Send me your settings please

**Comment by Metroid-Prime** [comment]
sent via discord PM @adirh3

**Comment by adirh3** [comment]
@Metroid-Prime Is your "Settings Search" active? In Settings -> Settings Search -> Enable Application?

**Comment by Metroid-Prime** [comment]
This is working on a different computer with a non-tuned portable  install.

I wonder if it's because I have so many things with the name "settings" inside them that it's pushing it to the bottom (below 30th result) and that's why I'm not seeing it?

I'll check for that setting when I get home later.

**Comment by adirh3** [comment]
@Metroid-Prime any update?

**Comment by MakeshVineeth** [comment]
Works fine from my end.

![image](https://user-images.githubusercontent.com/19371684/124299861-87c18880-db7b-11eb-9e9a-30f2f811c5dd.png)

@Metroid-Prime @Nomad-0 Can you guys confirm this on latest version?

**Comment by Nomad-0** [comment]
I'm not being able to find it again, which I think because I limited the number of the _max search results_ to 30

![image](https://user-images.githubusercontent.com/76395594/124307020-04a72f00-db89-11eb-9601-c20387b84388.png)

I think the best would be to indicate fs settings as _**options**_ or _**preferences**_ or something like this, while keeping the _settings_ for system settings only

**Comment by adirh3** [comment]
> I'm not being able to find it again, which I think because I limited the number of the _max search results_ to 30
> 
> ![image](https://user-images.githubusercontent.com/76395594/124307020-04a72f00-db89-11eb-9601-c20387b84388.png)
> 
> I think the best would be to indicate fs settings as _**options**_ or _**preferences**_ or something like this, while keeping the _settings_ for system settings only

Can you validate this is the issue by increasing the max results cap?

**Comment by Metroid-Prime** [comment]
search tag only OFF, but I still don't see it.

I put the search results max to 500 and tried to scroll through hundreds of items, but I didn't see that gear icon. I'm still suffering from the ? Question mark icon issue.

Ideally the settings (like Listary) should be routed to the very top to avoid this.
![image](https://user-images.githubusercontent.com/1836362/124342806-8a23e280-db7b-11eb-8939-8897be9eed33.png)

**Comment by MakeshVineeth** [comment]
Oops, I've also started facing this issue lately. Unable to find the **Fluent Search Settings**.

**Comment by Nomad-0** [comment]
did you try grouping the items? now it gets higher with the grouping. though I'm still on for giving different names to system settings and FS settings 

![image](https://user-images.githubusercontent.com/76395594/127265695-6d8686df-906e-44e6-aa41-cc15e2786a1f.png)

**Comment by MakeshVineeth** [comment]
Yeah, it's getting displayed when grouping settings. Though I would prefer to leave it at default i.e., **Smart**.

**Comment by Metroid-Prime** [comment]
@adirh3  informed me a while back that one can press ALT + ENTER at FS main search menu to bring up Settings.
As far as I am concerned, this satisfies my needs to bring up settings window. Closing ticket.
