### ISSUE TITLE
Impossible to add tags after search query

### ISSUE THREAD

**Issue by christubuntu** [adirh3/Fluent-Search#130]
https://user-images.githubusercontent.com/55885756/122355137-f5ea3680-cf51-11eb-99d6-fc5b50fbb0b3.mp4

**Describe the bug**
In previous versions of FS, one used to be able to insert a tag after typing the search query. But now, it's impossible

**To Reproduce**
1. Open Fs, type search query (ex. blast
2. Insert "folder" tag
3. FS won't search a folder named blast, instead, it'll start a new empty search with "folder' tag

**Expected behavior**
FS used to search a folder named blast when the tag was inserted after the search term

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 10 Version: [e.g. 20H1]
 - Fluent Search Version [e.g. 0.9.85.65]

**Additional context**
I don't know if this feature was removed because of issue it caused, but it was very useful.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.85.70
