### ISSUE TITLE
minimal style resize bug

### ISSUE THREAD

**Issue by ltu00** [adirh3/Fluent-Search#132]
**Describe the bug**
minimal style resize bug

**To Reproduce**
1. set window style minimal
2. launch FS
3. resize search bar horizontal

**Expected behavior**
show huge

**Screenshots**
![image](https://user-images.githubusercontent.com/50564608/122409522-c8cf6f80-cfb5-11eb-9752-755a3e09578c.png)

**Desktop (please complete the following information):**
 - Windows 10 Version: [e.g. 20H1]
 - Fluent Search Version [e.g. 0.9.85.65]

**Comment by adirh3** [comment]
@ltu00 Can you let me know why would you like to resize the search bar vertically?
Trying to resize vertically will stretch the expanded window, and this is by design

**Comment by Metroid-Prime** [comment]
Not sure if this is a bug based on @adirh3 's comment but I'll label it as a bug since the user posted it as such.

**Comment by ltu00** [comment]
> stretch

no ,i am trying resize search bar horizontal, and then it changed vertical too.
