### ISSUE TITLE
Open uninstall 

### ISSUE THREAD

**Issue by DamaniMC** [adirh3/Fluent-Search#133]
I find myself frequently trying to uninstall programs and being forced to use the windows button to get to the "uninstall" / "add or remove programs ". If this could be done straight from fluent search by typing uninstall that would be ideal.

**Comment by adirh3** [comment]
@DamaniMC Did you try searching for the app in FS then press uninstall?

**Comment by Metroid-Prime** [comment]
> I find myself frequently trying to uninstall programs and being forced to use the windows button to get to the "uninstall" / "add or remove programs ". If this could be done straight from fluent search by typing uninstall that would be ideal.

There is workaround for this. You can create a shortcut for Add-remove programs from the old control panel and put it in a folder. Then enable the App search in FS and point it to the folder that has the shortcut..

**Comment by Nomad-0** [comment]
confirming this one, pressing _uninstall_ on the search bar menu takes to the settings instead of uninstalling it directly

**Comment by Nomad-0** [comment]
This one's now working on my end, would you like to check it again? @DamaniMC

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.76                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
