### ISSUE TITLE
Refresh button is partially visible in Plugins window

### ISSUE THREAD

**Issue by MakeshVineeth** [adirh3/Fluent-Search#135]
**Bug Description**
The Refresh button is bit glitched in Plugins window as small bottom part of the icon got overlapped and is not properly visible.

**Steps To Reproduce**
1. Go to Plugins window either though Tray icon or through Settings.
2. Wait for all the plugins is load.
3. The Refresh icon is not looking good.

**Expected behavior**
Default size of the Plugins window can be increased so that the Resize button is fully visible.

**Screenshots**
![2021-06-18](https://user-images.githubusercontent.com/19371684/122518296-a463a980-d02e-11eb-8842-38ddf854b880.png)

**Desktop Information:**
 - Windows 10 Version: 21H1
 - Fluent Search Version: 0.9.85.70

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.85.75

**Comment by Nomad-0** [comment]
confirming fix and closing. @MakeshVineeth please let me know if you disagree
