### ISSUE TITLE
No Gap between Search Bar and the Plugin card in Plugins window

### ISSUE THREAD

**Issue by MakeshVineeth** [adirh3/Fluent-Search#136]
**Describe the bug**
The screenshot says it all, there is no gap between the search bar and the plugins card when scrolled. Also, the plugin card minutely overlaps with the search bar.

**Steps To Reproduce**
1. Go to Plugins window.
2. Wait for the Refresh to complete.
3. Try to scroll down.
4. And check the padding/gap between the search bar and the plugin results.

**Screenshots**
![2021-06-18 (4)](https://user-images.githubusercontent.com/19371684/122520717-98c5b200-d031-11eb-8b66-ae5efcf72dbe.png)

**Desktop Information:**
 - Windows 10 Version: 21H1
 - Fluent Search Version: 0.9.85.70

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.85.75

**Comment by Nomad-0** [comment]
confirming fix and closing. @MakeshVineeth please let me know if you disagree.
