### ISSUE TITLE
Use of Circular Progress Indicator instead of Linear Progress Bar in Plugins window

### ISSUE THREAD

**Issue by MakeshVineeth** [adirh3/Fluent-Search#137]
Right now, Fluent Search displays a horizontal progress bar while the plugins are being refreshed in the Plugins window. But as you can see from the screenshot, it is not looking that good. It would be better to display a Circular Progress Indicator **beside** the Search Bar instead.

![2021-06-18 (5)](https://user-images.githubusercontent.com/19371684/122521789-decf4580-d032-11eb-88b6-f06a9356b5a5.png)

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.85.75

**Comment by Nomad-0** [comment]
closing as the fix is confirmed.
