### ISSUE TITLE
DRAG'N'DROP - Close FS when copy/move files

### ISSUE THREAD

**Issue by kwanice** [adirh3/Fluent-Search#138]
**Is your feature request related to a problem? Please describe.**
maybe it can be nice when we want to copy or move a file, to close FS after copy or move a file

**Describe the solution you'd like**
Close FS search windows

**Comment by Nomad-0** [comment]
I actually disagree with this one. When I want to move multiple files, I have to invoke and search FS for each file separately.

**Comment by kwanice** [comment]
when for example u are on whatsapp web or desktop, u want to copy a file, a pic, u open fs, u drag ur files to the windows, and u cant see if the files is correctly inserted because the search windows is in the middle of the screen, so you cant see if the files has been moves or copy...

**Comment by adirh3** [comment]
> when for example u are on whatsapp web or desktop, u want to copy a file, a pic, u open fs, u drag ur files to the windows, and u cant see if the files is correctly inserted because the search windows is in the middle of the screen, so you cant see if the files has been moves or copy...

I'd suggest you disabling "Top most" in settings

**Comment by adirh3** [comment]
@kwanice see my comment above, should fix the problem you're describing. Closing it, feel free to reopen.
