### ISSUE TITLE
Group stay collapsed

### ISSUE THREAD

**Issue by Najah101** [adirh3/Fluent-Search#139]
If I collapse a group in the settings and reopen the settings, the group should stay collapsed.
![image](https://user-images.githubusercontent.com/85425543/122588726-0b0fb400-d07d-11eb-8c2c-5ca0ff01f7d8.png)

**Comment by Metroid-Prime** [comment]
Agree with this.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.76                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
