### ISSUE TITLE
Fullscreen mode setting

### ISSUE THREAD

**Issue by Metroid-Prime** [adirh3/Fluent-Search#14]
The settings left pane can be confusing for the average user and even for me. I have to step back and look at it and realize there's multiple logical discrepancies: 
1) Move plugins into their own section under "Plugins". they should not be under search applications.
2) If possible, move Microsoft To-Do to a plugin. People who don't need or use ToDo shouldn't be forced to use it.  (_EDIT: Sign In button was moved to ToDo window. Thank you_!)
3) Change "Settings" name to something much more descriptive. This is very confusing as user doesn't know what Settings specifies Not sure what the best name is but something like "Windows OS Settings" or "System Settings" or "OS Settings"

![image](https://user-images.githubusercontent.com/1836362/120913632-51145300-c64d-11eb-8d60-c6bc06de172e.png)

![image](https://user-images.githubusercontent.com/1836362/120913644-60939c00-c64d-11eb-9e8a-052cf6161448.png)

**Comment by Nomad-0** [comment]
Agree with this. Or maybe the FS settings could be changed to options/preferences

**Comment by adirh3** [comment]
@Metroid-Prime This is fixed IMO
To-Do not going to become plugin due to it breaking for users who uses it.

**Comment by Metroid-Prime** [comment]
TY @adirh3   I understand about Todo.
