### ISSUE TITLE
Two Separate Options: 1 to hide Taskbar Icon & 1 to hide Tray icon

### ISSUE THREAD

**Issue by MakeshVineeth** [adirh3/Fluent-Search#142]
Whenever we launch the FS window, it will show a Taskbar icon like shown in the image below. It would be awesome if there is an option to hide it through FS Settings.

![2021-06-19 (2)](https://user-images.githubusercontent.com/19371684/122631709-1a2d4b00-d0eb-11eb-969a-99a9174a0da2.png)

Additionally, provide an option to hide the tray icon in FS Settings > Appearance.

**Comment by Metroid-Prime** [comment]
@Nomad-0  and I support this request.

I would definitely turn off the taskbar one

**Comment by Nomad-0** [comment]
agree, I personally prefer not to have this one by default
![image](https://user-images.githubusercontent.com/76395594/122631834-64fd9180-d0f0-11eb-877c-92a4df2491d5.png)

**Comment by Metroid-Prime** [comment]
> agree, I personally prefer not to have this one by default
> ![image](https://user-images.githubusercontent.com/76395594/122631834-64fd9180-d0f0-11eb-877c-92a4df2491d5.png)

Yes I agree with this true.  Default setting should be taskbar OFF, system ON.  This is a no-brainer as it's good interface

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.88.4

**Comment by Nomad-0** [comment]
solved on my end

**Comment by MakeshVineeth** [comment]
Yes, works fine for me too. @Metroid-Prime Can you confirm the same?

**Comment by adirh3** [comment]
No need so many people confirming it.
If it does not work for anyone feel free to reopen this.
