### ISSUE TITLE
Reduce tag description of chromium

### ISSUE THREAD

**Issue by MakeshVineeth** [adirh3/Fluent-Search#145]
This is something that I and @Nomad-0 agreed upon. The tag description of chromium is too long and taking lot of space.

![2021-06-21 (1)](https://user-images.githubusercontent.com/19371684/122710101-3c56d280-d27d-11eb-82a0-a2d3ab12e45a.png)

**Tip:** Make it minimal like **"Search in Chromium Browsers"** or something along the lines. As @Nomad-0 have said, people will get used to `TAB` behavior eventually, and no need to include Press TAB in tip.
**Alternative Tip:** If devs are planning to extend this search functionality to include non-chromium browsers like FireFox or Opera, then it can be generalized i.e., simply **Search in Web Browsers** for tag description & rename the `chromium` tag to `browser` or something similar.

**Comment by MakeshVineeth** [comment]
Some overlapping issues:

![image](https://user-images.githubusercontent.com/19371684/124298958-817edc80-db7a-11eb-8842-7a180b77e8ea.png)

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.88.4

**Comment by MakeshVineeth** [comment]
Confirming the fix. Closing.
