### ISSUE TITLE
Move Plugins window to FS Settings instead of separate window.

### ISSUE THREAD

**Issue by MakeshVineeth** [adirh3/Fluent-Search#146]
This is something I, @Nomad-0 and @Metroid-Prime agreed upon in our Discord chat earlier. As title says, it feels more consistent if the plugins window will be moved to FS Settings itself. You can name it something like **Plugins Manager**

**Comment by Nomad-0** [comment]
changing it to modification as it depends upon devs discretion

**Comment by Metroid-Prime** [comment]
As mentioned, I agree with this. Having plugins compartmentalized into the settings would be 1 less place for users to go.
I also recommend removing the plugins window and tiny menu icon altogether when or if it's embedded as plugins manager in FS settings.

Concur with @Nomad-0  that this is at @adirh3  's discretion but  I agree with @MakeshVineeth  that it's good design.

**Comment by adirh3** [comment]
The plan is to make the plugins eco system richer by having more plugin types like previews, workflows, custom files operations, etc.
I believe this will make people look for plugins much more, so opening the settings for them would be inefficient IMO.

**Comment by Metroid-Prime** [comment]
> The plan is to make the plugins eco system richer by having more plugin types like previews, workflows, custom files operations, etc.
> I believe this will make people look for plugins much more, so opening the settings for them would be inefficient IMO.

Sounds good. Can't wait!  @MakeshVineeth  should we close this as wontfix?

**Comment by MakeshVineeth** [comment]
> The plan is to make the plugins eco system richer by having more plugin types like previews, workflows, custom files operations, etc.
> I believe this will make people look for plugins much more, so opening the settings for them would be inefficient IMO.

Sounds awesome, looking forward to it 😃 @Metroid-Prime Yes we can close this now.
