### ISSUE TITLE
Use the same keyboard shortcut to show/hide preview

### ISSUE THREAD

**Issue by christubuntu** [adirh3/Fluent-Search#147]
**Is your feature request related to a problem? Please describe.**
Use same keyboard shortcut to show/hide preview. 

**Describe the solution you'd like**
Ex. I use Ctrl+Enter to show preview, but I need to use Esc. to hide it. This requires shifting my fingers position.

**Describe alternatives you've considered**
If same shortcut was used, I wouldn't need to move fingers when previewing files.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.76                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
