### ISSUE TITLE
Non english character broken in search bar (but ok in result)

### ISSUE THREAD

**Issue by hoshins** [adirh3/Fluent-Search#148]
**Describe the bug**

**To Reproduce**
1. Activate Fluent Search search bar
2. Enter non english character (eg. "한글" in Korean)
3. Entered character broken (displayed as square)

**Expected behavior**
Display non english character correctly.

**Screenshots**
I can't attach screenshot due to company's security policy.

**Desktop (please complete the following information):**
 - Windows 10 Version: [21H1]
 - Fluent Search Version [0.9.85.85]

**Additional context**
N/A

**Comment by Nomad-0** [comment]
Support for more languages will be added near/after release (version 1.0.0)

**Comment by adirh3** [comment]
@hoshins Did you try changing the font to Korean font in Settings -> Appearance -> Font family?

**Comment by hoshins** [comment]
> @hoshins Did you try changing the font to Korean font in Settings -> Appearance -> Font family?

I did it but not works

**Comment by Nomad-0** [comment]
@adirh3 should I label it as a bug?

**Comment by adirh3** [comment]
> @adirh3 should I label it as a bug?

There is no support for many languages, sometimes I forget which.
As you said the support will be added near version 1.0.0.

**Comment by Nomad-0** [comment]
oh, I thought this one was added. I'm labeling it as enhancement then.

**Comment by alanjustalan** [comment]
Hi,I want to know when will solve this problem?  Search box cannot display Chinese is not very convenient

**Comment by Nomad-0** [comment]
https://github.com/adirh3/Fluent-Search/issues/153#issue-928033808

![image](https://user-images.githubusercontent.com/76395594/127264217-f79c08cf-1ec7-491a-8e0b-b19c302422f4.png)

**Comment by MileShaw** [comment]
Me, too. How can I solve this problem?
![image](https://user-images.githubusercontent.com/57314553/128586377-0b9adc20-b38d-4dff-8fee-2c6990cab7b6.png)

**Comment by nutnutwin** [comment]
@Nomad-0 Thank you. So far CJK fonts works fine for me

Currently using Sarasa

**Comment by adirh3** [comment]
> Hi,I want to know when will solve this problem? Search box cannot display Chinese is not very convenient

Should be solved by the end of the year (probably sooner)

**Comment by nutnutwin** [comment]
> Me, too. How can I solve this problem?
> 
> ![image](https://user-images.githubusercontent.com/57314553/128586377-0b9adc20-b38d-4dff-8fee-2c6990cab7b6.png)
> 
> 

you can use CJK font
like simhei(黑体) or simsun(新宋体? ), or fangsong(仿宋)

Personally i use sarasa Available on GitHub

**Comment by theweeeknd** [comment]
> > Me, too. How can I solve this problem?
> > ![image](https://user-images.githubusercontent.com/57314553/128586377-0b9adc20-b38d-4dff-8fee-2c6990cab7b6.png)
> 
> you can use CJK font like simhei (黑体) or simsun (新宋体？), or fangsong (仿宋)
> 
> Personally i use sarasa Available on GitHub

i know it sounds a little _weird_ but, in my case none of these (更纱黑体, 思源黑体, 微软雅黑, even Microsoft YaHei UI _Light_ ) works _except_ the only one : Microsoft YaHei UI.

![image_472](https://user-images.githubusercontent.com/84619641/152633579-8e005f9d-3935-472d-b413-a60e4de4b639.png)

![image_471](https://user-images.githubusercontent.com/84619641/152633581-1fa274ea-decd-4bb1-87fd-9c89919d2be0.png)

**Comment by adirh3** [comment]
> > > Me, too. How can I solve this problem?
> > > ![image](https://user-images.githubusercontent.com/57314553/128586377-0b9adc20-b38d-4dff-8fee-2c6990cab7b6.png)
> > 
> > 
> > you can use CJK font like simhei (黑体) or simsun (新宋体？), or fangsong (仿宋)
> > Personally i use sarasa Available on GitHub
> 
> i know it sounds a little _weird_ but, in my case none of these (更纱黑体, 思源黑体, 微软雅黑, even Microsoft YaHei UI _Light_ ) works _except_ the only one : Microsoft YaHei UI.
> 
> ![image_472](https://user-images.githubusercontent.com/84619641/152633579-8e005f9d-3935-472d-b413-a60e4de4b639.png)
> 
> ![image_471](https://user-images.githubusercontent.com/84619641/152633581-1fa274ea-decd-4bb1-87fd-9c89919d2be0.png)

Thanks for the info, in the next version all characters will show regardless of the selected font, so it should solve this issue.

**Comment by nutnutwin** [comment]
@adirh3 

Hi, thank you for dealing with this problem. 
On my OS I tried
> LXGW WenKai Mono
> Segoe (Default )
and CJK are properly displayed

✨One more small issue, I found that with both fonts, emojis are not properly displayed(shown as tofu)
I tried
✔️❌✨
(Please refer to the attachment
(Should I open an new issue for this? Really thank you for your work. 
<img width="252" alt="20220206_Sun -074528" src="https://user-images.githubusercontent.com/34512273/152661754-072c21e4-7a7b-4693-850f-358a9a418ee4.png">
<img width="263" alt="20220206_Sun -075147" src="https://user-images.githubusercontent.com/34512273/152661755-bd5fe520-8281-4ee3-8c83-c8e4e675dba3.png">
<img width="136" alt="20220206_Sun -075926" src="https://user-images.githubusercontent.com/34512273/152661780-301e0cb5-38fe-47af-9f66-30f765975f7b.png">

**Comment by adirh3** [comment]
@nutnutwin @hoshins can you please confirm whether all Chinese/Korean characters display correctly?

**Comment by nutnutwin** [comment]
@adirh3 Hi I cannot say All Chinese and Japanese characters work fine, 
but I have found no garbled characters, including emoji in my recent update to "0.9.91.30"

Thank you
