### ISSUE TITLE
Display File Indexer Status on FS Tray Icon

### ISSUE THREAD

**Issue by MakeshVineeth** [adirh3/Fluent-Search#149]
It would be awesome if FS can display the File Indexer status on the FS Tray Icon.

- Indexer finished and ready to search: **Green** dot on the tray icon.
- Indexing is in progress: **Yellow** dot on the tray icon.

Just like Offline/Online status in Messengers. This can especially help users who deal with a lot of external storage devices on daily basis. We can get an overall idea just by looking at Tray Icon and we can start using the File Search when it's ready.

**Comment by Metroid-Prime** [comment]
I love this idea and support it wholeheartedly!!  I have a question and a suggestion: 

Question:  how long does it take to index? It feels like FS does it within a few seconds.

Suggestion:
Indexer finished and ready to search: Green dot on the tray icon.
Indexing is in progress: Yellow dot on the tray icon.
Something went wrong with indexing (?):  Red dot on tray icon

**Comment by MakeshVineeth** [comment]
Yes FS takes a few seconds. But I guess that depends on amount of storage and number of files too. Would be awesome to have this status on tray icon 👌

**Comment by adirh3** [comment]
Due to system tray being limited (can't have tooltips, icon looks weird depending on screen DPI), I have built it into the search bar.
When Fluent Search is indexing, it will show a progress ring in the search bar with indication of which drives/paths it's currently indexing.
Closing, thanks :)
