### ISSUE TITLE
Plugins Auto-update

### ISSUE THREAD

**Issue by Metroid-Prime** [adirh3/Fluent-Search#15]
Allow user to auto-update plugins

**Comment by Nomad-0** [comment]
agree. Also, it'll be best to have the update menu on plugins of settings.

**Comment by mochigithub** [comment]
> agree. Also, it'll be best to have the update menu on plugins of settings.

Welcome @Nomad-0 !  I don't know what you mean by this.   
![image](https://user-images.githubusercontent.com/1836362/120913682-a7819180-c64d-11eb-88fe-3193f029f5f7.png)

**Comment by Nomad-0** [comment]
yes, that's what I meant

**Comment by adirh3** [comment]
The plugins auto updates now, forgot to update here

**Comment by Metroid-Prime** [comment]
yay, thank you Adir! Long been coming
