### ISSUE TITLE
A minimize button on Settings window

### ISSUE THREAD

**Issue by Nomad-0** [adirh3/Fluent-Search#150]
When I have FS as always on top, sometimes it's hard to do other things while keeping the settings open. I have to close the settings in this case. A minimize button on settings would be helpful for scenarios like this.

**Comment by MakeshVineeth** [comment]
Nice, it's essential to have a **Minimize** button for such windows. Here's my upvote 👍

**Comment by Metroid-Prime** [comment]
Can't believe we didn't think about this before. So much to do! 
Have my upvote.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.88.3

**Comment by Nomad-0** [comment]
closing as the enhancement is implemented.
