### ISSUE TITLE
Prioritization might not be working

### ISSUE THREAD

**Issue by Nomad-0** [adirh3/Fluent-Search#152]
**Describe the bug**
currently facing an issue that apps are below the file results though it is given more priority in settings.

**To Reproduce**
1. Set up prioritization for a result type
2. search for the result

**Expected behavior**
the most prioritized result should show at the top if the context is matched 

**Screenshots**
![image](https://user-images.githubusercontent.com/76395594/123028786-ccbe2000-d401-11eb-9069-6bc2362b7e52.png)
![image](https://user-images.githubusercontent.com/76395594/123028795-d182d400-d401-11eb-9f97-de99e21fa9cf.png)

**Desktop (please complete the following information):**
 - Windows 10 Version: [21H1]
 - Fluent Search Version [0.9.86.0]

**Comment by adirh3** [comment]
Should be fixed, closing
