### ISSUE TITLE
Search box cannot display Chinese

### ISSUE THREAD

**Issue by wxydejoy** [adirh3/Fluent-Search#153]
![Snipaste_2021-06-23_17-07-26](https://user-images.githubusercontent.com/81625961/123069634-8985a080-d445-11eb-9657-22a9919fbe76.png)
In addition, I would like to have a Chinese version

**Comment by wxydejoy** [comment]
In addition, I suggest that you can feedback suggestions in the software instead of the browser, which is more efficient

**Comment by Nomad-0** [comment]
adding it as duplicate as it seems similar to issue #148 . Please check and let me know if you disagree.

**Comment by Nomad-0** [comment]
currently closing the issue as it is the same as #148
