### ISSUE TITLE
Req. Drag and drop from preview window

### ISSUE THREAD

**Issue by christubuntu** [adirh3/Fluent-Search#154]
**Is your feature request related to a problem? Please describe.**
I would like a way to drag files/folders from the preview window

**Describe the solution you'd like**
Dragging a file/folder from the preview window onto another process (File Explorer, Website, etc.)

**Additional context**
I know I can simply open the containing folder and drag from Windows explorer, but I think doing so FS search preview is faster. Maybe tag this as a minor request/modification.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.76                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
