### ISSUE TITLE
[FR] Calculator plugin takes in standard characters like x for multiplication and so on

### ISSUE THREAD

**Issue by rsmyst** [adirh3/Fluent-Search#155]
Often time, when using fluent search for minor multiplications, I am forced to use symbols like * for multiplying values like in programming languages instead of the standard x which I use in the windows search bar and practically every other place.

The calculator plugin should automatically also consider values x to mean multiplication like every browser and search engines do. 
Example screenshot from edge chromium below.

![image](https://user-images.githubusercontent.com/30620767/123202812-fa689f00-d4bd-11eb-93de-782700770320.png)

**Comment by adirh3** [comment]
@rsmyst thanks for the feedback, this has been added a while ago, forgot to update here.
Closing, thanks!
