### ISSUE TITLE
Display Web icon for Bookmarks/History when a default icon is not available.

### ISSUE THREAD

**Issue by MakeshVineeth** [adirh3/Fluent-Search#156]
Sometimes, Icons won't be available for some bookmarks/history items. Either it is can be a browser issue or the website itself is no more. In such scenarios, FS will display a <img src="https://docs.microsoft.com/en-us/windows/uwp/design/style/images/segoe-mdl/e9ce.png" height="20" align="center"></img> icon like below:

![2021-06-24](https://user-images.githubusercontent.com/19371684/123203145-81744200-d4d3-11eb-8b83-4b483d5ac7cf.png)

It would look better if FS can show a Web/Globe icon instead.

**Comment by Metroid-Prime** [comment]
Is this a duplicate or related to issue  #74?

**Comment by MakeshVineeth** [comment]
I don't think so, the issue you've linked is a bug in FS itself whereas the issue I've proposed is an enhancement to existing default behavior. As @adirh3 has mentioned previously, Fluent Search will take those website icons from Browser itself, and when it's not available, it will show that <img src="https://docs.microsoft.com/en-us/windows/uwp/design/style/images/segoe-mdl/e9ce.png" height="20" align="center"></img> icon.

The screenshot I've shared: Issue is with my Browser itself, not with FS. In Vivaldi Browser, I have to use **Update Thumbnails** function in order to load all the icons. Also, there can many 404 pages too among those URLs. So proposal is to show a Web/Globe icon instead of <img src="https://docs.microsoft.com/en-us/windows/uwp/design/style/images/segoe-mdl/e9ce.png" height="20" align="center"></img> for neat look.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.88.78

**Comment by MakeshVineeth** [comment]
Confirmed the fix. Closing.
