### ISSUE TITLE
Tag description shouldn't show when Minimal User Interface is turned on

### ISSUE THREAD

**Issue by Mr-Frankenstein** [adirh3/Fluent-Search#157]
**Describe the bug**
 Tag description shouldn't show when Minimal User Interface is turned on.

**To Reproduce**
1. Search something
2. See Tag description

**Screenshots**
![image](https://user-images.githubusercontent.com/85425543/123210693-ff3e4a80-d4df-11eb-9dde-4a6a88875473.png)

**Desktop (please complete the following information):**
 - Windows 10 Version: 21H1
 - Fluent Search Version: 0.9.86.1

**Additional context**
If any users don't like this suggestion then the tag description text should be positioned on the right side where the settings icon was.
![image](https://user-images.githubusercontent.com/85425543/123210965-6a881c80-d4e0-11eb-9693-c752ad817427.png)

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.89.50
