### ISSUE TITLE
Web suggestions are not working

### ISSUE THREAD

**Issue by Mr-Frankenstein** [adirh3/Fluent-Search#158]
**Describe the bug**
My web search suggestions are not working but sometimes when I'm typing the last letter of a word it shows. It's not constant. 

**To Reproduce**
1. Use any web search tag.
2. Search something
3. See error

**Expected behavior**
Web suggestions should show.

**Screenshots**
![image](https://user-images.githubusercontent.com/85425543/123212148-09f9df00-d4e2-11eb-814d-9d3949be2db1.png)
https://user-images.githubusercontent.com/85425543/123308030-ce423200-d540-11eb-9f7d-fad1fbe8bcbd.mp4

**Desktop (please complete the following information):**
 - Windows 10 Version: 21H1
 - Fluent Search Version: 0.9.86.1

**Additional context**
No one else reported this on Discord I think. So this is maybe because of my settings.

**Comment by adirh3** [comment]
@Nomad-0 Can you reproduce it? @Mr-Frankenstein any chance is due to your internet?

**Comment by Nomad-0** [comment]
I tried, working fine in my end

**Comment by Mr-Frankenstein** [comment]
This issue is fixed on the latest version.

**Comment by adirh3** [comment]
Nothing changed but it can fail due to it using the internet
