### ISSUE TITLE
Occasional Lag spikes when using fluent search 

### ISSUE THREAD

**Issue by rsmyst** [adirh3/Fluent-Search#160]
I attend classes all morning. So, when I have something like google meet running in the background and use fluent search, the typing kinda skips over some letters. I mean that all letters appear but some letters don't pop up continuosly. It just appears suddenly with the next letter instead of appearing individually letter by letter if you get what I mean.

**Expected behavior**
No lag spikes

**Desktop (please complete the following information):**
 - Windows 10 Version: 20H1
 - Fluent Search Version: 0.9.86.0
 - Dual core CPU if that matters (i7-7500U)

**Comment by adirh3** [comment]
@rsmyst Can you check if using "Disable instant search" fixes the issue?
In Settings -> In-app search

**Comment by MakeshVineeth** [comment]
I must say even I'm facing this, but didn't report it earlier, as I thought that lag is because of my potato system 😅 Looks like disabling instant search made it bit better but not perfect.

**Comment by rsmyst** [comment]
> @rsmyst Can you check if using "Disable instant search" fixes the issue?
> In Settings -> In-app search

I attended a zoom session and tried fluent search and would like to confirm that, it does in fact still lag then. It misses up to 4-6 characters
Something else I noticed was soon after I restarted, I waited for FS to open and elevate to admin.
After that, I launched it with the shortcut but after typing around 30-40 characters in quick succession, it just crashed.

**Comment by rsmyst** [comment]
> I must say even I'm facing this, but didn't report it earlier, as I thought that lag is because of my potato system 😅 Looks like disabling instant search made it bit better but not perfect.

That didn't help me, unfortunately.. Maybe marginally...

**Comment by adirh3** [comment]
@rsmyst @MakeshVineeth can you check if disabling Settings -> Processes -> Search in app content helps?
Thanks

**Comment by adirh3** [comment]
> > @rsmyst @MakeshVineeth can you check if disabling Settings -> Processes -> Search in app content helps?
> > Thanks
> 
> I have tried this and can confirm it still doesn't seem to help. On a sidenote, my fans rev up massively when having a meeting + using fs search. Like a fan speed spike.
> I've done some digging around using task manager and found that
> 
> 1. My cpu runs at about 20% with a meeting running on average
> 2. Upon launching FS search and using, it spikes to 70-80% and then returns to around 35-40%

Upon launching Fluent Search for the first time or just opening it with default shortcut?

Also, I don't think the input delay issue is related to CPU spikes unless they're near the 100%, if Fluent Search causes CPU spikes when it's running in the background then something is wrong.

I will try checking with other users on Discord if any have similar issue and then we might find the root cause.

**Comment by rsmyst** [comment]
> Upon launching Fluent Search for the first time or just opening it with default shortcut?
> 
> Also, I don't think the input delay issue is related to CPU spikes unless they're near the 100%, if Fluent Search causes CPU spikes when it's running in the background then something is wrong.
> 
> I will try checking with other users on Discord if any have similar issue and then we might find the root cause.

Okay clarification. Opening it with shortcut and not for first time. It happens when opening it suddenly after a good amount of break since the last use of fluent search.
FS is not causing spikes while in Background. Only when using the shortcut and searching something.

**Comment by MakeshVineeth** [comment]
Disabling process search doesn't help me much with speed. But it looks like the lags are caused only when FS has to generate different set of results. When I search using a specific tag e.g. settings or chromium, it doesn't seem to lag for me. @rsmyst Can you confirm the same?

**Comment by rsmyst** [comment]
> Disabling process search doesn't help me much with speed. But it looks like the lags are caused only when FS has to generate different set of results. When I search using a specific tag e.g. settings or chromium, it doesn't seem to lag for me. @rsmyst Can you confirm the same?

Yea I think I noticed something similar as well. I had previously chalked it up to random stutters but maybe it's generating new results that causes it. A massive cpu spike for 2 seconds

**Comment by adirh3** [comment]
@rsmyst Let me know if you notice any improvements in 0.9.87.0

**Comment by MakeshVineeth** [comment]
I'm still facing that text lag when I'm typing too fast i.e., each letter will appear with a delay as mentioned in OP. Version 0.9.88.1

**Comment by adirh3** [comment]
> I'm still facing that text lag when I'm typing too fast i.e., each letter will appear with a delay as mentioned in OP. Using FS version 0.9.88.1

Can you check if this is related to a specific setting? 
Try disabling each search app and see if it changes anything.
Also, do you have adaptive color on?

**Comment by MakeshVineeth** [comment]
> > I'm still facing that text lag when I'm typing too fast i.e., each letter will appear with a delay as mentioned in OP. Using FS version 0.9.88.1
> 
> Can you check if this is related to a specific setting?
> Try disabling each search app and see if it changes anything.
> Also, do you have adaptive color on?

It seems like Files search is the one that's causing the text lag. After I disable it, and try to type fast, I no longer face that lag. Also, I don't have adaptive color on.

**Comment by rsmyst** [comment]
> @rsmyst Let me know if you notice any improvements in 0.9.87.0

It doesn't seem too much smoother to me personally even in this version

**Comment by rsmyst** [comment]
> > > I'm still facing that text lag when I'm typing too fast i.e., each letter will appear with a delay as mentioned in OP. Using FS version 0.9.88.1
> > 
> > 
> > Can you check if this is related to a specific setting?
> > Try disabling each search app and see if it changes anything.
> > Also, do you have adaptive color on?
> 
> It seems like Files search is the one that's causing the text lag. After I disable it, and try to type fast, I no longer face that lag. Also, I don't have adaptive color on.

too bad we can't disable file search since that's the point of the app... 
Good luck for fixing it! Take your time!

**Comment by adirh3** [comment]
@rsmyst @mv you guys have SSD or HDD?

**Comment by MakeshVineeth** [comment]
SSD

**Comment by rsmyst** [comment]
> @rsmyst @mv just wondering you guys have SSD or HDD?

512 gb SATA SSD

**Comment by MakeshVineeth** [comment]
@adirh3 Just now I faced something weird and thought I'd like to share. Looks like FS has caused massive CPU hikes. So much that rest of the system has become slower temporarily, even the typing has become slower in rest of the applications. This has happened to me twice today: Once when launching the FS for the first time, and once in the background. I did not check the Task Manager but I could tell because when I faced that lag, I immediately closed both **Discord App** and **FS**. Boom! All of a sudden, system and text typing speed came back to normal. I could hardly think if it is caused by Discord as I've been running that app since quite a long time 🤔

**Comment by adirh3** [comment]
> @adirh3 Just now I faced something weird and thought I'd like to share. Looks like FS has caused massive CPU hikes. So much that rest of the system has become slower temporarily, even the typing has become slower in rest of the applications. This has happened to me twice today: Once when launching the FS for the first time, and once in the background. I did not check the Task Manager but I could tell because when I faced that lag, I immediately closed both **Discord App** and **FS**. Boom! All of a sudden, system and text typing speed came back to normal. I could hardly think if it is caused by Discord as I've been running that app since quite a long time

It's due to In-app search try disabling it.
On startup it's slow and it's a known issue, it will improve over time.

**Comment by MakeshVineeth** [comment]
Facing the same text typing lag in 0.9.88.4; But I observed something: Setting the File Indexer to Windows Search seems to smoothen up the things a little bit.

**Comment by adirh3** [comment]
@MakeshVineeth @rsmyst Can you please try the following -

- Make sure Use GPU is enabled
- Make sure Adaptive Color is disabled
- Change the max search results to a small number (5-10)
- Change the search delay to High
- Rebuild index using Fluent Search
- Adding more directories to ignore in the File indexer and then rebuild index

After testing all the above, please let me know if any of them reduced lags, it will help me know the right direction for mitigating this issue.

**Comment by rsmyst** [comment]
> @MakeshVineeth @rsmyst Can you please try the following -
> 
> * Make sure Use GPU is enabled
> * Make sure Adaptive Color is disabled
> * Change the max search results to a small number (5-10)
> * Change the search delay to High
> * Rebuild index using Fluent Search
> * Adding more directories to ignore in the File indexer and then rebuild index
> 
> After testing all the above, please let me know if any of them reduced lags, it will help me know the right direction for mitigating this issue.

Update, I changed search delay to auto and the performance is much smoother over all. Changing it to anything other than that option causes massive lag spikes though. 
Keeping search delay to Auto also doesn't cause CPU spikes
