### ISSUE TITLE
I can't open it

### ISSUE THREAD

**Issue by scheduardo** [adirh3/Fluent-Search#161]
**Describe the bug**
It crashes on starting.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 10 Home Single Language 21H1
 - Fluent Search Version 0.9.86.0

**Additional context**
Nome do aplicativo com falha: FluentSearch.exe, versão: 0.9.86.0, carimbo de data/hora: 0x607f5cf5
Nome do módulo com falha: KERNELBASE.dll, versão: 10.0.19041.1081, carimbo de data/hora: 0xde3fc775
Código de exceção: 0xe0434352
Deslocamento da falha: 0x0000000000034ed9
ID do processo com falha: 0x17dc
Hora de início do aplicativo com falha: 0x01d768f1152ff616
Caminho do aplicativo com falha: C:\Program Files\Fluent Search\FluentSearch.exe
Caminho do módulo com falha: C:\WINDOWS\System32\KERNELBASE.dll
ID do Relatório: 251fc68b-f127-4479-8df6-e28ff583d2b2
Nome completo do pacote com falha: 
ID do aplicativo relativo ao pacote com falha: 

![fs-error](https://user-images.githubusercontent.com/19599264/123260695-3dca0a00-d4cc-11eb-9965-d67f7d3c0913.png)

**Comment by adirh3** [comment]
Thanks @scheduardo can you check if there is another event viewer entry please?

**Comment by scheduardo** [comment]
https://www.loom.com/share/f3dc10594cd448ff8708b2c548178e5b

**Comment by adirh3** [comment]
> https://www.loom.com/share/f3dc10594cd448ff8708b2c548178e5b

OK got it thanks, this is something that's something that is already fixed in the nightly version and will be available for all soon.

If you'd like you can install the nightly version from here, it's very stable -
https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by adirh3** [comment]
@scheduardo It's been fixed on the latest version, you can download from here - https://fluentsearch.net
Let me if it's working for you, thanks!

**Comment by adirh3** [comment]
Closing it feel free to reopen if it's still not working

**Comment by scheduardo** [comment]
It's working. Tks.

Em sáb., 26 de jun. de 2021 19:14, Lighto ***@***.***>
escreveu:
