### ISSUE TITLE
Operations Pane Closes on Mouse Over

### ISSUE THREAD

**Issue by HobbesKo** [adirh3/Fluent-Search#162]
**Describe the bug**
The operations pane closes when the mouse pointer enters the operations pane and goes below the first item

**To Reproduce**
1. Move mouse pointer into operations pane
2. Move pointer below the first item ('Open')

**Expected behavior**
Operations pane stays open to allow selection of an operation

**Desktop (please complete the following information):**
 - Windows 10 Pro Version: 10.0.19042
 - Fluent Search Version 0.9.86.1

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.88.1

**Comment by Nomad-0** [comment]
@HobbesKo can you please confirm if the issue is solved?

**Comment by HobbesKo** [comment]
Looking good my end. Nice one, thanks.

**Comment by adirh3** [comment]
> Looking good my end. Nice one, thanks.
> 
> Should I still be able to drag the left hand edge of the pane to be able to resize it?
> Resizing is no longer possible.

Yes it should be possible, working on my machine.
If it's not for you can reopen this, thanks :)
