### ISSUE TITLE
Opening Fluent Search opens a tiny transparent window 

### ISSUE THREAD

**Issue by tranquilknight** [adirh3/Fluent-Search#163]
**Describe the bug**
Opening the app creates a transparent window. Doesn't matter if it's from the tray or via the hotkey.

**To Reproduce**
It happened a couple of times randomly. I cannot pinpoint what triggered this, so I cannot reproduce it.

**Expected behavior**
I could not move or interact with the window. Clicking on it popped a thicker border at the top. This window stays above every other window.

**Screenshots**
![12](https://user-images.githubusercontent.com/10994511/123448384-7a931f80-d5f8-11eb-9a73-a954a5899d4c.PNG)
![11](https://user-images.githubusercontent.com/10994511/123448398-7e26a680-d5f8-11eb-8db7-51a5be3b3bca.PNG)

**Desktop (please complete the following information):**
 - Windows 10 Version: 21H1 19043.1081
 - Fluent Search Version: 0.9.86.0

**Comment by adirh3** [comment]
@tranquilknight Does it still happen? it should be fixed by the latest nightly version.

**Comment by tranquilknight** [comment]
I'm away from PC so not updated to latest nightly but I will try latest version as soon as possible and report if it's still there.

In a previous versoin (updated a couple of weeks ago), this exact issue hasn't happened recently. But there's something similar. Instead of a tiny transparent window there's a white acrylic regular size box with similar thin borders.

**Comment by adirh3** [comment]
> I'm away from PC so not updated to latest nightly but I will try latest version as soon as possible and report if it's still there.
> 
> In a previous versoin (updated a couple of weeks ago), this exact issue hasn't happened recently. But there's something similar. Instead of a tiny transparent window there's a white acrylic regular size box with similar thin borders.

Thanks! If you are able to reproduce it can you send me a process dump in PM?
