### ISSUE TITLE
Setting Categories should not be deselectable

### ISSUE THREAD

**Issue by hpr1999** [adirh3/Fluent-Search#164]
## Summary
In the settings UI, it's possible to deselect the current category in the tree view, resulting in a state where there's no indication which category we're looking at on the left.

**Low-Priority.**

## To reproduce
1. Open FS
2. Open Settings ("Appearance is now selected by default")
3. Click Appearance while it's still active (indicator in accent color).
4. Now Appearance is still open on the right half, but the indicator in the tree on the left is gone

## Expected behavior
You should only be able to click on categories other than the current one, since it lets the UI look slightly inconsistent.

### After 2) 
![image](https://user-images.githubusercontent.com/26067274/123477588-8c77c100-d5fe-11eb-964c-98e6432e81f3.png)

### After 3)
![image](https://user-images.githubusercontent.com/26067274/123477620-9a2d4680-d5fe-11eb-8926-177700a092b7.png)

### Windows
|Info|Value|
|-----|----|
| Edition| Windows 10 Home|
| Version | 21H1|
| OS build | 19043.1055|

### Fluent Search
- Version 0.9.86.0
- Installed via MS-Store

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.76                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by hpr1999** [comment]
Tested: Seems to work on my machine in the nightly 0.9.91.76. ✅
