### ISSUE TITLE
Settings-Search description disappears 

### ISSUE THREAD

**Issue by hpr1999** [adirh3/Fluent-Search#165]
## Summary
On a Settings-Search result, the description disappears when changing focus to the "action-area".

## To Reproduce
1. Open FS
2. Search for a Settings-Item, example query "go to next process"
3. Hit right arrow key
4. The description vanishes

## Expected behavior
The description should stay visible.

## Screenshots
After 2):
![image](https://user-images.githubusercontent.com/26067274/123478758-33109180-d600-11eb-8831-a717442e35e2.png)
After 3):
![image](https://user-images.githubusercontent.com/26067274/123479149-c649c700-d600-11eb-9db9-dfae8676f2d1.png)

### Windows
|Info|Value|
|-----|----|
| Edition| Windows 10 Home|
| Version | 21H1|
| OS build | 19043.1055|

### Fluent Search
- Version 0.9.86.0
- Installed via MS-Store

## Context
When changing focus, the description re-appears.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.88.1

**Comment by Nomad-0** [comment]
solved on my end, can you please validate? @hpr1999

**Comment by hpr1999** [comment]
I'll try to validate this evening.

**Comment by hpr1999** [comment]
I was a bit confused until switching to the nightly feed - can now confirm that this no longer occurs.
