### ISSUE TITLE
Option to disable screen search

### ISSUE THREAD

**Issue by rsmyst** [adirh3/Fluent-Search#166]
**Is your feature request related to a problem? Please describe.**
I would like for an option to disable the screen search to be implemented. I often time find myself opening the screen search accidentally and it gets annoying quickly. Thanks.

**Comment by Nomad-0** [comment]
Are you having trouble accidentally pressing the hotkeys? If that's the problem, you can just remove the hotkeys from settings>search applications>screen
![image](https://user-images.githubusercontent.com/76395594/123514246-c6ef6580-d6b3-11eb-9ed4-9447555a9fc2.png)
