### ISSUE TITLE
[0.9.88.0] Preview : images are scaled to fit the width causing them to be cropped 

### ISSUE THREAD

**Issue by cannibalox** [adirh3/Fluent-Search#169]
in 0.9.88.0, the native preview scales images so that their width is filling the FS window.
This behavior makes images to be cropped and/or appear pixelated (for small images)

related pic:
![image](https://user-images.githubusercontent.com/4605693/123530374-c5e12700-d6f9-11eb-9203-461565e129c2.png)

expected behavior : images should entirely fit inside the FS window by default, with an appropriate uniform scaling.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.88.1

**Comment by Nomad-0** [comment]
can you please validate? @cannibalox

**Comment by cannibalox** [comment]
fixed in 0.9.88.1
