### ISSUE TITLE
Chromium searches don't work

### ISSUE THREAD

**Issue by lucius346346** [adirh3/Fluent-Search#170]
Chromium searches don't seem to work for me at all. I've checked paths to both Chrome and Edge - they are correct.

 - Windows 10 Version: 20H1
 - Fluent Search Version 0.9.88.0 (same with previous version)

**Comment by hpr1999** [comment]
I think I used to have this issue when the profile I used wasn't Chromium's `Default` profile, but instead named something like "Profile 1" or whatever. Maybe you could add some information / screenshots of your Chromium paths and how the directories look so adir has a chance to check?

**Comment by lucius346346** [comment]
> I think I used to have this issue when the profile I used wasn't Chromium's `Default` profile, but instead named something like "Profile 1" or whatever. Maybe you could add some information / screenshots of your Chromium paths and how the directories look so adir has a chance to check?

It's C:\Users\lucius\AppData\Local\Microsoft\Edge\User Data\Default

I even clean installed Chrome, same result.

**Comment by adirh3** [comment]
> > I think I used to have this issue when the profile I used wasn't Chromium's `Default` profile, but instead named something like "Profile 1" or whatever. Maybe you could add some information / screenshots of your Chromium paths and how the directories look so adir has a chance to check?
> 
> It's C:\Users\lucius\AppData\Local\Microsoft\Edge\User Data\Default
> 
> I even clean installed Chrome, same result.

Might be asking the obvious, but are the Chromium app and configurations enabled? (Look for the enable application and in the Chromium apps paths table there is Enabled column)

**Comment by lucius346346** [comment]
These are settings I'm using.
![Screenshot](https://user-images.githubusercontent.com/43910504/123541483-1fbb0e80-d745-11eb-927f-a6528f68488b.png)

**Comment by adirh3** [comment]
@lucius346346 Do you have "Send crash diagnostic" on in Settings -> System? 
Also, can you check if it does not find anything when using either of the supported tags? `chromium` `history` `bookmarks`

**Comment by lucius346346** [comment]
> @lucius346346 Do you have "Send crash diagnostic" on in Settings -> System?
> Also, can you check if it does not find anything when using either of the supported tags? `chromium` `history` `bookmarks`

It was turned off. I switched it on.

These tags shows nothing, but strangely I've noticed bookmarks and history finds "git.exe" from Program Files after I type "git".

Also, I've installed FS on my work machine. It also doesn't work. Same version of Windows.

**Comment by lucius346346** [comment]
Update: It doesn't work on Windows 11 either. Maybe it's related to system locale?

**Comment by adirh3** [comment]
> Update: It doesn't work on Windows 11 either. Maybe it's related to system locale?

Interesting, can you ping me on Discord later today?

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.88.70

**Comment by adirh3** [comment]
Glad it's finally working :)
