### ISSUE TITLE
clicking on "restart computer" cmd crashes FS

### ISSUE THREAD

**Issue by christubuntu** [adirh3/Fluent-Search#171]
**Describe the bug**
Clicking on "restart computer" cmd crashes FS

**To Reproduce**
1. Open FS
2. Search for "restart computer"
3. Pin the result by clicking on it or doing Alt+P
4. FS crashes and disappears from the system tray. You have to launch FS again.

**Expected behavior**
The result should be pinned

**Screenshots**

https://user-images.githubusercontent.com/55885756/123540544-d4523180-d73f-11eb-906f-c8fa44795502.mov

**Desktop (please complete the following information):**
 - Windows 10 Version: [e.g. 20H1]
 - Fluent Search Version [e.g. 0.9.88.0]

Additional infos= doesn't happen for files/folders

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.88.1

**Comment by Nomad-0** [comment]
@christubuntu can you please confirm if the issue is solved?

**Comment by christubuntu** [comment]
Fixed
