### ISSUE TITLE
Scroll bar masking the pin result icon

### ISSUE THREAD

**Issue by christubuntu** [adirh3/Fluent-Search#172]
**Describe the bug**
Pin result icon and scroll bar are too close together, making pinning results a little hard

**To Reproduce**
1. Open FS and input search keyword
2. Hover the mouse over the pin icon (go from right to left)
4. The scroll bar makes it hard to click on the pin icon

**Expected behavior**
The pin icon should be offset a little to the left

**Screenshots**

https://user-images.githubusercontent.com/55885756/123540700-9e617d00-d740-11eb-9f1f-85a2c079e669.mov

**Desktop (please complete the following information):**
 - Windows 10 Version: [e.g. 20H1]
 - Fluent Search Version [e.g. 0.9.88.0]

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.88.1

**Comment by Nomad-0** [comment]
@christubuntu can you please confirm if the issue is solved?

**Comment by christubuntu** [comment]
Fixed
