### ISSUE TITLE
Windows 7 support?

### ISSUE THREAD

**Issue by tomasts248** [adirh3/Fluent-Search#173]
Do note that running portable version in W7 may cause the process to replicate till eventually crashing Windows, well I managed to terminate all process with ProcessHacker before that happened. If no support for Windows 7 is planned/added at least there should be a warning and the program should terminate itself instead.

**Comment by adirh3** [comment]
@tomasts248 
Sorry about the inconvenience, I will change it to not run in-case the OS version is not supported.
Support for Windows 7 got broken a few versions ago, I might bring it back if enough people will be interested in that.

**Comment by tomasts248** [comment]
Well I'm definitively interested and hope more people are as well, question may I download and older version then to try it out? which one should run on W7? I just find out about your app recently, been using Everything portable but as I read it has integration with it, which is great.

**Comment by adirh3** [comment]
> Well I'm definitively interested and hope more people are as well, question may I download and older version then to try it out? which one should run on W7? I just find out about your app recently, been using Everything portable but as I read it has integration with it, which is great.

I don't think I even got that version saved; I will see tomorrow if there is a quick way to make it work on Windows 7 again.
Note that even if it will run on Windows 7 it will miss some features that uses Win10 APIs.

**Comment by tomasts248** [comment]
Okey! thank you  ;-)

> Note that even if it will run on Windows 7 it will miss some features that uses Win10 APIs.

Which features may that be? more or less?

**Comment by adirh3** [comment]
@tomasts248 
I have been trying for a few hours, but unfortunately it seems that will require more work, probably days to create a different version that can run on non-Windows 10/11.
This is mainly because I am using many frameworks built only for Windows 10 by Microsoft.

Sorry, but since there are more critical bugs to fix, this is not prioritized unless I see more users with this requirement.

**Comment by Metroid-Prime** [comment]
7 > 8 > 10 > 11

We're about 4 versions behind with Windows 7, which was released in 2009!  Even Apple who is legendary for supporting old systems typically retires support for system software that old.    I don't see an easy fix to this as the frameworks are windows 10 based. 

@tomasts248   I am closing it. If you have any comments or feel strongly, feel free to reopen.
