### ISSUE TITLE
Quicklook Preview : doesn't auto update on file change

### ISSUE THREAD

**Issue by cannibalox** [adirh3/Fluent-Search#176]
**Describe the bug**
If the File Preview provider is set to Quicklook, when I invoke the preview windows (shift+enter or shift+space in my case), then use arrow u/d to select another file in the main FS window, the Quicklook preview doesn't show the newly selected file, it displays the first image that was selected. 

the preview auto-updates to show the selected file when the File Preview Provider is set to `FluentSearch`.

This happens with 0.9.88.0 and 0.9.88.1 win10 1809 ltsc.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.76                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by adirh3** [comment]
@cannibalox can you please have a look at the open preview issues? this and #200
Audio preview will be improved as your suggestions in Discord soon as well

**Comment by cannibalox** [comment]
@adirh3 sry for the late reply: yes the image preview can now auto switch to the selected image from the file list (both with QuickLook and Fluent as preview providers).

there is a small qol issue : . with quicklook as the preview provider, the preview window doesn't persist its location : 
* if I move the preview window, it will keep its location when switching from images to images as long as the next file can be previewed
* as soon as the selected file is a format that can't be previewed, then the location of the preview window will reset to the default location (? not sure about that)
