### ISSUE TITLE
App icons in results are too small

### ISSUE THREAD

**Issue by lucius346346** [adirh3/Fluent-Search#177]
Most app icons appear to be too smal. They are rendered as tiny dots.

![Screenshot_1](https://user-images.githubusercontent.com/43910504/123608688-42116280-d7ff-11eb-82af-b4c89eff0283.png)

**Comment by Nomad-0** [comment]
issue confirmed. I guess it's related to software located on program files x86 folder

**Comment by adirh3** [comment]
@lucius346346 Does it not look like that in Explorer?

**Comment by lucius346346** [comment]
It seems that they look OK till medium setting in Explorer. They have this margin around them after that.
![Screenshot_1](https://user-images.githubusercontent.com/43910504/123913068-15d02000-d97e-11eb-9b0b-2a7c8853404b.png)
![Screenshot_2](https://user-images.githubusercontent.com/43910504/123913072-1668b680-d97e-11eb-8c51-0a74e1c3be8d.png)
![Screenshot_3](https://user-images.githubusercontent.com/43910504/123913073-17014d00-d97e-11eb-93f8-3fd1d702e081.png)
![Screenshot_4](https://user-images.githubusercontent.com/43910504/123913074-17014d00-d97e-11eb-9a5a-16943dc04763.png)

**Comment by adirh3** [comment]
@lucius346346 How does it show in the start menu?
Seems like this app developer made weird 256x256 icon, I can change all icons to 128x128 but then they all lose quality

**Comment by lucius346346** [comment]
It looks normal. Also in other apps like Wox. Shouldn't FW retrieve icon at whatever size it currently need? It seems this program has multiple icons 16x16, 32,32 and so on inside exetuable.

**Comment by Metroid-Prime** [comment]
Experiencing same issue

![image](https://user-images.githubusercontent.com/1836362/149093271-61f5f71b-8bf8-4aaf-98fd-9c5c87bb9281.png)

**Comment by adirh3** [comment]
You can now change icon size (resolution) in Settings -> Search -> Icon resolution.
Setting it to `Low` will achieve same result as other launchers (Wox, Listary, etc.), which is 64x64 resolution
