### ISSUE TITLE
Results are invisible on list

### ISSUE THREAD

**Issue by Nomad-0** [adirh3/Fluent-Search#178]
**Describe the bug**
Sometimes the results don't appear on the result list. However, they are there as arrow keys can be moved and they are shown on the operations pane. It's not consistent but reporducable
![image](https://user-images.githubusercontent.com/76395594/123629424-18bff900-d836-11eb-84e5-dafef2942a2f.png)

**To Reproduce**
It's not constant. Simply searching causes it some times

**Expected behavior**
The results should show on the list

**Desktop (please complete the following information):**
 - Windows 10 Version: [21H1]
 - Fluent Search Version [0.9.88.1]

**Comment by Mr-Frankenstein** [comment]
It happens to me too

**Comment by lucius346346** [comment]
In my case it happens only when grouping option is enabled.

**Comment by HobbesKo** [comment]
I have this issue also.
Mouse over the operations pane shows the 'missing' results.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.88.3
