### ISSUE TITLE
The Unpin action doesn't highlight 

### ISSUE THREAD

**Issue by Mr-Frankenstein** [adirh3/Fluent-Search#180]
**Describe the bug**
The Unpin in the home screen doesn't high like the other shortcuts.

**To Reproduce**
1. Pin a result to the home screen 
2. Right-click on the result
3. Hover mouse over the Unpin action

**Expected behavior**
Unpin should highlight like the others

**Screenshots**
https://user-images.githubusercontent.com/85425543/123670273-a8779e80-d85a-11eb-8625-e3ed14be3177.mp4

**Desktop (please complete the following information):**
 - Windows 10 Version: 21H1
 - Fluent Search Version: 0.9.88.1

**Comment by adirh3** [comment]
This is fixed, forgot to add to changelogs.
