### ISSUE TITLE
Jump to last-focused folder directory if a windows folder/file-selection dialogue is open

### ISSUE THREAD

**Issue by Gremious** [adirh3/Fluent-Search#182]
**Is your feature request related to a problem? Please describe.**

Listary hijacks a select window dialogue a bit - when you click things like "save image" or "open file" in whatever app, and the generic Windows file/folder selection dialogue opens - if you focus a currently open explorer folder (e.g. alt-tab to it), then switch focus back to the dialogue, Listary automatically changes the dialogue to that directory.

This is something that I actually use _a lot_. 90% of the time when I want to save a file (or more often - select an install location for software) I already have the folder I want open, or, I use Listary to open it by searching a single word. I do not know if this is within the scope of this app, but I would absolutely love to see it Implemented, and it is, to my knowledge, one of only 3 featres Listary has over Fluent Search.

**Describe the solution you'd like**

I would like Fluent Search to, on-focus, change the windows folder/file selection dialogue to the last-focused explorer window, if focused while the dialogue is open.

**Describe alternatives you've considered**

Running Listary and Fluent-Search together - doesn't feel right to have to file searchers on the same system runing and indexing things simultaneously, especially if I'm not using one of them for searching.

**Additional context**

Video example of listary: 
https://imgur.com/a/gCTomAR
(Note that clicking the folder was actually unnecessary and you can just alt-tab twice and it'd do it)

**Comment by Nomad-0** [comment]
Hello, can you please go to settings>advanced>context and toggle the "**copy context to file dialogs**" on and see if that fulfills your need?

**Comment by Gremious** [comment]
It does! This is exactly the functionality I was looking for
My appologies for not scouring the settings hard enough (=
