### ISSUE TITLE
Some settings revert back to defaults after a reboot

### ISSUE THREAD

**Issue by tranquilknight** [adirh3/Fluent-Search#186]
**Describe the bug**
After the recent app update (0.9.86 >0.9.87.1) from Microsoft Store. Some settings are reverting to defaults after a reboot. Closing the app does not affect these settings.

**To Reproduce**
Change hotkeys and, the option to start minimized at startup. These options revert to their original values.

**Expected behavior**
Changed settings should not revert after a reboot.

**Desktop (please complete the following information):**
 - Windows 10 Version: 21H1 19043.1081
 - Fluent Search Version: 0.9.87.1

**Comment by adirh3** [comment]
@MrparM does it happen for you when you close FS safely using the system tray icon?

I fixed a similar issue in `0.9.88.1` which is a nightly version.
If you'd like you can check it by using the portable/exe version (it won't interfere with the Store version)

**Comment by MrparM** [comment]
> 
> 
> @MrparM does it happen for you when you close FS safely using the system tray icon?
> 

No. It does not happen after closing from system tray. Only a reboot affected settings.

**Comment by adirh3** [comment]
> > @MrparM does it happen for you when you close FS safely using the system tray icon?
> 
> No. It does not happen after closing from system tray. Only a reboot affected settings.

When you reboot, do you force apps to close?
Fluent Search needs to close safely to save settings right now.

In the next version I changed it to save settings automatically when you change them.

**Comment by MrparM** [comment]
> When you reboot, do you force apps to close?

Not really. Sometimes it is Steam, other than that there isn't anything.

**Comment by adirh3** [comment]
> > When you reboot, do you force apps to close?
> 
> Not really. Sometimes it is Steam, other than that there isn't anything.

Ok thanks for the input, this will be improved in the next version.

**Comment by adirh3** [comment]
@tranquilknight Did it happen again after recent updates? Should be fixed after >= 0.9.90

**Comment by tranquilknight** [comment]
No, I don't think it has happened again. I switched to portable version a while ago. It's been fine so far. I'll try to change some things and observe for a few days. 

Unrelated – updating the portable version requires manual killing of the Fluent Search service. Maybe a prompt to kill the service would be a bit better for the end user.

**Comment by adirh3** [comment]
> No, I don't think it has happened again. I switched to portable version a while ago. It's been fine so far. I'll try to change some things and observe for a few days.
> 
> Unrelated – updating the portable version requires manual killing of the Fluent Search service. Maybe a prompt to kill the service would be a bit better for the end user.

It should kill it automatically after 0.9.90, from which version did you update?

**Comment by tranquilknight** [comment]
> 

I'm not sure about the stable version I'm using on my main account. On another account, updating Nightly has gone successfully once. Recently, installation of 0.9.91.33 failed, and I had to overwrite it manually. I think it kills the main process but does not kill file indexer service.

**Comment by tranquilknight** [comment]
> @tranquilknight Did it happen again after recent updates? Should be fixed after >= 0.9.90

I tried to check this over a few days by changing a couple of settings. It's fixed!

**Comment by adirh3** [comment]
> > @tranquilknight Did it happen again after recent updates? Should be fixed after >= 0.9.90
> 
> I tried to check this over a few days by changing a couple of settings. It's fixed!

Thanks for checking! If you still have issues with portable update please create a new issue
