### ISSUE TITLE
Window Startup Position - Settings Window Not Behaving

### ISSUE THREAD

**Issue by HobbesKo** [adirh3/Fluent-Search#187]
**Describe the bug**
Setting Window startup position to 'Last position' has the settings window open on the left of the screen, which is not where it last was.

**To Reproduce**
1. Set window startup position to 'Last position'
2. Open settings

**Expected behavior**
The settings window opens in the position it was last at.

**Desktop (please complete the following information):**
 - Microsoft Windows 10 Pro 10.0.19042 Build 19042
 - Fluent Search Version 09.88.1

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 1.0.0.11                                          . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
