### ISSUE TITLE
issue with folder previews (fixed number of columns instead of reflow)

### ISSUE THREAD

**Issue by cannibalox** [adirh3/Fluent-Search#189]
the folder preview should reflow instead of having a fixed max number of columns (go from 5 to 1 column) ? 

![20210629_NUC8_zbyslEEnTN](https://user-images.githubusercontent.com/4605693/123813196-fe008980-d8f4-11eb-8342-204b8db3f244.gif)

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.88.2

**Comment by cannibalox** [comment]
thank you for the fix !
