### ISSUE TITLE
Fluent Search UI glitches occasionally

### ISSUE THREAD

**Issue by MakeshVineeth** [adirh3/Fluent-Search#190]
**Describe the bug**
The screenshots says it all. The UI glitches in a weird manner. Even though it happens randomly, I faced it quite a number of times. Feel free to change the title of this issue to a suitable one, right now, I can't think of any suitable title.

**Probable Steps to Reproduce**
1. Make sure `Always clear search tags` option is **disabled**.
2. Enable `Hide when losing focus` and `Reset search when opening` options.
3. Type some really long random line into the search bar and click on somewhere else on Desktop to hide the FS.
4. Launch FS again, check if your searched text reappears and thus by not respecting the `Reset search when opening` option.
5. Try to delete that text by pressing `Ctrl + A` and `Delete` on the Keyboard.
6. See the glitch.

**Expected behavior**
It should not glitch the FS window.

**Screenshots**
![2021-06-29 (1)](https://user-images.githubusercontent.com/19371684/123822682-22bb2800-d91a-11eb-82d6-b78307c10f30.png)
![2021-06-29](https://user-images.githubusercontent.com/19371684/123822687-2484eb80-d91a-11eb-871c-1b3ad3dcb6f9.png)

**Desktop (please complete the following information):**
 - Windows 10 Version: 21H1
 - Fluent Search Version: 0.9.88.1

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.88.3

**Comment by MakeshVineeth** [comment]
Confirming the fix. Closing.

**Comment by MakeshVineeth** [comment]
Again facing some random UI glitches like this:

![image](https://user-images.githubusercontent.com/19371684/125791452-66d2a54c-5f06-4129-8fab-43061d9ca7ad.png)

**Comment by MakeshVineeth** [comment]
Probable Steps to Reproduce:

- Make sure Search UI is filled with content i.e., search tag, searched text and results.
- Open Settings from Icon available on FS Search window.
- Toggle some random settings like `Search tag only` for any plugin/search application.
- Go back to Search UI, it should glitch.

**Comment by MakeshVineeth** [comment]
Another probable steps to reproduce these UI glitches:

- Be on Home Screen.
- Go to Settings from Home Screen.
- Change `Accent color` to anything random.
- Go back to Home Screen, then it should have the same glitch.

**Comment by MakeshVineeth** [comment]
Not facing lately, closing atm.
