### ISSUE TITLE
Max Search Results should not work on tags

### ISSUE THREAD

**Issue by Najah101** [adirh3/Fluent-Search#191]
Max Search Results should not work when using a tag. I use group results, so I set my Max Search Results to 5 because if I don't the search results will get so cluttered. But when I use a tag there is a lot of empty space because of that.

![image](https://user-images.githubusercontent.com/85425543/123844711-f959c680-d930-11eb-8288-43fbb4e873b4.png)

I think this will be useful for people who use Group Search Results.

Feel free to change the issue to a more understanding one.

**Comment by adirh3** [comment]
Thanks for the feedback, I think that having a different setting for max search results based on search will only confuse users.
Closing
