### ISSUE TITLE
0.9.88.2 in preview mode, it's not possible to go up a folder with `backspace`

### ISSUE THREAD

**Issue by cannibalox** [adirh3/Fluent-Search#193]
**Describe the bug**
in preview mode, it's not possible to go up a folder with the keyboard, `backspace` takes me back to the `search input box`

win10 logseq 0.9.88.2

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.88.75

**Comment by cannibalox** [comment]
thank you  for the fix
