### ISSUE TITLE
Ability to Switch System Theme right within Fluent Search

### ISSUE THREAD

**Issue by MakeshVineeth** [adirh3/Fluent-Search#195]
Whenever we wanted to change the theme of Windows OS to Light/Dark Theme, we have to go all the way to System Settings > Personalization > Colors > Choose Theme from Drop Down Menu. That is a long way to just change a system theme. Instead, I would really like to have a shortcut `Switch System Theme` right within Fluent Search that changes the theme in few steps. Pressing Enter on that result should switch the theme between Light/Dark, it can also have a toggle in the Right Panel if needed, but I feel pressing Enter is much faster.

**Comment by adirh3** [comment]
@MakeshVineeth develop a plugin for it, it's should be relatively easy

**Comment by MakeshVineeth** [comment]
> @MakeshVineeth develop a plugin for it, it's should be relatively easy 

Since it is a single shortcut, isn't it better to embed it in FS instead of having a separate plugin? 

Because I felt changing setting something like System Theme is really common.

**Comment by Nomad-0** [comment]
I think having it in built-in commands would be really great

**Comment by adirh3** [comment]
@MakeshVineeth @Nomad-0 see the Task I shared on Discord, it lets you do exactly that.

**Comment by MakeshVineeth** [comment]
The original suggestion was to have it built-in instead of having a separate plugin or task, but the task would suffice the needs for now.
