### ISSUE TITLE
Pinned results navigation error

### ISSUE THREAD

**Issue by Mr-Frankenstein** [adirh3/Fluent-Search#196]
**Describe the bug**
I have to press the right arrow key two times to go from the **first pinned result** to the **second one**

**To Reproduce**
1. Pin two results on the home screen
2. Trigger FS
3. Press the _down arrow key_
4. navigate to the **second pinned result** using the _right arrow_
5. see the error

**Expected behavior**
I should be able to navigate to the **second pinned** result with 1 press

**Desktop (please complete the following information):**
 - Windows 10 Version: 20H1
 - Fluent Search Version 0.9.88.2

**Comment by Nomad-0** [comment]
@Mr-Frankenstein this issue is seemed to be solved, please check and close if it is.

**Comment by Mr-Frankenstein** [comment]
> @Mr-Frankenstein this issue is seemed to be solved, please check and close if it is.

This issue is fixed. You can close it now
