### ISSUE TITLE
An option to stop FS automatically if OS version is not supported

### ISSUE THREAD

**Issue by Femtometer** [adirh3/Fluent-Search#198]
**Describe the bug**
When I run it, CPU usage increase to 100%.

![截屏_2021-07-02_09-07-29](https://user-images.githubusercontent.com/5461891/124209915-0fc47580-db1d-11eb-8af0-c989ae885922.png)

**Sorry, I didn't see that "Windows7 Not Supported". Please close this issue.**

**Comment by Femtometer** [comment]
Would be better if it can verify the os version then stop when not supported.

**Comment by Metroid-Prime** [comment]
At the very least a very obvious warning on first startup saying Windows 7 is not supported and will not work properly.

I don't think we should stop people from using it just because they're on a specific system.

**Comment by Nomad-0** [comment]
Actually, FS lost the compatibility with Windows 7 after the implementation of some new features, thus, we added it on the front page of GitHub that FS no longer supports Windows 7. (The compatibility might come back in the future if enough users want it) (#173) 

However, **Adir is working on FS not to run at all if the OS version is not supported**. I'd like to close the issue after the implementation of this (unless others disagree, of course).

**Comment by adirh3** [comment]
The issue when Fluent Search restarted itself many times is fixed. 
Added documentations both in GitHub and website that only Windows 10 and 11 are supported.

Closing, thanks!
