### ISSUE TITLE
preview window (fluent native) steals focus form the search bar

### ISSUE THREAD

**Issue by cannibalox** [adirh3/Fluent-Search#199]
**Describe the bug**
the preview window (fluent) is now stealing focus and in case it opens on a text file or binary, it will be in edit mode... I need to `alt tab` my way back to the search bar (or use the mouse)
if `preview > open with the search window` is on, that makes it very cumbersome to use FS : 
 * one can inadvertently input text in the prevew area instead of making a search due to the wrong window being in focus
 * on first launch; the name of the previewed file is not displayed so it can be arror-prone, see pic below : (Feature Request : add the name of the current file in the prevew window (either in the bottom margin or as a tiny text overlay in the lower left corner)
![image](https://user-images.githubusercontent.com/4605693/124264642-0810cb00-db35-11eb-98d8-321773f3d281.png)

win10 1809 + FS 0.9.88.3 portable

**Comment by adirh3** [comment]
@cannibalox does it still happen on latest nightly?

**Comment by cannibalox** [comment]
yes, mostly the same issue with extra info : 
## using 0.9.90.993, file preview provider : fluent search
- the preview window steals focus : I can't continue to type on the main FS window, I need to `esc` to close the preview  or use the mouse to refocus the main window
- I've lost the ability preview text files. no preview window appear at all... even the 'internal' preview pane is empty for .txt or .md files (but at least we edit text files by mistake now.... :) )
![image](https://user-images.githubusercontent.com/4605693/150049284-6c40177e-975c-4b0f-9cf5-04c961ca9568.png)
- the preview window doesn't auto start even though `open with the search window` is ON 
- the preview window never stays open even though `keep open` is ON, the pin icon also doesn't work. As soon as I select another file by going back to the main search window, the preview closes itself.


## using quicklook as file preview provider :
- everything works ok, it opens automatically with the search window, it stays opened, it can preview text files, it does  **not** steal focus
- one issue though : the quicklook preview always opens at the center on first start, behind my main search window. So I need to move it out of the way manually (thus, losing focus from search) 
- and no text preview in the **native preview pane** of the main search window either but that's to be expected I guess.

**Comment by cannibalox** [comment]
related : 
https://github.com/adirh3/Fluent-Search/issues/243 https://github.com/adirh3/Fluent-Search/issues/243
https://github.com/adirh3/Fluent-Search/issues/459 Preview Window steals focus at every keystroke
https://github.com/adirh3/Fluent-Search/issues/467 Text preview is gone

**Comment by adirh3** [comment]
@cannibalox thank you for all the information, it's much appreciated!

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.994

**Comment by cannibalox** [comment]
nice job ! preview auto-opens, does not steal focus anymore and can remain on top, saves its location. 
text preview is also back and working ! (btw is there a way to tweak the default colors for syntax highlighting ?

closing, thank you for the fix !

**Comment by Metroid-Prime** [comment]
Closing this ticket @cannibalox 

For your question "(btw is there a way to tweak the default colors for syntax highlighting ?" please either post a question in Discord or post a question in Github
