### ISSUE TITLE
***GITHUB SITE REQ*** Add RSS functionality to FS Github page

### ISSUE THREAD

**Issue by Metroid-Prime** [adirh3/Fluent-Search#2]
Title says it all,
Please add RSS functionality to the FS Github page so those of us who use RSS heavily can easily track new issues and the ones we reported.

**Comment by mochigithub** [comment]
I have a workaround for this.  I created an email using Inoreader's Pro plan and all of Github's emails are routed there.  Boom, instant notifications of updates to issues :)

**Comment by Nomad-0** [comment]
yeah, but maybe not close the issue. As others might need this option

**Comment by mochigithub** [comment]
Agreed. Not sure how much work it is, but I think it would still be beneficial.   

Just an FYI for everyone -- one can have Github send notifications by email if that's acceptable for you.

**Comment by Metroid-Prime** [comment]
@Nomad-0 @adirh3 
I hope it's OK but I feel this should be closed. RSS works for email and it's not worth polluting FS's github with this minor request.

For those of you who want RSS w/ github - you can achieve this with Inoreader Pro
