### ISSUE TITLE
[preview window] (Quicklook) : will not auto close with FS, will not remember previous position

### ISSUE THREAD

**Issue by cannibalox** [adirh3/Fluent-Search#200]
**Describe the bug**
0.9.88.3 portable  : 
preview / quicklook will not auto close with FS and `open at center: off` is not  working (preview/quicklook is always at the center)

**Repro**
`preview > open with search : on` and `open at center : off` 
* press `alt ctrl` to invoke fs + preview : 
     * search bar opens, preview opens in the center , diregarding `open at center : off` 
* press `alt ctrl` again to close FS : the fs search bar closes but the preview is still displayed
* press `alt ctrl` a third time : FS appears and the preview window closes

**Comment by adirh3** [comment]
@cannibalox There is no way currently to control QuickLook in any way AFAIK, it's API is only "Open {path}"

**Comment by cannibalox** [comment]
but the behavior has changed in latest versions. 
in former fluent, when the quicklook preview opened, it didn't steal the focus and it used to close with the main fs window.
Now it closes on the second shortcut.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.76                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by cannibalox** [comment]
* it's mostly working, but not consistently : the quicklook preview auto-closes with esc or ctrl+alt but it sometimes doesn't auto-close, I can't consistently repro why... I just browse the file list with the quicklook preview, then close FS (tries both with `esc` and `ctrl alt` and sometimes the preview window will remain opened once the FS window is closed (Preview>Interactions>Keep Open is `OFF`)
 with quicklook as the preview provider, the preview window doesn't persist its location :

* also about the preview window location: if I move the preview window, it will keep its location when switching from images to images **as long as the next file can be previewed**, but as soon as the selected file is a format that **can't be** previewed, it seems the location of the preview window will reset to the default location (? not sure about that) for all subsequent previews (then I have to move the preview window, etc)
* when the Quicklook preview window is auto-resized to fit a new file preview, it seems the center of the resize is based on the right border (meaning the right side of the window is unchanged and the left side is moved to accomodate the new width), this behavior can create overlapping with the main FS window when the Quicklook preview if on the right side of the FS window.

**Comment by adirh3** [comment]
> * it's mostly working, but not consistently : the quicklook preview auto-closes with esc or ctrl+alt but it sometimes doesn't auto-close, I can't consistently repro why... I just browse the file list with the quicklook preview, then close FS (tries both with `esc` and `ctrl alt` and sometimes the preview window will remain opened once the FS window is closed (Preview>Interactions>Keep Open is `OFF`)
>   with quicklook as the preview provider, the preview window doesn't persist its location :
> * also about the preview window location: if I move the preview window, it will keep its location when switching from images to images **as long as the next file can be previewed**, but as soon as the selected file is a format that **can't be** previewed, it seems the location of the preview window will reset to the default location (? not sure about that) for all subsequent previews (then I have to move the preview window, etc)
> * when the Quicklook preview window is auto-resized to fit a new file preview, it seems the center of the resize is based on the right border (meaning the right side of the window is unchanged and the left side is moved to accomodate the new width), this behavior can create overlapping with the main FS window when the Quicklook preview if on the right side of the FS window.

Thanks for the detailed feedback!

Currently QuickLook itself does not support anything other than just opening it, so it's a bit problematic. 
When trying to move the window from FS, I can't know the preview size until it's fully opened and then you will see the window moves in delay, which from my testing is quite annoying.

I might try create a PR to add support for more capabilities, but it won't happen anytime soon (sorry).

**Comment by cannibalox** [comment]
I mostly use the fluent preview nowadays, so it's not a show stopper by any means :) thank you for all the improvements on FS. 
should I leave this issue open for future tracking ?

**Comment by adirh3** [comment]
@cannibalox sorry for missing your comment. If you're still experiencing the QuickLook issue, please open a new issue.
I am having hard time tracking old issues (especially those in comments)
