### ISSUE TITLE
Can't open folder after first search when invoking FS on desktop

### ISSUE THREAD

**Issue by Chance92** [adirh3/Fluent-Search#201]
**Describe the bug**
Can't open folder after first search when invoking FS on desktop.

**To Reproduce**
1. Make sure you are on desktop;
2. Invoke FS, search for a folder and open it with Enter key;
3. Minimise the folder window, so that you are back to desktop;
4. Invoke FS, search for the same folder and open it with Enter key. Somehow the folder will stay minimised (bug1);
5. Make sure you are still on desktop, invoke FS, search for a different folder and open it;
6. The folder window will switch to the new folder, but still minimized (bug2);
7. Close the folder window, invoke FS, search for a different folder and try to open it. FS will fail to open the folder (bug3).

**Expected behavior**
FS should be able to open the folder and bring it to the front.

**Screenshots**
Nothing out of ordinary.

**Desktop (please complete the following information):**
 - Windows 10 Version: 21H1
 - Fluent Search Version 0.9.88.3 exe

**Additional context**
The issues seem to disappear if FS is not invoked on desktop.

**Comment by adirh3** [comment]
@Chance92 Thanks for the repro steps, much appreciated

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.88.4

**Comment by Chance92** [comment]
Thanks. I just checked with 0.9.88.4. It seems bug1 and bug2 are fixed, but bug3 remains. Besides, when I try to open a different folder, FS will switch the current folder window, regardless of minimisation, to the new folder, instead of opening a new window. Is this intended behaviour?

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.88.60

**Comment by Chance92** [comment]
Just tested with 0.9.88.60. It appears all three bugs are fixed. However, I found that if I open a folder with FS on desktop, minimise the window and open a different folder with FS, the minimised window will switch to the new folder. If I switch to a different process in-between, FS will open a different window for the second folder. Is this by design?

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.88.95

**Comment by Chance92** [comment]
The issues are fixed. Thanks!
