### ISSUE TITLE
FS crashes when couldn't find results

### ISSUE THREAD

**Issue by Chance92** [adirh3/Fluent-Search#204]
**Describe the bug**
FS would crash when the search term couldn't yield any results.

**To Reproduce**
Steps to reproduce the behaviour:
1. Invoke FS
2. Enter a search term that doesn't match anything on your computer, either meaningful words or something like adfybasefaiob
3. If FS couldn't find anything, it would crash after a few seconds.

**Expected behavior**
Not to crash.

**Screenshots**
![bug](https://user-images.githubusercontent.com/85488695/124369663-2fb38080-dc66-11eb-8a6e-3421dd07acae.gif)

**Desktop (please complete the following information):**
 - Windows 10 Version: 21H1
 - Fluent Search Version 0.9.88.4 exe

**Additional context**
This one is quite serious.

**Comment by adirh3** [comment]
@Chance92 I can't reproduce it, can you send me your settings in Discord?

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.88.75

**Comment by Chance92** [comment]
Thanks. I'll test it in the next few days.

**Comment by Chance92** [comment]
I think it is finally fixed. Thank you.
