### ISSUE TITLE
Hotkey gets lost on Reboot

### ISSUE THREAD

**Issue by meathrel** [adirh3/Fluent-Search#207]
**Describe the bug**
The hotkey on the files application gets lost after a reboot

**To Reproduce**
1. Set a shortcut key for the files application
2. Verify that the shortcut key works 
3. Reboot
4. Use shortcut key and it will not open file search
5. Reset in app and it will then work until next reboot.
 
**Expected behavior**
Shortcut is retained after reboot

**Desktop (please complete the following information):**
 - Windows 10 Version: 21H1
 - Fluent Search Version 0.9.88.4

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.88.60

**Comment by Nomad-0** [comment]
@meathrel can you please confirm and close the issue if solved?

**Comment by meathrel** [comment]
Confirm resolved, sorry it took me a while.
