### ISSUE TITLE
Mica effect is not consistent in Home Screen and Search Window

### ISSUE THREAD

**Issue by MakeshVineeth** [adirh3/Fluent-Search#209]
**Describe the bug**
Please take a look at the screenshot. The Mica effect is getting disappeared randomly while messing with FS Settings, even if it is nothing related to Appearance. However, this is happening only with Home Screen and Search window. Settings Window still has the Mica effect as shown in the 2nd screenshot.

**To Reproduce**
1. Enable Acrylic Blur and set Opacity to 75%
2. Verify if you can see the Mica effect on the Home Screen.
3. Now go back to Settings, and try to change some random settings like Max Search Results or any.
4. The Mica effect will now disappear on both Home Screen and Search Window.

**Expected behavior**
It should be consistent across all windows and changing other settings should not affect this.

**Screenshots**
![2021-07-07](https://user-images.githubusercontent.com/19371684/124743699-9ae9a500-df3b-11eb-9896-598f2b328632.png)
![2021-07-07 (1)](https://user-images.githubusercontent.com/19371684/124744122-0b90c180-df3c-11eb-8f66-9e5510fdf938.png)

**Desktop (please complete the following information):**
 - Windows 11 Version: 21H2 (Insiders Build 22000.51)
 - Fluent Search Version 0.9.88.5
 
**Additional Context**
When this happens, a restart is going to fix it but this is just a temporary solution because everytime we change some settings, we have to restart FS to get back the Mica effect.

**Comment by adirh3** [comment]
@MakeshVineeth when a window loses focus the Mica effect will disable, this is consistent with Microsoft Windows 11 guidelines

**Comment by MakeshVineeth** [comment]
> @MakeshVineeth when a window loses focus the Mica effect will disable, this is consistent with Microsoft Windows 11 guidelines 

Interesting. So if I opened Settings, the FS Search Window behind it is losing focus and thus disabling Mica effect. Am I right?

If that's the case, Mica effect should be back when FS Search is relaunched using the usual shortcut key right? Currently it's permanently disabling Mica effect until we restart the whole FS.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.88.60

**Comment by MakeshVineeth** [comment]
Still facing in the latest version 0.9.88.60

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.88.65

**Comment by MakeshVineeth** [comment]
Confirming the fix, closing.
