### ISSUE TITLE
Bug opening folders from the Pinned/Suggested screens

### ISSUE THREAD

**Issue by christubuntu** [adirh3/Fluent-Search#211]
**Describe the bug**
Opening folders in the pinned/suggested screens only works once. Opening the same folder for the second time doesn't work.

**To Reproduce**
1. Launch FS, Open any folder from the pinned/suggested screen
2. This is important. Close File Explorer
3. Open FS and open the same folder or any other folder from that pinned/suggested screen
4. Nothing happens.

**Expected behavior**
File Explorer should open. Notice that opening the same folder from the Windows Search works. To fix, I have to quit/reopen FS or reboot/sign out of Windows

**Screenshots**

https://user-images.githubusercontent.com/55885756/124917449-24f54480-dff4-11eb-804e-0f57fba043e9.mp4

**Desktop (please complete the following information):**
 - Windows 10 Version: [e.g. 20H1]
 - Fluent Search Version [e.g. 0.9.88.5]

**Additional context**

**Comment by adirh3** [comment]
Can't reproduce it, @Nomad-0 can you?

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.88.60

**Comment by Nomad-0** [comment]
> Can't reproduce it, @Nomad-0 can you?

I can't. works fine on my end

**Comment by christubuntu** [comment]
Fixed
