### ISSUE TITLE
Bug. "Open Directory" for files/folder in pinned/suggested pages always opens the "Video Library" Folder 

### ISSUE THREAD

**Issue by christubuntu** [adirh3/Fluent-Search#212]
**Describe the bug**
Whenever I try to open containing folder of any file/directory in the pinned/suggested screen, File explorer will open the Video Library Folder

**To Reproduce**
1. Right click any file/folder in the pinned/suggested page
2. Click on 'Open Directory"
3. File explorer will open the "Video library folder"

**Screenshots**

https://user-images.githubusercontent.com/55885756/125039612-f9776600-e096-11eb-9c6b-4a498a3373ee.mp4

**Desktop (please complete the following information):**
 - Windows 10 Version: [e.g. 20H1]
 - Fluent Search Version [e.g. 0.9.88.60]

**Additional context**
doing the same thing from FF search doesn't reproduce the bug. It might be related to a bug I had earlier that was fixed (https://github.com/adirh3/Fluent-Search/issues/211)

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.88.65

**Comment by christubuntu** [comment]
Fixed
