### ISSUE TITLE
Account-/Permission-Management

### ISSUE THREAD

**Issue by hpr1999** [adirh3/Fluent-Search#213]
**Is your feature request related to a problem? Please describe.**
With the introduction of OneDrive-based settings synchronization and MS-ToDo Search, there's now two external services requiring Login, both from Microsoft. This can make it somewhat unclear which permissions Fluent-Search currently has.
Also, this can lead to multiple Logins -  one on each feature's page.

**Describe the solution you'd like**
A special UI could be used to manage permissions acquired from different services, starting with the MS-integration.
A sketch:
![image](https://user-images.githubusercontent.com/26067274/125087405-bf28bb80-e0cc-11eb-8298-e547a107b35b.png)
When trying to enable ToDo, for example, the setting would be disabled and a hint would link to the settings page "Manage Online Services" (or "Manage Accounts" or "Manage Permissions").
There, users could transparently see and change what services the user has access to. Then, after confirming the change, only one Login will be necessary. (When disabling permissions, there should be some warning text which features will be disabled)

**Describe alternatives you've considered**
Another short term alternative could be clarifying that FS "has acquired permissions for [for example] Microsoft To-Do" on the settings page, instead of being "signed in to the Microsoft Account". That way, the different logins are better explained and it's more reasonable to be logged in to To-Do but not yet logged in to the settings synch.

**Additional context**
This UI could also serve as the basis for future permissions, in case other online services will be added.
Examples: GoogleDrive, other Search-Applications with Online-Features, etc.

**Comment by hpr1999** [comment]
**Note:** Adir already said that this is not going to be done anytime soon.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.76                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by hpr1999** [comment]
Hm if I'm reading the changelog correctly, the difference is that the login to Microsoft is now unified?
It changes this ticket, but still has some of the same (**minor**) problems:
- I don't exactly have an overview which permissions FS has (in fact I missed this when logging in and was quiet surprised I gave the ToDo permissions without realising)
- I can't separately grant the permissions anymore.

**Comment by adirh3** [comment]
> Hm if I'm reading the changelog correctly, the difference is that the login to Microsoft is now unified? It changes this ticket, but still has some of the same (**minor**) problems:
> 
> * I don't exactly have an overview which permissions FS has (in fact I missed this when logging in and was quiet surprised I gave the ToDo permissions without realising)
> * I can't separately  selectively grant the permissions anymore.

Yes, it's unified, all permissions are manageable per App in your Microsoft account, I don't think FS should manage it as well.
Also, before granting permissions it will tell you exactly which permissions FS requires (in the MS login window)
