### ISSUE TITLE
Alternative Navigation Controls

### ISSUE THREAD

**Issue by hpr1999** [adirh3/Fluent-Search#214]
**Is your feature request related to a problem? Please describe.**
For a keyboard centered application, FS still requires reaching over to the arrow keys regularly, which hampers efficiency.
Is there a possibility for a more efficient navigation scheme?

**Describe the solution you'd like**
I have no concrete design for an alternative navigation, however some pointers / ideas:
In keyboard-centric Linux-based applications, there is some popularity of respecting the vim-navigation scheme, in which it's possible to use H (<-) J (v) K (^) L (->) for navigation. This allows more efficient movement for touch-typists that already have their fingers resting on the so-called "home-row" of the keyboard. 

This would obviously require an additional modifier or toggle to switch between navigation and typing in the search bar.
If a toggle is chosen, SPACE could additionally be used as equivalent to ENTER, since it is the most easily used key.

Clarification: this would have to be AN OPTIONAL, ADDITIONAL control scheme, since it's not so widely spread amongst a "normal" user base.

**Describe alternatives you've considered**
For gaming users, WASD might be an interesting alternative to HJKL, and is arguably more intuitive than the vim keys, which don't have the arrow-key-like layout with up physically on top of down.

**Comment by Nomad-0** [comment]
Isn't your request somewhat similar to https://github.com/adirh3/Fluent-Search/issues/90 ?

**Comment by hpr1999** [comment]
It is, yes, I must've missed it.
I think there's still a difference in approach, though: While customizing these navigation keys is certainly nice, it wouldn't support assigning normal keys like H/J/K/L without additional work, since that would conflict with the normal type-to-search input mode.

I think my suggestions are more exotic / need more work.
A combination of both would be to make the keys that #90 mentions customizable, but also provide a keybinding to toggle a sort of navigation mode, in which the search bar isn't focused / is not receiving keystrokes as letters.

**Comment by hpr1999** [comment]
The question is what to do with the issues, I'm not sure if merging them makes sense, considering the goal is similar, but the approach / ambition quite different

**Comment by Metroid-Prime** [comment]
Perhaps close this one and your feedback directly to that post so it's viewable by Adir?

**Comment by hpr1999** [comment]
I kinda feel like this suggestion is outdated - also it's always possible to bind movement to CTRL+J / K, which seems to bepretty common practice among similar navigation schemes anyway.
