### ISSUE TITLE
Add the ability to search and launch installed Steam games.

### ISSUE THREAD

**Issue by Skyyblaze** [adirh3/Fluent-Search#215]
Since Steam games aren't added to the Start Menu Windows' Search Engine is quite useless for them thus I would like to see the ability for FluentSearch to search through and launch installed Steam games.

Launching Steam games is quite trivial and can be done like so:

`steam://rungameid/GAMEID`

or

`Steam.exe -applaunch GAMEID`

and it appears you can somehow interface and find out which games are installed with SteamCMD, an official tool by Valve which can be found here: https://developer.valvesoftware.com/wiki/SteamCMD

Maybe Fluent Search can make use of it too, I think some applications like Razer Synapse use it already and there's also a PowerShell script that adds all installed Steam games to the Start Menu which can be found here by user Matzurai: https://www.reddit.com/r/Steam/comments/3f53wv/windows_10_cant_find_installed_steam_games/

it also utilizes SteamCMD to a degree.

Adding all installed Steam games to the Start Menu like this isn't ideal though as the sheer amount of games some users might have installed needlessly bloats the Start Menu, the script has to run again after each installation of a game and shortcuts also have to be manually removed upon uninstalling a game.

Being able to have FluentSearch search and launch Steam games would be a far more elegant solution if possible.

**Comment by IgnusG** [comment]
I think this would be a good idea for a plugin

**Comment by Metroid-Prime** [comment]
Definitely plugin material.

**Comment by adirh3** [comment]
Added support for correctly parsing Steam link files in the Start menu folder, as discussed previously @Skyyblaze confirmed it's working.
Closing issue, thanks!
