### ISSUE TITLE
Launch FS through Single Click on Tray Icon

### ISSUE THREAD

**Issue by MakeshVineeth** [adirh3/Fluent-Search#218]
Right now, if one would like to launch FS by click on tray icon, they have to double click. It would awesome to have an option to launch FS through just single click on tray icon. Everything also has an option for this. Let the option be disabled by default.

**Comment by Nomad-0** [comment]
how about single click to launch FS and double click to show settings/plugin/about?

**Comment by MakeshVineeth** [comment]
> how about single click to launch FS and double click to show settings/plugin/about?

Yeah, that would be a good addition 👍

**Comment by Metroid-Prime** [comment]
I agree with this. Single click to launch FS would be a good idea.  

@Nomad-0  I assume by double click you mean simply launch settings window right?

**Comment by Nomad-0** [comment]
yeah, two different actions for single-click and double-click.
