### ISSUE TITLE
Instant Search searches only in the focused directory

### ISSUE THREAD

**Issue by Nomad-0** [adirh3/Fluent-Search#219]
**Describe the bug**
I'm not being able to find files that are not in the folder I'm currently in

![image](https://user-images.githubusercontent.com/76395594/125287580-ed153680-e33e-11eb-9f09-25217c307357.png)

though it finds files present in the folder

![image](https://user-images.githubusercontent.com/76395594/125287611-f7373500-e33e-11eb-98bc-a55bd2812ef1.png)

However, It finds the file through a normal search

![image](https://user-images.githubusercontent.com/76395594/125287646-fef6d980-e33e-11eb-85e2-7c2dfa579fdc.png)

**To Reproduce**
1. open explorer
2. go to a certain folder
3. try search a file from another folder

**Expected behavior**
Instant search should show results from all of explorer while prioritizing results from current folder

**Screenshots**
given above

**Desktop (please complete the following information):**
 - Windows 10 Version: [21H1]
 - Fluent Search Version [0.9.88.72]

**Comment by adirh3** [comment]
@Nomad-0 Ok I didn't understand at Discord sorry.
It shouldn't find files not in the current directory, as the feature states it's "in-app" not in all your pc.
To find files from all PC, use the normal search (if the explorer is in focus it will navigate in it as well)
