### ISSUE TITLE
Rebuild Index to Systray

### ISSUE THREAD

**Issue by Metroid-Prime** [adirh3/Fluent-Search#22]
Add option to "Rebuild Indexes" to right-click systray menu, especially if we're combining everything into 1 process

![image](https://user-images.githubusercontent.com/1836362/120909319-c6b9f800-c628-11eb-86fc-aa03cbd7b8eb.png)

**Comment by Metroid-Prime** [comment]
I think I am going to close this.  It seems that there's no need to rebuild index as open (like it was for Listary).

**Comment by Nomad-0** [comment]
I feel like it will still be a good edition though not much necessary

**Comment by Metroid-Prime** [comment]
Adir and I could have used it last night (Lol!) but I changed my mind on this.  FS used to need more frequent manual index rebuilding when it was in alpha stage but it's much better now. Don't want to clutter the systray interface :)
