### ISSUE TITLE
Installer unable to close FS during upgrade.

### ISSUE THREAD

**Issue by MakeshVineeth** [adirh3/Fluent-Search#220]
**Describe the bug**
Looks like Installer unable to close FS on first try. Have to click **Try again** for it to proceed. This is happening since last few updates.

**Steps To Reproduce**
1. Just try to upgrade FS to latest nightly version from the update dialog.
2. See if the Installer gave an error as shown in attached screenshot.

**Expected behavior**
Installer should be able to close all FS related services before proceeding to install or upgrade.

**Screenshots**
![image](https://user-images.githubusercontent.com/19371684/125312985-6c603580-e352-11eb-86fa-c054b0b816cb.png)

**Desktop (please complete the following information):**
 - Windows 11 Version: Insiders Build 22000.65
 - Fluent Search Version: 0.9.88.72

**Comment by Metroid-Prime** [comment]
I haven't seen this in Win10 LTSC 1809

**Comment by MakeshVineeth** [comment]
Not facing it lately, closing it. Will reopen if facing again.
