### ISSUE TITLE
"Open Directory in Command Line" fails if whitespace in directory path

### ISSUE THREAD

**Issue by xpac1985** [adirh3/Fluent-Search#222]
If you search/select a file and use "Open Directory in Command Line", it will fail, if that directory path contains e.g. a space.
This can likely be solved by wrapping the path in quotes.

**To Reproduce**
1. Search for a file that is in a path that contains spaces (in my case: `C:\Users\username\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup`)
2. Select "Open Directory in Command Line" on the right
3. See error

**Expected behavior**
Shell should open, and the working directory should be set to the directory containing the selected file.

**Screenshots**
![image](https://user-images.githubusercontent.com/6882771/125631008-226e630e-0b10-4091-bc6d-f219c8d2aec5.png)

**Desktop (please complete the following information):**
 - Windows 10 Version: 20H2, 19042.1083
 - Fluent Search Version 0.9.87.1

**Additional context**
I think wrapping the path after `cd` in quotes should easily solve this.

**Comment by adirh3** [comment]
It was already double quoted, apparently CMD requires double quotes and PowerShell single quotes.
Will be fixed in today's nightly version.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.88.99

**Comment by adirh3** [comment]
@xpac1985 Closing, it should be fixed on stable as well. Feel free to reopen if it still not working for you.
