### ISSUE TITLE
Option to change default watermark "Search anything" text to custom one.

### ISSUE THREAD

**Issue by MakeshVineeth** [adirh3/Fluent-Search#224]
This has been suggested by mikishaaaa on Discord.

As quoting it here:
> Maybe there could be an option to allow users to write anything they want instead of 'Search anything' when they open Fluent Search. It doesn't seem demanding to make and it's a nice personal touch.

PS: Posting it here for tracking.

**Comment by Metroid-Prime** [comment]
I don't know if many users want to go that granular, but I'll leave it up to the group.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.31                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by MakeshVineeth** [comment]
Confirmed the fix. Closing this issue.
