### ISSUE TITLE
Search not showing all files and folders

### ISSUE THREAD

**Issue by mragtronx8** [adirh3/Fluent-Search#229]
Search is not showing all files and folders

**Comment by Chance92** [comment]
Have you tried adjusting the following settings:
![image](https://user-images.githubusercontent.com/85488695/126051026-57566296-3475-4a93-97f9-51e0cd61afc8.png)
![image](https://user-images.githubusercontent.com/85488695/126051027-24c5058a-7575-4730-863e-b5ad68ad8d9a.png)

**Comment by mragtronx8** [comment]
**tried it, no luck.**

For example, i have a folder in D:\CLIENTS drive by the name of "Arc"
in everything search it shows up , but in FS = not showing 

thx

**Comment by Metroid-Prime** [comment]
You might need to post a little bit more info.  Screenshot proof of file you're missing and pictures of key settings (like files pane in settings)

**Comment by mragtronx8** [comment]
![image](https://user-images.githubusercontent.com/62798102/126058457-a3f367a5-8fbc-4590-bfc4-34a08dd1fbc3.png)

what key settings

**Comment by Metroid-Prime** [comment]
Perhaps picture showing you're indexing the folder that's not showing?  Adir would know other settings.

**Comment by adirh3** [comment]
Closing it until more information is provided, feel free to re-open.
