### ISSUE TITLE
Change size in MB to look cleaner

### ISSUE THREAD

**Issue by Metroid-Prime** [adirh3/Fluent-Search#23]
This is no-brainer and standard interface

kilobyte, megabyte, gigabyte, terabyte instead of "Size of MB 0.03891485883838".  This looks very hard to read for all users, novice and expert alike.

![image](https://user-images.githubusercontent.com/1836362/120909338-ebae6b00-c628-11eb-9dee-44ab14bcd2c6.png)

**Comment by MakeshVineeth** [comment]
I think this should be a bug, it is displaying incorrect sizes in the first place. Please look at the screenshots below.

![2021-06-19 (3)](https://user-images.githubusercontent.com/19371684/122632316-ab9ebc00-d0ef-11eb-8534-be47b3239626.png)
![2021-06-19 (4)](https://user-images.githubusercontent.com/19371684/122632319-accfe900-d0ef-11eb-943f-adc194c7aaaf.png)

**Comment by Nomad-0** [comment]
tagging it as a bug as per MV's comment above and theghostofgoya's comment in discord https://discord.com/channels/740636963396124714/740636963836788818/855675982887649311

**Comment by Metroid-Prime** [comment]
100% agree, this should be treated as a bug but didn't have the courage to ask others.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.85.85

**Comment by Nomad-0** [comment]
yes, fixed on my end

**Comment by Metroid-Prime** [comment]
Confirming fix & closing!
