### ISSUE TITLE
Copy full file path (including filename) through Copy Context in file explorer.

### ISSUE THREAD

**Issue by bytecut** [adirh3/Fluent-Search#231]
**Is your feature request related to a problem? Please describe.**
I want to be able to copy a file's FULL PATH (including filename) directly from file explorer, at the moment the Copy Context only copies current folder path. 

**Describe the solution you'd like**
I think it would make sense to make Copy Context actually copy complete file path when there's a file selected, otherwise keep current behavior (so if a file is not selected -- copy folder path)

**Describe alternatives you've considered**
At the moment I'm using Listary along side FS to compensate for some of the missing features, I don't see an alternative inside FS for it (copying filepath through FS' popup is not a valid option).

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.89.90
