### ISSUE TITLE
bookmark open with "/"

### ISSUE THREAD

**Issue by ltu00** [adirh3/Fluent-Search#232]
**Describe the bug**
bookmark open with "/"

**To Reproduce**
1. search any bookmark &　see the url 

**Expected behavior**
show the right url

**Screenshots**
![image](https://user-images.githubusercontent.com/50564608/126153174-9119bdd4-d1b9-4ab0-b899-5adee69c066f.png)
![image](https://user-images.githubusercontent.com/50564608/126155485-26c74d56-1db1-441f-a571-3253eb698e48.png)

![image](https://user-images.githubusercontent.com/50564608/126153265-c50575a2-c9cb-4201-8d02-99b6a5294266.png)

**Desktop (please complete the following information):**
 - Windows 11 Version: [e.g. 21H2]
 - Fluent Search Version [e.g. 0.9.88.86]

**Additional context**

**Comment by ltu00** [comment]
@Nomad-0 this bug make some bookmark can't open correctly.I think you should set medium priority or higher 🤣

**Comment by Nomad-0** [comment]
oh, I thought it creates problem only when copying URL. changing it then.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.88.95
