### ISSUE TITLE
"Process screen in background" will disable full screen searching

### ISSUE THREAD

**Issue by pzh200707** [adirh3/Fluent-Search#233]
**Describe the bug**
When I turned on "Process screen in background", only chrome shows the screen results.

**To Reproduce**
1. Set up 'Search Applications>Screen>Hotkeys>Search hotkey'
2. Press Search hotkey, then it shows the search results on all the windows.
3. Turn on 'Search Applications>Screen>Other>Process screen in background'
4. Press Search hotkey, then it shows the search results on Chrome only.

**Expected behavior**
While 'Search Applications>Screen>Other>Process screen in background' is on, pressing search hotkey should pull out the screen result in all windows.

**Screenshots**
![image](https://user-images.githubusercontent.com/26104496/126249086-7f1713f3-a823-4247-8018-1464fced5821.png)

**Desktop (please complete the following information):**
 - Windows 10 Version: 20H1
 - Fluent Search Version 0.9.87.1

**Comment by pzh200707** [comment]
![image](https://user-images.githubusercontent.com/26104496/126249270-d6b3d959-6aba-405b-9547-c842ab9b5c7c.png)

**Comment by adirh3** [comment]
@pzh200707 This is by design due to performance and memory consumption this won't work.

**Comment by Nomad-0** [comment]
@adirh3 should this be closed or kept as a feature request?
