### ISSUE TITLE
Pinned Folders / Files Disappearing after exit/restart

### ISSUE THREAD

**Issue by mragtronx8** [adirh3/Fluent-Search#234]
version 0.9.88.86
Pinned Folders / Files Disappearing after FS exit/restart

**Comment by Mr-Frankenstein** [comment]
Sometimes unpinned results reappear.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.88.92

**Comment by mragtronx8** [comment]
Version 0.9.88.92
when exiting FS, all pinned disappear.
Same with windows restart.
