### ISSUE TITLE
dual screen show full window  even set search bar only

### ISSUE THREAD

**Issue by ltu00** [adirh3/Fluent-Search#235]
**Describe the bug**
i have dual screens .everytime I move my mouse from one screen to other,it will show full windows at firsttime .
**To Reproduce**
0.dual screen
1. Go to Appearance set Windows Style : Search bar only
2. set Window startup position : Mouse screen center
3. turn off Home screen
4. move mouse  out the screen where FS last launched at , and launch FS

**Expected behavior**
show search bar only 

**Screenshots**
![image](https://user-images.githubusercontent.com/50564608/126945359-e86dcde1-5af5-4fc8-a893-fcd810021e4e.png)

**Desktop (please complete the following information):**
 - Windows 10 Version: 21H2
 - Fluent Search Version 0.9.88.90

**Additional context**

**Comment by minawaheed9697** [comment]
![26_07_2021 09_11_13_485](https://user-images.githubusercontent.com/73688266/126947617-f6e35c4b-cd7a-48aa-8ac2-b0e58fd99348.jpg)
Try to turn odd these 2 settings, please.

**Comment by ltu00** [comment]
> ![26_07_2021 09_11_13_485](https://user-images.githubusercontent.com/73688266/126947617-f6e35c4b-cd7a-48aa-8ac2-b0e58fd99348.jpg)
> Try to turn off these 2 settings, please.
not work for me .
