### ISSUE TITLE
Fluen Search always open on same virtual desktop on Windows 11

### ISSUE THREAD

**Issue by rhurta** [adirh3/Fluent-Search#236]
Hello, right now FS is opening always in the same Virtual Desktop on Win 11, so if you try to use it, it activate the Virtual Desktop where it was first activated.

How to reproduce this issue:
1. Create 2 or more Virtual Desktops on Win 11
2. Activate FS in one Virtual Desktop
3. Change to another Virtual Desktop
4. Activate FS
5. Virtual Desktop is changed to where FS was first activated

Expected behavior:
FS opens is the current Virtual Desktop

Thanks for your help

**Comment by adirh3** [comment]
@rhurta This is a Windows 11 issue, you can send them feedback (I did as well).
For now you can do Win+Tab and then right click FS window and press "Show windows from this app in all virtual desktops".
