### ISSUE TITLE
2 characters bookmark name can't search directly

### ISSUE THREAD

**Issue by ltu00** [adirh3/Fluent-Search#238]
**Describe the bug**
if bookmark's name just 2 character,it can't search directly,but can search by search tag "bookmark".
**To Reproduce**
1. save any website to bookmark,and set bookmark name just 2 character ,like "ss" "wb"
2. launch FS and search new bookmark directly . FS can't find it.
3. launch FS again and search new bookmark by search tag "bookmark".FS find it.

**Expected behavior**
2 character bookmark name can search directly

**Screenshots**
![image](https://user-images.githubusercontent.com/50564608/127428219-7a84ebbc-4fb7-48f7-ad6f-10e7f355fafc.png)
![image](https://user-images.githubusercontent.com/50564608/127428241-3845a6ed-adc4-4b11-86c0-0567f230d600.png)
![image](https://user-images.githubusercontent.com/50564608/127428309-02daba4b-c643-40ca-80bf-bbf7e4383058.png)

**Desktop (please complete the following information):**
 - Windows 11 Version: 21H2
 - Fluent Search Version 0.9.88.94

**Additional context**

**Comment by Nomad-0** [comment]
It might be because of result limitation, if your files have more priority than bookmarks, files with the search keyword would appear first, and with limitation, the result might not appear at all.

![image](https://user-images.githubusercontent.com/76395594/127491435-88151a64-5746-41f8-9506-c2452a93358a.png)

You might try grouping results by type and disable _show groups extended_ and check if the result appears in a different group

**Comment by ltu00** [comment]
> It might be because of result limitation, if your files have more priority than bookmarks, files with the search keyword would appear first, and with limitation, the result might not appear at all.
> 
> ![image](https://user-images.githubusercontent.com/76395594/127491435-88151a64-5746-41f8-9506-c2452a93358a.png)
> 
> You might try grouping results by type and disable _show groups extended_ and check if the result appears in a different group

not work for me . @Nomad-0

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.88.95

**Comment by ltu00** [comment]
This issue has been fixed in version 0.9.88.95
