### ISSUE TITLE
Instant Search glitch in Explorer and file dialogues

### ISSUE THREAD

**Issue by Nomad-0** [adirh3/Fluent-Search#239]
**Describe the bug**
sometimes instant search just keeps appearing and disappearing if I keep typing (like if I type a letter, it appears, I type another or two-letter, it disappears, another letter, it appears again). **that's why, I'm not being able to search anything with this feature**

(also, the windows background sound keeps appearing every time I invoke instant search)

**To Reproduce**
1. enable instant search
2. open explorer or file dialogue and start typing anything

**Expected behavior**
It should search as I type through and the windows background sound should not appear

**Screenshots**

https://user-images.githubusercontent.com/76395594/127727786-961279e7-fe27-40f2-96c5-90ff05f4d462.mp4

**Desktop (please complete the following information):**
 - Windows 10 Version: [21H1]
 - Fluent Search Version [0.9.88.95]

**Additional context**
It's not consistent but pretty regularly occurs

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.91

**Comment by Metroid-Prime** [comment]
@Nomad-0 Nomad-0 are you still having this issue?

**Comment by Nomad-0** [comment]
Seems like it's working fine now
