### ISSUE TITLE
Change logo color

### ISSUE THREAD

**Issue by Metroid-Prime** [adirh3/Fluent-Search#24]
Add a color to the outer border of the FS arrow logo so that it doesn't get hidden behind white or black backgrounds

**Comment by mochigithub** [comment]
EDIT: I think a light purple theme would be great. Perhaps a neon sign style?
![image](https://user-images.githubusercontent.com/1836362/120914257-b4a07f80-c651-11eb-87c8-563937c0e1ef.png)

**Comment by IgnusG** [comment]
I assume this is about the app list icon (since the taskbar corner icon already changes based on the theme). This might be doable through [theme support](https://docs.microsoft.com/en-us/windows/apps/design/style/xaml-theme-resources) - not sure if that's something usable for fluent though

**Comment by Metroid-Prime** [comment]
@IgnusG  sorry I missed your post.

Here's an example of the icon disappearing in a white background.   Download the app called Splat (https://www.dcmembers.com/skwire/download/splat/)  

Add Fluent Search to it and this is what you'll see. The icon is barely visible to the human eye. 

![image](https://user-images.githubusercontent.com/1836362/149641429-1b8716b2-3fc0-41f1-81bb-7a62fe0dcaf6.png)

**Comment by Metroid-Prime** [comment]
I'm closing this not because it isn't an issue but there are larger fish to fry
![image](https://user-images.githubusercontent.com/1836362/155902522-475f49fe-a891-4308-b38a-e6cccbcb07ec.png)
