### ISSUE TITLE
bookmark still can be search even removed

### ISSUE THREAD

**Issue by ltu00** [adirh3/Fluent-Search#240]
**Describe the bug**
bookmark still can search directly even has been removed

**To Reproduce**
1. delete any bookmark
2.. launch FS and search it by search tag "bookmark".it still here

**Expected behavior**
bookmark can't search directly when it removed

**Screenshots**
![image](https://user-images.githubusercontent.com/50564608/127740802-2bd78fa2-b048-42c0-99a1-8b3a9a9aa14e.png)

**Desktop (please complete the following information):**
 - Windows 11 Version: 21H2
 - Fluent Search Version 0.9.88.95

**Additional context**

**Comment by adirh3** [comment]
@ltu00 If you selected the bookmark result previously it's cached in Fluent Search, you can now remove it using the left button -
![image](https://user-images.githubusercontent.com/27368554/129402358-2f196146-6df4-408c-aa8d-bafde2de0c31.png)

**Comment by ltu00** [comment]
> @ltu00 If you selected the bookmark result previously it's cached in Fluent Search, you can now remove it using the left button -
> ![image](https://user-images.githubusercontent.com/27368554/129402358-2f196146-6df4-408c-aa8d-bafde2de0c31.png)

i can't find these icon,where?

**Comment by adirh3** [comment]
> > @ltu00 If you selected the bookmark result previously it's cached in Fluent Search, you can now remove it using the left button -
> > ![image](https://user-images.githubusercontent.com/27368554/129402358-2f196146-6df4-408c-aa8d-bafde2de0c31.png)
> 
> i can't find these icon,where?

It's at the top right of a displayed result - 
![image](https://user-images.githubusercontent.com/27368554/129447910-4140c25b-2381-4222-95dd-f4001768a956.png)

**Comment by ltu00** [comment]
> > > @ltu00 If you selected the bookmark result previously it's cached in Fluent Search, you can now remove it using the left button -
> > > ![image](https://user-images.githubusercontent.com/27368554/129402358-2f196146-6df4-408c-aa8d-bafde2de0c31.png)
> > 
> > 
> > i can't find these icon,where?
> 
> It's at the top right of a displayed result -
> ![image](https://user-images.githubusercontent.com/27368554/129447910-4140c25b-2381-4222-95dd-f4001768a956.png)

![image](https://user-images.githubusercontent.com/50564608/129448380-491550e5-0658-459b-a6a8-55b4d185c1c5.png)
there is nothing

**Comment by ltu00** [comment]
> > > @ltu00 If you selected the bookmark result previously it's cached in Fluent Search, you can now remove it using the left button -
> > > ![image](https://user-images.githubusercontent.com/27368554/129402358-2f196146-6df4-408c-aa8d-bafde2de0c31.png)
> > 
> > 
> > i can't find these icon,where?
> 
> It's at the top right of a displayed result -
> ![image](https://user-images.githubusercontent.com/27368554/129447910-4140c25b-2381-4222-95dd-f4001768a956.png)

i find it.it need to turn off minimalistic user interface first

**Comment by adirh3** [comment]
> > > > @ltu00 If you selected the bookmark result previously it's cached in Fluent Search, you can now remove it using the left button -
> > > > ![image](https://user-images.githubusercontent.com/27368554/129402358-2f196146-6df4-408c-aa8d-bafde2de0c31.png)
> > > 
> > > 
> > > i can't find these icon,where?
> > 
> > 
> > It's at the top right of a displayed result -
> > ![image](https://user-images.githubusercontent.com/27368554/129447910-4140c25b-2381-4222-95dd-f4001768a956.png)
> 
> i find it.it need to turn off minimalistic user interface first

Oh ok cool, so does it fix the issue?

**Comment by ltu00** [comment]
> > > > > @ltu00 If you selected the bookmark result previously it's cached in Fluent Search, you can now remove it using the left button -
> > > > > ![image](https://user-images.githubusercontent.com/27368554/129402358-2f196146-6df4-408c-aa8d-bafde2de0c31.png)
> > > > 
> > > > 
> > > > i can't find these icon,where?
> > > 
> > > 
> > > It's at the top right of a displayed result -
> > > ![image](https://user-images.githubusercontent.com/27368554/129447910-4140c25b-2381-4222-95dd-f4001768a956.png)
> > 
> > 
> > i find it.it need to turn off minimalistic user interface first
> 
> Oh ok cool, so does it fix the issue?

it fixed.
