### ISSUE TITLE
The right-pane remains empty

### ISSUE THREAD

**Issue by Nomad-0** [adirh3/Fluent-Search#242]
**Describe the bug**
Sometimes if I search something, the right pane doesn't show any details of the result

**To Reproduce**

It appears with a normal search. It's not consistent but appears often. Haven't found any way to reproduce it.

**Expected behavior**
The right pane should show details always

**Screenshots**
![image](https://user-images.githubusercontent.com/76395594/127772433-c282e642-8ba0-4bc6-9b7c-5999756a683a.png)

**Desktop (please complete the following information):**
 - Windows 10 Version: [21H1]
 - Fluent Search Version [0.9.88.95]

**Comment by adirh3** [comment]
@Nomad-0 Does it still happen?

**Comment by Nomad-0** [comment]
Not sure as I don't know how to reproduce it. closing it for now, will reopen if I face again

**Comment by Nomad-0** [comment]
facing it again @adirh3 , however, it gets ok after I type more
![image](https://user-images.githubusercontent.com/76395594/132992903-ecc13c3c-6af2-43f4-a962-35a4c0d46c39.png)

**Comment by Nomad-0** [comment]
re-opening as facing the bug on the latest version 0.9.89.75

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.60
