### ISSUE TITLE
[Preview] QuickLook preview pane appears behind the search window

### ISSUE THREAD

**Issue by Nomad-0** [adirh3/Fluent-Search#243]
**Describe the bug**
If QuickLook is set as the preview provider, whenever I select an item and try to see preview, the preview pane appears behind the search window.

**To Reproduce**
1. Go to settings>Preview>File preview provider
2. Set Quick look as preview provider
3. Open the search bar and try to get a preview of any file

**Expected behavior**
The preview pane should appear below or side of the search window (also adjust the size of the pane if necessary)

**Screenshots**
![image](https://user-images.githubusercontent.com/76395594/127799930-4b40c6c3-1187-4fe1-a5fd-32918194a487.png)

**Desktop (please complete the following information):**
 - Windows 10 Version: [21H1]
 - Fluent Search Version [0.9.88.95]

**Comment by adirh3** [comment]
This is due to Quick Look not being top most window. It might be possible to change in their settings.
You can also disable `Show at top most` in Fluent Search settings.
