### ISSUE TITLE
[modification] A separate key binding for preview within search window

### ISSUE THREAD

**Issue by Nomad-0** [adirh3/Fluent-Search#244]
**Is your feature request related to a problem? Please describe.**
Currently, if I want to get a preview of a file within the search window, e.g 1st result in search, I have to do this-
1. invoke FS and search for the file. 
> now I can't press space to get a preview as it'll only make a space in the text box. so I have to-

2. press `down arrow` to go to the 2nd result
3. press `up arrow` to go and select the 1st result
4. press `space` to preview the 1st result

as this being the process, the search window preview seems more complex than the full **Preview** function which requires only 2 steps> searching for a result and press `shift+enter`.

**Describe the solution you'd like**
changing the key binding for the Action panel preview will make the process easier. My proposal is shift+space in this case.
this will reduce the process to-
1. invoke FS and search for the file.
2. press shift+space

**Comment by adirh3** [comment]
The preview toggle key has been changed to `Alt`, which should solve the issue you're describing.
Having custom shortcut support for this may conflict with user's search hotkey, and I think may be a bit confusing.
Closing this, feel free to reopen if you think `Alt` is not sufficient.
Thanks!
