### ISSUE TITLE
Opening .EXE results in program CWD being System32

### ISSUE THREAD

**Issue by FelicitusNeko** [adirh3/Fluent-Search#246]
**Describe the bug**
When a .EXE file is opened directly using Fluent Search, that program's current working directory will always be `C:\Windows\System32`, which can lead to some problems in its execution (e.g. if it looks in the CWD for asset or config files).

**To Reproduce**
1. Open Fluent Search
2. Search for any given .EXE file
3. Open it

**Expected behavior**
The program opens with its CWD being the directory it's located in.

**Screenshots**
![image](https://user-images.githubusercontent.com/50271878/128062409-9716767f-9b8b-4b6a-a570-3ad07d9f316d.png)
Screenshot from Process Explorer after launching Aseprite.exe from Fluent Search (it was built from source, thus not installed and does not have a shortcut anywhere)

**Desktop (please complete the following information):**
 - Windows 11 Pro Beta 22000.100
 - Fluent Search 0.9.87.1

**Additional context**
While I have not tried .BAT or .CMD files, the result would likely be the same.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.88.97

**Comment by adirh3** [comment]
@FelicitusNeko Can you confirm it's fixed for you please?

**Comment by FelicitusNeko** [comment]
Would that I had access to this version. It doesn't appear to be on the website or in the Microsoft Store.

**Comment by adirh3** [comment]
> Would that I had access to this version. It doesn't appear to be on the website or in the Microsoft Store.

It's currently in the nightly builds, you can opt in for that in Settings -> System -> Release feed

**Comment by FelicitusNeko** [comment]
I don't seem to have the "Release feed" option, and advanced settings are enabled. Is this option not available if Fluent Search was installed via the Microsoft Store?

**Comment by FelicitusNeko** [comment]
![image](https://user-images.githubusercontent.com/50271878/129423695-c5015489-a01f-45ef-ab2a-ea2374fd29ca.png)

Okay, I set up the portable version to test this out (which ran into some problems updating, mind), and it seems that this issue is fixed.
