### ISSUE TITLE
Rename "IsEnabled" in settings.

### ISSUE THREAD

**Issue by Metroid-Prime** [adirh3/Fluent-Search#25]
This is not a bug, but not a feature either.

In the apps 'setting' section, the column for Custom app paths when added is "IsEnabled".  This should be Enabled (not IsEnabled) to keep consistent interface with others.

EDIT: Added pic:
![image](https://user-images.githubusercontent.com/1836362/120914467-3fce4500-c653-11eb-8dde-28432ecb74a7.png)

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.85.75

**Comment by Metroid-Prime** [comment]
Thank you for going above & beyond and changing all of the IsEnabled to Enabled.

Confirming fix & closing!

**Comment by adirh3** [comment]
> Thank you for going above & beyond and changing all of the IsEnabled to Enabled.
> 
> Confirming fix & closing!

Definition of "going above & beyond" -
![image](https://user-images.githubusercontent.com/27368554/122640030-cf6cfc80-d105-11eb-81e1-3bef016ef570.png)
