### ISSUE TITLE
Uninstalled apps are still shown in FS until we do a restart

### ISSUE THREAD

**Issue by MakeshVineeth** [adirh3/Fluent-Search#252]
**Describe the bug**
Whenever we uninstall any Windows Store app either through FS or through Start Menu etc., they're not being updated in real time in FS. We have to restart the FS for refresh.

**To Reproduce**
1. Search for any Windows Store app in FS.
2. Click on Uninstall App.
3. Verify if the app has been uninstalled in Start Menu.
4. The app will still be shown in FS.

**Expected behavior**
The status of installed/uninstalled apps should be updated in real time in FS.

**Desktop information:**
 - Windows 11 Version: Build 22000.132
 - Fluent Search Version: 0.9.88.99

**Comment by Nomad-0** [comment]
setting it low priority as it's fixed after restart

**Comment by adirh3** [comment]
@MakeshVineeth It should disappear after a minute, if it's not then it might not be fully uninstalled, please try to confirm it

**Comment by MakeshVineeth** [comment]
Yeah, no longer facing this issue. Closing.
