### ISSUE TITLE
File Dialogs

### ISSUE THREAD

**Issue by mragtronx8** [adirh3/Fluent-Search#254]
File dialogs to be supported by 3rd party file managers [eg: xyplorer / xplorer2 / total commander / etc.] "Feature Request"

**Comment by rajat-r** [comment]
Really need this!

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.46                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
