### ISSUE TITLE
UI search not working

### ISSUE THREAD

**Issue by Nomad-0** [adirh3/Fluent-Search#255]
**Describe the bug**
UI search tag don't show anything either on a normal search or with in-app search hotkey. 

**To Reproduce**
1. Go to normal search or in-app search
2. invoke **ui** tag
3. try to search anything
4. nothing shows

**Expected behavior**
UI search tag should show the buttons, tabs and others which we can see in a normal in-app search
![image](https://user-images.githubusercontent.com/76395594/129680040-80380492-7d1c-40b2-ba43-a83127fa4d0e.png)

**Screenshots**
normal search with **UI** tag

![image](https://user-images.githubusercontent.com/76395594/129680144-9d1a944a-9fbb-4251-9c8e-dc579a802bcd.png)

In-app search with **UI** tag

![image](https://user-images.githubusercontent.com/76395594/129680168-d5f7abcd-be62-42db-bc83-550453199ce9.png)

**Desktop (please complete the following information):**
 - Windows 10 Version: [21H1]
 - Fluent Search Version [0.9.88.9989]

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.89.2
