### ISSUE TITLE
Multiplication should be done by an x sign instead of asterisk

### ISSUE THREAD

**Issue by rsmyst** [adirh3/Fluent-Search#256]
I find hitting x much easier for multiplication since it's the way i generally write multiplication on paper. 
It'd be cool if x did that instead of asterisk. 
currently, x does some number conversion despite not having installed the plugin.
Thanks.

**Comment by Nomad-0** [comment]
Some of us prefer * as we do most things related to numbers with the Numpad. However, I understand your concern and hopefully the dev would find some workaround for that

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.89.2

**Comment by Nomad-0** [comment]
closing it, feel free to reopen if the issue is not fixed for you
