### ISSUE TITLE
 Can the screen search function be activated separately? Or screen search application?

### ISSUE THREAD

**Issue by okwellok** [adirh3/Fluent-Search#259]
Hi,
As the title, I don’t need other extra functions, I only want the screen search function.

Can you use the screen search alone as an application？

Thank you for making such a good application！I'm sorry for my poor English.😭

**Comment by Nomad-0** [comment]
Screen Search is a part of Fluent Search, so you can't use it without keeping FS running. However, You can disable other search options from settings > search applications and also the indexer from settings > search applications > file > file indexer. You can set a hotkey for screen search and can invoke only screen search using that hotkey.

**Comment by okwellok** [comment]
@Nomad-0  Thank you for your reply. Is there any other software similar to screen search

**Comment by Nomad-0** [comment]
You can use the Vimium Chrome extension for your browser. But for all other applications on pc, I haven't found any other alternative as efficient as FS
