### ISSUE TITLE
Install program auto run in chinese when fluent search is running

### ISSUE THREAD

**Issue by urql** [adirh3/Fluent-Search#262]
---
name: Bug report
about: Create a report to help us improve
title: ''
labels: ''
assignees: ''

---

When I try to install any program with multilanguage when fluentsearch is running, the language selection pop up for a while and automatically run the installer in chinese language.

**To Reproduce**
1. Have fluent search running
2. Install everything multilanguage
3. language selection pop up for a second and then gone
4. the installer start in chinese language

**Expected behavior**
Language selection stays waiting for user input

**Desktop**
 - Windows 10 Version: 21H1
 - Fluent Search Version 0.9.88.9989

**Additional context**
When fluentsearch is not running, installer works as intended.

Hope this will help to make fluentsearch the best launcher, thank you Adirh

**Comment by urql** [comment]
> @urql Do you have "Copy context to file dialogs" in Settings -> Context (Advanced) enabled?

yes I do. Is it relevant?

**Comment by adirh3** [comment]
> > @urql Do you have "Copy context to file dialogs" in Settings -> Context (Advanced) enabled?
> 
> yes I do. Is it relevant?

Can you please check if disabling it solves the problem?

**Comment by urql** [comment]
> Can you please check if disabling it solves the problem?

Yes it does behave correctly when I disable the "Copy context to file dialogs" setting.

**Comment by adirh3** [comment]
@urql This should be fixed on the latest stable, closing it feel free to reopen
