### ISSUE TITLE
CJK Characters are shown as Garbled(Tofu)

### ISSUE THREAD

**Issue by nutnutwin** [adirh3/Fluent-Search#263]
Thank you for the great work, considering switching from other Launcher...

**Describe the bug**
Chinese/Japanese Characters are not shown properly
✨Current workaround, switched to CJK font
https://github.com/be5invis/Sarasa-Gothic

**To Reproduce**
1. Activate FluentSearch
2. Type Chinese/Japanese
  eg. "日本語"/"日语"
3. Characters are garbled
4. font is default as Segoe

**Expected behavior**
Characters are shown properly(with somekind of fallback font, like in browser)

**Screenshots**
<img width="170" alt="20210827_Fri -224446" src="https://user-images.githubusercontent.com/34512273/131137001-d4d59fdc-2ae8-4d4a-85f4-5f55f468e033.png">

**Desktop (please complete the following information):**
 - Windows 10 Version: 20H2
 - Fluent Search Version: 0.9.88.9989(Just downloaded as portable)

**Additional context**

**Comment by Nomad-0** [comment]
closing it as a **duplicate issue**, please report it in #148 's comment
