### ISSUE TITLE
Problem with Chinese/Japanese IME

### ISSUE THREAD

**Issue by nutnutwin** [adirh3/Fluent-Search#264]
**Describe the bug**
1. IME location
When trying to type in Chinese/Japanese IME in SearchBar, 
IME Candidate Window(where you can pick from list of words) stick to the Top-Left of Window. 
This happened in early version of Sublime Text Editor, but got fixed later.

2. when the Candidate window is shown, Pressing Enter should be processed by IME. 
in current version, it is handled by Fluent Search, which turns into a "select current item"

**To Reproduce**
1. IME Location
- Activate Fluent Search
- Type some Japanese(GoogleIME)
2. Same as above. 
- Type some alphabets, Press Space to convert
- Press Enter

**Expected behavior**
as described above

**Screenshots**
1. IME Location
<img width="332" alt="20210827_Fri -231523" src="https://user-images.githubusercontent.com/34512273/131141447-9cac8c87-d646-46b1-be03-ca244beadc90.png">

**Desktop (please complete the following information):**
 - Windows 10 Version: 20H2
 - Fluent Search Version 0.9.88.9989(Just downloaded as portable)

**Additional context**
If you need a video/more screenshots, please let me know

**Comment by nutnutwin** [comment]
https://github.com/ransome1/sleek/issues/161
another app I reported with similar problem(now fixed)

**Comment by adirh3** [comment]
@nutnutwin Thanks, proper support for IME and Chinese will be available is being worked.

**Comment by nutnutwin** [comment]
@adirh3 Thank you for your reply. Looking forward to the Fix.
Also I searched here and official site and found no url for donation. 
I wonder if it is possible. (like paypal.

**Comment by adirh3** [comment]
> @adirh3 Thank you for your reply. Looking forward to the Fix.
> Also I searched here and official site and found no url for donation.
> I wonder if it is possible. (like paypal.

Closing this since it's duplicate with #148 
There is donate button on the website - https://fluentsearch.net/

**Comment by nutnutwin** [comment]
@adirh3 I must have missed that because I use search instead of my eyes...my bad...
though this #264 is not the same with #148
#264 is about IME support(showing candidate window properly, and handling Enters...), while #148 is about displaying characters unsupported by the font

May I open this issue again? Thank you.

**Comment by nutnutwin** [comment]
@adirh3 hi, do you need a screen record for clarification? thank you
I went through #148 and I am quite sure they are different problems...
Sorry for being naggy
