### ISSUE TITLE
Setting the search hotkey as "win" breaks emoji entry in other apps

### ISSUE THREAD

**Issue by brimwats** [adirh3/Fluent-Search#265]
I am on: Windows 10 - 20H2 (OS Build 19042.1165)

I am using Version: 0.9.89.1. I followed the instructions here to install the alpha: https://discord.com/channels/740636963396124714/740637280590495866/880008224919654401 

Here is a gif:

![s1jKwjAhsj](https://user-images.githubusercontent.com/49103046/131204624-f1b82d7e-da25-454f-9c86-034489a1aad2.gif)

**Comment by brimwats** [comment]
Idk if you updated something @adirh3 but now this doesn't happen in all apps—just ones like Signal (above) or my task app (amazing marvin) but not like discord or chrome.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.89.9940
