### ISSUE TITLE
Updating accent colour with windows

### ISSUE THREAD

**Issue by minawaheed9697** [adirh3/Fluent-Search#267]
Changing the accent color with changing the windows color automatically.

**Comment by adirh3** [comment]
@Nomad-0 can you confirm it? Works for me if I choose System color

**Comment by Nomad-0** [comment]
@adirh3 yes, working for me too

**Comment by adirh3** [comment]
Closing feel free to reopen if it does not work for you

**Comment by adirh3** [comment]
> @adirh3 EXE. I am using the stable version.

Sorry for delay in response @minawaheed9697, what Windows do you use? Did you set the accent color to "System color" in Settings -> Appearance?

**Comment by minawaheed9697** [comment]
No matter, bro.
Win 10. 
Yes, I set it, but I noticed something strange. The FS color changes with the windows except from Blue color i.e. if the windows changes from brown to any other color, the FS changes, but if the windows changes color from blue, the FS color does not change.

**Comment by adirh3** [comment]
@minawaheed9697 this should be fixed on latest nightly, I can't repro this.
Feel free to reopen if you're still experiencing the issue.
