### ISSUE TITLE
Include File Path in Search

### ISSUE THREAD

**Issue by ghost007** [adirh3/Fluent-Search#269]
Everything Search from VOID TOOLS has a neat feature to also search for the file path. This enables you find files within a folder with a certain name quite easily. This is somthing I'm missing desperately as it allows for an much easier search.

Exampel Search Term: "Office exe"

Result: Setup.exe in File path D:/Software/Office/

**Comment by adirh3** [comment]
Hey @ghost007 you can already search inside paths by searching having a slash
For example "\Office\ exe"
Or even full path- "D:\Software\Office\ exe" 
You can also use "*.exe" to make sure you get only exe files and not files with exe in their name.

**Comment by adirh3** [comment]
@ghost007 Closing it as it's already implemented, feel free to reopen if I misuderstood.
