### ISSUE TITLE
Re-do Custom Color placeholders  in Settings

### ISSUE THREAD

**Issue by Metroid-Prime** [adirh3/Fluent-Search#27]
Add custom squares (2?) to allow user to add custom colors to empty squares to the appearance tab | color setting

![image](https://user-images.githubusercontent.com/1836362/120909380-68d9e000-c629-11eb-94d6-4e7a424a0ed8.png)

Plus, I really _really_ don't like having to type in 8 digit hex code for custom colors.  This is very non-intuitive. Maybe add some form of a color picker?

![image](https://user-images.githubusercontent.com/1836362/120914928-df8cd280-c655-11eb-9641-355d95b72ece.png)

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.88.90

**Comment by Metroid-Prime** [comment]
I don't see any empty boxes in the accent color section. Should we be seeing that?

**Comment by adirh3** [comment]
> I don't see any empty boxes in the accent color section. Should we be seeing that?

Only added the color picker one, I will not add custom color boxes atm since it will require bigger change

**Comment by Metroid-Prime** [comment]
Ok thanks @adirh3
