### ISSUE TITLE
Keyword to open specific folder / file

### ISSUE THREAD

**Issue by urql** [adirh3/Fluent-Search#270]
**Is your feature request related to a problem? Please describe.**
I have several folder with same / similar name scattered across my system.  
I'm always frustrated when it try to find a specific folder with similar name  

**Describe the solution you'd like**
I'd like to assign a keyword to open specific folder / file

**Describe alternatives you've considered**
I try to append somewhat unique name to my folder but it make it look inconsistent & chaotic

**Additional context**

**Comment by adirh3** [comment]
@urql Hey, in general after you select a result once it will be prioritized by FS, but if you did not you can try using `Search mapping` or `Custom search tags`.
Here is an explanation how to use it -

For `Search mapping` go to Settings -> Toggle advanced -> Power user -> Enable search mapping.
Then add new record like - 
Input - `mycoolfolder`
Output - `C:\Temp\mycoolfolder`
Now when you search `mycoolfolder` it will actually search for the exact path.


For `Custom search tag` go to Settings -> Search tags -> Map searched tag.
Then add new record similar as above.
Now you can start typing 'mycoolfolder` and press `TAB` to insert search tag, this will allow you to search inside that folder.

Please let me know if I understood correctly the problem and if this helps.

**Comment by urql** [comment]
Thank you for the explanation, I tried `Custom search tag` before and it works as you explained.

However the `Search mapping` confuses me, I can see that fluent recognize the Search Mapping (blue arrow icon on right side) but it still doesn't show the intended folder, it keep suggesting other folder

![210905 CUSTOM SEARCH](https://user-images.githubusercontent.com/24861328/132131091-57e3d780-50bc-4759-a202-65f120fb8781.jpg)
 
in this case I assign keyword `pub` to `\\server\public` however when I type `pub`, fluent suggest me other folders.

I use everything for the indexing engine, does it affect the result?

Thank you

**Comment by adirh3** [comment]
> Thank you for the explanation, I tried `Custom search tag` before and it works as you explained.
> 
> However the `Search mapping` confuses me, I can see that fluent recognize the Search Mapping (blue arrow icon on right side) but it still doesn't show the intended folder, it keep suggesting other folder
> 
> ![210905 CUSTOM SEARCH](https://user-images.githubusercontent.com/24861328/132131091-57e3d780-50bc-4759-a202-65f120fb8781.jpg)
> 
> in this case I assign keyword `pub` to `\\server\public` however when I type `pub`, fluent suggest me other folders.
> 
> I use everything for the indexing engine, does it affect the result?
> 
> Thank you

Sorry for the delay, in the current stable version searching for exact path will not necessarily return the folder itself, but it might return files/folders inside it.
This is fixed in the nightly builds if you'd like to try it. 
For now, you can pin that folder (ALT+P or click the pin icon), and it will show on top.

Hope this helps, let me know if it works out for you.

**Comment by urql** [comment]
Hi Adirh, the nightly build works great. Thank you.

I was wondering if there is a menu for managing pinned item? 
sometimes the search result does not find things we want, it would be beneficial to have a menu to manually manage pinned item

Thank you.

**Comment by adirh3** [comment]
> Hi Adirh, the nightly build works great. Thank you.
> 
> I was wondering if there is a menu for managing pinned item?
> sometimes the search result does not find things we want, it would be beneficial to have a menu to manually manage pinned item
> 
> Thank you.

What do you mean by managing pinned items? Wouldn't that be like the home screen? 
Currently the only way to pin a result is searching for it.

**Comment by urql** [comment]
exactly, the only way to add item to pin is by search result, meanwhile sometimes it is hard to get correct result from file search.

well one way to overcome in nightly is by `search mapping` and pin it from there.

**Comment by adirh3** [comment]
> exactly, the only way to add item to pin is by search result, meanwhile sometimes it is hard to get correct result from file search.
> 
> well one way to overcome in nightly is by `search mapping` and pin it from there.
> 
> well I guess we can live with it. I will close the issue for now.
> 
> Thank you @adirh3

If you have any feedback on the search experience and ideas how to improve it, please feel free to share, through Github/Mail/Discord.

Thanks!
