### ISSUE TITLE
unnecessarily large confirmation window when uninstalling apps using FS

### ISSUE THREAD

**Issue by marcelweitzel** [adirh3/Fluent-Search#273]
**Describe the bug**
when trying to uninstall apps using FS, the confirmation window is unnecessarily large

![image](https://user-images.githubusercontent.com/46997355/132127327-24b52888-4cfb-4ccd-a462-59da35c090f3.png)

**To Reproduce**
1. type app name into FS
2. choose "uninstall"
3. look at window

**Expected behavior**
an appropriately sized window asking for a confirmation

**Desktop (please complete the following information):**
Edition	Windows 10 Pro
Version	21H1
Installiert am	‎11.‎12.‎2019
Betriebssystembuild	19043.1165
Leistung	Windows Feature Experience Pack 120.2212.3530.0

 - Fluent Search Version 0.9.89.1

**Comment by Nomad-0** [comment]
Closing as the report is the same as issue #115
