### ISSUE TITLE
0.9.89.2 Freeze on Startup

### ISSUE THREAD

**Issue by Chance92** [adirh3/Fluent-Search#275]
**Describe the bug**
After being updated to 0.9.89.2, FS froze and stopped responding after startup.

**To Reproduce**
1. Upgrade or clean install 0.9.89.2;
2. Run FS;

**Expected behavior**
Not to freeze.

**Screenshots**
![image](https://user-images.githubusercontent.com/85488695/132206416-c067da00-9db0-4507-b504-619b427aebc1.png)

**Desktop (please complete the following information):**
 - Windows 10 Version: 21H1
 - Fluent Search Version 0.9.89.2

**Additional context**
Tried deleting blast folders and clean install. No luck.

**Comment by adirh3** [comment]
Fixed in 0.9.89.21, thanks

**Comment by Chance92** [comment]
Thanks for fixing it so fast.
