### ISSUE TITLE
Function Request - Translation Plugin...

### ISSUE THREAD

**Issue by BruceGeng2012** [adirh3/Fluent-Search#277]
**Not an issue, but translation add-on request. LOL...**
Actually fact, this is my first time use the app. Was using listary...This is the most awesome one I've never tryed before...Possible add translation module which can be easily switch on/off? Really love the app [...]

**Comment by adirh3** [comment]
@BruceGeng2012 Glad you liked it, did you try installing the Translator plugin? You can configure hotkey for it if you're using it frequently

**Comment by BruceGeng2012** [comment]
Yap...been using this function for a few days...put translation web url and
configure hotkey, search tag...seems like more convenient right now...thx
pal...

**Comment by adirh3** [comment]
Closing it, feel free to reopen if I misunderstood.
