### ISSUE TITLE
Taskbar icon wrong theme (color)

### ISSUE THREAD

**Issue by Jaap-van-Hengstum** [adirh3/Fluent-Search#278]
**Describe the bug**
The taskbar icon theme uses the "default app mode" setting. It should use the "default Windows mode" setting.

**To Reproduce**
In the Windows settings, set "default app mode" to light and "default Windows mode" to dark. Now the taskbar is in dark mode and so is the Fluent Search icon. 

**Expected behavior**
The Fluent Search icon should be in light mode.

**Desktop (please complete the following information):**
 - Fluent Search Version [e.g. 0.9.89.31]

**Screenshots**
![image](https://user-images.githubusercontent.com/1670232/132468632-bead3672-567c-4373-8d3b-d2641bf8208d.png)
![image](https://user-images.githubusercontent.com/1670232/132465658-4d6c2c91-bfdb-48f1-9745-b1e388b844ce.png)

**Comment by adirh3** [comment]
@Jaap-van-Hengstum should be fixed, closing this
