### ISSUE TITLE
Bookmark search should allow folder names in search terms

### ISSUE THREAD

**Issue by Jaap-van-Hengstum** [adirh3/Fluent-Search#279]
Bookmark search seems to only search in the bookmark title. In my situation, I put my bookmarks inside folders (and subfolders) and a lot of identifying information is in the folder names and not in the bookmark title. 

It would be nice if bookmark search also included the folder names. For example, when you have the folder structure:

Microsoft
└── Office
 &nbsp;&nbsp;&nbsp;├── Word
 &nbsp;&nbsp;&nbsp;├── Excel
 &nbsp;&nbsp;&nbsp;├── Outlook
 &nbsp;&nbsp;&nbsp;└── Powerpoint

You should be able to search for "bookmark: office" or "bookmark: microsoft office" and find every bookmark in the "Microsoft/Office" folder, or search for "bookmark: microsoft word" and find only (or prioritize) the "Word" entry in the "Office" folder and not in other folders.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.89.50

**Comment by adirh3** [comment]
@Jaap-van-Hengstum as this has been implemented, I am closing it.
