### ISSUE TITLE
 alt+enter to open FS setting not work

### ISSUE THREAD

**Issue by ltu00** [adirh3/Fluent-Search#280]
**Describe the bug**
 alt+enter to open FS setting not work

**To Reproduce**
1. launch FS search bar 
2. press alt+enter
3. FS setting can't pop up.and FS crash occasionally

**Expected behavior**
show setings window

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 11 Version: 22449.1000
 - Fluent Search Version 0.9.89.31

**Additional context**

**Comment by adirh3** [comment]
@ltu00 are you using the Direct2D?

**Comment by ltu00** [comment]
> @ltu00 are you using the Direct2D?

yes
