### ISSUE TITLE
Support for bookmarks search in Firefox browser (when using in-app search feature)

### ISSUE THREAD

**Issue by DJiMMYSVRT** [adirh3/Fluent-Search#282]
**Is your feature request related to a problem? Please describe.**
Not related to a problem. 
Bookmarks search for chromium-based browsers is perfect. 
But some of us use non-chromium browsers at the same time for different tasks.

**Describe the solution you'd like**
"In-app" bookmarks search for Firefox **Quantum** & maybe other browsers that use the same engine.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.30                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
