### ISSUE TITLE
can't update FS

### ISSUE THREAD

**Issue by pinusm** [adirh3/Fluent-Search#283]
**Describe the bug**
I can't update FS. I get the following error message in App Installer:
App installation failed with error message: Windows cannot install package FluentSearch.SideLoad_0.9.89.35_x64__pgwv7fezznhxy because a different package FluentSearch.SideLoad_0.9.89.1_x64__4139t8dvwn2ka with the same name is already installed. Remove package FluentSearch.SideLoad_0.9.89.1_x64__4139t8dvwn2ka before installing. (0x80073cf3)

**To Reproduce**
1. check for new FS version (I'm on the beta/nightly channel)
2. download an try to install
3. See error

This also happens when I download an APPX installer directly from the [repo](https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/appx).

When I download the exe installer I can update without any issues.

**Screenshots**
![image](https://user-images.githubusercontent.com/10765331/132698167-8226836e-4d57-4cd3-833b-9ac53d034bf6.png)

**Desktop (please complete the following information):**
 - Windows 10 Version: 21H1
 - Fluent Search Version 0.9.89.1 (also had this in a previous version, but I can't remember the exact version)

**Comment by adirh3** [comment]
@pinusm unfortunately  due to certificate renewal the Appx package will not let you update, you will have to uninstall.
You can backup your settings in Settings -> Sync, by exporting settings.
Also, I suggest installing the EXE version as I am planning to drop the Appx version soon due to many issues with it.
