### ISSUE TITLE
Options for decimal places and significant figures

### ISSUE THREAD

**Issue by Chance92** [adirh3/Fluent-Search#284]
**Is your feature request related to a problem? Please describe.**
Calculator results smaller than 0.005 are rounded down to 0.

**Describe the solution you'd like**
Please consider providing an option for setting decimal places and significant figures of calculator results. Long results can be displayed with scientific notation to save space.

**Describe alternatives you've considered**

**Additional context**
0.004 is too big to be ignored in many circumstances.

**Comment by adirh3** [comment]
@Chance92 is it better in the latest version?

**Comment by Chance92** [comment]
Absolutely. I'll close this one for now.
