### ISSUE TITLE
Accented characters in path are not supported by Context

### ISSUE THREAD

**Issue by TheFireRed** [adirh3/Fluent-Search#285]
**Describe the bug**
When a folder path includes an accented character, Fluent Search Context copies a � symbol.

**To Reproduce**
1. Open a File Dialog (AIMP, press `Insert` key)
2. Check a folder with an accented character in File Explorer (`E:\Downloads\Música`)
3. Go back to the File Dialog
4. Explorer is unable to load the file because it replaced accented characters with � symbols (`E:\Downloads\M�sica`)

**Expected behavior**
File Dialog should open the folder, as seen in the video with an example of a path without an accented character.

**Video**
https://user-images.githubusercontent.com/9060830/132999393-ad45c090-aac3-4ec8-9167-f1e851085f0e.mp4

**Desktop**
 - Windows 10 21H1 19043.1202
 - Fluent Search 0.9.88.9989

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.89.87

**Comment by TheFireRed** [comment]
Updated to version 0.9.89.87 and can confirm this is now working as intended. Thanks so much!
