### ISSUE TITLE
Can't Open Folder When Focused on Desktop

### ISSUE THREAD

**Issue by Chance92** [adirh3/Fluent-Search#289]
**Describe the bug**
FS can't open folders when invoked on desktop.

**To Reproduce**
1. Close all windows and go to desktop;
2. Click on desktop to make sure desktop is in focus;
3. Use hotkey to invoke FS;
4. Search for a folder and try to open it with enter key.

**Expected behavior**
FS should be able to open the folder regardless of focus.

**Screenshots**
None.

**Desktop (please complete the following information):**
 - Windows 10 Version: 21H1
 - Fluent Search Version 0.9.89.50

**Additional context**
The bug is consistent throughout the last few nightly releases.

**Comment by adirh3** [comment]
@Chance92 Does it happen on 0.9.89.55? I can't reproduce this

**Comment by Chance92** [comment]
Yes it happens on 0.9.89.55 as well. If I open a window or click on the task bar first, then FS works fine. I'll try a clean install later.

**Comment by adirh3** [comment]
> Yes it happens on 0.9.89.55 as well. If I open a window or click on the task bar first, then FS works fine. I'll try a clean install later.

No need to clean install, just needed to know it's reproducible on 89.55, thanks

**Comment by adirh3** [comment]
@Chance92 I still can't reproduce it, any chance it's somehow fixed?
@Nomad-0 can you repro it?

**Comment by Nomad-0** [comment]
no, I can't

**Comment by Chance92** [comment]
I managed to reproduce the bug on another computer running win10 and the latest version of FS. It's a bit strange. At first everything works fine even if I click on the desktop before invoking FS. However, after I moved the location of some items on the desktop, it starts to behave exactly like the previous computer.
Here's the desktop view setting of my old computer:
![image](https://user-images.githubusercontent.com/85488695/134765887-45a623c3-6e13-4809-8b1b-460eeabc5e00.png)

On the new computer, the "Auto arrange icons" setting is also checked.

**Comment by adirh3** [comment]
> @adirh3 It seems the bug is related to the option of 'Opening folders in existing explorer window'. After I turned it off, the bug no longer occurs.

Can't repro it on Win10/Win11, I recently changed something that might've solved that, can you confirm please?

**Comment by Chance92** [comment]
It seems to be fixed. Thank you.
