### ISSUE TITLE
 Remember the **size and position** of ALL windows (including plugin)

### ISSUE THREAD

**Issue by Metroid-Prime** [adirh3/Fluent-Search#29]
Title says it all. Remember the **size and position** of ALL windows (including plugin) after user changes it.

**Comment by Metroid-Prime** [comment]
Adjusted title & req per Adir's advice.

**Comment by adirh3** [comment]
@Metroid-Prime FS saves now all sizes, but position will not be saved after restart.
I don't think keeping position is expected behavior (also it's problematic technically).
So I am closing it, feel free to reopen if you disagree.

**Comment by Metroid-Prime** [comment]
Both are ideal, but size is much important than position IMO.

Thank you for implementing this and I agree with closure.
