### ISSUE TITLE
Issue with context menu

### ISSUE THREAD

**Issue by christubuntu** [adirh3/Fluent-Search#293]
**Describe the bug**
When I click "copy" in the context menu, FS will immediately launch another instance of the same context menu and will paste the copied file to the Explorer process in focus

**To Reproduce**
1. Launch a file search in FS
2. Right click and copy
3. FS launches the context menu again and immediately paste the file the focused Explorer process, in my case it's the desktop. If another directory was opened in Explorer, it would have pasted in that folder instead.

**Expected behavior**

**Screenshots**

https://user-images.githubusercontent.com/55885756/133880675-db319d34-a5aa-46ea-b35f-17781593374f.mp4

**Desktop (please complete the following information):**
 - Windows 10 Version: [e.g. 20H1]
 - Fluent Search Version [e.g. 0.9.89.70]

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.89.90
