### ISSUE TITLE
Trouble with Accent Picker

### ISSUE THREAD

**Issue by brimwats** [adirh3/Fluent-Search#295]
Somewhat related to #294 - I wanted to update my accent color to match the solarized theme. When I did that from here https://ethanschoonover.com/solarized/ using windows color picker (on the right) FS did not update: 

![image](https://user-images.githubusercontent.com/49103046/134046126-2bd9d425-c894-4b4f-a220-27e7d4094ab2.png)

**Comment by brimwats** [comment]
I also tried clicking the checkbox and without the #

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.89.90

**Comment by adirh3** [comment]
@brimwats Can you check if it's fixed for you?

**Comment by brimwats** [comment]
sorry for the delay! I can check in a day or so, travelling today :)

**Comment by adirh3** [comment]
No rush, hf :)

**Comment by brimwats** [comment]
it works!! thanks so much!
