### ISSUE TITLE
UI : when using monospace fonts, UI text is cropped at the end

### ISSUE THREAD

**Issue by cannibalox** [adirh3/Fluent-Search#297]
UI problem when user sets a monospace font : (see green arrows showing cropped pixels at the end of words)
![image](https://user-images.githubusercontent.com/4605693/134193074-76b859a0-02a3-41cb-925e-4409429bfff1.png)
![FluentSearch_Fluent_Search_20210921_1055_ddDStmUN6Q](https://user-images.githubusercontent.com/4605693/134193104-bf827343-5533-4e99-9190-e87abf7a50bd.png)

**Comment by adirh3** [comment]
@cannibalox should be fixed, re-open if it's not for you
