### ISSUE TITLE
Resize/Rescale Option "Smaller Size Feature Option"

### ISSUE THREAD

**Issue by mragtronx8** [adirh3/Fluent-Search#298]
an option to **resize/rescale** the search bar **SIZE** [search bar only OR full window]
FEATURE REQUEST to make size SMALLER "as per need"

reason for request: eye problem with big sizes

**Comment by IgnusG** [comment]
I think this is already done with the search bar only mode @mragtronx8?

![image](https://user-images.githubusercontent.com/6438760/134733367-02a159bd-393e-4cec-a37a-924667a3042f.png)

![image](https://user-images.githubusercontent.com/6438760/134733250-d4a115ab-4228-4318-8d37-f1d699a3f5d4.png)

**Comment by mragtronx8** [comment]
> I think this is already done with the search bar only mode @mragtronx8?
> 
> ![image](https://user-images.githubusercontent.com/6438760/134733367-02a159bd-393e-4cec-a37a-924667a3042f.png)
> 
> ![image](https://user-images.githubusercontent.com/6438760/134733250-d4a115ab-4228-4318-8d37-f1d699a3f5d4.png)

hello IgnusG,
thx for the tip. I know about your suggestion.
My request is to have the ability to rescale the search bar size.
There was a bug in fs when u disable animation; the bar size gets smaller "very neat to work with".

Best Regards,
Mragon

**Comment by IgnusG** [comment]
> > I think this is already done with the search bar only mode @mragtronx8?
> > ![image](https://user-images.githubusercontent.com/6438760/134733367-02a159bd-393e-4cec-a37a-924667a3042f.png)
> > ![image](https://user-images.githubusercontent.com/6438760/134733250-d4a115ab-4228-4318-8d37-f1d699a3f5d4.png)
> 
> hello IgnusG,
> thx for the tip. I know about your suggestion.
> My request is to have the ability to rescale the search bar size.
> There was a bug in fs when u disable animation; the bar size gets smaller "very neat to work with".
> 
> Best Regards,
> Mragon

Ahh I see, that might be a useful feature. The bug is tracked here https://github.com/adirh3/Fluent-Search/issues/302 and should now be fixed
