### ISSUE TITLE
Allow acrylic to be used instead of mica for the search window

### ISSUE THREAD

**Issue by IgnusG** [adirh3/Fluent-Search#299]
**Is your feature request related to a problem? Please describe.**
The mica background effect is pleasant when used as a decoration for windows - even larger surfaces as in the settings menu, but it's distracting on the search bar and results. Using a blank white or dark color is helpful in introducing separation between the search content and the surrounding windows next to it or below it. Adding acrylic to it was a nice touch. 

Mica however distorts this effect because we are suddenly digging into the screen and showing the background on an already busy environment.

**Describe the solution you'd like**
My understanding was that Mica would be used for larger surfaces and acrylic for smaller elements where appropriate. Granted the search results aren't exactly small but the search bar itself is and just opening it in the minimal mode creates a bit of a distraction from the actual task - searching.

In the image below we have a busy desktop with a maximized window on top of which fluent is opened. Since it now displays the blurred background we are bringing another color gradient to the forefront which is distracting.

![image](https://user-images.githubusercontent.com/6438760/134732238-47c15244-2133-43f5-a5d2-2153df4eb309.png)

I think it would ultimately be best to leave this up to the user to decide and allow for selecting acrylic along mica.

**Comment by adirh3** [comment]
@IgnusG Thanks for the in-depth explanation, using Acrylic effect in Windows 11 is available in the nightly builds. You can try that by changing release feed to `nightly` in Settings -> System, or you can install portable version of nightly build if you'd like to keep the normal stable version.
