### ISSUE TITLE
Indexed Paths buggy

### ISSUE THREAD

**Issue by Metroid-Prime** [adirh3/Fluent-Search#3]
When clicking + button under indexed paths in files tab in settings, the user cannot enter a directory until they close the settings window, re-open settings and navigate back to that setting. THEN one is able to click into the field and enter path

**Comment by adirh3** [comment]
I believe this is fixed, can you check @Metroid-Prime?

**Comment by Metroid-Prime** [comment]
> I believe this is fixed, can you check @Metroid-Prime?

Confirming fix. The + button now opens a file dialogue window, which in my opinion is much more user friendly! Thank you
