### ISSUE TITLE
Rebuild button

### ISSUE THREAD

**Issue by TreviSyn** [adirh3/Fluent-Search#300]
No rebuild button on setting\files (version 0.9.89.87)
![Cattura](https://user-images.githubusercontent.com/91346889/134732785-90a43690-4540-4a9b-9768-cea678eb8b5b.JPG)

**Comment by adirh3** [comment]
@TreviSyn You need to install the service so the index is initially built and then rebuild will be available.

**Comment by TreviSyn** [comment]
Tried but nothing happened. How to check if service is installed?

**Comment by adirh3** [comment]
> Tried but nothing happened. How to check if service is installed?

Did you install Fluent Search through the Microsoft Store or using Appx installer?
Currently there is an issue with installing services through Microsoft Store app installer for some suers, I suggest installing the EXE version - https://fluentsearch.net

**Comment by TreviSyn** [comment]
Installed exe version, make update and now all work correctly!
Thank you very much
I love your app :)

**Comment by adirh3** [comment]
> Installed exe version, make update and now all work correctly!
> Thank you very much
> I love your app :)

Np, glad you liked it :)
