### ISSUE TITLE
Moving the search bar in search bar only mode opens the result page

### ISSUE THREAD

**Issue by IgnusG** [adirh3/Fluent-Search#301]
**Describe the bug**
When moving the search bar an empty result page seems to open. It does not close until a search is performed (even when closed and opened again using the shortcut).

**To Reproduce**
1. Switch on minimal mode
2. Open Fluent Search
3. Move the search bar on the right edge (or somewhere where it lets you - would be nice if this would be allowed everywhere similar to the Mac Search bar but that's a feature request of itself)
4. An empty result page opens

**Expected behavior**
The result page should stay closed as no search was yet performed

**Screenshots**
![image](https://user-images.githubusercontent.com/6438760/134732979-aa5352ee-21af-4290-b770-50ccc584b8b6.png)

**Desktop (please complete the following information):**
 - Windows 11 Version: 21H2
 - Fluent Search Version 0.9.88.9989 (again with the suggestions in a bug report - I'm sorry - could we make the version number in About copiable?)

**Comment by adirh3** [comment]
@IgnusG I believe this should be fixed in the nightly builds as well, as I can't reproduce it.

**Comment by IgnusG** [comment]
Yap, closing
