### ISSUE TITLE
Disabling the window animation leaves the search bar in the initial animations size (not the final)

### ISSUE THREAD

**Issue by IgnusG** [adirh3/Fluent-Search#302]
**Describe the bug**
After disabling the window animation it appears that the search bar stays in the initial smaller size when opened. The background effects are not applied either.

Disabling all animations has the same effect.

**To Reproduce**
1. Disable window animations
2. Open search bar
3. Observe smaller size

**Expected behavior**
The search bar should have the final larger size instead of the smaller one.

**Screenshots**
Normal
![image](https://user-images.githubusercontent.com/6438760/134734563-1b0e540e-3c3c-4751-9214-701e6340d8e7.png)

With window animation disabled
![image](https://user-images.githubusercontent.com/6438760/134734616-317c0b85-05d7-49fc-9f33-a797b68efc75.png)

**Desktop (please complete the following information):**
 - Windows 11 Version: 21H2
 - Fluent Search Version 0.9.89.87

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.89.90

**Comment by adirh3** [comment]
@IgnusG Closing it, feel free to reopen if it's not fixed for you.

**Comment by Explorare** [comment]
Met the same issue on Windows 10 22H2 with Fluent Search 0.9.91.9994
![image](https://user-images.githubusercontent.com/5090766/215337276-59666c60-6b8c-4de5-9e37-33be4bd83e47.png)

**Comment by Explorare** [comment]
Relaunch the program solved the problem.
