### ISSUE TITLE
switching/changing tags in the right side panel, crashes fs

### ISSUE THREAD

**Issue by mragtronx8** [adirh3/Fluent-Search#303]
#BUG
switching/changing tags in the right side panel, crashes fs

![image](https://user-images.githubusercontent.com/62798102/134945590-ff97b801-6c3d-49b1-b399-49eb0d977e56.png)

when mouse clicking on any tag "right panel", FS will crash

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.89.98
