### ISSUE TITLE
Ms login

### ISSUE THREAD

**Issue by TreviSyn** [adirh3/Fluent-Search#306]
i tried todo feature giving access to MS account but after disable option on FS and remove permit from MS account, every time i launch FS, chrome open on MS login page

**Comment by adirh3** [comment]
@TreviSyn I will check it, for now try disabling Microsoft To-Do app, also did you click log out button in Settings?

**Comment by TreviSyn** [comment]
Sorry adirh, my fault :( I don't see logout button. I think that disable function disable access to MS account.
Very noob ^^
Love your app and make a little donation ;)
