### ISSUE TITLE
Start at startup doesn't work on APPX build

### ISSUE THREAD

**Issue by aukaheng** [adirh3/Fluent-Search#307]
**Describe the bug**
Enabling "Start at startup" doesn't work.

**Desktop (please complete the following information):**
 - Windows 11 Beta Channel (22000.194)
 - Fluent Search 0.9.89.98

**Additional context**
The Windows Installer build works properly.

**Comment by adirh3** [comment]
@aukaheng can you please check if it created a shortcut in the startup folder?
Run -> shell:startup

**Comment by aukaheng** [comment]
Yes it did.
"Fluent Search - Shortcut"

Clicking the shortcut doesn't run Fluent Search.
The shortcut is pointing to "FluentSearch.SideLoad_4139t8dvwn2ka!FluentS........"

**Comment by adirh3** [comment]
@aukaheng Thanks I will fix it, but I recommend using EXE version, as I plan to stop providing Appx soon.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.89.991
