### ISSUE TITLE
[Req] Pressing Down arrow key shows Pinned items in "Search bar only" mode

### ISSUE THREAD

**Issue by christubuntu** [adirh3/Fluent-Search#308]
As seen in the video below, launching FS in search bar only mode and pressing the down arrow key should show the pinned/suggested items

https://user-images.githubusercontent.com/55885756/135269956-8f8ad585-0194-498b-b1f9-2a14af1ae87f.mp4

.

**Comment by adirh3** [comment]
This is a bug, thanks
