### ISSUE TITLE
right side menu icons are not appearing properly, when menu is fitted

### ISSUE THREAD

**Issue by mragtronx8** [adirh3/Fluent-Search#309]
right side menu icons are not appearing properly, when menu is fitted [minimalistic & non-minimalistic] 

CORRECT DISPLAY
![image](https://user-images.githubusercontent.com/62798102/135311402-73cb4bc8-065a-4283-ab6f-31c8cbc8182c.png)

#BUG
![image](https://user-images.githubusercontent.com/62798102/135311449-6e628926-1342-4bd7-a81d-9f478d10807f.png)

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.89.991
