### ISSUE TITLE
Add "About" pane to bottom of settings.

### ISSUE THREAD

**Issue by Metroid-Prime** [adirh3/Fluent-Search#31]
Add "About" pane to the top pane of the left toolbar (where MS sign-in is now) and house a searchable and copy-able changelog.  Bonus points if you respect dark mode :)
![image](https://user-images.githubusercontent.com/1836362/122171778-f04afe80-ce34-11eb-9d8e-950bc2e806ce.png)

**Comment by Nomad-0** [comment]
I think the "about" pane should be on bottom instead of the top (e.g. Listary)

**Comment by mochigithub** [comment]
> I think the "about" pane should be on bottom instead of the top (e.g. Listary)


Agreed.  I am fine with About window being at the bottom as well.

**Comment by Metroid-Prime** [comment]
EDITED original picture post and added additional details needed.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.88.60

**Comment by Metroid-Prime** [comment]
Only thing that's missing is the changelog.  Is there a way to keep a page with all of the changelog information and have that available perhaps via link in the about box?

**Comment by adirh3** [comment]
> Only thing that's missing is the changelog. Is there a way to keep a page with all of the changelog information and have that available perhaps via link in the about box?

Like this? https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search/distribution_groups/exe

**Comment by Metroid-Prime** [comment]
> > Only thing that's missing is the changelog. Is there a way to keep a page with all of the changelog information and have that available perhaps via link in the about box?
> 
> Like this? https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search/distribution_groups/exe

I remember this, but it doesn't include nightly releases.   Nightly releases should be included with a nightly tag. Perhaps also have a changelog link in the about box?

**Comment by Metroid-Prime** [comment]
Closing this as it's been added as an **i** info box in the later versions of FS
![image](https://user-images.githubusercontent.com/1836362/149641408-2246c99e-95ac-41d0-b8c4-b99d39a98097.png)
