### ISSUE TITLE
files/results appearing  in right side menu

### ISSUE THREAD

**Issue by mragtronx8** [adirh3/Fluent-Search#311]
when viewing for example an app/.exe; 
files/results "that do not belong in the menu" are appearing 

#Bug
![image](https://user-images.githubusercontent.com/62798102/135314288-998d9b27-85c5-4127-9109-2e61a1ccae92.png)

**Comment by Nomad-0** [comment]
@adirh3 is this file history?

**Comment by mragtronx8** [comment]
> @adirh3 is this file history?

yes "files appearing, are from history".
 
these files have been deleted from my system.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.89.991
