### ISSUE TITLE
Fuzzy Search Results

### ISSUE THREAD

**Issue by IgnusG** [adirh3/Fluent-Search#312]
**Is your feature request related to a problem? Please describe.**
When I search for stuff I sometimes make typos if I try to type quickly like: `dege` instead of `edge` (app search) or `digrams` instead of `diagrams` (file search) and `termnal` instead of `terminal` (process switching).

**Describe the solution you'd like**
It would be nice if fluent search would detect these and either offer something along the lines of `Did you mean: ...` or if it was integrated into the machine learning algorithm (I'm not familiar how those systems are connected). Just something so that searching for a slightly misspelled entry can still produce relevant results.

**Alternatives you've considered**
Maybe something like levenshtein distance or algorithms based on it can be used to compare the results but I'm not familiar with how resource intensive this might be. 

**Additional context**
I'm unsure how feasible this is. It might be too complex to implement. Would be a cool feature though 😅 - haven't seen many system search apps do this, yet almost every browser search engine does.

**Comment by kidimbwi** [comment]
great request, would love to see this in Fluent Search.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.60                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by kidimbwi** [comment]
not the original requester but i'd like to thank you for implementing this feature. have tested this and so far, from my limited testing, it works as requested. Thank you again for adding this ability to FS.
