### ISSUE TITLE
prioritization "very high" not saving

### ISSUE THREAD

**Issue by mragtronx8** [adirh3/Fluent-Search#314]
prioritization "very high" not saving #BUG

when going to prioritization, and selecting very high; i have to choose it twice to select "very high", first time it gives blank. 

![image](https://user-images.githubusercontent.com/62798102/135723974-5dcaeb53-0aef-4dcb-9577-bdbd5adc15fe.png)

and after i select very high and set it; it will go away when i close and reopen settings again
very high not SAVING

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.89.993

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.89.9931
