### ISSUE TITLE
Add a minimize button to the downloading dialog when updating Fluent Search

### ISSUE THREAD

**Issue by kidimbwi** [adirh3/Fluent-Search#317]
**Is your feature request related to a problem? Please describe.**
when a new version is downloading, the dialog box showing the progress cannot be minimized. i have to move it out of the way until the download completes and i can start the installation.

**Describe the solution you'd like**
add a minimize button to the downloading update dialog box.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.89.9950

**Comment by kidimbwi** [comment]
> This issue has been potentially fixed in version 0.9.89.9950

minimize button confirmed when updating to version 0.9.89.9955, Thank you again for the quick implementation of this feature.
