### ISSUE TITLE
Search Bar Shortkeys

### ISSUE THREAD

**Issue by mragtronx8** [adirh3/Fluent-Search#318]
#Bug - version 0.9.89.9950
when using ctrl+ctrl or shift+shift in search / in app search [shortcut keys]
the search bar is not fading away "when i go away from the search bar, and press/click somewhere else", unless something is typed in the bar or i press a mouse click on the bar itself; then it fades out.
 
Otherwise the search bar remains hovering.

**Comment by adirh3** [comment]
@Nomad-0 Could you repro it?
