### ISSUE TITLE
Every time my system boots up, I get asked to give Fluent Search admin access

### ISSUE THREAD

**Issue by sguergachi** [adirh3/Fluent-Search#321]
**Describe the bug**
when I run Fluent Search i get interrupted by a "Give Admin Access" dialogue box. I dont want to see this dialogue box each time I startup.
**To Reproduce**
1. Set the app to startup and restart computer, it will show an admin box refering to "Indexer" something.

**Expected behavior**

I expect the app to run silently in the background

**Screenshots**

I cant get a screenshot of the admin dialogue unfortunately

**Desktop (please complete the following information):**
 - Windows 10 Version: [e.g. 20H1]
 - Fluent Search Version [e.g. 0.9.80.0]

**Additional context**

**Comment by sguergachi** [comment]
This is still an issue with the MS store version. Will it ever be fixed there?

**Comment by adirh3** [comment]
> This is still an issue with the MS store version. Will it ever be fixed there?

I am trying my best, but the Microsoft Store is problematic for this kind of app.
Can you please check if the service is installed now?

**Comment by sguergachi** [comment]
I already installed the appx version and it seems to be there. I'm not sure if the MS store version fixed it.

**Comment by adirh3** [comment]
> I already installed the appx version and it seems to be there. I'm not sure if the MS store version fixed it.

The Microsoft Store and Appx should be the same, do you get UAC prompt now?

**Comment by adirh3** [comment]
Closing, should work with Appx installation now. Feel free to reopen.
