### ISSUE TITLE
Fluentsearch doest not get focus after restart

### ISSUE THREAD

**Issue by urql** [adirh3/Fluent-Search#322]
**Describe the bug**
hotkey bring fluent up but not giving focus to search. have to manually select fluent search to type.
this only happens after restart. subsequent hotkey invocation works correctly.

**To Reproduce**
1. Restart Computer
2. Press predefined hotkey
3. start typing

**Expected behavior**
I can search directly after hitting the hotkey after restart

**Desktop (please complete the following information):**
 - Windows 10 Version: 21H1
 - Fluent Search Version 0.9.89.9950

**Comment by IgnusG** [comment]
I have a similar problem when some Windows UI is in front of the search bar. For example when I open the wifi panel and press the shortcut fluent appears but the wifi panel stays open and keeps its focus until you manually click on fluent - that closes the wifi panel and focuses fluent. Maybe something similar is happening to you and a Windows UI element is taking the focus after restart?

**Comment by urql** [comment]
update to version 0.9.89.9975, the issue persists. only after restart though. subsequent invocation works fine.

**Comment by XuShenLZ** [comment]
I observed the same thing in version 0.9.89.9990, OS version Win 11 21H2 22000.348.
The search box doesn't have focus when restarting Fluent Search (reboot the computer for sure also does that).

**Comment by adirh3** [comment]
Should be fixed, if not reopen.
