### ISSUE TITLE
When will the software support Chinese interface?

### ISSUE THREAD

**Issue by ttxhxz** [adirh3/Fluent-Search#323]
1、I mean the software interface and the text of the settings in Chinese
2、It is not the same as questions #148  and #153  , please do not merge them together

**Comment by nutnutwin** [comment]
> > 1、I mean the software interface and the text of the settings in Chinese 2、It is not the same as questions #148 and #153 , please do not merge them together
> 
> I plan to translate Fluent Search to multiple languages sometime after 1.0.0, don't have any ETA though

Do you need any help with translation? I can help with Simplified Chinese and Japanese

**Comment by adirh3** [comment]
> > > 1、I mean the software interface and the text of the settings in Chinese 2、It is not the same as questions #148 and #153 , please do not merge them together
> > 
> > 
> > I plan to translate Fluent Search to multiple languages sometime after 1.0.0, don't have any ETA though
> 
> Do you need any help with translation? I can help with Simplified Chinese and Japanese

You have amazing timing.
I was just posting on Discord asking for help with translation.
Please join the Discord server and post translations - https://discord.gg/W2EuWvD6GD

Thanks!

**Comment by nutnutwin** [comment]
@adirh3 Great! 
Not familiar with Discord, but will see what I can do!

**Comment by adirh3** [comment]
@ttxhxz updating that the interface is almost fully translated to Chinese in 0.9.91.x nightly version.
If you can please check it out and let me know if you have any feedback.

**Comment by ttxhxz** [comment]
> @ttxhxz updating that the interface is almost fully translated to Chinese in 0.9.91.x nightly version. If you can please check it out and let me know if you have any feedback.

Wow, I just saw this news today, very excited, I have re-downloaded the beta version of the software, the stable version I downloaded before almost missed this news. I'll try it out today, and if you have any questions, I'll give you feedback~
