### ISSUE TITLE
color tuning

### ISSUE THREAD

**Issue by mragtronx8** [adirh3/Fluent-Search#329]
color tuning # Bug
when i first launch fs, and wait for it to load.
and then goto setting appearance to tune border color.
FIRST TIME: am able to enter and edit the color. "it works"
![image](https://user-images.githubusercontent.com/62798102/137597796-dcb805c5-bb1f-4e95-96d3-8e1c0308ba35.png)

but when i close the setting, and reopen settings again; to "maybe" want to modify the color.
here "on second edit / re-tune", FS CRASHES and exits

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.89.9965
