### ISSUE TITLE
Requesting Feature or Plug-in for Shutting Down/Sleeping/Restarting PC and for Switching User or Logging Out.

### ISSUE THREAD

**Issue by attaboyBrad** [adirh3/Fluent-Search#330]
As the title says...

I'd love if FS had feature or plugin for common operations like "sign-out", "switch user", "shut down", "restart", etc. I have different user accounts on my desktop for work and personal use and switch between them a dozen or more times per day.  Right now I've got Ueli re-installed and I only use it for that feature.

**Comment by attaboyBrad** [comment]
Thanks Nomad. I was thinking of something more direct that what you describe, but it turns out it was already there: if I just type in 'shutdown' a shortcut to Command shows up and I can just hit enter twice on the result to shut down.  My mistake for not seeing it earlier.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.0

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.1

**Comment by attaboyBrad** [comment]
It has! Thanks very much.
