### ISSUE TITLE
Limit scope of access to OneDrive for Sync

### ISSUE THREAD

**Issue by hmnd** [adirh3/Fluent-Search#336]
**Is your feature request related to a problem? Please describe.**
Sync currently requests full read/write (`onedrive.readwrite` scope) permissions to the user's OneDrive. This is a potential security concern.

**Describe the solution you'd like**
Support the `onedrive.appfolder` scope instead, which limits Sync's scope to files created by the Fluent Search.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.0

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.1
