### ISSUE TITLE
Ad hoc hotkey to open folders in new Explorer window from search result

### ISSUE THREAD

**Issue by ryanmholmes** [adirh3/Fluent-Search#340]
Sometimes, I like to open folders in an existing Explorer instance. Other times, I want to open a folder search result in a new instance. Often, these different desires occur back-to-back in a work session, but there is currently no ad hoc option for this. 

There is a great new setting that allows some choice: open all directories in a new window. However, that eliminates the option to use folder search to navigate down within the same open Explorer window, which is also useful.

The current default behavior appears to be that open directory from a search result opens said result in the focused Explorer window or even in any other non-minimized Explorer window. When all Explorer windows are minimized, default behavior is to open a new instance of Explorer.

I'd like a hotkey within each folder search result beneath Open Directory (Ctrl+2 by default) called Open Directory in New Window. It could be Ctrl+3 by default but be configurable as with all other hotkeys.

Then I could keep the typical behavior for folders to open within the current Explorer window so I can navigate down a file tree with the keyboard quickly. But I could also choose to quickly open additional instances as needed along the way - without changing the global setting.

Thank you, Adir! Great work.

**Comment by adirh3** [comment]
@ryanmholmes why is this closed? That's a good suggestion I was planning to do something similar

**Comment by ryanmholmes** [comment]
Hey, @adirh3. This is also Rhino on Discord btw. I would love that! But I realized after posting that I don't really understand the current behavior as well as I thought. It seems erratic to me...I can't figure out under what circumstances it's opening directory results in a new Explorer window vs. an existing one.
