### ISSUE TITLE
Hidden on Startup

### ISSUE THREAD

**Issue by hced** [adirh3/Fluent-Search#347]
**Is your feature request related to a problem? Please describe.**
When starting up, Fluent's search window is shown in its full glory.

**Describe the solution you'd like**
I'd like Fluent's window to be hidden oon startup.

Here's my current setting (start minimized) which doesn't seem to kick in:

![Snag_3d2b1075](https://user-images.githubusercontent.com/93350/139239855-6693c1d8-11b3-4b90-8228-a394dddcc919.png)

Fluent version: 0.9.89.9990
Windows 10 Pro: version 21H1

**Comment by adirh3** [comment]
@hced Sorry for the late reply, I still can't repro this.
Would be appreciated if you can send me your Settings directory in a zip in `%appdata%\Blast\Settings` in a PM (through mail support@fluentsearch.net or Discord adirh3#9979)

**Comment by hced** [comment]
> @hced Would be appreciated if you can send me your Settings directory in a zip 

Preferences sent via email 20 seconds ago. ;-)

**Comment by adirh3** [comment]
@hced Thanks.
Two questions -
1. Does it happen only on system startup? Or also when you just normally launch FS?
2. If it happens only on system startup - can you double check that the version that's loading is the portable one.

**Comment by hced** [comment]
> @hced Thanks. Two questions -
> 
> 1. Does it happen only on system startup? Or also when you just normally launch FS?
> 2. If it happens only on system startup - can you double check that the version that's loading is the portable one.

1. Only on system startup. Not when double-clicked in the OS.
2. Affirmative, it's the portable version.

**Comment by hced** [comment]
@adirh3 

The fault was entirely me! I had somehow manually placed the link to the app in the autostart folder. Removing the manual file solved the issue. (It triggered a double-open it seems.)
![Snag_64161](https://user-images.githubusercontent.com/93350/143621113-1471cba1-1575-4890-8baf-58e1509fd722.png)

**Comment by adirh3** [comment]
> @adirh3
> 
> The fault was entirely me! I had somehow manually placed the link to the app in the autostart folder. Removing the manual file solved the issue. (It triggered a double-open it seems.) ![Snag_64161](https://user-images.githubusercontent.com/93350/143621113-1471cba1-1575-4890-8baf-58e1509fd722.png)

FS was opened twice or was one of the shortcuts pointing to a different installation that didn't have StartMinimized toggle?

**Comment by hced** [comment]
> > @adirh3
> FS was opened twice or was one of the shortcuts pointing to a different installation that didn't have StartMinimized toggle?

Yes, opened twice. The manually created .lnk shortcut pointed to `"C:\Portable\Fluent Search\fluent-search-portable\FluentSearch.exe"` and the application-created to the exact same executble.
