### ISSUE TITLE
Ctrl Shift C cannot use by other software while Fluent Search running

### ISSUE THREAD

**Issue by Lutra-Fs** [adirh3/Fluent-Search#349]
**Describe the bug**
`Ctrl-Shift-C` cannot use by 1Password 8.4.0 while Fluent Search running. without fluent search, the password can be put into the clipboard correctly with a keyboard shortcut.
I have checked the settings and there is no `Ctrl-Shift-C` in Fluent Search Settings.
**To Reproduce**
1. Press `Ctrl-Shift-Space` to open quick access of 1Password.
2. Select an item
3. Press `Ctrl-Shift-C `(copy password)
4. No response
**Expected behavior**
Copy the password correctly.

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 10 Version: Windows 11 22489
 - Fluent Search Version 0.9.89.1

**Comment by adirh3** [comment]
@Lutra-Fs it's set by copy context in Settings -> Advanced -> Context.
I will add a page you can see all set hotkeys, it's much needed.

**Comment by Lutra-Fs** [comment]
Yeah, thanks for clarifying. I set the key bind to another one. Now everything works again! ☺️
