### ISSUE TITLE
Transparency is on while set at none

### ISSUE THREAD

**Issue by trungng2006** [adirh3/Fluent-Search#351]
**Describe the bug**
Fluent search  is opaque while the transparency effect is set on None

**To Reproduce**
I  was messing with the theme and different ways to choose accent color (system color is off)

**Expected behavior**
![image](https://user-images.githubusercontent.com/71961905/139718607-926cae66-a44e-49f5-a7c9-5c297d86a409.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/71961905/139717282-316c8761-afe7-43f1-bdf1-f146dc18fc4f.png)

**Desktop (please complete the following information):**
 - Windows 11 Version: KB5006746
 - Fluent Search Version 0.9.90.11

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.22

**Comment by trungng2006** [comment]
This is fixed for me. 
Thank you!

**Comment by adirh3** [comment]
Closing as the fix has been released and confirmed working. If you're still experiencing this on the latest version, please reopen.
