### ISSUE TITLE
Unable to scroll till the last row on Home Screen

### ISSUE THREAD

**Issue by MakeshVineeth** [adirh3/Fluent-Search#353]
**Describe the bug**
In more recent versions of FS, Scrolling is not working till the last row on Home Screen. It will not even show any scroll bar on hover.

**To Reproduce**
1. Launch FS
2. Make sure Home Screen is enabled with `Suggestion rows` set to 0 (default setting)
3. Check Scrolling on Home Screen
4. See error.

**Expected behavior**
A Scroll Bar should be visible on hover and it also be able to scroll till the last row.

**Screenshots**

As you can see from below video, there is one more last row beneath the 4th one, but no scrolling to it.

https://user-images.githubusercontent.com/19371684/140272462-c06e304a-feec-424f-a1bf-53f3c2762a49.mp4

I had to resize the window, to make it appear now like this:

![image](https://user-images.githubusercontent.com/19371684/140273435-136a37e5-f5a0-4f27-8c5f-ad4e79fcdcfb.png)

**Desktop Version:**
 - Windows 11 Version: 22000.282
 - Fluent Search Version: 0.9.90.11

**Comment by adirh3** [comment]
@MakeshVineeth should be solved on latest nightly, reopen if not
