### ISSUE TITLE
Delayed custom previews will be shown on wrong search results

### ISSUE THREAD

**Issue by MakeshVineeth** [adirh3/Fluent-Search#354]
**Describe the bug**
Consider we have a custom preview that will take a while either due to networks calls or other delays & if users scroll to a different result in the meantime, that custom preview will be shown on different results. Please check screen recording for better understanding.

**To Reproduce**
1. Search for any result that has a delay for loading custom preview (e.g., Wikipedia Results)
2. Hover onto that delayed result and immediately scroll to a different result.
3. Make sure you're scrolling even before the custom preview is loaded.
4. See error. Preview of another result will be shown on different results.

**Expected behavior**
If user scrolls to a different result in the meantime, the custom preview that is **yet** to be loaded should be discarded & correct result has to be shown.

**Screen recording**

https://user-images.githubusercontent.com/19371684/140278322-04e0e6ed-fcdb-4d60-9ba5-a38c48799750.mp4

**Desktop information:**
 - Windows 11 Version: 22000.282
 - Fluent Search Version: 0.9.90.11

**Comment by adirh3** [comment]
@MakeshVineeth can you still repro this? I can't on latest nightly version

**Comment by MakeshVineeth** [comment]
Still facing the issue in the latest version.

FS Version: 0.9.91.76

**Comment by adirh3** [comment]
> Still facing the issue in the latest version.
> 
> FS Version: 0.9.91.76

Still showing the wrong preview? Or you mean it shows in delay?

**Comment by MakeshVineeth** [comment]
> > Still facing the issue in the latest version.
> > 
> > FS Version: 0.9.91.76
> 
> Still showing the wrong preview? Or you mean it shows in delay?

Yeah it shows in delay and in the meantime, if we change to a different result, the old result will be shown on that.

**Comment by adirh3** [comment]
> > > Still facing the issue in the latest version.
> > > FS Version: 0.9.91.76
> > 
> > 
> > Still showing the wrong preview? Or you mean it shows in delay?
> 
> Yeah it shows in delay and in the meantime, if we change to a different result, the old result will be shown on that.

Ok finally got to repro that, will fix it.
In general I think it's better to return the control immediately and load data from wiki in background, it will translate to better experience for the user

**Comment by MakeshVineeth** [comment]
Yeah that would be nice, if there are some search results that have delayed previews, FS can return any generic result and update it when the preview is ready.

**Comment by adirh3** [comment]
> Yeah that would be nice, if there are some search results that have delayed previews, FS can return any generic result and update it when the preview is ready.

That would be a bit akward IMO, I meant that you can build the WIKI preview without the description (title, buttons) and in the description write `Loading..`, return that control, and then in the background load the info from Wikipedia and update it.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.76                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.77                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by MakeshVineeth** [comment]
Will make 

> > Yeah that would be nice, if there are some search results that have delayed previews, FS can return any generic result and update it when the preview is ready.
> 
> That would be a bit akward IMO, I meant that you can build the WIKI preview without the description (title, buttons) and in the description write `Loading..`, return that control, and then in the background load the info from Wikipedia and update it.

Yeah, will bring in some changes in Wiki plugin to improve the loading experience. And in the latest version, delayed previews on wrong results has been fixed, thank you for fixing and closing this issue :)
