### ISSUE TITLE
Wrong system tray icon color

### ISSUE THREAD

**Issue by Dominiquini** [adirh3/Fluent-Search#356]
**Describe the bug**
My system tray icon is black. It should be white!

**To Reproduce**
1. Open Fluent Search with system tray icon enabled
2. View the icon

**Expected behavior**
Icon should be white. Or I should be able to change it!

**Screenshots**
![KNbzTgGbtI](https://user-images.githubusercontent.com/1180808/140969836-682fdfc4-8206-49e9-b46b-52cec71686c8.png)

**Desktop (please complete the following information):**
 - Windows 10 Version: 21H1 (OS Build 19043.1320)
 - Fluent Search Version: 0.9.90.15

**Additional context**
I tested the exe and appx installers!

**Comment by adirh3** [comment]
@Dominiquini Is your Windows colors (theme) is set to Dark for both apps and Windows?

**Comment by Dominiquini** [comment]
Windows Mode -> Dark
App Mode -> Light

* I see here that the icon change to white if I select the Dark for the 'App Mode'! But I thing that the icon should decide it's color based on the 'Windows Mode', like all other apps do!

Thanks

**Comment by adirh3** [comment]
> Windows Mode -> Dark App Mode -> Light
> 
> I see here that the icon change to white if I select 'Dark' for the 'App Mode'! But I thing that the icon should decide it's color based on the 'Windows Mode', like all other apps do!
> 
> Thanks

Thanks for confirming, I wish it was simple, but the Windows API is always reporting the App mode unfortunately. 
By other apps, do you know other apps that change their icon based on Windows theme?

**Comment by Dominiquini** [comment]
Dropbox, for example, change the icon color based on the 'Windows Mode' settings! Some other icons too, like the Volume and WiFi icons!

**Comment by adirh3** [comment]
> Dropbox, for example, change the icon color based on the 'Windows Mode' settings! Some other icons too, like the Volume and WiFi icons!

Ok thanks, will look into it

**Comment by Dominiquini** [comment]
Maybe it's simple to allow us select the icon color manually!

Thanks.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.20

**Comment by Dominiquini** [comment]
In the Appearance menu, in the Colors section, if I select 'Use System Colors', this app should use the 'App Mode' settings, which in my case is 'Light', but is now showing 'Dark'! If I select manually the color scheme to 'Light', works fine!
The icon color that needs to verify the 'Windows Mode' and choose the opposite color, for contrast!

Thanks.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.22

**Comment by Dominiquini** [comment]
> 
> 
> This issue has been potentially fixed in version 0.9.90.22

Appears to be working now!

Thanks.
