### ISSUE TITLE
Option to bring back the search icon instead of the fluent search icon

### ISSUE THREAD

**Issue by IgnusG** [adirh3/Fluent-Search#358]
**Is your feature request related to a problem? Please describe.**
The new icon is nice but it would be cool to have an option to switch back to the old search icon. I prefer it in the minimal setup.

**Additional context**
Brought in with version 0.9.90.20 I think

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.31                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by IgnusG** [comment]
![image](https://user-images.githubusercontent.com/6438760/159159745-f6d65d2d-af0c-4b8e-89c7-cf1c4235591f.png)

👌👌
