### ISSUE TITLE
Shadow is very prominent (intense with low spread)

### ISSUE THREAD

**Issue by IgnusG** [adirh3/Fluent-Search#359]
**Describe the bug**
The shadow of fluent search is by far the most prominent one from all apps which can become distracting to some degree.
It would be nice if it was softer or if an option was given to tweak it's intensity.

**Expected behavior**
Shadow is not as prominent or is configurable.

**Screenshots**
### Shadow for files

![image](https://user-images.githubusercontent.com/6438760/141115718-d389e78e-b6a0-4ceb-9d81-71530885a3d5.png)

### Shadow for terminal (which itself has quite a large shadow - but not as intense)

![image](https://user-images.githubusercontent.com/6438760/141115808-13081e66-b001-4a9e-888e-9018135ba2ed.png)

### Fluent search shadow

![image](https://user-images.githubusercontent.com/6438760/141115836-c24fbc0a-d9b5-471b-9f2c-e4dbb3994abc.png)

**Desktop (please complete the following information):**
 - Windows Version: Windows 11 21H2 (22000.282)
 - Fluent Search Version 0.9.90.20

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.22

**Comment by u-Sir** [comment]
> 
> 
> This issue has been potentially fixed in version 0.9.90.22

still difference with other app

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.25

**Comment by IgnusG** [comment]
Wow, the change is like night and day:

Version 0.9.90.22

![image](https://user-images.githubusercontent.com/6438760/141678074-f648e1bd-e26e-45fc-8f0a-79df1018664a.png)

New Version 0.9.90.25

![image](https://user-images.githubusercontent.com/6438760/141678095-4ac45c09-aaee-4497-b473-e663b589ee6f.png)

Like it a lot ❤️
