### ISSUE TITLE
About window Text Difficult to Read w/ Dark Mode

### ISSUE THREAD

**Issue by Metroid-Prime** [adirh3/Fluent-Search#36]
Make text "privacy policy" and "fluentsearch.net" more  readable than current dark blue 

![image](https://user-images.githubusercontent.com/1836362/120909580-3630e700-c62b-11eb-8524-7f31e968ab64.png)

**Comment by adirh3** [comment]
@Metroid-Prime I believe this is more readable with the recent color changes right?

**Comment by Metroid-Prime** [comment]
> @Metroid-Prime I believe this is more readable with the recent color changes right?
@adirh3  Please forgive me, did I miss a feature recently? My about menu in v. x70 I see the same thing. 

![Uploading image.png…]()

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.85.85

**Comment by Metroid-Prime** [comment]
Confirming & closing.
Looks beautiful
![image](https://user-images.githubusercontent.com/1836362/122702977-6d93bc00-d205-11eb-942b-9ed892d2bcb9.png)
