### ISSUE TITLE
FR: Make autoupdate or less UAC demands.

### ISSUE THREAD

**Issue by brimwats1** [adirh3/Fluent-Search#360]
I figured i'd file a FR for this, but when FS updates I need to click download, approve the UAC and then do the UAC when it launches again. I had to do this twice today, so would love to have to do it less or not at all.

**Comment by adirh3** [comment]
@brimwats, using the latest nightly, install FS **not** in program files, and you will have only 1 UAC which is to **start** the indexer service after an update.
Let me know if it works for you.

**Comment by brimwats** [comment]
where do I install it then? I just went with default. this is a fr for the default

**Comment by adirh3** [comment]
> where do I install it then? I just went with default. this is a fr for the default

When opening the installer press "install only for me", you will see it doesn't have a UAC icon.
You will have to uninstall the current version for it to show.

**Comment by brimwats** [comment]
I don't want to install it only for me, I want to install it for multiple users. You mentioned in discord that you intended to remove one but it hasn't happened (which is fine, it's not a stress!) so this FR exists as a reminder and a ticket for that.

**Comment by adirh3** [comment]
@brimwats just ping me on Discord to discuss this

**Comment by brimwats** [comment]
> @brimwats just ping me on Discord to discuss this

I can do that, here is where we talked about it originally and you said you'd fix:
https://discord.com/channels/740636963396124714/740636963836788818/890760247168352286

but it's no worries if i just need to reinstall. is there a way to reinstall that will get it in the right place (i.e. not double uac)

feel free to close this if needed

**Comment by adirh3** [comment]
> > @brimwats just ping me on Discord to discuss this
> 
> I can do that, here is where we talked about it originally and you said you'd fix: https://discord.com/channels/740636963396124714/740636963836788818/890760247168352286
> 
> but it's no worries if i just need to reinstall. is there a way to reinstall that will get it in the right place (i.e. not double uac)
> 
> feel free to close this if needed

Yes, I was not aware you installed on program files, so I thought it might be a bug.
After further checking it should show only 1 UAC when installing on non-program files.

Let me know if it still shows two UAC after reinstalling, thanks.

**Comment by adirh3** [comment]
@brimwats Closing this, let me know if you feel this can somehow improve.

Here is a technical explanation of each UAC -
1. When installed in Program Files, UAC is a must to write there, you can decide to not install there to avoid it.
2. The indexer is a service, to stop/start/install services UAC is necessary. I could split the indexer to a different installation to avoid that, but that would make FS almost twice the size and would require an additional updater for it.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.92.68                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by brimwats** [comment]
working for me!
