### ISSUE TITLE
When I hit CTRL + V to paste into the search field it dismiss the search screen

### ISSUE THREAD

**Issue by sguergachi** [adirh3/Fluent-Search#361]
- Hit Alt + Space to open Fluent Search
- Hit Ctrl + V and the screen dismisses

**Comment by adirh3** [comment]
@sguergachi it's since there is a default keyboard shortcut for pasting text for some results, I may disable it when the search bar is in focus

**Comment by sguergachi** [comment]
Yeah it's confusing because this is a flow I expect to work. Copy some text and do a quick search for it in fluent search via keyboard.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.22
