### ISSUE TITLE
Appearance "Custom" Transparency Set To NONE

### ISSUE THREAD

**Issue by mragtronx8** [adirh3/Fluent-Search#362]
Appearance "Custom" Transparency Set To NONE **is not working**
#BUG
![image](https://user-images.githubusercontent.com/62798102/141339203-422dd949-a332-474e-908c-7d9e6c83a4ce.png)
![image](https://user-images.githubusercontent.com/62798102/141338857-605910d8-eb5c-4a4d-8fa3-a56fe0b6777c.png)

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.22
