### ISSUE TITLE
Invalid indexer Windows Search

### ISSUE THREAD

**Issue by Ao-Last** [adirh3/Fluent-Search#370]
**Describe the bug**
After changing the indexer to `windows search`, searching for files failed.
**To Reproduce**
1. Go to Fluent Search Settings -> Search Applications -> Files -> File indexer
2. Choose Windows search
3. Close the setting and typing the search keyword
4. See no match result.

**Screenshots**

![Snipaste_2021-11-15_11-34-08](https://user-images.githubusercontent.com/63785048/141719729-5dca53c7-9b2f-4ad9-a851-a3f071b942b7.png)

**Desktop (please complete the following information):**
 - Windows 10 Version:  21H1
 - Fluent Search Version: 0.9.89.9990

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.33                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
