### ISSUE TITLE
Remove insignificant extra zeros from the calculation result in the Calculator

### ISSUE THREAD

**Issue by vinnlee** [adirh3/Fluent-Search#372]
**Describe the bug**
I don't want to see extra zeros after the calculation result as well as when copying the result.

**Expected behavior**
Don't show those extra zeros after the calculation result.

Example:

- 0.700 become 0.7
- 0.12345 stay 0.12345

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.45

**Comment by vinnlee** [comment]
@adirh3 Has version 0.9.90.45 been released?
I'm on version 0.9.89.9990 but when I click "check for updates". It just says "Your current version is up to date".

**Comment by adirh3** [comment]
> @adirh3 Has version 0.9.90.45 been released? I'm on version 0.9.89.9990 but when I click "check for updates". It just says "Your current version is up to date".

It's part of the `nightly` release feed, which are daily releases and less stable.
You can update to it by changing the `Release feed` in Settings -> System.

**Comment by vinnlee** [comment]
Just changed the `Release feed` to `nightly` and updated to the latest version (0.9.90.78).
Confirmed the issues now resolved.
