### ISSUE TITLE
Add hotkey setting to travel in the search results

### ISSUE THREAD

**Issue by fanhwid** [adirh3/Fluent-Search#374]
Please consider add a hotkey setting, so user could use "CTRL+N" to select the next search result item, and use "CTRL+P" to select the previous search result item.
thanks!

**Comment by fanhwid** [comment]
@adirh3 @Nomad-0 Please consider add this fearure in the daily build, TKS

**Comment by fanhwid** [comment]
@adirh3 Long time passed, will you consider this enhancement or not?

**Comment by adirh3** [comment]
> @adirh3 Long time passed, will you consider this enhancement or not?

Yes, sorry there are too many issues opened so I missed few.
Feel free to bump issues here or in Discord.

On topic, can you describe what would be the advantages over arrow keys? Also, will you set it to be the same hotkey as the search hotkey?
I planned to add open to use the search hotkey to go to next result (like Ctrl+R in Linux), but adding dedicated hotkey might be even more customizable.

**Comment by fanhwid** [comment]
> > @adirh3 Long time passed, will you consider this enhancement or not?
> 
> Yes, sorry there are too many issues opened so I missed few. Feel free to bump issues here or in Discord.
> 
> On topic, can you describe what would be the advantages over arrow keys? Also, will you set it to be the same hotkey as the search hotkey? I planned to add open to use the search hotkey to go to next result (like Ctrl+R in Linux), but adding dedicated hotkey might be even more customizable.

OK, If I can use "CTRL+N" and "CTRL+P" to move to the next and previous search result, My finger don't need to leave the keyboard. For now, I have to move my right hand to the "Arrow“ key to select the other search result.
I think it's a good idea leaving the hotkey customizable.

**Comment by Metroid-Prime** [comment]
I don't understand this request.  Can you illustrate it with a screenshot.  You want to select the next search result with CONTROL + N?  Instead of arrows?

**Comment by fanhwid** [comment]
> I don't understand this request. Can you illustrate it with a screenshot. You want to select the next search result with CONTROL + N? Instead of arrows?

Not instead. Like in listary or flow launcher, We could use either way. 
In Listary/Flow Launcher, I could also use "CTRL+J/K", in a vim-like style.
So I think it's better to leave the hotkey customizable.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.33                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
