### ISSUE TITLE
The Chinese don't support well, It don't display correctly

### ISSUE THREAD

**Issue by fanhwid** [adirh3/Fluent-Search#376]
![image](https://user-images.githubusercontent.com/72638192/143252687-a157b418-2648-40a3-b567-9a63a3902cf5.png)
When I Input Chinese in the search window, it don't display correctly, like in the picture.
Please Consider fix it.
Thinks

**Comment by adirh3** [comment]
@fanhwid Please change your font family to font that supports Chinese.
In Settings -> Appearance -> Font family, change to something like `Microsoft YaHei`
