### ISSUE TITLE
Translator plugin tags are showing even though the plugin is turned off

### ISSUE THREAD

**Issue by Mr-Frankenstein** [adirh3/Fluent-Search#38]
![Capture](https://user-images.githubusercontent.com/85425543/120912626-6a99b700-c6ae-11eb-9a47-c9064e9debbf.PNG)
![image](https://user-images.githubusercontent.com/85425543/120912627-6ec5d480-c6ae-11eb-9a12-5b25fa4ad6dc.png)

**Comment by mochigithub** [comment]
I can confirm, but this happens to ALL of the  search apps and plugins, not just translate! 
This is a high priority bug
![image](https://user-images.githubusercontent.com/1836362/120915393-3b585b00-c658-11eb-84b5-3024a0af9400.png)

**Comment by mochigithub** [comment]
I believe this is also the same as issue #1

**Comment by mochigithub** [comment]
Closing per Najah (Mr. F's) request.  Reopened my ticket #1  as it's the same issue. Applying duplicate label.
