### ISSUE TITLE
tasks panel background becomes transparent

### ISSUE THREAD

**Issue by u-Sir** [adirh3/Fluent-Search#380]
**Describe the bug**
tasks panel background becomes transparent(even Transparency effect is Mica)

**To Reproduce**
1. go to tasks panel

**Expected behavior**

**Screenshots**
![图片](https://user-images.githubusercontent.com/93647031/144429783-404b425c-6313-4243-83d0-816c19c5c2b4.png)

**Desktop (please complete the following information):**
 - Windows 11 Version: 21H2
 - Fluent Search Version 0.9.90.54

**Additional context**

**Comment by adirh3** [comment]
@u-Sir does it still happen?

**Comment by u-Sir** [comment]
> @u-Sir does it still happen?

fixed in 0.9.90.62
