### ISSUE TITLE
Love the app, almost worth paying for.

### ISSUE THREAD

**Issue by L0garithmic** [adirh3/Fluent-Search#381]
Just missing a few small things.

As much as yours does better then Listiary, it is missing the basic functions.
I search for Adobe. It gives me this hodge podge list of adobe programs, missing half my programs. It's ugly and shows the word App in front of every result. Listiary just showed me all my Adobe apps right away, just by name. Without tags being shown, which I can not find how to turn off.

You have the ability to set a priority for a certain tag. That is good. Now let me apply priority to the app itself to LOW.. I know it learns with AI. But I don't want to wait that long and hope the app works. It keeps suggesting the wrong apps! xD

So close to perfect man.

**Comment by adirh3** [comment]
> Just missing a few small things.
> 
> As much as yours does better then Listiary, it is missing the basic functions. I search for Adobe. It gives me this hodge podge list of adobe programs, missing half my programs. It's ugly and shows the word App in front of every result. Listiary just showed me all my Adobe apps right away, just by name. Without tags being shown, which I can not find how to turn off.
> 
> You have the ability to set a priority for a certain tag. That is good. Now let me apply priority to the app itself to LOW.. I know it learns with AI. But I don't want to wait that long and hope the app works. It keeps suggesting the wrong apps! xD
> 
> So close to perfect man.

Thanks for the feedback!
I made few changes in the nightly versions to improve search for scenarios like this.
Can you please share a screenshot of the search results, when they are not ordered as you expected?

**Comment by L0garithmic** [comment]
I just realized that you can, in advanced settings, set minimalist user interface... This should NOT be advanced lol.. It should be recommended during setup!!! It would make your program much more modern feeling. Also, fixed most the issues I had with search aesthetics. 

But, it created a new issue. There are now no priority or pinning buttons. It went TOO minimal lol.
Also... The option to set a search result to LOW priority would be a game changer.

Here. This is exactly what should be done.
![Search Results](https://user-images.githubusercontent.com/1237743/144716592-ad1b926b-967f-4880-b8e2-c3145ab3cf5d.jpg)
me

**Comment by L0garithmic** [comment]
I just realized that you can, in advanced settings, set minimalist user interface... This should NOT be advanced lol.. It should be recommended during setup!!! It would make your program much more modern feeling. That fixed most the issues I had with search aesthetics. 

HOWEVER.. it created a new issue. There are now no priority or pinning buttons. It went TOO minimal lol.
Also... One of the biggest things missing is an option to set a search result to LOW priority would be a game changer.

Here. This is how the gui should look
![final99](https://user-images.githubusercontent.com/1237743/144718449-bceee2c8-9bdd-4be3-ad16-e09cf8c83ca3.png)

Edit: Tweaking image. Deleted an important layer. Also I am a perfectionist.
Edit 2: Deleted old post. This is what I ultimately wanted to post and it was a WIP in mah brain.. 
Also, quite the masterpiece if I don't say so myself lol..

**Comment by adirh3** [comment]
> I just realized that you can, in advanced settings, set minimalist user interface... This should NOT be advanced lol.. It should be recommended during setup!!! It would make your program much more modern feeling. That fixed most the issues I had with search aesthetics.
> 
> HOWEVER.. it created a new issue. There are now no priority or pinning buttons. It went TOO minimal lol. Also... One of the biggest things missing is an option to set a search result to LOW priority would be a game changer.
> 
> Here. This is how the gui should look ![final99](https://user-images.githubusercontent.com/1237743/144718449-bceee2c8-9bdd-4be3-ad16-e09cf8c83ca3.png)
> 
> Edit: Tweaking image. Deleted an important layer. Also I am a perfectionist. Edit 2: Deleted old post. This is what I ultimately wanted to post and it was a WIP in mah brain.. Also, quite the masterpiece if I don't say so myself lol..

Thanks for the detailed feedback, much appreciated!

Let me start with the design, actually it is changed in nightly builds as well, here how it looks like by default - 
![image](https://user-images.githubusercontent.com/27368554/144720434-870535cb-90f0-41d1-8680-c440dc7cf730.png)
In the future I plan to let users customize what appears in each part of the screen, as every user has different preference to how it looks.
I understand your point about "advanced", the search tags used to not show by default, and due to that user never learnt how to use them. Since adding that by default the search tags feature has been used much more.
You can also achieve something similar to "Best Ultimate Minimal Mode" (lol), by dragging the search results separator to the right - 
![image](https://user-images.githubusercontent.com/27368554/144720624-acb1ccfa-7b1e-4c95-a1ac-22645e7a76a4.png)

As for the adobe results, not sure I totally understand, you search for `adobe` and only adobe apps are showing, how would Fluent Search know which one you prefer if you don't click on them?
After you select a result, it will show higher in the list, that's how Listary works as well.
If it is not working for you, it would be helpful if you can try the nightly version (Settings -> System -> Release feed) as I am working on improving this and need more feedback for the most recent version.
Note - the nightly feed is less stable.

**Comment by L0garithmic** [comment]
I completely agree on the "how would it know which one I prefer unless I click on it..". It couldn't. So my solution is to have an option. Where I manually tell fluent search that.  Certain results I like LESS then anything else. Instead of having to click all 6 apps I want to be on top. I'd rather select the 2 I don't want and add a -1 click weight to them lol. Like if I had clicked on everything else in the whole app but that haha.

It would also work incase I click on something a lot for a while but then don't want it to show up on top anymore, rather then outright banning it or removing it from the results

Also for the record. Listary ain't got sh*t on your app lol. Just needs some tweaking to make it best. During the initial install guide demo thing. Maybe include the note that you can enable minimal mode or. Just don't hide it behind advanced. 🤷‍♂️

**Comment by L0garithmic** [comment]
Is it me or is the most recent nightly stuck in transparent mode with no way to turn it of
![Screenshot_1](https://user-images.githubusercontent.com/1237743/144732287-4376cf46-6a25-4f73-99b6-bb4af26c28bb.png)

**Comment by adirh3** [comment]
> I completely agree on the "how would it know which one I prefer unless I click on it..". It couldn't. So my solution is to have an option. Where I manually tell fluent search that. Certain results I like LESS then anything else. Instead of having to click all 6 apps I want to be on top. I'd rather select the 2 I don't want and add a -1 click weight to them lol. Like if I had clicked on everything else in the whole app but that haha.
> 
> It would also work incase I clicked on something a lot for a while but then don't want it to show up on top anymore, rather then outright banning it or removing it from the results
> 
> Also for the record. Listary ain't got sh*t on your app lol. Just needs some tweaking to make it best. During the initial install guide demo thing. Maybe include the note that you can enable minimal mode or. Just don't hide it behind advanced. 🤷‍♂️
> 
> Also... Had NO idea that pane was resizeable haha. Nice! I'm dumb.. If it was an option where it just. Resized the panel lol it could be a "feature" haha

So, your suggestion is to have a "like" and "dislike" buttons? That's in addition the "pin" button? I thought about that previously, but didn't want to add too many buttons lol
As for the transparency bug it will be fixed in today's nightly.

**Comment by L0garithmic** [comment]
Essentially yeah. Sure. Like/dislike button lol. Also, yeah I get it, too many icons is ugly. Maybe put it in a right click menu or something. Or have it be an option to turn on and off if nobody wants. Or, have ALL buttons be turn on and off-able so people can have ALL TEH BUTTONZ or be like hashtag:NoButtons lol

Idk how hard gui changes are in your backend. You seem to have FANTASTIC control though and be a fricken genius when it comes to all of this so... Props.

New nightly fixed the transparency bug.

**Comment by adirh3** [comment]
> 

Thanks again for the feedback, it's appreciated!
Will probably add like/dislike buttons eventually with customization options.
Also, the "Other" section in Settings is a bug in nightly.

BTW if you'd like to join the Discord server to easily share any feedback/ask questions - https://discord.gg/W2EuWvD6GD
