### ISSUE TITLE
Jump to the current working folder when saving files

### ISSUE THREAD

**Issue by XuShenLZ** [adirh3/Fluent-Search#383]
**Is your feature request related to a problem? Please describe.**
When downloading or saving files, we want to direct to the current "working" folder to save them. But it is not possible now to use Fluent Search to do so.

**Describe the solution you'd like**
When I am using Listary + DOpus, I just need to press Ctrl+G when prompted to choose file saving location, and Listary will automatically change it to the current active folder in DOpus.  

**Describe alternatives you've considered**
Currently, when saving files, I tried toggle Fluent Search, manually type the current folder name, and choose "open directory". Sometimes it will work and open the directory in the "saving" dialog, but sometimes not. This seems to be a bug too. But anyway a more instant way to point to the current working folder in the file explorer, either native/Files/DOpus will be the best.

**Additional context**

**Comment by adirh3** [comment]
@XuShenLZ I assume this feature request is specifically for DOpus, as Explorer navigation is supported (simply search for folder and open it)
In the latest nightly version, I added support for "copying" path from one Explorer window using a hotkey (like Ctrl+G in Listary).
Support for more file managers will come in a future version.

**Comment by XuShenLZ** [comment]
Thanks! I am following the nightly version and discord. Have been enjoying this function for a while. Sorry for forgetting to close this issue. Thanks for the amazing work!

**Comment by standin000** [comment]
> @XuShenLZ I assume this feature request is specifically for DOpus, as Explorer navigation is supported (simply search for folder and open it) In the latest nightly version, I added support for "copying" path from one Explorer window using a hotkey (like Ctrl+G in Listary). Support for more file managers will come in a future version.

Dose the stable version 0.9.91.9995 have this feature, I can not find the hotkey for it, thanks!

**Comment by adirh3** [comment]
> > @XuShenLZ I assume this feature request is specifically for DOpus, as Explorer navigation is supported (simply search for folder and open it) In the latest nightly version, I added support for "copying" path from one Explorer window using a hotkey (like Ctrl+G in Listary). Support for more file managers will come in a future version.
> 
> Dose the stable version 0.9.91.9995 have this feature, I can not find the hotkey for it, thanks!

Yes it's in Settings -> Context (need to enable Avanced) -> Paste context hotkey
