### ISSUE TITLE
Add browse button to Open and Open folder in tasks

### ISSUE THREAD

**Issue by kidimbwi** [adirh3/Fluent-Search#386]
**Is your feature request related to a problem? Please describe.**

when adding a file or folder in the tasks window we have to copy its path into the File name or file path entry box.

**Describe the solution you'd like**

would like to see a browse for file or folder button added so that users can be able to browse to files or folders they want to add to a task.

**Additional context**

![Dialog 1](https://user-images.githubusercontent.com/65897337/144994721-9fc807f9-04d8-4216-9c85-54e593ccf1bf.png)

![Dialog 2](https://user-images.githubusercontent.com/65897337/144994847-7211a56e-b76d-4a8a-8a44-ee3736542b89.png)

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.72

**Comment by kidimbwi** [comment]
i'm running version 0.9.90.78 and the boxes appear to still be the same with no browse button available.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.83

**Comment by adirh3** [comment]
Closing this feel free to reopen if I misunderstood
