### ISSUE TITLE
Feat. Req.: Auto-hide

### ISSUE THREAD

**Issue by STaRDoGG** [adirh3/Fluent-Search#389]
Would love to see an auto-hide option added, where the FS window hides when it's clicked off of.

**Comment by adirh3** [comment]
@STaRDoGG sorry for the late response, this is already available in Settings -> Search 0-> Hide when losing focus.
![image](https://user-images.githubusercontent.com/27368554/147850824-1a28ecf5-c0f5-476d-9499-40033987bc56.png)
Feel free to reopen if I misunderstood.
