### ISSUE TITLE
Hide search window on hotkey isn't working

### ISSUE THREAD

**Issue by Nomad-0** [adirh3/Fluent-Search#39]
**the bug**
when I press hotkey, the search window doesn't close. confirmed by **ZeStig** on discord.

**To Reproduce**
Open Fs.
Try to close fs pressing hotkey

**Screenshots**
![image](https://user-images.githubusercontent.com/76395594/120914292-19de8a00-c6bf-11eb-913e-28bd50238ad3.png)

**Desktop (please complete the following information):**
 - Windows 10 Version: [21H1]
 - Fluent Search Version [0.9.85.1]

**Comment by mochigithub** [comment]
Can confirm. I changed my hotkey to Ctrl + Space and that opens FS but does not close it even with setting on.

**Comment by adirh3** [comment]
This_issue_has_been_potentially_fixed_in_version_

**Comment by Nomad-0** [comment]
Issue fix confirmed. Closing.
