### ISSUE TITLE
Feat Req: Syntax highlighter 

### ISSUE THREAD

**Issue by STaRDoGG** [adirh3/Fluent-Search#390]
A plugin to syntax highlight all the usual/common source code extensions in the preview window.

It would make searching for specific snippets of code when doing a search MUCH easier.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.993

**Comment by STaRDoGG** [comment]
@adirh3 awesome! I installed via the Windows Market; how long until it'll pick up the update?

**Comment by Metroid-Prime** [comment]
> @adirh3 awesome! I installed via the Windows Market; how long until it'll pick up the update?

I have portable and I got the new version via auto-updater

**Comment by adirh3** [comment]
> @adirh3 awesome! I installed via the Windows Market; how long until it'll pick up the update?

Hey! This update is still not available through the Microsoft Store as it's not stable yet.
To get nightly updates, you must install Fluent Search using the EXE/Portable installation (links in website) and then change the release feed in Settings -> System -> Release feed to Nightly.
The stable update will come to the Microsoft Store in the next two weeks.
