### ISSUE TITLE
tasks connect window can't scroll by wheel

### ISSUE THREAD

**Issue by u-Sir** [adirh3/Fluent-Search#391]
**Describe the bug**
tasks connection window can't scroll by wheel

**To Reproduce**
1. right click on any trigger,select connect

**Expected behavior**
scroll

**Screenshots**
![图片](https://user-images.githubusercontent.com/93647031/145500389-1b56d64c-4e37-4313-847d-72d91dfb6142.png)

**Desktop (please complete the following information):**
 - Windows 11 Version: 21H2
 - Fluent Search Version 0.9.90.68

**Additional context**

**Comment by adirh3** [comment]
@u-Sir should be fixed on latest nightly, can you confirm please?
