### ISSUE TITLE
support searching bookmarks and history from firefox

### ISSUE THREAD

**Issue by u-Sir** [adirh3/Fluent-Search#393]
**Is your feature request related to a problem? Please describe.**
Now FS can't search bookmarks and history from firefox.

**Describe the solution you'd like**
support searching bookmarks and history from firefox .

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.30                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
