### ISSUE TITLE
add option to open url with specific browser

### ISSUE THREAD

**Issue by u-Sir** [adirh3/Fluent-Search#394]
**Is your feature request related to a problem? Please describe.**
I want to open url in different browser when i have dual screen.

**Describe the solution you'd like**
add option to open url with specific browser
![图片](https://user-images.githubusercontent.com/93647031/146669817-a75d2e40-3bea-4355-8a49-100eb538d15b.png).
![图片](https://user-images.githubusercontent.com/93647031/146669846-7c1238c2-932f-498a-b89e-7b975658c1ea.png)

**Comment by adirh3** [comment]
@u-Sir you can do that with open file operation, by using the exe of the browser and the URL  as argument

**Comment by u-Sir** [comment]
> @u-Sir you can do that with open file operation, by using the exe of the browser and the URL as argument

but just like last pic, sometime i want to open url with specific browser after typing.

**Comment by adirh3** [comment]
> > @u-Sir you can do that with open file operation, by using the exe of the browser and the URL as argument
> 
> but just like last pic, sometime i want to open url with specific browser after typing.

Yes you can do that, just instead of using open URL, use open file and open the browser with arguments. 
You can add that to all `http` search results using the Result selector trigger.

**Comment by u-Sir** [comment]
> > > @u-Sir you can do that with open file operation, by using the exe of the browser and the URL as argument
> > 
> > 
> > but just like last pic, sometime i want to open url with specific browser after typing.
> 
> Yes you can do that, just instead of using open URL, use open file and open the browser with arguments. You can add that to all `http` search results using the Result selector trigger.

fine, i will try it.
