### ISSUE TITLE
web search not show empty 

### ISSUE THREAD

**Issue by u-Sir** [adirh3/Fluent-Search#396]
**Describe the bug**
web search not show empty

**To Reproduce**
1. add web search "https://www.baidu.com/s?wd="
2. launch fs and type tag name and press `tab`
3. the results not empty , see the follow pics

**Expected behavior**
the results show empty when switch to web search tag

**Screenshots**
![图片](https://user-images.githubusercontent.com/93647031/147304180-01183220-516f-48a6-a48a-5fc5aa9482ff.png)
![图片](https://user-images.githubusercontent.com/93647031/147304185-87558a40-8516-41b8-bd8a-9cdea12d82c2.png)

**Desktop (please complete the following information):**
 - Windows 11 Version: 21H2
 - Fluent Search Version :0.9.90.75
**Additional context**

**Comment by adirh3** [comment]
@u-Sir Custom search tags are not exclusive, so setting `b` as search tag will also search for files with `b` as extension.
I suggest using the full name `Baidu` as search tag, as it will most likely not require most key pressed (type `b` then FS will suggest Baidu).
Also, you can set ignored file extension in Settings -> Files -> Ignored file extensions 
![image](https://user-images.githubusercontent.com/27368554/147982233-85eb2046-e721-433d-8490-33878f762c16.png)

**Comment by u-Sir** [comment]
> @u-Sir Custom search tags are not exclusive, so setting `b` as search tag will also search for files with `b` as extension. I suggest using the full name `Baidu` as search tag, as it will most likely not require most key pressed (type `b` then FS will suggest Baidu). Also, you can set ignored file extension in Settings -> Files -> Ignored file extensions ![image](https://user-images.githubusercontent.com/27368554/147982233-85eb2046-e721-433d-8490-33878f762c16.png)

ok
