### ISSUE TITLE
Currency converter

### ISSUE THREAD

**Issue by hazardousthingy** [adirh3/Fluent-Search#399]
An idea for a plugin to be able to convert currency in Fluent search on the fly

![82392659-10f22a80-9a62-11ea-9a31-4ddac05327c1](https://user-images.githubusercontent.com/11718983/148287948-bca75585-ea4b-47b0-8c31-ba0f89aca646.png)

**Comment by eikaramba** [comment]
i am coming from ueli and this is the only feature currently missing. so yes, that would be great, one could use the same code from ueli and the api service to quickly transform the values

**Comment by eikaramba** [comment]
i build this functionality now with the task functionality. works great, input "13 EUR in USD" into the search and you get the amount :) unpack the yaml file into your tasks directory to use
[convert currencies.zip](https://github.com/adirh3/Fluent-Search/files/8010277/convert.currencies.zip)
