### ISSUE TITLE
Single Intro help window slightly too small

### ISSUE THREAD

**Issue by Metroid-Prime** [adirh3/Fluent-Search#40]
Please make this intro window slightly bigger. It has an unnecessary scrollbar when the window could be made a little bigger.
![image](https://user-images.githubusercontent.com/1836362/120914616-3beef280-c654-11eb-9839-089d948d6b67.png)

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.85.75

**Comment by Metroid-Prime** [comment]
Can confirm fix. Closing
