### ISSUE TITLE
Fluent Search Settings : square icon’s right side is erased

### ISSUE THREAD

**Issue by adrienm7** [adirh3/Fluent-Search#400]
**Describe the bug**
It’s a little issue, but it’s always better to solve it. So, when the settings page of FS is opened, the square button (to put in fullscreen) isn’t exactly a square. The right side is kinda erased (cf. screenshot below).

**To Reproduce**
1. Go to the Settings

**Screenshots**
![image](https://user-images.githubusercontent.com/49562406/148416413-b9066137-0142-4046-ae82-0562afbbd3a4.png)

**Desktop (please complete the following information):**
 - Windows 10
 - Fluent Search Version : 0.9.80

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.90

**Comment by adrienm7** [comment]
I updated to the latest version. The issue is indeed fixed.
Thanks.
