### ISSUE TITLE
icons in prioritization setting show square

### ISSUE THREAD

**Issue by u-Sir** [adirh3/Fluent-Search#402]
**Describe the bug**
icons in prioritization setting show square

**To Reproduce**
1. Go to fs settings --> advanced --> prioritization
2. see the square

**Expected behavior**
icons show correctly

**Screenshots**
![图片](https://user-images.githubusercontent.com/93647031/148481655-b38993da-ad81-46af-9207-2df64b2000ee.png)

**Desktop (please complete the following information):**
 - Windows 11 Version: 21H2
 - Fluent Search Version 0.9.90.90

**Additional context**

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.91
