### ISSUE TITLE
FS <> everything pipe stuck ?

### ISSUE THREAD

**Issue by cannibalox** [adirh3/Fluent-Search#404]
**Describe the bug**
using Everything indexer on nightly FS (+ everything 1.5 beta, win 10 ltsc21h2) : 
I can use some Everything functions in FS like `contents:mysearch` (which pulls indexed file contents from Ev), but if I try to use an everything function like `focal-length:24mm`, that runs for a long time : 
- I get no results in FS (but there are hits in Everything 1.5)
- after that, the pevious `contents:mysearch` doesn't return any result either
- then FS doesn't return any results from my NAS at all, and I need to restart FS. I can still search on local drives normally  though

it seems that the long query makes FS buggy.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.91

**Comment by cannibalox** [comment]
confirmed, thank you for the fix !

**Comment by gitthangbaby** [comment]
in all August builds, Everything search takes like 30s to produce one result. In total, it finds only little, and nothing from network drives. Is FS connecting to Everything or just trying to search its database?

**Comment by adirh3** [comment]
> in all August builds, Everything search takes like 30s to produce one result. In total, it finds only little, and nothing from network drives. Is FS connecting to Everything or just trying to search its database?

Do you use Everything 1.5 or 1.4? can you please try to revert FS version to see if that's what caused the issue

**Comment by gitthangbaby** [comment]
> Do you use Everything 1.5 or 1.4? can you please try to revert FS version to see if that's what caused the issue
Using Everything 1.4.1.1018 (can't see 1.5 anywhere), and Fluent Search 0.9.91.9995 stable and then 0.9.92.20 to 44. Slow and limited results every time sadly.
