### ISSUE TITLE
web search icon not totally change

### ISSUE THREAD

**Issue by u-Sir** [adirh3/Fluent-Search#405]
**Describe the bug**
web search icon not totally change

**To Reproduce**
1. see the pic below
![图片](https://user-images.githubusercontent.com/93647031/148627300-e1db873c-51a6-4a14-b864-50729c8d19c5.png)

**Desktop (please complete the following information):**
 - Windows 11 Version: 21H2
 - Fluent Search Version 0.9.90.91

**Additional context**

**Comment by adirh3** [comment]
Reopening, haven't fixed it

**Comment by adirh3** [comment]
lol I guess I did fix it and forgot
