### ISSUE TITLE
Add DuckDuckGo to "Web suggestion provider" as option.

### ISSUE THREAD

**Issue by Metroid-Prime** [adirh3/Fluent-Search#408]
(Assuming the entry is working) works: 

Add DuckDuckGo to "Web suggestion provider".  Leave Google as default .
Entry (without quotes)   "https://ac.duckduckgo.com/ac/?q=%s&type=list"

![image](https://user-images.githubusercontent.com/1836362/148733376-d352fdf2-c674-40fa-bbcd-b6271f74056b.png)

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.94

**Comment by Metroid-Prime** [comment]
Updated to latest version, but cannot confirm
![image](https://user-images.githubusercontent.com/1836362/148904901-e5dd37e7-b896-4cc8-afdf-3ff047d2f933.png)

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.95

**Comment by Metroid-Prime** [comment]
Still seeing same thing (No DDG) in .95
