### ISSUE TITLE
Ability to sort in web searches

### ISSUE THREAD

**Issue by Metroid-Prime** [adirh3/Fluent-Search#409]
Pic explains it all:
![image](https://user-images.githubusercontent.com/1836362/148734051-a74a6de7-f42a-43c8-8543-f4f9ae86c341.png)

Clicking it, sorts, clicking again sorts the opposite way as most users would expect. The image column ((2nd) I don't  think should be sortable

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.94

**Comment by Metroid-Prime** [comment]
Thank you, I can confirm. I hope the issue we spoke about with sorting issues doesn't come back!  
Closing ticket
