### ISSUE TITLE
***GITHUB*** Please add "UI/UX improvement" option

### ISSUE THREAD

**Issue by mochigithub** [adirh3/Fluent-Search#41]
What do you all think? 

Should we add a 3rd option to FS's Github  when clicking new issue:

Bug Reports
Feature Request 
 **UI/UX improvement?**

**Comment by Nomad-0** [comment]
agree, also another one dedicated to posts related to plugins only

**Comment by mochigithub** [comment]
> agree, also another one dedicated to posts related to plugins only

Agreed! Plugins option would be useful too.



One caveat though -- if the user were allowed to apply labels, I would be fine with having plugin  or UI/UX enhancement  labels. This is how Flow Launcher github does it, but only the devs seem to be able to apply the label :(

**Comment by mochigithub** [comment]
We've added the following labels, so I'm closing this 
![image](https://user-images.githubusercontent.com/1836362/120919528-f5f35800-c66e-11eb-988a-03e886b5edae.png)
