### ISSUE TITLE
Tag text disappear when resizing column

### ISSUE THREAD

**Issue by Metroid-Prime** [adirh3/Fluent-Search#410]
![image](https://user-images.githubusercontent.com/1836362/148734890-98da0488-fb30-4d46-bbc6-10ec5188cedd.png)

![image](https://user-images.githubusercontent.com/1836362/148734901-bf82c1cd-3538-4ce6-8407-44cf0b70c24c.png)

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.94

**Comment by Metroid-Prime** [comment]
You're on fire today Adir!  Confirming fix. Closing!
