### ISSUE TITLE
Add Description Column in Map Searched Tag column

### ISSUE THREAD

**Issue by Metroid-Prime** [adirh3/Fluent-Search#411]
Pic says it all:

PM me on discord if it doesn't make sense :)

Should help the user describe what the search tag is for (Like Listary - which has this)
![image](https://user-images.githubusercontent.com/1836362/148745659-d86efae7-384e-4a71-be72-f830fb523c0e.png)

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.94

**Comment by Metroid-Prime** [comment]
Can confirm. You even put the column by default at end which is even better :)

Closing!
