### ISSUE TITLE
ui not totally loaded

### ISSUE THREAD

**Issue by u-Sir** [adirh3/Fluent-Search#414]
**Describe the bug**
ui not totally loaded

**To Reproduce**
1. Go to FS settings--> Web
2. See error

**Expected behavior**

**Screenshots**
![图片](https://user-images.githubusercontent.com/93647031/148877100-dde2a825-6c32-47dc-8237-9ebafe5841b9.png)
![图片](https://user-images.githubusercontent.com/93647031/148877135-1dec0208-8bbe-4f7a-b3fc-0d2cfbc2208c.png)

**Desktop (please complete the following information):**
 - Windows 11 Version: 21H2
 - Fluent Search Version 0.9.90.94
**Additional context**

**Comment by adirh3** [comment]
Thanks @u-Sir, is it consistent?
Do you have multiple monitor setup? if so does it happen like that on every screen?

**Comment by u-Sir** [comment]
> 
yes,it always happened when i go to `Web` . 
no , i 'm using single monitor now.

**Comment by u-Sir** [comment]
> Thanks @u-Sir, is it consistent? Do you have multiple monitor setup? if so does it happen like that on every screen?

if i switch to other setting page the setting ui work well. it only happened in `Web` setting page.

**Comment by adirh3** [comment]
> > Thanks @u-Sir, is it consistent? Do you have multiple monitor setup? if so does it happen like that on every screen?
> 
> if i switch to other setting page the setting ui work well. it only happened in `Web` setting page.

Thanks can you please share your screen DPI and resolution? (Can check that in Windows system settings)

**Comment by u-Sir** [comment]
> > > Thanks @u-Sir, is it consistent? Do you have multiple monitor setup? if so does it happen like that on every screen?
> > 
> > 
> > if i switch to other setting page the setting ui work well. it only happened in `Web` setting page.
> 
> Thanks can you please share your screen DPI and resolution? (Can check that in Windows system settings)
3840x2160 scaled 150%

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.96
