### ISSUE TITLE
Some Icons showing up small (RAR)

### ISSUE THREAD

**Issue by Metroid-Prime** [adirh3/Fluent-Search#415]
Running latest nightly. 

Adir - this was on the work computer (Windows 10 Version 1909    Build 18363.1801).   Reproducible.  
![image](https://user-images.githubusercontent.com/1836362/149038703-0934cff4-6c72-4755-8627-71b537a9e433.png)

The RAR file is an example of the small icon that makes it look a bit unsightly.

**Comment by adirh3** [comment]
Thanks, it's duplicate with #177 so closing this (you can subscribe in #177 for notification)
