### ISSUE TITLE
Focus on Fluent Search hit or miss on hotkey activation

### ISSUE THREAD

**Issue by toddletoon** [adirh3/Fluent-Search#416]
**Describe the bug**
When opening Fluent Search using my hotkey (Ctrl - Ctrl), the search bar shows as normal, but the keyboard is still "connected" to the previous app. Typing in the search box doesn't work until I manually click into Fluent Search to start typing. It happens most often when quickly starting to type after hitting the hotkey. This can happen with any app but I found Adobe apps produce the bug more often.

**To Reproduce**
1. Engage Fluent Search with hotkey _(Ctrl - Ctrl)_
2. Start typing anything - Fluent Search does not get keyboard focus

**Expected behavior**
Fluent Search takes notice of the keyboards input as soon as I engage Fluent Search with hotkey.

**Desktop (please complete the following information):**
 - Windows 10 21H2 (19044.1415)
 - Fluent Search (Nightly) 0.9.90.95

**Comment by adirh3** [comment]
@toddletoon please read my comment of #406 
Keep this open, I might be able to fix it eventually. But for now I recommend not using Ctrl+Ctrl

**Comment by toddletoon** [comment]
Oops didn't see that. I only saw a different one that didn't describe the problem the same way I was invoking it. I'll try a different key for now.

**Comment by toddletoon** [comment]
I should ask before I forget, which keys on the keyboard can be used to create hotkeys? I want to be able to use a key that I can hit in quick succession (such as the buggy Ctrl+Ctrl). I would also like to use keys that are less used, and I noticed that keys such as Pause Break and Scroll Lock can't be used.

**Comment by adirh3** [comment]
> I should ask before I forget, which keys on the keyboard can be used to create hotkeys? I want to be able to use a key that I can hit in quick succession (such as the buggy Ctrl+Ctrl). I would also like to use keys that are less used, and I noticed that keys such as Pause Break and Scroll Lock can't be used.

All keys other than `Escape` and `Tab` should work, if not please open a different issue for it.
In general the recommended hotkey is `Ctrl+Alt`, but I am using `Win` as hotkey as I don't use the start menu.
