### ISSUE TITLE
Settings Improvements

### ISSUE THREAD

**Issue by rajat-r** [adirh3/Fluent-Search#417]
These are rather low priority, but would be nice to have when you have a free moment..

- The Settings window loses its custom size when FS is exited and reloaded (though it retains it during the session). Would be nice if it stuck.
- It's really cool that FS provides a very easy way to change the Font throughout the app, though if the font selection list had the fonts actually listed in that actual font, it'd get much easier to pick the right one. (If this leads to increase in memory consumption, best would be to load/unload those fonts only when displaying that list)

Cheers!

**Comment by adirh3** [comment]
Thanks for the feedback @rajat-r!

1. You can retain the Settings window size by enabling `Keep window size after restart` in Settings -> Appearance (advanced)
2. Not sure what you mean by "actual font", are the Fonts shown in Settings -> Appearance -> `Font family` misses some fonts you have installed in Windows?

**Comment by rajat-r** [comment]
Hey @adirh3 !
1. Yes I already have that enabled. Maybe it matters that I'm running FS portable?
2. No I don't mean some fonts are missing - here, let me explain via pictures

This is FS
![image](https://user-images.githubusercontent.com/5120628/149180679-6ad5488b-e444-4102-8814-6233d4c37d89.png)

This is another app
![image](https://user-images.githubusercontent.com/5120628/149180742-09a25e6e-f40d-4a79-bd4a-3cb097ddfac7.png)

(but like I said, low priority - just a nice to have feature, not need to have)

**Comment by adirh3** [comment]
> Hey @adirh3 !
> 
> 1. Yes I already have that enabled. Maybe it matters that I'm running FS portable?
> 2. No I don't mean some fonts are missing - here, let me explain via pictures
> 
> This is FS ![image](https://user-images.githubusercontent.com/5120628/149180679-6ad5488b-e444-4102-8814-6233d4c37d89.png)
> 
> This is another app ![image](https://user-images.githubusercontent.com/5120628/149180742-09a25e6e-f40d-4a79-bd4a-3cb097ddfac7.png)
> 
> (but like I said, low priority - just a nice to have feature, not need to have)

Oh, you're using the nightly version? The height not saving is a bug, will fix it in today's update.
Now I understand what you mean about the font, thanks for the images. Will change it soon.
Thanks!

**Comment by rajat-r** [comment]
> Oh, you're using the nightly version? 

Yes! I want the latest and greatest! Also, can't have you telling me it's already fixed hahha

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.96

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.96

**Comment by rajat-r** [comment]
Wow @adirh3! You're sure lightning fast! I just tested them out and the improvements look amazing!

I'm going to put this one just here, because it's very related to the above fonts update. I noticed that the font scale slider is very difficult to work with - it jumps the whole UI when you try to move it using mouse (because it tries to update in realtime, while it should wait for the mouse button to let go first), and it doesn't work if I try to click on it and use the keyboard left/right to update it.

You could add the aforementioned wait to fix the issue, or maybe replace the slider with a control like this?
![image](https://user-images.githubusercontent.com/5120628/149283257-194acec3-b9fd-496f-bde8-d725e7490885.png)

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.97

**Comment by rajat-r** [comment]
Works perfectly now, thank you!
