### ISSUE TITLE
Tasks window should retain last size and zoom level

### ISSUE THREAD

**Issue by erohtar** [adirh3/Fluent-Search#418]
Just like Settings window, Tasks window should remember previous custom values like height/width and zoom. Right now it doesn't even retain them after you close and reopen within the same FS run instance.

Edit: I've always felt the resize on the Settings/Tasks windows on FS is buggy, now I realize it works differently than all other windows. Instead of clicking and dragging the side, FS windows resize works by clicking, letting go, moving mouse, and then clicking again at the right size - is that by design?

Thank you!

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.97

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.97

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.98

**Comment by erohtar** [comment]
This seems to be working great now, thank you!
