### ISSUE TITLE
Move Plugin Refresh Button to Top Right.

### ISSUE THREAD

**Issue by Metroid-Prime** [adirh3/Fluent-Search#42]
It doesn't make any sense to put this at the bottom as the plugin window. Here's why:

1. FS doesn't remember the saved window size.  (I've got a feature req for this)
2. The user most of the time doesn't even see it if they don't resize the window
3. There's room in the top toolbar. Better to compartmentalize the settings together, not create an extra row and lose screenspace for 1 setting. 

![image](https://user-images.githubusercontent.com/1836362/120915551-1a443a00-c659-11eb-8813-135da4224af0.png)

**Comment by Nomad-0** [comment]
IMO, best would be to add this whole plugin window to Settings

**Comment by mochigithub** [comment]
> IMO, best would be to add this whole plugin window to Settings


Yes, I agree with this and even posted a feature request for it: https://github.com/adirh3/Fluent-Search/issues/30

I dislike the entire idea of a window just for plugins as they should be part of the settings, plain and simple.  My vote goes for abolishing the plugins window altogether.

**Comment by Metroid-Prime** [comment]
I will tentatively close this as it's been completed.
![image](https://user-images.githubusercontent.com/1836362/120959990-d19b8800-c70f-11eb-9f39-83dc134ee2f7.png)


@adirh3  The location is fine now, but I recommend not putting it next to the search field as it's not associated with the search field.   
![image](https://user-images.githubusercontent.com/1836362/120960058-ed069300-c70f-11eb-8143-18d6d39169b8.png)
