### ISSUE TITLE
start minimized not work

### ISSUE THREAD

**Issue by u-Sir** [adirh3/Fluent-Search#420]
**Describe the bug**
start minimized not work

**To Reproduce**
1. Go to settings ,set start minimized on
2. restart FS
3. fs still popped up

**Expected behavior**

**Screenshots**
![图片](https://user-images.githubusercontent.com/93647031/149309863-11c90b79-da53-4514-91a9-6e6ba5f76244.png)

**Desktop (please complete the following information):**
 - Windows 11 Version: 21H2
 - Fluent Search Version 0.9.90.96

**Additional context**

**Comment by adirh3** [comment]
@u-Sir which FS version? (EXE/Portable)

**Comment by u-Sir** [comment]
> @u-Sir which FS version? (EXE/Portable)

exe

**Comment by adirh3** [comment]
@u-Sir does it happen only on Windows startup? or in general?
For some reason I can't repro it

**Comment by Metroid-Prime** [comment]
@adirh3 FYI I cannot reproduce this in Portable.   Mine launches in tray every time.

**Comment by u-Sir** [comment]
@adirh3 @Metroid-Prime it happen only on Windows startup. and it also happen on my other pc .(portable version).

**Comment by IgnusG** [comment]
Same issue after latest update

**Comment by Metroid-Prime** [comment]
> Same issue after latest update

Can confirm.  x.993 shows at startup.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.997

**Comment by Metroid-Prime** [comment]
This looks fixed on my end @IgnusG   OK to close?

**Comment by erohtar** [comment]
I can confirm. FS finally started minimized after the update.
