### ISSUE TITLE
Ctrl Shift Q / Ctrl Q can't be used by other software while Fluent Search is running

### ISSUE THREAD

**Issue by Elaws** [adirh3/Fluent-Search#421]
I don't use process history navigation (we already have `alt + tab` on Windows) : is there a way to disable `Ctrl + Q` and `Ctrl + Shift + Q` shortcuts ?

Thank you !

**Comment by rajat-r** [comment]
You mean this in settings?
![image](https://user-images.githubusercontent.com/5120628/149403400-d2ca51bd-acf8-4e36-97ef-bc9b832a9b24.png)

**Comment by adirh3** [comment]
@Elaws, as @rajat-r said above me, disable the "Go to previous/next process" hotkeys by -
1. Go to Settings -> Processes 
2. Click on the hotkey
3. Press `Escape` and then click `Stop listening`

**Comment by Elaws** [comment]
This is perfect, thank you @rajat-r and @adirh3 ! Sorry, it was a bit hidden under the different menus.

**Comment by adirh3** [comment]
> This is perfect, thank you @rajat-r and @adirh3 ! Sorry, it was a bit hidden under the different menus.

FYI - try using the search in Settings next time, as there are many settings, and it might be hard to find manually.
Also, for general information, the `Process history` feature is different from Alt+Tab in two ways -
1. It keeps linear timeline of your process usage, can be useful if you're switching between multiple processes repeatedly 
2. It instantly switches process without waiting for you to release the key

**Comment by Elaws** [comment]
> FYI - try using the search in Settings next time, as there are many settings, and it might be hard > to find manually.

Thank you, I will keep this in mind.

> the Process history feature is different from Alt+Tab in two ways 

Oh indeed, I see how this can be very useful now and different from `alt + tab`, thanks for these details.
