### ISSUE TITLE
Search Bar view doesn't expand sometimes

### ISSUE THREAD

**Issue by erohtar** [adirh3/Fluent-Search#423]
I also came across a bug that I don't recall happening earlier.
Basically, when opening FS with Search Bar view, it doesn't expand sometimes when it's launched with a tag specific hotkey (Ctrl+Tilde) in this case.

I use the hotkey I've set to open a certain tag search (the one I set up per your guidance in Discord - I suggested you make a quick blog post of it), and I have FS open to just the search bar view, then when I just press down key, expecting it to expand and let me go through my preset results, it doesn't expand and the focus is lost from the search field. I'm guessing it's still going through the result list, but outside of view.

It doesn't happen 100% of the times, but I'd say 3-4 out of 5.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.98

**Comment by erohtar** [comment]
I believe this has been fixed, thank you!!
