### ISSUE TITLE
Removing tags doesn't seem to be working correctly

### ISSUE THREAD

**Issue by erohtar** [adirh3/Fluent-Search#425]
**Describe the bug**
One of the apps that I removed a custom tag from, showed up in results of that tag search still and then had the tag added to it again.

**To Reproduce**
Steps to reproduce the behavior (what I did)
1. Launched a custom tag search via hotkey
2. Removed the tag using right click on one of the apps that I earlier added it on 
3. Firstly, it didn't immediately take effect and the item didn't disappear out of the view right away
4. Then when I Esc out, and launch that tag search again, that app shows up in that list at the bottom and still has that tag 

To make it weirder, if in that list of tagged item results I scroll down to this app, it shows up and has that tag, but if I search for its name, it doesn't show up.

**Expected behavior**
Removing tag should immediately remove that item from that tag's results and shouldn't show up again

**Desktop (please complete the following information):**
0.9.90.97

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.98

**Comment by erohtar** [comment]
I believe this working correctly too, thank you!!
