### ISSUE TITLE
Icons show up as ? For certain files

### ISSUE THREAD

**Issue by Metroid-Prime** [adirh3/Fluent-Search#426]
Hi Adir et al,

Window 10 LTSC 2021 - see version below:
![image](https://user-images.githubusercontent.com/1836362/149611574-f9bc3df0-af10-4bef-a945-209f27d3ecfc.png)

Fluent Search not showing icons properly:
![image](https://user-images.githubusercontent.com/1836362/149611597-bc5297db-2419-43e5-a60b-bccd776d54f6.png)

Properties of URL file - assigned as default app as Firefox Portable
![image](https://user-images.githubusercontent.com/1836362/149611611-57ccbf41-49ea-4f3b-8aa6-6c269dd84722.png)

Listary shows this properly: 
![image](https://user-images.githubusercontent.com/1836362/149611640-45b5945a-77aa-47d3-bb18-373b5fe6d5e6.png)

**Comment by Metroid-Prime** [comment]
Adir wants me to leave this open.   I deleted the Windows Updates.url file already but it's a confirmed bug Adir fixed for next beta version.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.99

**Comment by Metroid-Prime** [comment]
Confirming fix and closing.
