### ISSUE TITLE
Icons showing up tiny in FS

### ISSUE THREAD

**Issue by Metroid-Prime** [adirh3/Fluent-Search#427]
I'm starting to think this might be a bug/glitch in FS? 
Version:
![image](https://user-images.githubusercontent.com/1836362/149611804-b396dedd-6975-433c-bb28-4ed9def50ad1.png)

Fluent Search: 
![image](https://user-images.githubusercontent.com/1836362/149611823-da7cb186-6d9e-4acf-8335-cc141ff346ba.png)
![image](https://user-images.githubusercontent.com/1836362/149611839-2e638382-f1f6-4985-8313-6538c66451e6.png)
![image](https://user-images.githubusercontent.com/1836362/149611850-d52bc91e-18bf-4d88-9d62-4796eeb794e9.png)
![image](https://user-images.githubusercontent.com/1836362/149611871-72026c3c-c473-4dde-b77f-35b16992eae5.png)
![image](https://user-images.githubusercontent.com/1836362/149611876-31f95d7f-e44f-4696-904b-fdd736c9ba35.png)
![image](https://user-images.githubusercontent.com/1836362/149611895-0c4e22d0-8593-44d7-b183-66702d3c0e53.png)
![image](https://user-images.githubusercontent.com/1836362/149612095-f1455c57-5afa-428b-b990-0cf050ad199c.png)

All of these icons are showing up properly in Listary, Here's one example: 
![image](https://user-images.githubusercontent.com/1836362/149611914-5029390f-6070-453f-b550-60298b7c5a2c.png)

**Comment by Metroid-Prime** [comment]
Consulted with Adir. This is happening because the icons don't have 128x128 sized icons. Viewing the EXEs in Resource Hacker shows that.

Icons that have 128x128 do show the proper sized icon.  Adir is going to figure something out to make these icons show up properly on searching even with smaller icons.

**Comment by Metroid-Prime** [comment]
Ironically this is probably the most annoying bug I see every day. I rely on the icons to guide my eyes as to where I should be clicking and the tiny icons makes that more challenging.   

Is there a way to fix this without sacrificing too much performance?

**Comment by Nomad-0** [comment]
> Ironically this is probably the most annoying bug I see every day. I rely on the icons to guide my eyes as to where I should be clicking and the tiny icons makes that more challenging.
> 
> Is there a way to fix this without sacrificing too much performance? I can't be the only one seeing this. @Nomad-0 @MakeshVineeth

same here

**Comment by Metroid-Prime** [comment]
Glad other people are noticing this as well!!

Help us obi-wan-@adirh3.... You're our only hope :(

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.26                                         \nChangelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by Metroid-Prime** [comment]
Is there documentation on how this setting works?  It seems like the "Large" options make the items extra small and the small and extra small options normalize the icons.  It seems like Extra Small is the best setting for me.

The drop down also seems a little finicky  when clicked. Doesn't always open on first click.

![image](https://user-images.githubusercontent.com/1836362/157581966-2b35c386-d06e-46b0-8b9d-e023a4164c8d.png)

**Comment by Metroid-Prime** [comment]
![image](https://user-images.githubusercontent.com/1836362/157582167-2e1b84ca-35e9-428b-8eb9-a88d51eec8f3.png)

**Comment by kanjieater** [comment]
I was going to post the same issue. How can I find this setting to fix it?

**Comment by kanjieater** [comment]
> This issue has been potentially fixed in version 0.9.91.26 \nChangelog - [install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe](https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe)

I am on 0.9.92.72 and still have small icons. I used the icon resolution option and set to very low, and now things seem to be consistently sized. Is there any way to get the highest resolution available without defaulting to the lowest?
