### ISSUE TITLE
Fluent Search 100% crash when sorting by Image in Web settings (reproducible)

### ISSUE THREAD

**Issue by Metroid-Prime** [adirh3/Fluent-Search#429]
Latest version of FS:
![image](https://user-images.githubusercontent.com/1836362/149612448-8b14ef18-48c6-4d71-8824-331d795f5b74.png)

**2x Crash logs sent 1/14/22  10:48 - 10:49 PM PST** 
![image](https://user-images.githubusercontent.com/1836362/149612535-30eb6d79-f722-44b4-bf50-a77b083869ff.png)

**Comment by Metroid-Prime** [comment]
Reviewed this ticket with Adir and he's reproduced the  crash. Also present in OEM portable install.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.99

**Comment by Metroid-Prime** [comment]
Confirm. Clicking the column does nothing as it should be.
