### ISSUE TITLE
Visual/Functional glitches entering/exiting Alt-views

### ISSUE THREAD

**Issue by erohtar** [adirh3/Fluent-Search#430]
1) When I have this view open, and **the focus is on right pane**:
![image](https://user-images.githubusercontent.com/5120628/149612772-ba3c87e9-9976-4426-8eef-067092cb374d.png)
..and I press Alt to switch view, then the expanded ghost border remains on the miniFB:
![image](https://user-images.githubusercontent.com/5120628/149612806-61c074fa-9e44-4b39-bc0d-2e762d349af2.png)
This is repeatable for me and happens every single time.

2) When switching Alt views from search bar, search bar stays in keyboard focus. 
When switching Alt views from results list, results list stays in keyboard focus.
But when switching Alt views from the right pane, keyboard focus doesn't stay there.. and I can't even tell sometimes where the focus has gone. I just have to keep pressing arrow keys till it returns somewhere.
Like in one case, if the right pane has commands showing and has focus, then I press Alt, the focus seemingly goes to the LS window, and pressing arrow key suddenly adds a ghost border around the window:
![image](https://user-images.githubusercontent.com/5120628/149612966-32d2e54b-2250-4cec-8468-c4a0a9b0d703.png)

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.99

**Comment by Metroid-Prime** [comment]
@erohtar  please confirm fix

**Comment by erohtar** [comment]
Working great now, thank you!

**Comment by Metroid-Prime** [comment]
Welcome! Thanks to Adir for his hard work.
