### ISSUE TITLE
100% FS Tasks Crash  (reproducible) 

### ISSUE THREAD

**Issue by Metroid-Prime** [adirh3/Fluent-Search#431]
Hi @adirh3 
FS version:
![image](https://user-images.githubusercontent.com/1836362/149612973-4b8de745-bda2-4d87-8533-be21a7234071.png)
![image](https://user-images.githubusercontent.com/1836362/149612976-0c80ccf5-584a-4d3f-9357-b1c8ca39bc76.png)

1/14/22 11:06 PM  PST  - Crash logs sent.    Another crash log sent 11:08 PM PST  1/14/22

Description: Was clicking + in the Tasks section, typed name, and clicked OK. Crashed

**Comment by Metroid-Prime** [comment]
Reviewed this ticket with Adir and he's reproduced the  crash. Also present in OEM.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.99

**Comment by Metroid-Prime** [comment]
Confirming, no longer crashes. Closing ticket.
