### ISSUE TITLE
Remember location for plugins by default

### ISSUE THREAD

**Issue by Metroid-Prime** [adirh3/Fluent-Search#432]
Latest version of FS

![image](https://user-images.githubusercontent.com/1836362/149613091-cd4b7ac4-745c-448a-95a5-373ac962e2d7.png)

Plugins window should remember size, position and location on window by default.  There should be no setting to adjust this.

![image](https://user-images.githubusercontent.com/1836362/149613084-e29087d7-6561-4c05-b427-c53828f15447.png)
![image](https://user-images.githubusercontent.com/1836362/149613086-56beaf88-9691-43de-834f-5bf7df95bd35.png)

**Comment by adirh3** [comment]
Close either of these #29, maybe rename this to change all windows to keep size.
FYI, not going to focus on it for now as all the important windows have size kept.

**Comment by Metroid-Prime** [comment]
Oops, I searched but couldnt find the old one.  Thought I was having Deja vu.   I'll close the new one and keep this and rename it.

**Comment by Metroid-Prime** [comment]
Closing. Please reference #29
