### ISSUE TITLE
Add folder name like Listary & Alfred to minimalistic mode (Files section)

### ISSUE THREAD

**Issue by Metroid-Prime** [adirh3/Fluent-Search#433]
Latest FS:
![image](https://user-images.githubusercontent.com/1836362/149613206-99f2a855-9f7b-4024-b1aa-639e3bb3555a.png)

Can we please add the folder names like Alfred & Listary pretty please in Minimalistic mode?  When in this mode, it makes it impossible to figure out which folder is which without hovering over it which gets annoying fast :(

![image](https://user-images.githubusercontent.com/1836362/149613203-ed3a6a7e-4705-4fb7-af7e-05ec629802b5.png)

Here's Listary:
![image](https://user-images.githubusercontent.com/1836362/149613209-72faf3f6-796d-4c8e-bf49-44420e5c8c55.png)

Here's Alfred:
![image](https://user-images.githubusercontent.com/1836362/149613214-c21947a2-8b5f-4b29-bc2e-2ea417e13d30.png)

**Comment by adirh3** [comment]
@Metroid-Prime I wonder which part of the UI is making you not use the "normal" mode?
Other than the result type, I don't see two much difference from this - 
![image](https://user-images.githubusercontent.com/27368554/149631587-f7d3d0eb-93b1-4af5-ba3c-11dad491d562.png)

Obviously Alfred/Listary don't have result grouping, and you can disable it in FS.

**Comment by Metroid-Prime** [comment]
I can't remember specifically why I changed back to minimal but like we talked about it could be for a good reason like "File" prefix while type grouping.

@adirh3  can you list everything that is is changed with Minimalistic view? 

Even in minimalistic design, this just doesn't seem right to me.  The path should always be shown even in minimal mode.
@MakeshVineeth @Nomad-0   do you guys have any opinions about this?  Without the directory listed, one viewing folders in Files plugin can't tell which folder is which when they're named the same.

**Comment by MakeshVineeth** [comment]
> I can't remember specifically why I changed back to minimal but like we talked about it could be for a good reason like "File" prefix while type grouping.
> 
> @adirh3 can you list everything that is is changed with Minimalistic view?
> 
> Even in minimalistic design, this just doesn't seem right to me. The path should always be shown even in minimal mode. @MakeshVineeth @Nomad-0 do you guys have any opinions about this? Without the directory listed, one viewing folders in Files plugin can't tell which folder is which when they're named the same.
> 
> EDIT: For example, searching folder "System" will show many folders you won't know which ones are the actual folders you're interested in without clicking on or hovering over each one.

Agreed with this. It will surely confuse users when there are two folders with same name and the Minimalistic mode doesn't show the path. So maybe it would be nice to just show the relative path of the folder/file instead of an absolute path. This way, it'll still look bit minimal and path is also shown.

**Comment by Metroid-Prime** [comment]
@MakeshVineeth  question is would a relative path even help?  It's better than nothing but my thought is not
![image](https://user-images.githubusercontent.com/1836362/149648183-c3c02f97-6b4b-4119-8af8-61340808a37b.png)

**Comment by MakeshVineeth** [comment]
> @MakeshVineeth question is would a relative path even help? It's better than nothing but my thought is not ![image](https://user-images.githubusercontent.com/1836362/149648183-c3c02f97-6b4b-4119-8af8-61340808a37b.png)

The Alfred screenshot that you've shared in above comments seems to use relative paths, it is looking pretty useful and also minimal to me. Nevertheless, an option to switch between relative/absolute path (for minimal mode only) may solve with this issue.

**Comment by Metroid-Prime** [comment]
It's a little bit like comparing apples to oranges I know but it still gives a pretty complete path.  There's no C or D drive on the Mac but the rest of the dir is there.

![image](https://user-images.githubusercontent.com/1836362/149649108-20866ea1-c032-418c-ae2b-d0dab4819860.png)

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.991

**Comment by Metroid-Prime** [comment]
Thank you @adirh3  I can confirm minimalistic view is now showing complete dir name.
![image](https://user-images.githubusercontent.com/1836362/149697566-400832e8-12b6-4eb4-bf19-ede49974cdc2.png)

I think this was the right decision.
