### ISSUE TITLE
Web Search panel very laggy/slow when scrolling. 

### ISSUE THREAD

**Issue by Metroid-Prime** [adirh3/Fluent-Search#435]
LAtest FS:
![image](https://user-images.githubusercontent.com/1836362/149613463-db2653e7-e921-4688-b276-0c1be87f205c.png)

![image](https://user-images.githubusercontent.com/1836362/149613497-d83cb672-4d96-439d-8834-350824b87ef7.png)

**Comment by Metroid-Prime** [comment]
I understand this might be due to a large web.json file but there is something very.... Unnatural... about the lag.  I wonder if FS is somehow reading the full resolution of the image files and that's what is causing the lagging? The way Adir described it, the images get encoded for better portability.

**Comment by Metroid-Prime** [comment]
I will send @adirh3  a copy of my web.json file in ~30 min

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.991

**Comment by Metroid-Prime** [comment]
@adirh3 , I don't know what you did, but it's working much smoother now!   Thank you for this fix!   I will unfortunately need to post another bug that I've been dealing with but will another github issue for bookmarking purposes.
