### ISSUE TITLE
Advanced Settings / Prioritization tab confusing for users

### ISSUE THREAD

**Issue by Metroid-Prime** [adirh3/Fluent-Search#436]
Latest FS:
![image](https://user-images.githubusercontent.com/1836362/149613572-7ee45f44-a016-4e03-a0cc-767359f3110a.png)

Under Search app prioritization, that seems pretty straight forward.
Then you get to Result type prioritization which entirely confuses me. What is the point of this feature? How is it different than Search app prioritization?  

Also  This settings interface for it is very confusing to me. 
![image](https://user-images.githubusercontent.com/1836362/149613565-e5c9fff0-7fcf-4b7f-84c9-35b5fb3133ca.png)
![image](https://user-images.githubusercontent.com/1836362/149613568-aae68f33-21fd-4f95-b99e-b58c287a49a7.png)

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.994

**Comment by Metroid-Prime** [comment]
@adirh3  Feedback:

1. Fix this: ![image](https://user-images.githubusercontent.com/1836362/150279632-c4d88128-1653-45a3-bb4e-20358c79c63a.png)

2. What's changed here?  I'm a little less confused now but still confused about the layout.  Do I still hand type stuff? If so, what?  There's only 3 entries in the light bulb.

**Comment by Metroid-Prime** [comment]
I'm closing this because:
1. I don't remember what I means by "with R" in the picture. Possibly a spelling mistake?
2. I do see the change now.
