### ISSUE TITLE
tasks name and icon should align

### ISSUE THREAD

**Issue by u-Sir** [adirh3/Fluent-Search#438]
**Describe the bug**

**To Reproduce**
1. Go to 'tasks`

**Expected behavior**

**Screenshots**
![图片](https://user-images.githubusercontent.com/93647031/149614552-72e3217d-7c5f-4cca-b660-3211cb4d2676.png)

**Desktop (please complete the following information):**
 - Windows 11 Version: 21H2
 - Fluent Search Version 0.9.90.98

**Additional context**

**Comment by erohtar** [comment]
The empty space there is actually meant for the Author name:
![image](https://user-images.githubusercontent.com/5120628/149614720-9617cea5-d806-49ed-9648-af54753b4571.png)

Though it should maybe move it to center when no author specified, but the misalignment isn't unintentional.
