### ISSUE TITLE
Ignore Tags

### ISSUE THREAD

**Issue by Mr-Frankenstein** [adirh3/Fluent-Search#44]
There is a lot of tags which I don't know what they do. For example lc_messages, list, listitem, list_def, and Combo box. A feature to ignore tags, so they won't show in the search bar.

![image](https://user-images.githubusercontent.com/85425543/120915983-72645600-c6c4-11eb-9763-77eb772a63e2.png)
![image](https://user-images.githubusercontent.com/85425543/120915986-72fcec80-c6c4-11eb-963a-45d1e93d1c08.png)

**Comment by mochigithub** [comment]
@Mr-Frankenstein  @adirh3  could this be because Fluent Search is searching the processes and listing those?

**Comment by adirh3** [comment]
> @Mr-Frankenstein @adirh3 could this be because Fluent Search is searching the processes and listing those?

Yes, list items tags are used for in-process search.
Will add system-wide option to disable search tags soon.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.85.40

**Comment by Nomad-0** [comment]
Closing the issue as the issue seems to be fixed. @Mr-Frankenstein please check.
