### ISSUE TITLE
W needs to be capitalized in the settings menu for Open With

### ISSUE THREAD

**Issue by Metroid-Prime** [adirh3/Fluent-Search#443]
Capitalize the W to emphasize the "Open With" not open _with_ .  
![image](https://user-images.githubusercontent.com/1836362/149641876-cde39bd3-8c58-47f3-ad17-796af7078162.png)

![image](https://user-images.githubusercontent.com/1836362/149641856-62f331f5-1922-4bcd-82e6-c1f505374fd9.png)

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.991

**Comment by Metroid-Prime** [comment]
Confirmed. TY!
