### ISSUE TITLE
!!! Autoupdater is corrupting FS executable, crashing FS on startup for past 2 betas !!! (reproducible)

### ISSUE THREAD

**Issue by Metroid-Prime** [adirh3/Fluent-Search#444]
@adirh3  same issue you and I discussed together.  Happened again today with newest beta as of 2 hours ago.

 I sent you the good and bad executable with hashes via Discord. The bytes are precisely the same.

The only solution is to go to the nightly portable download appcenter and download update manually:
https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/portable

For anyone experiencing the same with portable installed by autoupdater, please post.

**Comment by Metroid-Prime** [comment]
This happened again with latest beta (.991). I had to download from nightly website to get to stop crashing.
Hashes were difference. Bytes the same.

**Comment by Metroid-Prime** [comment]
Have not seen this for latest beta. Closing and will reopen if it happens again

**Comment by Metroid-Prime** [comment]
Happening again @adirh3 !  Reopening.    I've sent you the file.

![image](https://user-images.githubusercontent.com/1836362/149878451-ea7178e2-720d-48fa-8924-903db4413329.png)

**Comment by adirh3** [comment]
@Metroid-Prime closing this as we have discussed it on Discord.

**Comment by Metroid-Prime** [comment]
happened again 1/21/22. (I'm putting this here for tracking purposes)

**Comment by Metroid-Prime** [comment]
Happened again last week and today.  Fluentsearch.exe losing its digital signature causing change in hash.

**Comment by adirh3** [comment]
> Happened again last week and today. Fluentsearch.exe losing its digital signature causing change in hash.

FYI it's not losing digital signature. The file has changed (somehow), causing the digital signature to break.
