### ISSUE TITLE
add a column `run as admin` on commands

### ISSUE THREAD

**Issue by u-Sir** [adirh3/Fluent-Search#446]
**Is your feature request related to a problem? Please describe.**
i want set a new tag that run cmds as admin

**Describe the solution you'd like**
add a column `run as admin` 
![图片](https://user-images.githubusercontent.com/93647031/149650894-2837f51e-06ff-4604-93f3-bf8454303c72.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by Metroid-Prime** [comment]
Are you thinking the user can check a checkbox under a "Run as admin"  column to run that specific function as admin? 
I wouldn't need this but it makes sense to me.
