### ISSUE TITLE
Networked files no longer indexing new beta (0.9.90.99)

### ISSUE THREAD

**Issue by Metroid-Prime** [adirh3/Fluent-Search#447]
![image](https://user-images.githubusercontent.com/1836362/149656129-218137e9-b48d-4688-8cfb-ab49c0532747.png)

This file is found...
![image](https://images.githubusercontent.com/1836362/149656149-9b57483b-2ac7-4c52-892b-7fceda29ad6a.png)

....but other files in the same folder are not on a network share that's mapped to O:\ in explorer.

Win10 LTSC 2021 
![image](https://user-images.githubusercontent.com/1836362/149656188-5c67a641-a661-4f22-988f-59452f89e6ca.png)

**Comment by adirh3** [comment]
@Metroid-Prime the image of the file is not showing.
Also FYI - the indexer was not changed, you sure you don't think it's changed since you were using Everything previously?

**Comment by Metroid-Prime** [comment]
You were right @adirh3   When we were talking, I reverted back to FS indexer forgetting that I switched because of networked files Lol.  Hopefully you can get this resolved before v1.00. I'm closing this since I thought there was a ticket out already for it.
