### ISSUE TITLE
White bar around FS prevents use.

### ISSUE THREAD

**Issue by Metroid-Prime** [adirh3/Fluent-Search#448]
Probably in newest beta.  Solution is to close and re-open or revert back to old versions.
Prevents me to being able to effective use the app.  Had to revert to Listary back again. 

Visual Examples of what it looks like:
![image](https://user-images.githubusercontent.com/1836362/149656297-6549e17d-403d-4c83-8c4e-fba0fddc1d0d.png)
![image](https://user-images.githubusercontent.com/1836362/149656301-409cabdb-8550-4233-84ff-c13befea7ad8.png)

Any idea what this could be?

**Comment by adirh3** [comment]
Will fix it.
@Metroid-Prime FYI, this is because of preview. You might've missed it but preview now triggers with `Alt` which you might not notice.

**Comment by Metroid-Prime** [comment]
TY good sir.  I knew about preview but was that white bar a bug?  Never seen that prior to this beta.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.991

**Comment by Metroid-Prime** [comment]
If I run into this with new beta I will reopen! TY Adir for the fix <3
