### ISSUE TITLE
Search field is retained even after closing settings window.

### ISSUE THREAD

**Issue by Metroid-Prime** [adirh3/Fluent-Search#45]
This is reproducible and introduced 0.9.85.1  with the settings search feature.
![image](https://user-images.githubusercontent.com/1836362/120916092-5cbb4600-c65c-11eb-9eff-57b92e83181f.png)
When the settings window is closing, that setting should be emptied.

**Comment by Metroid-Prime** [comment]
clarification:  if you  type some meaningless blob of text "kdfldklfdk" into the search field, the entry is not remembered when closing settings and re-opening.  However, when you type an entry that triggers a hit (e.g. "search hotkey", _that_ entry remains in the toolbar after going back to settings.   The default behavior should be that search field be empty every time

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.85.55

**Comment by Nomad-0** [comment]
Fixed on my end

**Comment by Metroid-Prime** [comment]
Can confirm  fixed. Closing
