### ISSUE TITLE
FS sees Alt-Tab GUI as a separate Process

### ISSUE THREAD

**Issue by erohtar** [adirh3/Fluent-Search#452]
As discussed on Discord earlier, a Process Switch Trigger fires if I switch from Old to New process quickly, but if I take a moment on the Alt-Tab window to select my target window, then it doesn't fire -> FS sees Alt-Tab GUI as a separate Process

**Comment by adirh3** [comment]
@erohtar this should've been fixed long ago, forgot to mention here (also rechecked now).
Closing, feel free to reopen if it's still not working for you.
