### ISSUE TITLE
Big ugly blurred outline around FS Tooltip popups

### ISSUE THREAD

**Issue by erohtar** [adirh3/Fluent-Search#453]
**Describe the bug**
Pictures to explain what I mean:

![image](https://user-images.githubusercontent.com/5120628/149723032-e3391ac8-09c8-433d-bfb9-712b4957d362.png)
![image](https://user-images.githubusercontent.com/5120628/149723095-fa91d993-07bc-47da-a2fb-835e8723f976.png)
![image](https://user-images.githubusercontent.com/5120628/149723329-99c9cbb0-f6b7-4187-add9-b3937eada83a.png)

**Comment by adirh3** [comment]
@erohtar Windows 10 version?

**Comment by erohtar** [comment]
Yes Adir

**Comment by adirh3** [comment]
> Yes Adir

I mean which_ Windows 10 version?
Also, did you disable `Use GPU` in settings -> System?

**Comment by erohtar** [comment]
Oh my bad lol
Here:
![image](https://user-images.githubusercontent.com/5120628/149724062-4ef12712-365b-4d45-81e9-e52af6675281.png)

And yes, it was disabled. Bad idea?

**Comment by adirh3** [comment]
> Oh my bad lol Here: ![image](https://user-images.githubusercontent.com/5120628/149724062-4ef12712-365b-4d45-81e9-e52af6675281.png)
> 
> And yes, it was disabled. Bad idea?

Yes when keeping that disabled some effects will not work, I will just disable them.
But in general I recommend not disabling that

**Comment by erohtar** [comment]
But I actually have all effects disabled:
![image](https://user-images.githubusercontent.com/5120628/149725559-2b591b20-e09a-4b41-a65f-705bebbab88e.png)

**Comment by erohtar** [comment]
> I will just disable them

Or did you actually mean you would disable them in FS code?

**Comment by adirh3** [comment]
> > I will just disable them
> 
> Or did you actually mean you would disable them in FS code?

meant in the code

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.992

**Comment by erohtar** [comment]
Oh so "Big ugly blurred" is technically acrylic? lol
Thanks for the fix!
