### ISSUE TITLE
Blank full window when set to search bar only

### ISSUE THREAD

**Issue by erohtar** [adirh3/Fluent-Search#454]
**Describe the bug**
I'm not sure what exactly caused it, but right now FS is showing this when set to search bar only:
![image](https://user-images.githubusercontent.com/5120628/149738101-51518d87-c639-4c99-ba88-54d35ea28e5a.png)

It was working okay on same release a few mins ago.

**Comment by erohtar** [comment]
Btw this only went away after restarting FS.

**Comment by adirh3** [comment]
@erohtar was it when you resized FS manually when using `Search bar only`?

**Comment by erohtar** [comment]
@adirh3 yes it could have been. But it was a few days back and it has never happened before or after that run. But on that run it was repro each time.

**Comment by erohtar** [comment]
No this hasn't happened again for me
