### ISSUE TITLE
Dragging folder from FS > XYplorer causes processor crash 25%   (reproducible)

### ISSUE THREAD

**Issue by Metroid-Prime** [adirh3/Fluent-Search#455]
Xyplorer 22.70
![image](https://user-images.githubusercontent.com/1836362/149764132-eb5f5474-110c-48a6-8a25-f01a7a65da17.png)

Happens every time

Steps:
1. Open Xyplorer
2. Launch FS
3. Type "Test" in search field
4. Find folder
5.  Hold control and drag folder into XYplorer
6. Observe FS closes
7. open process hacker
8. observe FS has crashed 25% CPU (quad core) in background.  
9. observe FS is unresponsible to both trigger and right click tray menu clicks

![image](https://user-images.githubusercontent.com/1836362/149764448-837ebac9-51cb-4c3a-88f6-b2f2ead87c9b.png)
![image](https://user-images.githubusercontent.com/1836362/149764060-89a8bd67-78fd-49b2-ad9e-fd1c95ab0c5b.png)

![image](https://user-images.githubusercontent.com/1836362/149763975-efa81895-72a3-4158-a8f9-cb3901eb9410.png)

**Comment by adirh3** [comment]
@Metroid-Prime installed XYplorer latest portable. 
Can't repro this, does it happen with every folder? Any settings I should change in XYplorer?

**Comment by Metroid-Prime** [comment]
@adirh3  I sent you my tuned Xyplorer install  + animation + folder I was dragging.
If you watch the animation it should demo on how to crash FS
![image](https://user-images.githubusercontent.com/1836362/149897650-b8769b0b-7bcf-48d0-9873-ac257fb4b018.png)

**Comment by adirh3** [comment]
@Metroid-Prime interestingly I can't repro using your files.
Also tried using your FS settings, can please you check if it happens for you on other PCs?

**Comment by Metroid-Prime** [comment]
I will try tomorrow if I have a chance at work!

**Comment by Metroid-Prime** [comment]
I was able to reproduce this again tonight, but closing to save Adir some time. If it becomes a widespread problem with Xyplorer, i'll reopen
