### ISSUE TITLE
"Process" misnomer in FS

### ISSUE THREAD

**Issue by erohtar** [adirh3/Fluent-Search#456]
**Describe the bug**
When FS says Process anywhere, it actually means a Window, as it ignores processes that don't have a window open, and counts a process twice if it has two windows open
A window is a well known element in Windows and everyone is familiar with what it's supposed to mean, and FS's way to rename them seems confusing.

Window would mean the graphical rectangle that user interacts with, and process would mean any running task/process - whether in the foreground or background generating those windows. 
A process can have zero to any number of windows, but a window can be associated with only a single process.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 1.0.0.11                                          . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by erohtar** [comment]
Thank you, that naming makes a lot more sense now
