### ISSUE TITLE
FS Indexer not finding all results

### ISSUE THREAD

**Issue by mragtronx8** [adirh3/Fluent-Search#458]
everything indexer is locating more results than fs indexer.
I stopped using everything indexer "waiting for fix".
now having issues with fs indexer
#BUG

EXAMPLE: i have an mp3 song "around 20 versions"
fs indexer finds 8 only, while everything indexer locates almost all

**Comment by Metroid-Prime** [comment]
@mragtronx8  are these files on a network or network share? 
@adirh3  could this be related to the issue you and I spoke about last night?

**Comment by adirh3** [comment]
@Metroid-Prime pretty sure its related to normal NTFS drive and is a non-indexing issue.

@mragtronx8 need the following info -
Which drive is it? - C:\, network drive, external drive
Can you try changing the setting `Max files to process` to `0` - 
![image](https://user-images.githubusercontent.com/27368554/149842007-0f320400-fdbf-4303-8d41-f6086dda8404.png)
And see if you find results.

**Comment by mragtronx8** [comment]
my drive c / d / e are local drivers
no networks drives
max files already set to 0

**Comment by adirh3** [comment]
@mragtronx8 thanks, can you please try installing stable version of Fluent Search and check if it finds all files?
I made some changes to indexer that should result in **more** files being found so this is weird.
