### ISSUE TITLE
Preview Window steals focus at every keystroke

### ISSUE THREAD

**Issue by erohtar** [adirh3/Fluent-Search#459]
**Describe the bug**
![image](https://user-images.githubusercontent.com/5120628/149824235-bb093f78-f7fd-4093-a60b-9914457311bf.png)

With above setting enabled, it pops up with keyboard focus after every keystroke - I'd have to press esc after every key to go back to search.

**Expected behavior**
I'd expect it to open preview in its window but without stealing focus

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.992

**Comment by erohtar** [comment]
Much better, thank you!
Before closing this though, could I also request you to make the preview window retain size and position instead of jumping all around with each result selection?
With retaining window size, ideally the image previews of smaller images should not be zoomed in to stretch, but of larger images should be zoomed out enough to fit inside.

**Comment by adirh3** [comment]
> Much better, thank you! Before closing this though, could I also request you to make the preview window retain size and position instead of jumping all around with each result selection? With retaining window size, ideally the image previews of smaller images should not be zoomed in to stretch, but of larger images should be zoomed out enough to fit inside.

Sorry for missing this. 
This change was made based on other requests, the images do stretch, but the preview window size will change depending on the preview shown.
