### ISSUE TITLE
Tags on web search urls are not working

### ISSUE THREAD

**Issue by Nomad-0** [adirh3/Fluent-Search#46]
**Describe the bug**
I have added several `tag`s to some web search URLs e.g. `gg` for Google, `yt` for Youtube, 
![image](https://user-images.githubusercontent.com/76395594/120915979-a17cc680-c6c8-11eb-8836-7d7953a206db.png)

but no tags are shown if I type gg, yt, or several other web search tags. however, tags appear if I type the `Name` of the urls
![image](https://user-images.githubusercontent.com/76395594/120916015-cbce8400-c6c8-11eb-8409-257c03a914dd.png)
![image](https://user-images.githubusercontent.com/76395594/120916231-38964e00-c6ca-11eb-95ab-f35b46e71e81.png)

**To Reproduce**
add a short tag to a web search URL
open fs
try to type the short tag, press `tab` (your `insert tag key`)

**Expected behavior**
when I type the tag and press tab, the tag would appear

**Desktop (please complete the following information):**
 - Windows 10 Version: [21H1]
 - Fluent Search Version [0.9.85.1]

**Comment by mochigithub** [comment]
Can confirm. I had posted this under #issue 50

**Comment by Nomad-0** [comment]
closed due to duplicate
