### ISSUE TITLE
Collapsed search results should show title name - not top result in them

### ISSUE THREAD

**Issue by Metroid-Prime** [adirh3/Fluent-Search#460]
![image](https://user-images.githubusercontent.com/1836362/149836424-96418405-b9f8-4fc1-b44e-d93d57095695.png)

![image](https://user-images.githubusercontent.com/1836362/149836641-7bf10cf4-93b0-4b85-93da-a4a9625a2a87.png)

**Comment by Nomad-0** [comment]
I disagree with this one. In that way, I will have to open the collapsed results and select the result again to open it, and even I might have to search again if it's not there and repeat the process. while now I can just press enter after searching as most of the time the top result is the one I'm looking for and if its not, I just keep typing till I find it.

**Comment by Metroid-Prime** [comment]
I don't feel too married to this one;  I just thought it would be better design because it wasn't clear which results belonged to which section when they're collapsed.

The way I'm talking about shouldn't require any more than 1 click to continue the progress user was also in motion for.
![image](https://user-images.githubusercontent.com/1836362/149893166-42e22239-8245-40f3-b44d-25d932f913b1.png)

**Comment by Metroid-Prime** [comment]
I've thought a lot about this and @adirh3  - despite another user disagreeing, I strongly think current state for this in FS is NOT good design. when the section is collapsed, it should preserve the header text on the left side shown before collapsing and only show that when collapsed.

![image](https://user-images.githubusercontent.com/1836362/150748063-0acc97c3-1bf7-494c-b163-d79cc7c580bd.png)

**Comment by adirh3** [comment]
> I've thought a lot about this and @adirh3 - despite another user disagreeing, I strongly think current state for this in FS is NOT good design. when the section is collapsed, it should preserve the header text on the left side shown before collapsing and only show that when collapsed.
> 
> ![image](https://user-images.githubusercontent.com/1836362/150748063-0acc97c3-1bf7-494c-b163-d79cc7c580bd.png)

This is due to minimalistic UI, as you have seen users have different opinions on which UI part should show and when. I can't satisfy everyone yet, my plan is to make the search window editable using a studio like window.
Right now **by default** I think the search window is very clear, if you think it's not please explain why.

**Comment by adirh3** [comment]
![image](https://user-images.githubusercontent.com/27368554/150837806-fa2add60-c75e-4df5-8ab4-ab18eaf5823a.png)
@Metroid-Prime does this work?

**Comment by Metroid-Prime** [comment]
I would say that's better @adirh3   I am a little confused by the down arrow next to it.  These entries would show when the items are _collapsed_ right?

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.999

**Comment by Metroid-Prime** [comment]
Thank you Adir for listening. I think this is a very reasonable compromise of both positions posted.

![image](https://user-images.githubusercontent.com/1836362/150916486-98406117-6df4-4dab-8705-839786e5caad.png)

Confirming fix, closing!
