### ISSUE TITLE
Extraneous entries from Windows system are being shown in App shortcuts despite settings

### ISSUE THREAD

**Issue by Metroid-Prime** [adirh3/Fluent-Search#463]
I can't tell if this is a bug or enhancement request but I'll file it as low priority bug for now as it makes searching much harder in FS. 

One of my personal top struggles with FS has been its inability to focus the user's attention on the app shortcuts folders that I want.
It seems like there are 'hidden' folders in the Custom app path section.  Since I have "Search legacy apps" turned OFF, I am still seeing tens and tens of extraneous entries I don't care about in the 'App' search section. 
![image](https://user-images.githubusercontent.com/1836362/149842602-f90fa72c-3ed7-4f60-a220-00439f7fdd1a.png)

There doesn't seem to be any way of not showing all these extra entries.  There should be.  There needs to be! 

![image](https://user-images.githubusercontent.com/1836362/149842504-0b7f7205-5e4a-46d3-901a-9e8a830920a2.png)

**Comment by adirh3** [comment]
@Metroid-Prime disable this setting -
![image](https://user-images.githubusercontent.com/27368554/149842969-713ecd5b-af08-49a5-95fd-fa3e656d756b.png)

**Comment by Metroid-Prime** [comment]
> @Metroid-Prime disable this setting - ![image](https://user-images.githubusercontent.com/27368554/149842969-713ecd5b-af08-49a5-95fd-fa3e656d756b.png)

It's already disabled (see screenshot in opening post, top of the first pic).  That's why I was suspecting this was a bug.

**Comment by Metroid-Prime** [comment]
Consulted with adir via discord. This sounds like a bug so I'll leave as such.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.992

**Comment by Metroid-Prime** [comment]
I think this is fixed Adir!  Closing and thank you! 
![image](https://user-images.githubusercontent.com/1836362/149847820-fac2da74-5c9f-4334-822f-b5d99d6c5f58.png)
