### ISSUE TITLE
 The FS hotkey doesn't work when you start the computer for the first time every day 

### ISSUE THREAD

**Issue by u-Sir** [adirh3/Fluent-Search#464]
**Describe the bug**
Recently, when my laptop was turned on for the first time every day, FS could not start normally that i can't launch FS by hotkey
. but i can find the FS processes in tasks manager, both `fluent search` and `fluent search.fileindex`. if i restart one more time it work correctly.

**To Reproduce**
1. shutdown windows for mins or may be more.
2. power on.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 11 Version: 21h2
 - Fluent Search Version 0.9.90.992

**Additional context**

**Comment by Metroid-Prime** [comment]
Have you tried running the app through the sys tray? Does it work from there?

**Comment by u-Sir** [comment]
> Have you tried running the app through the sys tray? Does it work from there?

no, i set `Shwo system tray icon` off. I'll try it.

**Comment by adirh3** [comment]
@u-Sir do you have `Sync` settings enabled?

**Comment by u-Sir** [comment]
> @u-Sir do you have `Sync` settings enabled?

yes

**Comment by adirh3** [comment]
@u-Sir can you check if it happens with version 90.993?

**Comment by u-Sir** [comment]
> @u-Sir can you check if it happens with version 90.993?

hmm, fs already updated to .994.😂 i will check it tomorrow

**Comment by u-Sir** [comment]
> @u-Sir can you check if it happens with version 90.993?

.994 still not fix.

**Comment by adirh3** [comment]
@u-Sir Can you please check if it happens when disabling Sync?

**Comment by u-Sir** [comment]
> @u-Sir Can you please check if it happens when disabling Sync?

it seems fixed in recently update
