### ISSUE TITLE
Text previews gone

### ISSUE THREAD

**Issue by erohtar** [adirh3/Fluent-Search#467]
**Describe the bug**
I thought of checking out the new syntax highlighting I thought I read about in changelog. But all the json/xml/ini etc files that I thought would look nicer, now show blank:
![image](https://user-images.githubusercontent.com/5120628/150216860-c8dd1066-150e-4037-b630-26bddf7ef998.png)

**Comment by adirh3** [comment]
@erohtar doesn't it look nicer when blank?
Just kidding fixed it in today's build

**Comment by erohtar** [comment]
Totally zen! lol

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.994

**Comment by Metroid-Prime** [comment]
@erohtar  I am seeing preview text now when I turned on my setting
![image](https://user-images.githubusercontent.com/1836362/150263257-3014372e-e950-4b12-8185-db4621011572.png)


close this?

**Comment by erohtar** [comment]
Much better, thank you!
