### ISSUE TITLE
Crash on Search

### ISSUE THREAD

**Issue by erohtar** [adirh3/Fluent-Search#468]
**Describe the bug**
I was about to type "blast\tasks" but I only reached "blast\t" ..
![image](https://user-images.githubusercontent.com/5120628/150629176-72a6c7c4-63dc-47fa-80c0-8f750cd2db5a.png)

**Expected behavior**
Not crash

**Screenshots**
As above

**Desktop (please complete the following information):**
 - Fluent Search Version 0.9.90.996

**Comment by Metroid-Prime** [comment]
I am able to type that text OK.  IMO this one is going to be a very tough one to figure out.

Is it reproducible on your end?

**Comment by erohtar** [comment]
Yeah I couldn't reproduce it either. But I have the send crash logs setting enabled and with the above details added maybe Adir can put together what happened there.

**Comment by adirh3** [comment]
@erohtar this is most likely caused by text file preview, will see if I can find a file that cause this for me as well

**Comment by adirh3** [comment]
@erohtar should be fixed on latest, please confirm

**Comment by erohtar** [comment]
Yeah it hasn't happened since then. I'll close this, thank you

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.9992
