### ISSUE TITLE
Support History Search in Chromium

### ISSUE THREAD

**Issue by erohtar** [adirh3/Fluent-Search#469]
**Is your feature request related to a problem? Please describe.**
FS already supports searching Default\Bookmarks (json) file for Chromium browsers. It'd be great if it searched Default\History (sqlite) file too. 
Right now I don't use Chromium bookmark searches in FS because the browser searches both history and bookmarks, while FS only searches bookmarks.

**Describe the solution you'd like**
The address bar search of browsers is okay, but being able to consolidate most common searches into a single app would be better.

**Comment by adirh3** [comment]
@erohtar it is searching in History, make sure the correct user is set in your Chromium paths

**Comment by erohtar** [comment]
You're right it IS searching that right now! Nice! I don't know why it wasn't doing that earlier, and I haven't changed any settings since then.
