### ISSUE TITLE
ALT F4 doesn't close setting when focused on New Search field

### ISSUE THREAD

**Issue by Metroid-Prime** [adirh3/Fluent-Search#47]
Title says it all.

When you're typing something into the search field and hit ALT+F4, it won't close the settings window while the focus is in that field. This is unexpected behavior.
![image](https://user-images.githubusercontent.com/1836362/120916543-0b608600-c65f-11eb-8497-265271de6015.png)

**Comment by Metroid-Prime** [comment]
*Edited original post with more information.

**Comment by Metroid-Prime** [comment]
After a review, I'm going to keep this open because I still find this behavior annoying and not expected for general UI/UX

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.76                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
