### ISSUE TITLE
Gif preview bug

### ISSUE THREAD

**Issue by erohtar** [adirh3/Fluent-Search#470]
**Describe the bug**
Shows image preview correctly on commands pane, but shows a text preview under preview mode:
![image](https://user-images.githubusercontent.com/5120628/150631526-1799a693-0d98-4e6b-bb12-e3c97dc51582.png)

![image](https://user-images.githubusercontent.com/5120628/150631529-82d2d74b-d928-473a-a54f-2dbfdd7a0b3c.png)

**Comment by Metroid-Prime** [comment]
Can confirm. I think I might have an idea of why this is happening......

![image](https://user-images.githubusercontent.com/1836362/150632160-991daafc-ce33-43c5-a7dd-e40a34752300.png)

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.997

**Comment by erohtar** [comment]
Works well now, thank you!
