### ISSUE TITLE
it will still have animation effect even it's disable

### ISSUE THREAD

**Issue by u-Sir** [adirh3/Fluent-Search#473]
**Describe the bug**
it will still have animation effect even it's disable

**To Reproduce**
1. turn off `Enalble animations` 
2. launch FS

**Expected behavior**
no animation

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 11 Version: 21H2
 - Fluent Search Version 0.9.90.998
 
**Additional context**

https://user-images.githubusercontent.com/93647031/150711395-1e9a124b-dd52-45ee-84dc-b5974a32d697.mp4

**Comment by u-Sir** [comment]
I reset it , it works correctly. it happened in 0.9.90.997 update to 0.9.90.998.

**Comment by Metroid-Prime** [comment]
I was just typing up a bug report.  (Thankfully I checked my RSS  feed prior to doing so).

Can confirm this is a problem in v998

**Comment by Metroid-Prime** [comment]
@adirh3  did you fix this in .999?  It's fixed now! 🗡️ 
@u-Sir  please update and confirm if still happening!
