### ISSUE TITLE
Add changelog link to About window. 

### ISSUE THREAD

**Issue by Metroid-Prime** [adirh3/Fluent-Search#474]
![image](https://user-images.githubusercontent.com/1836362/150715048-4da04763-8fc0-447c-abfa-f3c3de698226.png)

**Comment by Metroid-Prime** [comment]
The rationale for this is some of the best apps have links to their changelog somewhere in the about menu. This is especially true for Mac apps.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.9991

**Comment by Metroid-Prime** [comment]
@adirh3  FYI I don't see v9991 posted. I will check this once updater gets to it.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.9992

**Comment by Metroid-Prime** [comment]
Yay! Confirmed. Closing
