### ISSUE TITLE
plugins windows can't scroll by trackpad or wheel

### ISSUE THREAD

**Issue by u-Sir** [adirh3/Fluent-Search#475]
**Describe the bug**
plugins windows can't scroll by track pad or wheel after the page loading complete
![图片](https://user-images.githubusercontent.com/93647031/150737844-99474d75-27b5-420e-8504-f0bb1f37287f.png)

**To Reproduce**
1. Go to plugins 
![图片](https://user-images.githubusercontent.com/93647031/150737960-92737d72-8710-4b21-a183-3e7eb019b900.png)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 11 Version: 21H2
 - Fluent Search Version 0.9.90.998

**Additional context**

**Comment by Metroid-Prime** [comment]
I don't have a trackpad, but my middle mouse (Logitech MX Master 2) works fine for scrolling Plugins window after loaded, FYI!
![image](https://user-images.githubusercontent.com/1836362/150746244-9e8e49d6-8aa6-4c64-9cc9-981d6575d6f7.png)

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.999
