### ISSUE TITLE
FS INDEXER - Characters Bug

### ISSUE THREAD

**Issue by mragtronx8** [adirh3/Fluent-Search#477]
characters like " ñ Ş ü ğ / etc " are not found with FS INDEXER "if the object search has these characters" 

eg: if searching for seyma 
and file name = "Señorita ( Violin Cover ) _ Şeyma Abdüsselamoğlu"
everything INDEXER find such term, but fs INDEXER doesn't

fs indexer = finds all, except when search item {name} contains letter/characters like  " ñ Ş ü ğ / etc"

**Comment by adirh3** [comment]
Thanks! duplicate with #388
