### ISSUE TITLE
SEARCH BAR SIZE

### ISSUE THREAD

**Issue by mragtronx8** [adirh3/Fluent-Search#478]
![image](https://user-images.githubusercontent.com/62798102/151208530-27d3ac57-0f8b-4bcd-9593-d0b814073ef7.png)

feature request: to make the search bar width go more smaller; without affecting the right side icons.
what's the smallest width size that can done; while preserving right icons.

can it be made more smaller [width]

**Comment by adirh3** [comment]
@mragtronx8 why did you close it?
