### ISSUE TITLE
File Prioritization issue

### ISSUE THREAD

**Issue by erohtar** [adirh3/Fluent-Search#480]
**Describe the bug**
I have these extensions prioritized:
![image](https://user-images.githubusercontent.com/5120628/151588403-55c11321-16c1-4532-a849-28f684a43f8d.png)

But still when I search for an exe file that I haven't used before through FS before, it pops up all kinds of random files first and the prioritized extensions are ignored. Sometimes they don't even show up in the first 15-20 items that FS is set to display.
Quite frustrating.

Here's an example where exe should be right at the top, but it's the last:
![image](https://user-images.githubusercontent.com/5120628/151588834-71dd345a-5ac7-4995-9d2d-a2da79eb4e66.png)

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.9994

**Comment by erohtar** [comment]
I'm not sure if it's fixed. I just updated FS and tested again, and it shows same problem:
![image](https://user-images.githubusercontent.com/5120628/151699743-60ebc6f4-fa2c-4844-95f3-f69e80dd3d76.png)

Here are my other priority settings:
![image](https://user-images.githubusercontent.com/5120628/151699751-39783133-c000-4c97-abdc-9a0eb74129d7.png)
![image](https://user-images.githubusercontent.com/5120628/151699754-25a34631-6ebe-4099-a0f1-4f06ceed3d5d.png)

**Comment by adirh3** [comment]
@erohtar disable this new setting -
![image](https://user-images.githubusercontent.com/27368554/151699949-bf875234-20ae-485c-ab28-3d6990063f69.png)
And check again

**Comment by erohtar** [comment]
Okay this is after disabling the 'learn' setting:
![image](https://user-images.githubusercontent.com/5120628/151700033-9690e9e5-9440-4f70-9b15-283bf8e31d5d.png)

And this is after also making the extension list blank:
![image](https://user-images.githubusercontent.com/5120628/151700044-428ff451-f16f-43f7-bacc-f150ab801b1a.png)

**Comment by adirh3** [comment]
@erohtar did you enable 'Order results by time' in Settings -> files?

**Comment by erohtar** [comment]
Ah yes it was enabled. But how would one know what takes priority - File type or date?
I'd think type should come first and then date on files that're otherwise considered equal priority - but maybe let it be a user setting if you don't agree.

Btw this is after turning it off:
![image](https://user-images.githubusercontent.com/5120628/151702404-8fd2e54c-d33c-4d53-a5fc-80eebe96885e.png)

**Comment by adirh3** [comment]
@erohtar as the setting says, it **orders** results by time modified **ignoring** all other priorities and machine learning. (This was requested by other users)
By default, FS already prioritizes results by time when results have similar priorities.

**Comment by erohtar** [comment]
Oh I'm sorry, I missed reading that description there carefully. I believe this can be closed now, thank you!
