### ISSUE TITLE
search tag icon on searchbar can't remove occasionally

### ISSUE THREAD

**Issue by u-Sir** [adirh3/Fluent-Search#482]
**Describe the bug**
search tag icon on search bar can't remove occasionally

**To Reproduce**
1. add web search like pic below, and set `always clear search tags` on
![图片](https://user-images.githubusercontent.com/93647031/151667527-97cf5f73-c7e8-4970-aa39-8bf33ddaaeb4.png)
2. use `bilibili` to search anything
3. launch FS search bar again

**Screenshots**
![图片](https://user-images.githubusercontent.com/93647031/151667622-a8df060c-433f-49f1-bcb9-8449af644b08.png)
![图片](https://user-images.githubusercontent.com/93647031/151667628-c84f0ce4-07e3-4637-aa90-288af5f5bc34.png)

**Desktop (please complete the following information):**
 - Windows 11 Version: 21H2
 - Fluent Search Version 0.9.90.9993

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.9995

**Comment by u-Sir** [comment]
> This issue has been potentially fixed in version 0.9.90.9995

in version 0.9.90.9995, it still happened occasionally .

**Comment by adirh3** [comment]
@u-Sir I can't repro this, does it happen only with that web search? or others as well, such as Google?

**Comment by u-Sir** [comment]
> @u-Sir I can't repro this, does it happen only with that web search? or others as well, such as Google?

it seems fixed. I can't repro this too now.
