### ISSUE TITLE
support full-text search

### ISSUE THREAD

**Issue by u-Sir** [adirh3/Fluent-Search#483]
https://anytxt.net/, something like anytxt.

**Comment by adirh3** [comment]
@u-Sir You mean file content search?

**Comment by u-Sir** [comment]
> @u-Sir You mean file content search?

yes

**Comment by WalterNagelGmbH** [comment]
Would be very nice to get this feature.

**Comment by Pupka-Lipinski** [comment]
would be nice to get this feature

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.92.0                                          . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by Explorare** [comment]
This issue has been marked as completed, but I don't think file content search feature has been implemented in the recent release. Did I miss something?
