### ISSUE TITLE
Start as Search Bar only, looking into last results starts at second entry

### ISSUE THREAD

**Issue by erohtar** [adirh3/Fluent-Search#484]
**Describe the bug**
When FS is set to start as Search Bar only, and I want to select one of the previously launched items and press down arrow, the window is expanded and the SECOND result is selected (because the first result was already selected but there's no way to tell what is it, except remembering it). 

**Expected behavior**
When only the search bar is showing, the first down arrow should only expand the window, but not traverse down the result list.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.94                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by erohtar** [comment]
Yes, that bit is finally working as expected, thank you
