### ISSUE TITLE
Pasting search term doesn't expand FS window

### ISSUE THREAD

**Issue by erohtar** [adirh3/Fluent-Search#485]
**Describe the bug**
If you have FS set to search bar only, then paste a search term, then the window does not auto-expand, even though the new results are loaded. 
Even weirder, if I backspace clear the search term, then window goes back to search bar only (which is good), but if I paste the search term again, this time the window expands correctly!

**Comment by adirh3** [comment]
@erohtar should be solved on latest

**Comment by erohtar** [comment]
Yes! working great now, thank you!
