### ISSUE TITLE
Change "Alpha" text to "Pre-release"

### ISSUE THREAD

**Issue by Metroid-Prime** [adirh3/Fluent-Search#49]
This was supposed by 2 or 3 others in Discord.

Change the "Alpha" text to "Nightly" 

EDITED by Metroid Prime on 6/6/21 10:11 PM PST due to comment made by user below. I agree Nightly is much better description than everything else mentioned.

**Comment by Sriknath** [comment]
Or nightly?

**Comment by Metroid-Prime** [comment]
> Or Nightly?

@Sriknath  we talked about this yesterday and I believe Pre-release was decided. I'm fine with Nightly or Pre-release. Will leave it up to @adirh3   Either of those is better than Alpha

**Comment by Nomad-0** [comment]
I think it's not much required now as Adir added an explanation here. However, some text might be missing here-
![image](https://user-images.githubusercontent.com/76395594/120961712-25de5080-c780-11eb-8828-5be7a8b521ec.png)

**Comment by Metroid-Prime** [comment]
Can I change this request?
@Nomad-0  @adirh3  I actually agree with @Sriknath that **Nightly** is the top option for this hands down.

"Stable" and "Nightly" flow together the best

**Comment by adirh3** [comment]
This_issue_has_been_potentially_fixed_in_version_

**Comment by Nomad-0** [comment]
@adirh3 maybe a change here too?
![image](https://user-images.githubusercontent.com/76395594/121111505-cbe99380-c830-11eb-8c36-11270e3ca7eb.png)

**Comment by kwanice** [comment]
![image](https://user-images.githubusercontent.com/14847187/121297101-17b04180-c8f2-11eb-89f5-e8064b8de8cb.png)
still something wrong :p

**Comment by Metroid-Prime** [comment]
Nice catch @kwanice  I just noticed the same.  I'll keep the issue open. Should be a very easy fix.
@adirh3  once reference text is fixed, please close the ticket and tag me.

**Comment by adirh3** [comment]
I plan to change all descriptions very soon so I skipped it for now

**Comment by Metroid-Prime** [comment]
I'll go ahead & close this then as the original request was fulfilled. We look forward to new descriptions :)
