### ISSUE TITLE
FS does not find files on networked drives at startup.

### ISSUE THREAD

**Issue by Metroid-Prime** [adirh3/Fluent-Search#490]
.9999 stable. When FS is launched at startup, files from O:\ network share drive are not indexed by FS.  When re-launched, it finds all of the relevant files.

**Comment by adirh3** [comment]
@Metroid-Prime does it work on latest nightly? forgot to attach this issue on changelogs

**Comment by Metroid-Prime** [comment]
@adirh3  unfortunately not :(  

FS's indexing for network files is really working.

**Comment by Metroid-Prime** [comment]
Confirmed to @adirh3  on 2.27.22 that this is still an issue.  Mac OSX network drives are showing up as NTFS drives - that might be the issue.

Reverted to everything until FS indexer fixed.

**Comment by Metroid-Prime** [comment]
This has been fixed 91.25 nightly. Closing!
