### ISSUE TITLE
Release Feed option not available in system settings

### ISSUE THREAD

**Issue by riotrah** [adirh3/Fluent-Search#491]
**Describe the bug**
Hello!

This is one of my favorite OSS windows apps of all time ( alongside FancyWM ).

Anyways, I observe that instructions indicate to upgrade to Nightly by using the Release Feed dropdown in Settings > System. However, I do not see it there, regardless of Advanced on/off.

I cannot remember right now how I installed FS, though I think it might have been winget or MSStore.

**To Reproduce**
1. Go to 'Settings'
2. Click on 'System'
3. See no release feed ( screenshot attached )

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/22646419/152632561-a0b8dd84-eabb-4dff-a479-fb9608c57bad.png)

**Desktop (please complete the following information):**
Edition	Windows 10 Pro
Version	21H1
OS build	19043.1466
Experience	Windows Feature Experience Pack 120.2212.3920.0

 - Fluent Search Version === 0.9.90.9999

**Additional context**
I'd installed and used FS on a previous laptop, and recall a Release Feed dropdown ( I think! ) being present

**Comment by Metroid-Prime** [comment]
![image](https://user-images.githubusercontent.com/1836362/152632959-272f4a2f-db01-4f20-a773-aa5ad1adb64d.png)
 This is what I see in .9999.

Looks normal to me?

**Comment by adirh3** [comment]
Hey @riotrah, it is not possible to use the nightly feed when installing through the Microsoft Store.
Also, note that right now the nightly and the stable builds are identical (the nightly will update next week)
