### ISSUE TITLE
Exclude files by pattern, not only by path

### ISSUE THREAD

**Issue by eikaramba** [adirh3/Fluent-Search#493]
I'm using the file search and get a lot of files in the gradle or node_modules folders, which have quadrillions of files in them. so in ueli i was able to exclude them by a pattern.

In fluent search i can only specify paths, but that is not working as i have node_modules folders for every node project i am starting and already have to many to specify them manually.

i think that could be an easy feature to add right?

**Comment by eikaramba** [comment]
Okay i switched to Everything (was using it in ueli before anyway) and because you can specify exclude patterns in everything it seems to work now. Sry for creating this ticket.

this means this ticket is only valid if one is using the internal search engine. with everything you can make this work.

**Comment by adirh3** [comment]
@eikaramba There is no support yet for include/exclude **indexed** files/folders by pattern. Will add it in next version.

Have you tried using Prioritizations? The `Context prioritization` in Settings (Advanced) -> Prioritization gives you the ability to exclude any results based on their context.
Context can be file path, URL and more.
![image](https://user-images.githubusercontent.com/27368554/152679844-d0bc6a3e-5395-447b-b3e5-1ad962221b1d.png)

**Comment by eikaramba** [comment]
nice that could also work. your app is incredible powerful! It means something after years of listary, ueli, powertools run to end up with fluent search now :)

**Comment by adirh3** [comment]
> nice that could also work. your app is incredible powerful! It means something after years of listary, ueli, powertools run to end up with fluent search now :)

Glad it's been useful for you! 
Feel free to share any feedback here or in Discord :)

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.19                                         \nChangelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by eikaramba** [comment]
in the changelog it is mentioned that you can only filter files by wildcards. can i also exclude folders via regex/file name as the requirement of this ticket would be to exclude all e.g. "node_modules" folders on the pc

**Comment by adirh3** [comment]
@eikaramba I apologize for not replying for a while, you can filter all node_modules folders using the context prioritization feature, e.g. `*\node_modules\*`.
Closing, feel free to reopen if needed.

**Comment by eikaramba** [comment]
@adirh3 thank you for that info. however this is not working
![grafik](https://github.com/adirh3/Fluent-Search/assets/1320525/0cffe06c-44cc-4f99-92fc-c855f680eab1)
i tried all 3 columns.

still having lot of results from node_modules folders in the search results
