### ISSUE TITLE
Minor UI problem with Rebuild Index when new path is added/removed

### ISSUE THREAD

**Issue by nutnutwin** [adirh3/Fluent-Search#494]
**Describe the bug**
Settings > Files
UI issue

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Files'
3. Scroll down to 'paths and indexing', add/remove a path
4. See error(Screenshot)

**Expected behavior**
｢press the Rebuild index button **above**｣
conflict with
｢press Rebuild index button **below**｣

also I didn't find any "Rebuild button"...? 

**Screenshots**

<img width="630" alt="20220207_Mon -072236" src="https://user-images.githubusercontent.com/34512273/152704042-1d9b4f3c-7ebf-4474-bd90-80b779704a44.png">

**Desktop (please complete the following information):**
 - Windows 11 Version: 21H2
 - Fluent Search Version [e.g. 0.9.99.9999]

**Additional context**

**Comment by adirh3** [comment]
@nutnutwin thanks, this should be fixed on latest nightly

**Comment by nutnutwin** [comment]
@adirh3 Thank you for your time!
