### ISSUE TITLE
Unable to enter or change new web search tags.

### ISSUE THREAD

**Issue by Metroid-Prime** [adirh3/Fluent-Search#495]
Running 0.9.91.1. Not sure when this started.
I cannot modify existing or new entries.  All I can do is delete them or add new ones, but none of the text boxes work anymore to enter information!

![image](https://user-images.githubusercontent.com/1836362/152709345-01c071e3-24a1-4fa2-b288-56b19541437f.png)

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.12

**Comment by Metroid-Prime** [comment]
Fixed in .12, closing
