### ISSUE TITLE
On Screen Hints Are Too Large

### ISSUE THREAD

**Issue by choskeli** [adirh3/Fluent-Search#498]
**Is your feature request related to a problem? Please describe.**
When you use "Search in-app using Screen hotkey" the hints it brings up on screen are too large, making it difficult to tell what UI element the hint is actually referring to.

**Describe the solution you'd like**
Hints should be smaller by default and possibly a different color. Similar to hints from cvim, hunt and peck, vimac or other applications that show on screen hints.

**Describe alternatives you've considered**
Ideally size, foreground color, background color, and transparency would be configurable.

**Comment by adirh3** [comment]
@choskeli I will make it customizable, but FYI right now it's based on the `Font Scale` setting

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.42                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
