### ISSUE TITLE
On Screen Hints Don't Efficiently Use Character Options

### ISSUE THREAD

**Issue by choskeli** [adirh3/Fluent-Search#499]
**Is your feature request related to a problem? Please describe.**
The on screen hints when using "Search using Screen hotkey" never uses single character hints and only allows A-Z for the character set.

**Describe the solution you'd like**
Allow the hint character set to be configurable (e.g. why can't ; or , or . or 4 or 7 be a hint). Use single character hints whenever possible (e.g. you don't need to use all 2 character options to fill all hints, so use some 1 character options instead. Only stop using 1 character options if it would force some options to be 3 character)

**Describe alternatives you've considered**
Modifying hunt and peck to be faster so it can be used instead for this purpose.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.82                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
