### ISSUE TITLE
Ghost icon in system tray

### ISSUE THREAD

**Issue by Metroid-Prime** [adirh3/Fluent-Search#5]
This was a regression bug from v0.9.82.40 onwards I believe.

Exiting app leaves ghost icon in the notification tray (Windows 10 64bit). Is this a system issue or one exclusive to FS?  This was fixed in changelog on 5/29, but was reintroduced on release from 5/30

**Comment by mochigithub** [comment]
I've noticed this occurs especially after FS upgrades. When exiting from the right click | exit   sys tray menu it doesn't seem to happen.

**Comment by mochigithub** [comment]
This is not reproducible, ugh.  Was this fixed again in the past version? I have not seen it during the latest 2 updates.  

**If anyone has seen this behavior please post here!**

**Comment by Nomad-0** [comment]
I faced this on the latest update, so it's not fixed yet I guess. (I've faced it mostly after upgrade)

**Comment by adirh3** [comment]
The icon will not remove when FS crushes, and you probably noticing it more lately since the last few versions were unstable.
Check if it's removed once you exit FS safely.

**Comment by Metroid-Prime** [comment]
I believe it is, yes.

@adirh3  Strangely I've seen it in recent memory when FS was auto-updating itself.  I assume when the updater is quitting FS gracefully and not force quitting it? 

I tried to replicate it myself and I couldn't but I will continue to monitor this.  @Nomad-0  if you're able to replicate or seeing it in non-crashing situations, please feel free to speak up :)

**Comment by Metroid-Prime** [comment]
FYI: @adirh3  @Nomad-0   I just saw this ghosting issue on Windows 10 LTSC  as the FS auto-updater updated to 0.9.85.50.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.85.75

**Comment by Nomad-0** [comment]
It still occurs.

**Comment by Metroid-Prime** [comment]
Well, I can confirm it still happens _when updating to .75_ but I don't know if that's because it's inherent to the version before it. We'll have to wait for the next version to find out if it's fixed in .75

**Comment by Nomad-0** [comment]
> Well, I can confirm it still happens _when updating to .75_ but I don't know if that's because it's inherent to the version before it. We'll have to wait for the next version to find out if it's fixed in .75

you can find out by killing FS with kill plugin

**Comment by Metroid-Prime** [comment]
Well, I think "killing" FS is unfair. I'd be fine with it not ghosting during proper closure during updating.
Not ghosting at all would be best, but I'm not sure how Adir is going to achieve that when the app is killed as it won't be running lol

**Comment by Nomad-0** [comment]
just found out it's the same if we kill other apps also. I think maybe it's something with OS?

**Comment by Metroid-Prime** [comment]
yes I believe so.  I think this is not a request we can expect Adir to fix as it's a windows issue. I think the only time I would expect FS to NOT ghost is when it's reinstalling itself.

**Comment by adirh3** [comment]
> yes I believe so. I think this is not a request we can expect Adir to fix as it's a Microsoft Windows issue issue. I think the only time I would expect FS to NOT ghost is when it's reinstalling itself.
> 
> @adirh3 if we can get this not to ghost during FS's reinstallations that would be good enough for me. If it's too much effort, **please** let me know and I'll close this. This is honestly not a high priority for me.

I fixed it in the last version you will see it's clearing the icon the next update

**Comment by Metroid-Prime** [comment]
I didn't see it this time.  @Nomad-0  what say yee? I'll close this and if we see it happening, reopen
