### ISSUE TITLE
Prioritize Text over Tree-View Items, Buttons, etc. in On Screen Application Search

### ISSUE THREAD

**Issue by choskeli** [adirh3/Fluent-Search#500]
**Is your feature request related to a problem? Please describe.**
When searching within an application, Tree-View has priority over Text for on screen search. However, clicking the Tree-View element typically doesn't work (as in it does nothing), while clicking the Text element typically does work.

**Describe the solution you'd like**
Text should be higher priority (probably higher than all other UI elements).

**Comment by adirh3** [comment]
> **Is your feature request related to a problem? Please describe.** When searching within an application, Tree-View has priority over Text for on screen search. However, clicking the Tree-View element typically doesn't work (as in it does nothing), while clicking the Text element typically does work.
> 
> **Describe the solution you'd like** Text should be higher priority (probably higher than all other UI elements).

Thanks, you mean tree view item, right? Because the normal tree view will just expand/collapse when triggered

**Comment by choskeli** [comment]
> > **Is your feature request related to a problem? Please describe.** When searching within an application, Tree-View has priority over Text for on screen search. However, clicking the Tree-View element typically doesn't work (as in it does nothing), while clicking the Text element typically does work.
> > **Describe the solution you'd like** Text should be higher priority (probably higher than all other UI elements).
> 
> Thanks, you mean tree view item, right? Because the normal tree view will just expand/collapse when triggered

Yes "TreeItem"

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.34                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
