### ISSUE TITLE
remove connection, the line not gone

### ISSUE THREAD

**Issue by u-Sir** [adirh3/Fluent-Search#502]
**Describe the bug**
remove connection, the line not gone

**To Reproduce**
1. Go to 'tasks'
2. remove any connection
3.  See error

**Expected behavior**
the line should removed

**Screenshots**
![图片](https://user-images.githubusercontent.com/93647031/153794875-e75d24a2-f7c0-4ad3-ae45-aebe73f7227d.png)

**Desktop (please complete the following information):**
 - Windows 11 Version: 21H2
 - Fluent Search Version 0.9.91.15

**Additional context**

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.24                                         \nChangelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
