### ISSUE TITLE
Add an option to open links with a single click rather than double click

### ISSUE THREAD

**Issue by shockproof22** [adirh3/Fluent-Search#503]
Simply open links with a single click to slightly speed up searching.
An option in the settings would be greatly appreciated!

**Comment by Metroid-Prime** [comment]
If I'm reading this request correctly, I don't like this idea. Double click is more natural + If one left clicked on an item, it would the user be able to select an item?

**Comment by shockproof22** [comment]
what I mean is when I type a query in the search bar and a list of suggestions come up, if it's the 1st result then just entering it works; but say I'm interested in the 5th result then currently I have to double click it and only then the file or website will open.
single left click "selects" it and opens it in the right pane (which I don't want)

In windows search all of this happens with a simple single-left click which I'm sure everyone is already used to.

And if you are favouring double left click just cause, on a single left click it first shows the details in the right pane then again clicking on it to open; then this can simply be fixed by small arrows next to the result like in windows results to "select" the result without opening it and again clicking to open it.

single left clicking to open results just feels more natural to me after using windows search for so many years.

windows search results handle this correctly,
![S (805) (12-13)](https://user-images.githubusercontent.com/60001922/153816234-5a087c36-1479-4ce1-83ed-53fa10ff0e7d.png)
 
but in this app no arrows,
![S (806) (12-01)](https://user-images.githubusercontent.com/60001922/153817440-ec89a3e9-b49c-4807-be9e-ab483c316815.png)

so I think any of these 3 suggestions must be implemented,
1. adding these small arrows to first "select" the result and view it in the right pane
2. a togglable option in the settings to open results with a single left click
3. or an option to "select" the result and open in right pane using single **right** click and single **left** click to directly open the result

I'm sure any of these suggestions are not that hard to implement and for me personally would greatly improve the UX of this already wonderful and hugely customizable app.

**Comment by shockproof22** [comment]
also P.S I use this app just for web related stuff like website opening, bookmark searching, translate, definitions etc.

Fluent App Version: 0.9.90.9999
Windows 11 Version: 21H2 (OS build 22000.493)

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.16
Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
