### ISSUE TITLE
Fluent Search Settings/Customisation icon not visible in the window

### ISSUE THREAD

**Issue by Gargantuan5k** [adirh3/Fluent-Search#504]
**Describe the bug**
The gear icon next to search bar, used to open the customisation window for fluent search is not visible in Windows 11.

**To Reproduce**
1. Open fluent search
2. Look next to the search bar, no settings icon
3. See error

**Expected behavior**
Expected to see a settings icon next to the search bar to access customisation options, currently cannot find any way to customise the app

**Screenshots**
![No Settings icon ss](https://user-images.githubusercontent.com/73837135/153990339-c17cc008-e2b6-45cf-b2db-a4fd84ef5b0b.png)

**Desktop (please complete the following information):**
 - Windows 11 Version 21H2
 - Fluent Search Version 0.9.90.0

**Additional context**
N/A

**Comment by adirh3** [comment]
@Gargantuan5k thanks, the settings button has been removed due to user feedback.
You can open settings through - 
1. System tray menu
2. Right click search bar
3. Press SHIFT+ENTER in the search window
3. Search settings

**Comment by Gargantuan5k** [comment]
@adirh3 Didn't know that, thank you for the help! Closing issue now
