### ISSUE TITLE
Have white box on latest win11 build on Dev channel

### ISSUE THREAD

**Issue by kerwinxxx** [adirh3/Fluent-Search#507]
<img width="612" alt="image" src="https://user-images.githubusercontent.com/55703606/154902118-7575e426-30ec-4842-afde-8d89f7e422d3.png">

**Comment by adirh3** [comment]
@kerwinxxx I believe this is a issue that affecting other apps as well the Windows team is looking into

**Comment by adirh3** [comment]
@kerwinxxx I believe this is fixed on latest Windows 11 builds, closing.
Feel free to reopen if the issue still happens.
