### ISSUE TITLE
Wrong OneDrive Path

### ISSUE THREAD

**Issue by Chance92** [adirh3/Fluent-Search#508]
**Describe the bug**
When searching for items in OneDrive folder, FS often finds them in the ONEDRI~1 folder. When opening the path, the status of the items are often not available.

**To Reproduce**
1. Invoke FS and search for an item in a OneDrive folder.
2. See error

**Expected behavior**
FS should be able to find the path as seen in File Explorer.

**Screenshots**
<img width="565" alt="Snipaste_2022-02-21_11-21-13" src="https://user-images.githubusercontent.com/85488695/154946928-1aa8b5a4-995b-4a71-ad0a-c0790fb1a76d.png">
The first two folders are actually the same folder.

![image](https://user-images.githubusercontent.com/85488695/154947227-6d9b4ccd-5407-42ee-a052-a9e6d60438ac.png)

**Desktop (please complete the following information):**
 - Windows 10 Version: 21H1
 - Fluent Search Version 0.9.91.21

**Additional context**
This bug has existed for a very long time.

**Comment by adirh3** [comment]
@Chance92 does rebuild solve this?

**Comment by Chance92** [comment]
> @Chance92 does rebuild solve this?

Unfortunately it doesn't.

**Comment by adirh3** [comment]
> > @Chance92 does rebuild solve this?
> 
> Unfortunately it doesn't.

Is your E drive a partition, or a separate drive?

**Comment by Chance92** [comment]
> > > @Chance92 does rebuild solve this?
> > 
> > 
> > Unfortunately it doesn't.
> 
> Is your E drive a partition, or a separate drive?

It's a partition.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.47                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by Chance92** [comment]
Issue fixed. Thanks.
