### ISSUE TITLE
Prioritization settings table missing scrollbar 

### ISSUE THREAD

**Issue by Metroid-Prime** [adirh3/Fluent-Search#51]
![image](https://user-images.githubusercontent.com/1836362/120917706-7ca33780-c665-11eb-885f-146168a64709.png)

**Comment by Nomad-0** [comment]
I think showing the full table instead of scrolling inside the table would be better here. Adir told it's a bug.

**Comment by Metroid-Prime** [comment]
> I think showing the full table instead of scrolling inside the table would be better here. Adir told it's a bug. most of the tables had this problem previously.

Agree. Fully showing the table is appropriate.

**Comment by adirh3** [comment]
Duplicate with #6
