### ISSUE TITLE
Consider not setting ctrl + shift + c as a global hotkey by default

### ISSUE THREAD

**Issue by billie-spektor** [adirh3/Fluent-Search#510]
I was wondering why the element picker shortcut in Chrome / Edge stopped working and it turned out to be overruled by a Fluent Search global hotkey. I would suggest to reconsider registering this key combination as a global shortcut by default, as it conflicts with shortcuts in a number of popular programs (such as Chromium browsers, Microsoft Word, 1password). I know I can change the hotkey in Fluent Search, but initially I wasn't aware that the source of the conflict was Fluent Search. 

If you prefer keeping this default behaviour, it could help if all global shortcuts, including ctrl + shift + c, are mentioned in the welcome window.

**Comment by adirh3** [comment]
Thanks @billie-spektor, I will remove all default hotkeys except Ctrl+Alt and Ctrl+M by the next stable version (already available in nightly)
