### ISSUE TITLE
Web search suggestion on every web search (even though settings turned off)

### ISSUE THREAD

**Issue by Metroid-Prime** [adirh3/Fluent-Search#511]
Based on our discussion via Discord:

It gets fixed when (as you suggested) switching to Google, then off, but the problem re-appears when you re-launch FS
 
![image](https://user-images.githubusercontent.com/1836362/155879140-3838df83-8146-4b55-b404-ddeca959e097.png)

**Comment by Metroid-Prime** [comment]
Finding this behavior slows down all web searching and usurps CPU cycles :-(

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.37                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by Metroid-Prime** [comment]
Confirmed fixed, thank you.
