### ISSUE TITLE
Remove all contexts when the search bar restart.

### ISSUE THREAD

**Issue by yayiji** [adirh3/Fluent-Search#512]
Remove all contexts when the search bar restart.

**Comment by adirh3** [comment]
@yayiji I will need more information on that.
What do you mean by contexts?

**Comment by yayiji** [comment]
Sorry, I mean this:
![image](https://user-images.githubusercontent.com/12449762/156052622-10e2e764-011e-44b8-9925-7278b0e2b2fa.png)

I use the clipboard feature very frequently, but every time I open the Search bar it is replaced by the clipboard entry and I need extra action to start searching. I usually use one shortcut to open the Search Bar and another shortcut to open the clipboard, but now when I want to open the Search Bar there is often a chance that the last opened clipboard will be replaced. I wish there was an option to completely clear the last record, not just the text.

**Comment by adirh3** [comment]
> Sorry, I mean this: ![image](https://user-images.githubusercontent.com/12449762/156052622-10e2e764-011e-44b8-9925-7278b0e2b2fa.png)
> 
> I use the clipboard feature very frequently, but every time I open the Search bar it is replaced by the clipboard entry and I need extra action to start searching. I usually use one shortcut to open the Search Bar and another shortcut to open the clipboard, but now when I want to open the Search Bar there is often a chance that the last opened clipboard will be replaced. I wish there was an option to completely clear the last record, not just the text.

Did you try enabling `Always clear search tags` in Settings -> Search tags?

**Comment by yayiji** [comment]
Thanks, I didn't know there was this option before, now it's ok.
