### ISSUE TITLE
Folders do not open

### ISSUE THREAD

**Issue by Elaws** [adirh3/Fluent-Search#514]
**Description :**

Is there a known issue where sometimes folder do not open ? Restarting Fluent Search does not seem to solve the issue.

Thanks !

**Environment:**
- Dual monitor setup, with second monitor **to the left** of main monitor.
 - Windows 10 Version: [e.g. 21H2]
 - Fluent Search Version [e.g. 0.9.90.9999]

**Comment by adirh3** [comment]
@Elaws how do you open the folder? by searching and pressing Enter? on the home screen?

**Comment by Elaws** [comment]
Thanks for your reply : The folder is opened by searching an pressing Enter.

**Comment by adirh3** [comment]
> Thanks for your reply : The folder is opened by searching an pressing Enter.

Is it a specific folder or all folders? does it happen consistently?
Also, can you check if pressing with mouse on Open works?

**Comment by Elaws** [comment]
For the last few days, it happened at least once per day. Last time it happened, I tested with other folders and neither did they open.

I will tell you if pressing with mouse on "Open" works, next time it happens.

**Comment by Metroid-Prime** [comment]
I _think_ I'm also seeing this as well. I really can't say for sure as I wasn't paying attention closely but sometimes in the past week or two folders haven't been opening at random and I use exclusively keyboard "open parent folder" and XYplorer integration

**Comment by ikjadoon** [comment]
I am having the exact same issue. For me, it seems to happen when the index believe a folder exists, but it does not. Could this be anyone else's issue?

Apologies if this is a different bug than everyone else; if so, I can file a new issue.

Fluent _believes_ this path exists:

![image](https://user-images.githubusercontent.com/3848795/158042715-a80c0307-ac37-46bd-bc1d-9e7d768b46bf.png)

However, this folder does not exist; hidden items are enabled in File Explorer. Manually typing in the path in File Explorer also yields an error.

![image](https://user-images.githubusercontent.com/3848795/158042738-a79552d3-dc46-484a-98f4-eec5e19d408d.png)

![image](https://user-images.githubusercontent.com/3848795/158042759-b6885896-8173-4390-8392-4a693f616f15.png)

I've rebuilt the Fluent search File index 3x already and it still has this phantom path that always fails to open. Even more unusually, Fluent is meant to ignore this whole folder anyways: C:\users\me\AppData\Local,

![image](https://user-images.githubusercontent.com/3848795/158042884-d1b45840-781d-45f1-bc55-34d605643e75.png)

**Environment:**
Windows 11 Pro (2200.556)
Fluent Search 0.9.90.9999 (installed via *.exe for all users / UAC)
Dual monitors: left primary. Both 2560x1400, 24".

**Comment by adirh3** [comment]
@ikjadoon, sorry for the delayed response.
This is a different issue as you thought, but it's not related to file indexing.
App indexing happens from the start menu folder, since you got a lnk file to Notion in the start menu folder which is invalid.
You can remove that lnk file in `C:\ProgramData\Microsoft\Windows\Start Menu\Programs` to solve it.

**Comment by ikjadoon** [comment]
> @ikjadoon, sorry for the delayed response. This is a different issue as you thought, but it's not related to file indexing. App indexing happens from the start menu folder, since you got a lnk file to Notion in the start menu folder which is invalid. You can remove that lnk file in `C:\ProgramData\Microsoft\Windows\Start Menu\Programs` to solve it.

No worries: thank you for figuring out my issue! You were 100% right: it was a bad shortcut. For me, the bad Notion.lnk was lingering on a desktop folder I'd long forgotten about. I used the Start Menu + hover over the item to see its location + delete it. Somehow, Windows didn't offer the usual "This shortcut is broken. Would you like to delete it?" prompt.

Much appreciated. 🙏

**Comment by Chance92** [comment]
I have also encountered this issue. I think this issue is related to the "open folder in existing window" setting. When I turned if off, the issue seemed to be resolved.

**Comment by adirh3** [comment]
As @Chance92 mentioned, `open folder in existing window` is probably enabled.
I fixed the original bug where FS identified the desktop as an existing explorer window.
