### ISSUE TITLE
Selectively apply the "Show at top most" setting

### ISSUE THREAD

**Issue by kidimbwi** [adirh3/Fluent-Search#516]
**Is your feature request related to a problem? Please describe.**

when the setting is toggled on all Fluent Search windows appear on top of other windows. on Fluent Search's main window this setting can be useful but when in other Fluent Search windows like the settings, we see rather interesting behaviour. please refer to this screenshot showing what happens when the setting is toggled on, that is let Fluent Search appear above all windows, and i want to select a default file manager from Settings > Files > Default file manager

![FS](https://user-images.githubusercontent.com/65897337/156997804-240bf27f-8457-41a8-aaa6-fc8d11d1e55a.png)

the explorer selection dialog appears behind Fluent Search.

**Describe the solution you'd like**

if it were possible, it would be nice to have the "Show at top most" setting apply to the main Fluent Search window only or have the ability to customize which Fluent Search windows this setting should apply to.

Thank you.

**Comment by Metroid-Prime** [comment]
I empathize with what your saying, but I somehwat disagree with this.  Always at top means always at top for the entire app -- excluding the settings pane would create a logical fragment.

![image](https://user-images.githubusercontent.com/1836362/157006937-1e68dabf-f4bf-4dc5-b2ee-d72b0fb30dc3.png)


@Nomad-0 @MakeshVineeth  Not sure how you guys feel about it.

**Comment by kidimbwi** [comment]
Thank you for contributing to the discussion. i get where you're coming from but please refer to the screenshot i posted, currently the only option for us if we want proper function of explorer selection dialogs with show on top enabled is all(turn the option on) or nothing(turn it off) this feature is an attempt at asking for a middle ground since i my case i would prefer to have the main launcher window always on top but not the settings window.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.27                                         \nChangelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by kidimbwi** [comment]
just tested the latest version and the windows now open on top of Fluent Search even with the top most setting enabled. Thank you @adirh3 for sorting this out quickly.
