### ISSUE TITLE
On Screen hint shortcut should toggle hints

### ISSUE THREAD

**Issue by knausj85** [adirh3/Fluent-Search#518]
**Is your feature request related to a problem? Please describe.**
I activate fluent search's on screen hints via a Bluetooth switch, so it'd be nice if the same shortcut would hide the hints when active

**Describe the solution you'd like**
When the on-screen hints are active, the same shortcut should hide/deactivate the hints

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.42                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by knausj85** [comment]
Works great, thanks!
