### ISSUE TITLE
Optionally start Fluent Search from service

### ISSUE THREAD

**Issue by Nuno69** [adirh3/Fluent-Search#519]
**Is your feature request related to a problem? Please describe.**
Fluent Search has an option to start it automatically at boot. Checking this option seems to register Fluent Search somewhere in the shell:startup directory which of course gives the desired effect. However with Windows 8, 8.1, 10 and 11's delayed startup Fluent Search is available some good minute after the system startup, which is unacceptable considering the fact that the tool is designed to be used constantly during the computer operation.

**Describe the solution you'd like**
I want Fluent Search to be started by the system service (FluentSearchIndexer). This will make it so that the application starts right after log on, as system services have priority over user-space programs.

**Comment by Metroid-Prime** [comment]
1 minute after startup? I don't remember seeing this on my win10 (LTSC 2021) computer.  It does launch slow but 1 minute??

**Comment by adirh3** [comment]
@Nuno69 is it better after recent updates?
