### ISSUE TITLE
README Error: Stable/Nightly

### ISSUE THREAD

**Issue by brimwats** [adirh3/Fluent-Search#520]
Nightly version (Previously called Alpha)
Nightly versions are updated daily, and most likely to contain bugs. You can update to Nightly version by changing Settings -> System -> Release feed -> Nightly.

This option does not exist in my fluent:
![image](https://user-images.githubusercontent.com/73113656/158430271-2cdbc8f1-d995-4ab2-a29f-6975763e025c.png)

**Comment by adirh3** [comment]
> Nightly version (Previously called Alpha) Nightly versions are updated daily, and most likely to contain bugs. You can update to Nightly version by changing Settings -> System -> Release feed -> Nightly.
> 
> This option does not exist in my fluent: ![image](https://user-images.githubusercontent.com/73113656/158430271-2cdbc8f1-d995-4ab2-a29f-6975763e025c.png)

Did you install through the Microsoft Store? it's not available when installed through the store

**Comment by Metroid-Prime** [comment]
Chances are high this has been installed through MS Store.  Latest version works fine here.

**Comment by brimwats** [comment]
ah yeah, that's the only way I could stop the UAC from triggering twice all the time.

**Comment by adirh3** [comment]
> ah yeah, that's the only way I could stop the UAC from triggering twice all the time.

Why triggering twice? When opening the EXE installer select "Install only for me" and then it will not require UAC when installing

**Comment by brimwats** [comment]
i don't **want** to install just for me though, I have multiple users?

**Comment by adirh3** [comment]
> i don't **want** to install just for me though, I have multiple users?

I see, I know we talked about it before just wanted to let you know that writing to program files requires UAC, you can install it on any other folder and create LNK files manually for other users.
