### ISSUE TITLE
Open Parent Folder only works the first time with Directory Opus

### ISSUE THREAD

**Issue by DrBones** [adirh3/Fluent-Search#521]
**Describe the bug**
With Directory Opus as File Manger (in default "replace Explorer" mode of Dopus as well as when inputting the command line in the "Default file manager" setting directly), the "Open Parent folder" works only the first time it is uses. It works again, when closing the windows that Fluent Search has opened. This seems to have started with the fix for the context switch issue #87. At least it does still work in 0.9.91.26 and not in 0.9.91.29. I have not tried the versions in between yet. Will update if I find something.

**To Reproduce**
- Close all Dopus windows
- Open Fluent Search
- Search for anything and use "Open Parent Folder" Action
- Dopus window pops up as expected
- Leave Dopus window open and search for anything else and use "Open Parent Folder" action again
- nothing happens

**Expected behavior**
Each and every time the "Open Parent Folder" action is used, a window with the folder should be opened. If the same folder as a prior search that window should be ideally activated.

**Desktop (please complete the following information):**
 - Windows 10 Version: 21H2  - 10.0.19044 Build 19044
 - Fluent Search Version: 0.9.91.29

**Additional context**
This does still work in 0.9.91.26 (checked in the portable version though). Might be related to the fix for #87 since that works now and is also Dopus related. The screenshot shows the command line used. Note that the "DUALPATH c:\" is only used to see if that setting is actually used or the default "file explorer replacement mode" of Dopus.

![image](https://user-images.githubusercontent.com/212259/159022828-95e5fdb1-72fb-428e-b0c5-b0a83ff81a47.png)

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.30                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by DrBones** [comment]
Wow, thank you for the quick patch!

It only kinda fixes it, though. Now, it actually does navigatge to the parent window the second time (and third) around. However, it only honors the "Default File Manager" settings when there is no open DOpus window. 

If I use the settings below, it opens the directory of the hard coded *toml file but when a window is already present, it simply navigates within the active window to the new parent path of the searched file and ignores the arguments of the dopusrt.exe command completely. This isn't too bad for me, although I prefer to have a new window open every time I execute that action. 

![image](https://user-images.githubusercontent.com/212259/159132306-2e911a5c-4dae-4c65-bd5e-8dc19d2df1fc.png)

Thank you so much for this awesome program!

**Comment by adirh3** [comment]
> 

Glad it's been useful for you.

To make sure FS will always open a new instance please disable this setting in Files -
![image](https://user-images.githubusercontent.com/27368554/159134799-1ff12ca7-21f9-4fe8-8168-b2cfee10e9fb.png)

Let me know if it's working as you expected.

**Comment by DrBones** [comment]
OH!

My bad, that setting is right above, and I did not even notice it!

Thank you! It looks like this is working properly in 0.9.91.30 now. Just for completeness’s sake and for any other DOpus user; I really like the following settings (screenshot) with the toggle switch "Open folders in existing explorer window" off and with "NEW EXISTINGLISTER" for the DOpus arguments. Now it opens a new window when the folder is not open somewhere and activates the window where that particular folder is displayed when it is. For me that is kind of the best of both worlds.

Thank you @adirh3, now I can enjoy the automatic context switch AND open all the parent folders. Your turnaround time for features and fixes is as always amazing!

![image](https://user-images.githubusercontent.com/212259/159156582-38ffe02c-5099-455f-a376-ffc61703ebdb.png)
