### ISSUE TITLE
The Calculator should understand thousands separators (1,000 vs 1000) based on locale

### ISSUE THREAD

**Issue by ikjadoon** [adirh3/Fluent-Search#522]
**Is your feature request related to a problem? Please describe.**
The built-in calculator does not understand thousands separators (**1,000** vs **1000**), even though the calculator outputs results with embedded thousands separators (making sequential calculations difficult).

Thus, Fluent Search treats numbers with thousands separators as text search terms, and not as numbers, unfortunately.

![image](https://user-images.githubusercontent.com/3848795/159078276-060f3780-9a51-458f-b7e7-d13d89af5283.png)
![image](https://user-images.githubusercontent.com/3848795/159078300-31bd9a52-6672-439e-8ba5-cc215655ed20.png)

**Describe the solution you'd like**
The calculator should, according to locale, understand thousands separators and treat them as numbers.

For example in the US: 1,000 should be interpreted as 1000 in the calculator. 

I prefer if Fluent Search understood thousands separators (rather than removing them completely from the output), as sometimes users copy-paste from other sources that use thousands separators.

**Describe alternatives you've considered**
The user can manually remove the thousands separators, but it can become a little tedious with many sequential operations and / or large numbers:

1. 1800*2 = 3,600 (copy & paste this output for a new calculation)
2. 3,600 (**error**; remove comma)
3. 3600 (fixed)
4. 3600*8,736 = 31,449,600 (copy & paste this output for a new calculation)
5. 31,449,600 (**error**; remove commas)
6. 31449600 (fixed)
7. 31449600/52 = 15,724,800 (copy & paste this output for a new calculation)
8. 15,724,800 

And so on.

**Additional context**
Google, the Windows Calculator app, and other common calculators understand the thousands separator.

![image](https://user-images.githubusercontent.com/3848795/159079107-d88204f2-3398-480f-b335-1225f222b9b5.png)
![image](https://user-images.githubusercontent.com/3848795/159079208-41eb08bc-42cb-47c5-b69a-8b1810dba7f0.png)

**Tested Setup**
FS 0.9.90.9999 (*.exe)
Windows 11 Pro

**Comment by adirh3** [comment]
@ikjadoon thanks for the in-depth explanation!
Pushed a fix for it in today's nightly build.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.30                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by ikjadoon** [comment]
@adirh3 Oh, my goodness, that was quite fast. Thank you so much. This feature has long been a difficulty on some search applications, so to see it fixed is a very happy surprise.

I made the report to follow the easy-to-follow template, so I should thank you. 

I will test the latest build and report back here soon. Thank you so kindly: Fluent Search is becoming an excellent application to fully replace Listary (and this bug / feature was never implemented in Listary, either).

**Comment by adirh3** [comment]
> @adirh3 Oh, my goodness, that was quite fast. Thank you so much. This feature has long been a difficulty on some search applications, so to see it fixed is a very happy surprise.
> 
> I made the report to follow the easy-to-follow template, so I should thank you.
> 
> I will test the latest build and report back here soon. Thank you so kindly: Fluent Search is becoming an excellent application to fully replace Listary (and this bug / feature was never implemented in Listary, either).

Glad it's been useful for you.
Feel free to share any feedback, not everything will be addressed as fast but I can assure I take everything seriously :)

**Comment by Metroid-Prime** [comment]
@ikjadoon  let us know either way if it's fixed so we can close the ticket.

**Comment by ikjadoon** [comment]
> @ikjadoon let us know either way if it's fixed so we can close the ticket.

My apologies for the delay. I can confirm with 0.9.91.30 that the feature **is** working as intended from my tests. 🎊

Thank you so much.

![2022-03-19_16-44-34](https://user-images.githubusercontent.com/3848795/159137855-4ec3e30a-7389-483d-b563-dded8a5027c6.png)

>Glad it's been useful for you.
>Feel free to share any feedback, not everything will be addressed as fast but I can assure I take everything seriously :)

Much appreciated again, @adirh3. So far, it's been working great; you have an excellent program here.

**Comment by Metroid-Prime** [comment]
TY for confirming. Closing ticket.
