### ISSUE TITLE
Export button for Web searches

### ISSUE THREAD

**Issue by Metroid-Prime** [adirh3/Fluent-Search#523]
This is something I've wanted from these types of programs forever and Fluent Search would be the first one to implement it.

![image](https://user-images.githubusercontent.com/1836362/159141719-7af3e36a-4928-485b-a3be-f4ae29b31fad.png)

**Comment by adirh3** [comment]
@Metroid-Prime isn't this too specific? Why images to not be exported?
Can you please describe why do you need this feature? Since you can always export all FS settings in Settings -> Sync (into a JSON file)

**Comment by Metroid-Prime** [comment]
I must have posted this during one of my late nights, I don't even remember doing it 16 days ago!

Thinking about this yes it's too specific for general users and have decided to close it as there's too many things on the list to focus on.  I thought images were converted to a hash in the web.json and assumed  it couldn't be converted out.   I don't plan to use sync as I'm not a One Drive user. I

**Comment by adirh3** [comment]
> I must have posted this during one of my late nights, I don't even remember doing it 16 days ago!
> 
> Thinking about this yes it's too specific for general users and have decided to close it as there's too many things on the list to focus on. I thought images were converted to a hash in the web.json and assumed it couldn't be converted out. I don't plan to use sync as I'm not a One Drive user. I

FYI you don't need to use OneDrive, the export just plain exports the settings files, which you can keep as backup and import if needed

**Comment by Metroid-Prime** [comment]
Thx! I didn't even know that setting existed.  That should do for me. I can also backup my settings too manually by hand or by task scheduler.
