### ISSUE TITLE
COPY Line Alignment

### ISSUE THREAD

**Issue by mragtronx8** [adirh3/Fluent-Search#528]
when copying text from browser; in FS, the text is not properly aligned in COPY. #BUG

![image](https://user-images.githubusercontent.com/62798102/160272963-1bf19e30-785b-471a-9321-110055328ae4.png)

**Comment by adirh3** [comment]
@mragtronx8 does it still happen? If so can you write here text for example

**Comment by mragtronx8** [comment]
![image](https://user-images.githubusercontent.com/62798102/170828156-2d3a1b8e-118d-4f21-93fa-7e9e57518b38.png)

to reproduce, just select a text with mouse, and copy it

**Comment by adirh3** [comment]
> ![image](https://user-images.githubusercontent.com/62798102/170828156-2d3a1b8e-118d-4f21-93fa-7e9e57518b38.png)
> 
> to reproduce, just select a text with mouse, and copy it

I can't repro that, are you copying empty lines?
![image](https://user-images.githubusercontent.com/27368554/170828267-fb2082f3-7aff-461a-ad9d-f433374a6b15.png)
