### ISSUE TITLE
Width of bar is very long on hidpi monitor

### ISSUE THREAD

**Issue by IgnusG** [adirh3/Fluent-Search#529]
**Describe the bug**
Since the latest update which introduced the height size option the bar is incredibly wide.

**To Reproduce**
None needed.

**Expected behavior**
The width should not be that large. The previous behaviour was just about right.

**Screenshots**

![image](https://user-images.githubusercontent.com/6438760/160290918-62f83595-5848-4f95-a294-386816140545.png)
![image](https://user-images.githubusercontent.com/6438760/160290929-da4ea76d-37fa-4918-b5b3-f4f06a60e82f.png)

**Desktop (please complete the following information):**
 - Windows 11 Version: 22000.588
 - Fluent Search Version: 0.9.91.33
 - Resolution: 3840x2400
 - Scaling: 200%

**Comment by IgnusG** [comment]
I've updated my display driver and now its the opposite:

![image](https://user-images.githubusercontent.com/6438760/160463735-e75851fc-ff8f-4eb6-b1c9-5417f81ef43e.png)

![image](https://user-images.githubusercontent.com/6438760/160463753-0d8be292-2da8-4fdc-9499-4311994ede49.png)

**Comment by adirh3** [comment]
@IgnusG did you try to resize it? 
Do you have `Keep window size after restart` setting enabled? Try disabling that and restarting FS

**Comment by IgnusG** [comment]
Oh that's weird. I don't remember turning that option on. 
After turning it off and resetting everything seems to be back in order. Thanks!
