### ISSUE TITLE
Crash on latest nightly version

### ISSUE THREAD

**Issue by IgnusG** [adirh3/Fluent-Search#530]
**Describe the bug**
Latest version seems to have randomly crashed for me. I'm not sure what caused it but it might've been style related (or theme related) as the window first opened the blur, and then drew a border before it stopped responding.

**To Reproduce**
Unsure - I just opened fluent.

**Screenshots**
![image](https://user-images.githubusercontent.com/6438760/160297054-2f492030-1375-43c7-8c0b-f48135322396.png)

![image](https://user-images.githubusercontent.com/6438760/160297058-35ebc91f-4b6b-4a6e-88a3-0d20db84d8a4.png)

**Desktop (please complete the following information):**
 - Windows 10 Version: 22000.588
 - Fluent Search Version 0.9.91.33

**Comment by adirh3** [comment]
@IgnusG can you let it crash then go to Event Viewer -> Windows -> Application, you will see two errors for FS, can you send me them in PM in Discord please?

**Comment by IgnusG** [comment]
Unfortunately there is only one item available and it does not seem to contain much information:

```
The program FluentSearch.exe version 0.9.91.33 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.
 Process ID: 4214
 Start Time: 01d841f5c0cb763a
 Termination Time: 6
 Application Path: C:\Program Files\Fluent Search\FluentSearch.exe
 Report Id: ***
 Faulting package full name: 
 Faulting package-relative application ID: 
 Hang type: Unknown
```

![image](https://user-images.githubusercontent.com/6438760/160297514-6612bd57-6429-4501-aa85-7da210949669.png)

I will send you the details from it but I don't think they contain more information than what is specified above.

**Comment by IgnusG** [comment]
This might've possibly been a recent GPU driver update as per @adirh3. Closing for now
