### ISSUE TITLE
[Feature Request] Search by initials

### ISSUE THREAD

**Issue by alex3236** [adirh3/Fluent-Search#531]
## Is your feature request related to a problem? Please describe.
I have to use `visiual` to search for `Visual Studio Code`, `vscode` isn't work. However, `v s code` works.
Similarly, I can use `p s 2020` for `Adobe Photoshop 2020`, but `ps 2020` or `ps2020` can't.

That's not intuitive.

## Describe the solution you'd like
Add support for searching using initials.

For example: 

- `vscode` for `[V]isual [S]tudio [Code]`
- `ps 2020` or `ps2020` for `Adobe [P]hoto[s]hop 2020`

## Describe alternatives you've considered
Fluent Sarch doesn't bold the matched text, so I can't confirm what `v s code` and `p s 2020` found.

I don't know how you search for Apps, but this behaves similarly to PowerToys Run.
btw, Windows Search (Win+S on Windows) could identifies `vscode` correctly, but `ps2020` doesn't work.

I think it is possible to separate software names into single words. This is to avoid not being able to search for words that are not separated by space characters (e.g. `photo` and `shop` in `Photoshop`). Then, try to find these abbreviations when searching.

`Adobe Photoshop 2020` -> `adobe, photo, shop, 2020` <- `ps2020`

ofc, this may not be the best solution, just a vision I have.

## Additional context
Apps Search Results Comparison
| Keyword | Fluent Search | PowerToys Run | Windows Search | Listary |
| - | - | - | - | - |
| `ps2020` | X | X | X | **✓** |
| `ps 2020` | X | ✓ | X | **✓** |
| `p s 2020` | ✓ | ✓ | X | **✓** |
| `vscode` | X | X | ✓ | **✓** |
| `v s code` | ✓ | ✓ | X | **✓** |

## P.S.
Since Listary has been inactive for a long time, I was hoping for a replacement that was still in active development.
However, Listary is so smart and convenient using that I haven't found anything comparable to it. For example, search by initials and pinyin. This is why I think it's a shame that Listary is no longer active and not open source.

Hope Fluent Search will get better and better!

**Comment by adirh3** [comment]
@alex3236 thanks for the feedback!
Just wondering is this feature toggle able in Listary? This kind of search will hurt performance greatly unless its a hard coded dictionary (like start menu) so I wonder what it's doing there.
I will try to add something similar soon, but for now you should try the `Search mapping` feature in Settings -> Power user. It let's you map searches, so you could map `vscode` to `visual studio code`.

**Comment by alex3236** [comment]
> @alex3236 thanks for the feedback! Just wondering is this feature toggle able in Listary? This kind of search will hurt performance greatly unless its a hard coded dictionary (like start menu) so I wonder what it's doing there. I will try to add something similar soon, but for now you should try the `Search mapping` feature in Settings -> Power user. It let's you map searches, so you could map `vscode` to `visual studio code`.

Listary is not open source, and I haven't done any decompiling research, so I don't know what it does. But based on its performance and speed, I think it makes its own index, including full disk files, and apps found in specific locations. So it supports *pinyin* search of all files and initials search of apps.

**Comment by adirh3** [comment]
> > @alex3236 thanks for the feedback! Just wondering is this feature toggle able in Listary? This kind of search will hurt performance greatly unless its a hard coded dictionary (like start menu) so I wonder what it's doing there. I will try to add something similar soon, but for now you should try the `Search mapping` feature in Settings -> Power user. It let's you map searches, so you could map `vscode` to `visual studio code`.
> 
> Listary is not open source, and I haven't done any decompiling research, so I don't know what it does. But based on its performance and speed, I think it makes its own index, including full disk files, and apps found in specific locations. So it supports _pinyin_ search of all files and initials search of apps.
> 
> Also as a result, Listary doesn't give switches for these features, probably because doing them while indexing doesn't affect performance much.
> 
> In my use, Listary also does not appear to use a lot of CPU, and the indexes are updated in a timely manner.
> 
> btw, it seems that it has a folder blacklist setting provided in Listary 5 (not in 6 Beta). These folders will not be indexed. It includes AppData and temporary folders by default. (I'm not using Listary5 right now and I'm not sure I'm misremembering.) That may reduce indexing time by quite a bit?

Thanks for the reply, I was thinking about the Fuzzy Search feature in Listary, I believe it is toggle able, and it is giving you the ability to search without space, just like mentioned. It's doing it in in search time from my understanding.
I will try adding something similar soon.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.60                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.76                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.77                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
