### ISSUE TITLE
`Open URL` will trigger twice if enable `reset search when opening`

### ISSUE THREAD

**Issue by u-Sir** [adirh3/Fluent-Search#532]
**Describe the bug**
`Open URL` will trigger twice if enable `reset search when opening`

**To Reproduce**
1. Go to 'Setting->Search->Reset search when opening', turn it on.
2. Go to tasks, add `search` and `Open URL` blocks like these, and connect them:
![图片](https://user-images.githubusercontent.com/93647031/161679175-e727e7d6-2ee0-4871-bf5d-253af212c074.png)
![图片](https://user-images.githubusercontent.com/93647031/161679576-dfdba1c7-b258-4925-899e-3a52754c6e19.png)
3. open FS search bar, type `dis` and press `Tab` 

**Expected behavior**
url opened once

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 11 Version: 21h2
 - Fluent Search Version 0.9.91.35

**Additional context**

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.42                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
