### ISSUE TITLE
is it possible to remove `Nothing to show`?

### ISSUE THREAD

**Issue by u-Sir** [adirh3/Fluent-Search#533]
**Is your feature request related to a problem? Please describe.**
I have  a RSS task, using `verge` tag, it shows `nothing to show` even it has results.
![图片](https://user-images.githubusercontent.com/93647031/161680856-da137d67-1c0c-40ce-be94-ca621ff364e9.png)

**Describe the solution you'd like**
remove `nothing to show`

**Describe alternatives you've considered**

**Additional context**

**Comment by Metroid-Prime** [comment]
What is that Nothing to show?

**Comment by u-Sir** [comment]
> What is that Nothing to show?

![图片](https://user-images.githubusercontent.com/93647031/161692761-96cc1e44-6fff-407c-a941-ba66f55bccb0.png)

**Comment by Metroid-Prime** [comment]
Lol I saw the Nothing to Show but what does that represent? I've never used the RSS feed and never seen that before.

**Comment by u-Sir** [comment]
> Lol I saw the Nothing to Show but what does that represent? I've never used the RSS feed and never seen that before.

you can search anything not exist to trigger it. like this 
![图片](https://user-images.githubusercontent.com/93647031/161700307-bd84e25b-5e04-4a4c-a35f-70f86edff3bc.png)

**Comment by Metroid-Prime** [comment]
Ahh , yes. Agree I don't like the way this looks either.

Maybe take a listary-style approach?
![image](https://user-images.githubusercontent.com/1836362/162558497-11a1c812-489c-4aec-86c6-66e8da2dab7c.png)

**Comment by adirh3** [comment]
@u-Sir can you please send me the Task in Discord?

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.39                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
