### ISSUE TITLE
 The animation of right-click system tray icon is not smooth 

### ISSUE THREAD

**Issue by u-Sir** [adirh3/Fluent-Search#534]
**Describe the bug**
 The animation of right-click system tray icon is not smooth 

**To Reproduce**
1. just right click on tray icon

**Expected behavior**
animation smooth as search bar shows.

**Screenshots**
![screenshots](https://user-images.githubusercontent.com/93647031/161682319-42c984e1-2d9b-4d72-81f9-a65e7142a678.gif)

**Desktop (please complete the following information):**
 - Windows 11 Version: 21h2
 - Fluent Search Version 0.9.91.35

**Additional context**

**Comment by Metroid-Prime** [comment]
I'm seeing the same thing on .35 for the first right click

Win10 LTSC 2021 - 21H2

**Comment by adirh3** [comment]
Closing as the fix has been released and no further issues were reported. If you're still experiencing this on the latest version, please reopen.
