### ISSUE TITLE
FS crashed after second screen disconnected

### ISSUE THREAD

**Issue by u-Sir** [adirh3/Fluent-Search#535]
**Describe the bug**
FS crashed after remove external monitor

**To Reproduce**
1. connect second monitor, press `win + p` and select `second screen only`
2. open FS
3. disconnect the second screen
4. FS crashed

**Expected behavior**
keep FS running

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 11 Version: 21H2
 - Fluent Search Version 0.9.91.35

**Additional context**

**Comment by adirh3** [comment]
@u-Sir is it consistent? FS may crash when GPU driver is restarting, but it shouldn't be the case when disconnecting a display

**Comment by u-Sir** [comment]
> @u-Sir is it consistent? FS may crash when GPU driver is restarting, but it shouldn't be the case when disconnecting a display

yes, disconnecting second screen always makes FS crash.

**Comment by u-Sir** [comment]
it seems to have been fixed in latest version.
