### ISSUE TITLE
Plugin Settings changes cannot be saved

### ISSUE THREAD

**Issue by zHypnus** [adirh3/Fluent-Search#536]
system: Windows11 21H2 22000.593
version: 0.9.90.9999
Plugin Settings changes cannot be saved

**Comment by adirh3** [comment]
> system: Windows11 21H2 22000.593 version: 0.9.90.9999 Plugin Settings changes cannot be saved

Thanks for reporting this, the issue has been solved in the nightly builds (0.9.91.0).
If you'd like you can check it by changing the release feed in Settings -> System -> Release feed, but take into consideration that these builds are less stable.

**Comment by zHypnus** [comment]
> 

Sorry my english is not good
I tried to get a beta here [https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe](url) ,While the problem was resolved, new bugs emerged. Up to builds 0.9.91.35, The Firefox plugin doesn't recognize bookmarks correctly. I try to find the problem, may be some problem with the [firefox.json] writing. 
delete [firefox.json] And write again from (0.9.90.9999), bookmarks fine.

**Comment by adirh3** [comment]
> 

Will check it, thanks!

**Comment by adirh3** [comment]
@zHypnus I can't seem to repro this, does it happen when using multiple profiles in FireFox?

**Comment by zHypnus** [comment]
> @zHypnus I can't seem to repro this, does it happen when using multiple profiles in FireFox?
I only have one profile. current version 0.9.91.39. Now, I must turn off the enable button of the profiles, then restart the software and open it again to correct search.
My system is Chinese, but all paths(settings file and firefox profiles file)are english, if you can't seem to repro this, maybe it's my system language problems?
![Snipaste_2022-04-13_03-58-43](https://user-images.githubusercontent.com/91366384/163043557-47d809a8-626e-41e3-a5c9-27ec9f3f1320.png)

**Comment by adirh3** [comment]
Thanks @zHypnus, I believe I fixed the issues with FireFox plugin version 1.0.0.2, can you please check it and let me know if it works for you?

**Comment by zHypnus** [comment]
@[adirh3](https://github.com/adirh3)  The plugin is already working, thank you for your help!

**Comment by adirh3** [comment]
> @[adirh3](https://github.com/adirh3) The plugin is already working, thank you for your help!

Thanks for the update, closing this, feel free to keep sharing any feedback here :)
