### ISSUE TITLE
Hide Delete Option in Right Side Pane 

### ISSUE THREAD

**Issue by mragtronx8** [adirh3/Fluent-Search#537]
![image](https://user-images.githubusercontent.com/62798102/162590763-a07075c3-941b-4e2d-baa8-bbd96f464c27.png)

in red rectangle; can these be hidden
when Disable delete features = on

![image](https://user-images.githubusercontent.com/62798102/162590781-f2c26527-5e29-4586-bc46-a1f11c7da327.png)

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.40                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
