### ISSUE TITLE
Plugins "Duplicates"

### ISSUE THREAD

**Issue by mragtronx8** [adirh3/Fluent-Search#539]
DuckDuckGo Preview [Plugins List] #BUG
there are 2 plugins showing in the list

![image](https://user-images.githubusercontent.com/62798102/162596140-4ef9c326-e776-4937-88ee-c612d8e3c61e.png)

**Comment by adirh3** [comment]
@mragtronx8 I can't repro this, is it consistent?

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.41                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
