### ISSUE TITLE
Result type prioritization table half hidden when added

### ISSUE THREAD

**Issue by Metroid-Prime** [adirh3/Fluent-Search#54]
Steps 1  Go to Result Type Prioritization  table in settings
Steps 2: Click + 
Step 3: Observe half hidden table

![image](https://user-images.githubusercontent.com/1836362/120918534-c261ff00-c669-11eb-92b2-c3e0bd451aef.png)

**Comment by Metroid-Prime** [comment]
Replicated in v 0.9.8.85.75
![image](https://user-images.githubusercontent.com/1836362/122632027-dc95d700-d084-11eb-9387-ff22555cbcd4.png)

**Comment by adirh3** [comment]
@Metroid-Prime can you still repro this?
