### ISSUE TITLE
Can not copy the Context when using total commander

### ISSUE THREAD

**Issue by fanhwid** [adirh3/Fluent-Search#540]
Using "Context" feature：
when use windows explorer, the Copy context works well, the file path was copyed correctly.
But when use total commander, it's just copy the program name, not the file path.
![image](https://user-images.githubusercontent.com/72638192/162655578-c647b574-a0a3-452a-a0df-95ad2089be1d.png)
![image](https://user-images.githubusercontent.com/72638192/162655649-ce86e434-bfaa-4224-af75-a3fc063a2f65.png)

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.46                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by fanhwid** [comment]
![image](https://user-images.githubusercontent.com/72638192/164133759-9769f326-ba01-41d3-82bd-2fd44883b55e.png)
I don't think problem solved. Use "Shift+Ctrl+G", It still copyed the program name, like the picture above, it didn't copy the path in the total commander.
Please check it!
Total Commander Version 10.00 32 bit (2021-06-10)

**Comment by adirh3** [comment]
@fanhwid is it still the case? Pushed multiple changes to it since then.
I can't repro with latest 64bit total commander

**Comment by fanhwid** [comment]
> @fanhwid is it still the case? Pushed multiple changes to it since then. I can't repro with latest 64bit total commander

@adirh3 I tried again, the problem depends on the total commander version. FS worked well with 64bit total commander, but didn't work well with the 32bit version totalcmd.

**Comment by adirh3** [comment]
> > @fanhwid is it still the case? Pushed multiple changes to it since then. I can't repro with latest 64bit total commander
> 
> @adirh3 I tried again, the problem depends on the total commander version. FS worked well with 64bit total commander, but didn't work well with the 32bit version totalcmd.

Got it, will add support for 32bit, thanks!
My bad thinking it was not used anymore.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.67                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.67                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
