### ISSUE TITLE
Web search query can't contain space

### ISSUE THREAD

**Issue by ntwo1980** [adirh3/Fluent-Search#541]
**Describe the bug**
Web Seach query can't include space, otherwise, can't search.

**To Reproduce**
1. My web search settings:
![image](https://user-images.githubusercontent.com/5159627/162669543-8d2f3548-72f9-474b-ac11-1db4fe851c79.png)
2. When search with no space in query
![image](https://user-images.githubusercontent.com/5159627/162669694-6846efdd-bfa0-43eb-b248-53fde8579a31.png)
3. When search with space in query
![image](https://user-images.githubusercontent.com/5159627/162669785-66b9de06-7791-4f43-8c9f-c37ea1b5f6a2.png)

**Expected behavior**
Web search query can contain space.

**Desktop (please complete the following information):**
 - Windows 10 Version: 21H1
 - Fluent Search Version 0.9.90.9999

**Comment by Metroid-Prime** [comment]
I don't see this in nightly. It might've been fixed already! Try the nightly version and see if you can reproduce it there.

**Comment by ntwo1980** [comment]
Yes, the nightly build is OK. Thank a lot.

**Comment by u-Sir** [comment]
可以试下去掉`%s`
![图片](https://user-images.githubusercontent.com/93647031/162683915-1dada39f-918b-4864-8784-e98afbe03d11.png)
![图片](https://user-images.githubusercontent.com/93647031/162683983-bd60ae61-757e-4f9a-bb33-6879e7a391da.png)

**Comment by Metroid-Prime** [comment]
Closing per ntwo1980's comment.
