### ISSUE TITLE
Some files doesn't respect priorization setting

### ISSUE THREAD

**Issue by ntwo1980** [adirh3/Fluent-Search#542]
**Describe the bug**
Some files doesn't respect priorization setting

**To Reproduce**
1. My prioritization setting is:
![image](https://user-images.githubusercontent.com/5159627/162685173-4bd0eec8-f871-4583-92d9-1df947d9d59c.png)
2. When I make web search:
![image](https://user-images.githubusercontent.com/5159627/162685781-855d101f-2dfb-4731-8d4c-905b6dd89d70.png)
The result doesn't contain web search.
3. When I set file priorization to Low, it works better.
![image](https://user-images.githubusercontent.com/5159627/162686176-8662091b-99f9-4110-af84-2eb9e218811f.png)
But the result files are totally different with previous ones, I don't know what's rule of each file priority.

**Desktop (please complete the following information):**
 - Windows 10 Version: 21H1
 - Fluent Search Version 0.9.91.38

**Additional context**
Machine learning and Order files based on time have been disabled.

**Comment by adirh3** [comment]
@ntwo1980 isn't the real issue here is you get file results when using `google` tag? I assume `gg` is your tag for Google
Can you send me your settings folder (in `%appdata%\Blast\Settings`) in Discord PM please?

**Comment by adirh3** [comment]
@ntwo1980 are these files showing consistently? I don't see any reason why they would show when the input is `gg test`.
Can you please check if changing to Fluent Search indexer make these files not show?

**Comment by ntwo1980** [comment]
@adirh3, the Fluent Search indexer doesn't work on my machine. It can't index all files. I can provide everything db if it helps.

**Comment by adirh3** [comment]
@ntwo1980 can you please send me your settings files in `%appdata%\Blast\Settings` in Discord PM?

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.47                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by ntwo1980** [comment]
Yes, this is fixed. Thanks
