### ISSUE TITLE
FS Sometimes Opens Two Results When Using Enter Key

### ISSUE THREAD

**Issue by Chance92** [adirh3/Fluent-Search#543]
**Describe the bug**
When using enter key to open a result, FS sometimes opens an additional result.

**To Reproduce**
1. Invoke FS and search for something.
2. Using enter key to open the result that comes up first.
4. See error.

**Expected behavior**
FS should only open the selected result.
**Screenshots**

**Desktop (please complete the following information):**
 - Windows 10 Version: 21H2
 - Fluent Search Version 0.9.91.38

**Additional context**
I think I have seen this bug mentioned in one of the release notes, but it is still there.

**Comment by adirh3** [comment]
@Chance92, does it happen on all kind of results? does it happen when selecting a result does not close the search window?
I need more info as I can't repro it.

**Comment by Chance92** [comment]
@adirh3 It has happened on file results as well. I always use enter key to open a result and the search window automatically close after the key stroke. At least it seems that way.

**Comment by adirh3** [comment]
@Chance92 let me know if it happens after `0.9.91.46`, not sure if I fixed it since I can't repro. If it still happens please send me your settings in Discrod

**Comment by Chance92** [comment]
Seems fixed for now. Thanks.
