### ISSUE TITLE
Search file by Chinese need at least three letters

### ISSUE THREAD

**Issue by 745245208** [adirh3/Fluent-Search#544]
**Describe the bug**
When I search file by Chinese, I found that I can't search file less than three letters，like this:
![image](https://user-images.githubusercontent.com/16131756/163394811-93ef7974-ceb9-4595-880a-b6f4be5d578f.png)
But I can search file with three letter, like this:
![image](https://user-images.githubusercontent.com/16131756/163394924-23b5009b-2b14-4e66-acfb-16092594ccef.png)

In common place, Chinese word are combined by two letters, I need the search engine to search file with one or two Chinese letters

**Desktop (please complete the following information):**
 - Windows 10 Version: [e.g. 1909]
 - Fluent Search Version [e.g. 0.9.91.40]

**Comment by adirh3** [comment]
@745245208 thanks, can you please post the text of the search and file here, so I can verify that the fix works with your input.

**Comment by 745245208** [comment]
search text: 坚果 坚果云
search file name: 坚果云.lnk 我的坚果云

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.74                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by 745245208** [comment]
> This issue has been potentially fixed in version 0.9.91.74 . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

I update the Fluent Search to 0.9.91.77，but still find some file can not be search：
![image](https://user-images.githubusercontent.com/16131756/170848312-1683c177-c363-423b-b982-92353121ec82.png)
![image](https://user-images.githubusercontent.com/16131756/170848315-fb15d33f-8487-4590-9a5c-cd5cdb8c2bca.png)

**Comment by adirh3** [comment]
> > This issue has been potentially fixed in version 0.9.91.74 . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
> 
> I update the Fluent Search to 0.9.91.77，but still find some file can not be search： ![image](https://user-images.githubusercontent.com/16131756/170848312-1683c177-c363-423b-b982-92353121ec82.png) ![image](https://user-images.githubusercontent.com/16131756/170848315-fb15d33f-8487-4590-9a5c-cd5cdb8c2bca.png)

Did you enable support for Chinese search in Settings -> Search?
After you do make sure to rebuild index in Settings -> Files

**Comment by 745245208** [comment]
> Did you enable support for Chinese search in Settings -> Search? After you do make sure to rebuild index in Settings -> Files

It's OK after I enable Chinese support and rebuild index.
