### ISSUE TITLE
Some bugs when click win button when setting search hotkey to ctrl + ctrl

### ISSUE THREAD

**Issue by 745245208** [adirh3/Fluent-Search#545]
### bug1 
**Describe the bug**
When click win button with mouse, search bar not on the top

**To Reproduce**
1. set search hotkey ctrl+ctrl
2. Click on 'win' button 
3. ctrl+ctrl to open the search bar
4. search bar not on the top

**Expected behavior**
search bar on the top

### bug2
**Describe the bug**
When double click win button with mouse, search bar can't delete letter

**To Reproduce**
1. set search hotkey ctrl+ctrl
2. Click on 'win' button 
3. Click on 'win' button 
4. ctrl+ctrl to open the search bar
5. enter letter 'aaa'
6. try to delete letter ,fail

**Expected behavior**
search bar can delete letter

**Desktop (please complete the following information):**
 - Windows 10 Version: [e.g. 1909]
 - Fluent Search Version [e.g. 0.9.91.40]

**Comment by adirh3** [comment]
@745245208 please see my comment in #406
I suggest not using Ctrl+Ctrl as hotkey
