### ISSUE TITLE
Search Bar / Setting Menu "UN-MOVABLE"

### ISSUE THREAD

**Issue by mragtronx8** [adirh3/Fluent-Search#548]
unable to move the search bar or setting menu from its location 
its stuck where it opens [v.41 v.42 #BUG] - [v.40 issue is not there]

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.43                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
