### ISSUE TITLE
Moving ToDo Feature to Plugin

### ISSUE THREAD

**Issue by Metroid-Prime** [adirh3/Fluent-Search#55]
Not sure if this is possible, but ToDo is a niche function that should be contained to a plugin.  Searching through Microsoft To Do should not be considered a 'core' function and thus moved to a Plugin.

![image](https://user-images.githubusercontent.com/1836362/120918928-de66a000-c66b-11eb-84b2-8e893d3c7be8.png)

**Comment by adirh3** [comment]
This is not possible without making it a bad experience for people that already use it now

**Comment by Metroid-Prime** [comment]
> This is not possible without making it a bad experience for people that already use it now

Got it! Thanks Adir.  Closing with appropriate tag
