### ISSUE TITLE
instant search not works properly on desktop

### ISSUE THREAD

**Issue by u-Sir** [adirh3/Fluent-Search#550]
**Describe the bug**
instant search not works properly on desktop

**To Reproduce**
1. create an empty `text.txt` file on desktop
2. set in-app search like this:
![图片](https://user-images.githubusercontent.com/93647031/163699555-4e92ffcc-f06e-4c15-a28c-3d1af263f661.png)

3. `win + d` go back to desktop 
4. type `text`, there is no result from desktop
![图片](https://user-images.githubusercontent.com/93647031/163699603-1a0fe483-4ca1-4b09-a31e-a34f0fa07269.png)

**Expected behavior**
search anything from desktop

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 11 Version: 21h2
 - Fluent Search Version 0.9.91.43

**Additional context**

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.44                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
