### ISSUE TITLE
in-app search not support chinese(non-english?)

### ISSUE THREAD

**Issue by u-Sir** [adirh3/Fluent-Search#551]
**Describe the bug**
in-app search not support chinese(non-english?)

**To Reproduce**
1. in-app search set like this:
![图片](https://user-images.githubusercontent.com/93647031/163701011-db48e96f-e804-4425-99e5-1c17e9e4697b.png)

2. create an empty `测试.txt` file on any directory
3. open the directory in explorer and double press `ctrl` -> type `测试`
4. no matched result

**Expected behavior**
showing the `测试.txt` on top.

**Screenshots**
![图片](https://user-images.githubusercontent.com/93647031/163701123-bac06a38-7363-4441-a37b-259a3b5c11d7.png)

**Desktop (please complete the following information):**
 - Windows 1` Version: 21h2
 - Fluent Search Version 0.9.91.43

**Additional context**

**Comment by adirh3** [comment]
@u-Sir this is most likely due to indexer not indexing that file (which is a different issue), can you find it when searching normally?

**Comment by u-Sir** [comment]
> @u-Sir this is most likely due to indexer not indexing that file (which is a different issue), can you find it when searching normally?

no, i can't find it when searching normally.

**Comment by adirh3** [comment]
> > @u-Sir this is most likely due to indexer not indexing that file (which is a different issue), can you find it when searching normally?
> 
> no, i can't find it when searching normally.

Can you change the issue to represent the real issue? Are these new files, can you find them after rebuilding the index?

**Comment by u-Sir** [comment]
> > > @u-Sir this is most likely due to indexer not indexing that file (which is a different issue), can you find it when searching normally?
> > 
> > 
> > no, i can't find it when searching normally.
> 
> Can you change the issue to represent the real issue? Are these new files, can you find them after rebuilding the index?

it's the same problem as  #544. i closed this issuse
