### ISSUE TITLE
Integrate "Open With" dialog in-app

### ISSUE THREAD

**Issue by dalmo3** [adirh3/Fluent-Search#552]
Currently, the **Open With** action opens the default Windows dialog, which isn't great. Integrating it into the app (like Listary does) would allow for a much nicer experience.

**Comment by adirh3** [comment]
Thanks @dalmo3, I plan to have feature like described in #21 soon, for now you can do it using Tasks -

1. Open the Tasks window, by searching `tasks` or by opening it from the system tray menu
2. Create a new Task project
3. Right click the canvas, and select Triggers -> Result selector, there you can configure which files to match
4. First, make it work only for file results - 
<img width="495" alt="image" src="https://user-images.githubusercontent.com/27368554/163717719-42d5fab9-7236-4ccf-8c42-8771aadb8af3.png">

5. The `Context` is the file path, so you can do something like `*.txt` to match only `txt` files (configure it to use wildcards)
6. Save it, now right click again, Search -> Custom operation, fill it to your liking and save
7. Right click, Files -> Open, then in path put the EXE you would like to open and then in args you can pass the file path using `{searchResult.Context}`, like this - 
<img width="337" alt="image" src="https://user-images.githubusercontent.com/27368554/163717872-733ced90-b32a-4779-b4af-910e9c85de56.png">
8. Lastly, connect all the operations, it should look like this - 
<img width="411" alt="image" src="https://user-images.githubusercontent.com/27368554/163717901-9824d2ac-778a-4961-816e-dbbc437d679c.png">
Close the Tasks window, should and it should show in search like this -
<img width="582" alt="image" src="https://user-images.githubusercontent.com/27368554/163717998-ed62432e-1351-49b8-b176-92f17117b1a8.png">

**Comment by dalmo3** [comment]
Hey @adirh3, that's awesome, thanks for the guide. I got it to work :)

I'd just say maybe you meant to post that in https://github.com/adirh3/Fluent-Search/issues/21? 

The reason I opened this as a separate feature request is that it would allow for a more general use without needing to create tasks.

**Comment by adirh3** [comment]
> Hey @adirh3, that's awesome, thanks for the guide. I got it to work :)
> 
> I'd just say maybe you meant to post that in #21?
> 
> The reason I opened this as a separate feature request is that it would allow for a more general use without needing to create tasks.

I know, I believe that's the intent of #21 as well.
I will be closing this, so subscribe to #21 to get updates on this feature quest.
Thanks!
