### ISSUE TITLE
Dual screens extended vertically, Screen Search hints only display in one of the screens

### ISSUE THREAD

**Issue by dalmo3** [adirh3/Fluent-Search#553]
**Describe the bug**
I have a dual monitor setup with an external monitor above my laptop. The screen search hints only display in the external monitor.

- Toggling hints for a window open on the external monitor works as intended.
- Toggling hints for a window open on the laptop screen displays all hints at the above the top edge of the screen, i.e. at the bottom edge of the top screen.
- If a window span both screens, the hints from the top display fine but the hints from the bottom part of the window agglomerate at the edge.

Plus
- If I swap the top/bottom positions of the screens, still the hints only show in the external monitor.
- It doesn't seem to matter which is the main display
- No issues if I set up the extended desktop as side by side. As long as the side edges are touching, it works.

**To Reproduce**
Toggle screen hints.

**Expected behavior**
Hints in the right places.

**Screenshots**
Window on the bottom screen.
![image](https://user-images.githubusercontent.com/33860060/163755400-df3053bf-3f61-45d2-815a-8d09d042d039.png)

Window spanning both screens, external monitor on the top
![image](https://user-images.githubusercontent.com/33860060/163755461-545e65bd-a523-4b8b-a578-6854d230653a.png)

Window spanning both screens, external monitor on the bottom
![image](https://user-images.githubusercontent.com/33860060/163759515-f5d8dc3a-fa42-46ca-b400-1c9325400e98.png)
(PS. the taskbar just happens to be there but it makes no difference either)

**Desktop (please complete the following information):**
 - Windows 10 Version: 21H1
 - Fluent Search Version Stable 0.9.90.9999 and Nightly 0.9.91.44.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.45                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by dalmo3** [comment]
It is indeed. So quick. Thanks @adirh3!
