### ISSUE TITLE
Strange behavior when press backspace in middle of text in beta version

### ISSUE THREAD

**Issue by yyjdelete** [adirh3/Fluent-Search#557]
**Describe the bug**
Strange behavior when press backspace in middle of text
When you press `backspace` in middle of text, it will delete the right char(in the left of cursor), but the cursor don't move to left, so when you type new chars, it lead to wrong word.

**To Reproduce**
1. Input `123456` in search or any input bar in settings;
2. Move cursor to the place between `3` and `4`, (`123|456`)
3. Press `backspace` to remove `3`
4. Press `3` again

**Expected behavior**
`123456`

**Screenshots**
`124356`

**Desktop (please complete the following information):**
 - Windows 10 Version: Win11
 - Fluent Search Version: 0.9.91.45(beta), works well in stable

**Comment by Chance92** [comment]
I was just about to submit this one.

**Comment by adirh3** [comment]
Thanks @yyjdelete, should be fixed on latest nightly
