### ISSUE TITLE
File Dialog Context search can't open folders

### ISSUE THREAD

**Issue by rzippo** [adirh3/Fluent-Search#559]
**Describe the bug**
 I cannot open folders via the File Dialog Context search.

**To Reproduce**
1. Open a File Dialog for a folder (VS Code > Open folder)
2. Search for a folder by invoking Fluent Search
3. Explorer doesn't open the folder in File Dialog

**Expected behavior**
Explorer should select the folder and VS Code should open it, the same way this integration works when opening a file.

**Desktop**

* Windows 10 21H2 19044.1645
* Fluent Search 0.9.90.9999

**Comment by adirh3** [comment]
@rzippo, what's your Windows language?
Also, did you set Ctrl+K as hotkey for something?

**Comment by rzippo** [comment]
> what's your Windows language?

The system language is English (US). I also have Italian (Italy) installed, but not set as system language.

>  Also, did you set Ctrl+K as hotkey for something?

I did not set that hotkey for anything in Fluent Search.
The default hotkey for opening a folder in VS Code is Ctrl+K Ctrl+O, if it matters.

To invoke Fluent Search I use Ctrl+Alt while the file dialog is in focus, then search for the folder select it and press enter.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.48                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by rzippo** [comment]
I updated to 0.9.91.48 but it seems nothing has changed for the use case above.

**Comment by adirh3** [comment]
> Thanks for the quick response!
> 
> I updated to 0.9.91.48 but it seems nothing has changed for the use case above. Anything I can try to narrow down the issue?

Is it a folder or file dialog? will try installing VSCode later and check. 
Currently FS does not support folder dialogs (the small one).

**Comment by rzippo** [comment]
I am not that sure, it otherwise looks like a file dialog but asks for a folder.

![Screenshot](https://user-images.githubusercontent.com/16462616/164726593-b93e7d9a-9d4e-4482-bfda-432141549edc.png)

**Comment by rzippo** [comment]
I can confirm it is fixed for me, thanks!
