### ISSUE TITLE
File Dialog is not opening folders

### ISSUE THREAD

**Issue by mragtronx8** [adirh3/Fluent-Search#561]
### File Dialog is not opening folders
#BUG
Version 0.9.91.49

Cannot open folders via the File Dialog
selecting folders in folder dialogs is not working

**Steps to reproduce the behavior:**
Open a File Dialog for a folder (Notepad/Paint/etc > Open folder)
Search for a folder by invoking Fluent Search
Explorer/file manager doesn't open the folder in File Dialog

**Expected behavior**
Explorer/file manager should select the folder and notepad/paint/etc should open it, the same way this integration works when opening a file.

![image](https://user-images.githubusercontent.com/62798102/164934702-a4290235-241a-4ebf-af9d-f41828c31a48.png)

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.50                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
