### ISSUE TITLE
Transparency on white background

### ISSUE THREAD

**Issue by usernamelectro** [adirh3/Fluent-Search#565]
**Description**

There are some white traces on the edge of the input bar when the transparency effect is set to Transparent, Acrylic blur or Blur. 

**How to reproduce**

Go to the Settings > General > Effects > Window Style and set the Transparency
effect to either Transparent, Acrylic blur, or Blur.

**Expected behavior**

Other than that, there is no problem when the input panel is on dark background.
It is not necessarily a bug but it looks a little ugly, so it will look much better if it is clean.

**Screenshots**

![sshot-2022-04-27- 20-55-46](https://user-images.githubusercontent.com/8273701/165796140-3a645dd9-c884-498e-9435-7383537c41eb.png)
![sshot-2022-04-27- 20-57-45](https://user-images.githubusercontent.com/8273701/165796151-04842145-ccc1-40fb-87dd-857de2a69458.png)

When the input panel is above the dark background it is fine.

![sshot-2022-04-27- 21-08-57](https://user-images.githubusercontent.com/8273701/165796184-7a375fd3-7cbf-4f8c-bd71-23e3408ab525.png)
![sshot-2022-04-27- 21-09-22](https://user-images.githubusercontent.com/8273701/165796189-b2cfd312-b0cc-4150-9ebe-ae21213cb574.png)

**Desktop**

 - Windows 11 Version 21H2 OS Build 22000.652
 - Fluent Search Version 0.9.90.9999
 - CPU Intel i5 9400 with UHD 630 iGPU, no discrete GPU

**Comment by adirh3** [comment]
Thanks @usernamelectro, this should be fixed in the nightly versions.
If you'd like to verify that you can check it by updating in Settings-> Release feed -> Nightly.
Or download nightly portable just to check that, links here - https://github.com/adirh3/Fluent-Search/

**Comment by usernamelectro** [comment]
I have tested v0.9.91.53 Beta and can confirm that it is fixed now, thanks!
