### ISSUE TITLE
GitHub link in info window links to Avalonia website

### ISSUE THREAD

**Issue by rzippo** [adirh3/Fluent-Search#567]
As per title, the link leads to Avalonia instead of this repository. Tested on version 0.9.91.57.
Screenshot for clarity.

![image](https://user-images.githubusercontent.com/16462616/166417519-45d1c712-df27-426f-b248-982584e03da7.png)

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.60                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by rzippo** [comment]
I can confirm, fixed for me.
