### ISSUE TITLE
"Show at top most" should not apply to non-search windows

### ISSUE THREAD

**Issue by rzippo** [adirh3/Fluent-Search#569]
I have the setting "Show at top most" on to have the search window always appear on top, but this setting becomes annoying when looking at settings or tasks windows, which have no reason to be pinned on top.

**Comment by adirh3** [comment]
@rzippo other FS windows will show on top since otherwise the search window will be over them.
It is common to open other FS windows through search, like Settings to customize the search window and it would be inconvenient if it shows over the window it just opened.

**Comment by rzippo** [comment]
In my experience I never used them this way. I open settings and task window from the taskbar icon and would often have other windows like Discord that I want to read from in the meantime.

Wouldn't closing the search window also be a fix for this case, anyway?

**Comment by adirh3** [comment]
> In my experience I never used them this way. I open settings and task window from the taskbar icon and would often have other windows like Discord that I want to read from in the meantime.
> 
> Wouldn't closing the search window also be a fix for this case, anyway?

In some cases, like Appearance settings customization and Tasks result selector, you may want the search window open.
I will try to make it disable topmost when any other window is open, but if search is active alone it would be topmost. 
How does it sound?

**Comment by rzippo** [comment]
So the proposal would be

- If only search & another FS window is open, the latter is topmost
- If any other window is open, non-search windows are not topmost

If I understood correctly, this seems to address both use cases.

**Comment by adirh3** [comment]
> So the proposal would be
> 
> * If only search & another FS window is open, the latter is topmost
> * If any other window is open, non-search windows are not topmost
> 
> If I understood correctly, this seems to address both use cases.

Actually I meant -
- If only the search window is open, it is topmost
- If any other FS window is open, the search window will no longer be topmost
- All FS windows are NOT topmost all time

**Comment by rzippo** [comment]
Ok, this too is ok for me

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.62                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by rzippo** [comment]
I can confirm, fixed for me.
