### ISSUE TITLE
support search by `pinyin (Chinese romanization)`

### ISSUE THREAD

**Issue by u-Sir** [adirh3/Fluent-Search#571]
**Is your feature request related to a problem? Please describe.**
fuzzy search added in latest nightly, it's useful. And I hope FS support `pinyin (Chinese romanization)`

**Describe the solution you'd like**
e.g character:`中文`->pinyin_full:`zhongwen`->pinyin_initials:`zw`
I hope FS support search by pinyin_full/initials, since I have lot of files/folders name in Chinese.

**Comment by adirh3** [comment]
Duplicate with #375, closing.
Will consider it for 0.9.91.x
