### ISSUE TITLE
Fluent Search indexing/settings should support multiple windows user accounts

### ISSUE THREAD

**Issue by lumberingAutomaton** [adirh3/Fluent-Search#572]
I have two different windows user accounts. One for work and one for personal. I installed and configured Fluent Search on my work account and was attempting configuration on my personal account, when I found that indexing wasn't working as expected. After reaching out on discord, it was explained that the index resides in the installing account's appdata directory. Any account without access to the installation account's appdata will have no index at all.

An ideal solution might be for each windows user account to have it's own indexer/db and/or settings. This would allow each account to interact only within its own sandbox. This might also allow for things like per account theming, suggestions, and pins. This could be very useful for shared systems (I'm thinking of a family computer or something?).

As of now I'm using Fluent Search portable (per your suggestion) and it is working. It's great to work with, but non-optimal, as it's violating account permissions/encapsulation by having both accounts sharing the same settings and index. This leads to a much more... saturated experience than I would like (ideally I don't encounter things I can't or shouldn't interact with).

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.96                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
