### ISSUE TITLE
Search files  when opening a file

### ISSUE THREAD

**Issue by fanhwid** [adirh3/Fluent-Search#574]
Like the scenario below, I want to open a file in the folder "onedrive", and i use in-app search, but FS returns nothing.
So it's a good feature to find everything when using in-app search. Like in listary.
![image](https://user-images.githubusercontent.com/72638192/167301912-6efb17e9-e2cb-4a2d-b6fd-cfb67b43bb1b.png)
I set my in-app search hotkeys like this:
![image](https://user-images.githubusercontent.com/72638192/167301988-6271d0fc-7b90-4502-903f-d876a315055f.png)

Using listary, when i want to open a file, i just search it beside the dialog box, i could open it directly. It's a magic feature.
![image](https://user-images.githubusercontent.com/72638192/167302186-3e80ad18-4593-4c10-9595-ee78280e3387.png)

**Comment by adirh3** [comment]
@fanhwid, wouldn't it be against the point of "in-app" search if it just search in the entire system?
You can use normal search to find any files/folders and open it in the dialog, when on file dialog simply open FS, search for `OneDrive` and it should open in the file dialog

**Comment by fanhwid** [comment]
> @fanhwid, wouldn't it be against the point of "in-app" search if it just search in the entire system? You can use normal search to find any files/folders and open it in the dialog, when on file dialog simply open FS (normal hotkey), search for `OneDrive` and it should open in the file dialog

Got it，It works well, problem solved!

**Comment by adirh3** [comment]
@fanhwid FYI if you like multiple hotkeys, you can set hotkey to Files search to search only files/folders to make it even quicker
