### ISSUE TITLE
Win+Y 

### ISSUE THREAD

**Issue by mragtronx8** [adirh3/Fluent-Search#577]
Win+Y
#BUG

**this is happening in ALL FS**

first time it shows Win+Y, and after pressing hotkey, nothing happens.
and when u click again, Win+Y changes to None

![image](https://user-images.githubusercontent.com/62798102/167435846-179592f1-beee-47db-947a-37a3ed2b9605.png)
![image](https://user-images.githubusercontent.com/62798102/167435894-25c1394b-6f29-44eb-aadd-4b61c732d5be.png)

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.65                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
