### ISSUE TITLE
Integrate webhooks on FS's #Github Discord channel  

### ISSUE THREAD

**Issue by Metroid-Prime** [adirh3/Fluent-Search#58]
Requested by cannibalox on Discord on 6/6 0530 PST.

Integrate webhooks on FS's #Github Discord channel.  Instructions provided via this YouTube video: https://www.youtube.com/watch?v=-KDQqWNK3Tw

FlowLauncher's Discord page has this and I agree it's nice.

**Comment by Metroid-Prime** [comment]
Can confirm this is working properly.  Notified requestor via Discord channel

**Comment by adirh3** [comment]
Test

**Comment by adirh3** [comment]
This

**Comment by adirh3** [comment]
This%20in%version

**Comment by adirh3** [comment]
This+in+version

**Comment by adirh3** [comment]
test123

**Comment by adirh3** [comment]
test123

**Comment by adirh3** [comment]
This_issue_has_been_potentially_fixed_in_version_0.9.85.20

**Comment by adirh3** [comment]
tes test 123

**Comment by adirh3** [comment]
tes test 123

**Comment by adirh3** [comment]
tes test 123

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.85.20
