### ISSUE TITLE
Instantly search in file dialogs [xplorer2 & xyplorer]

### ISSUE THREAD

**Issue by mragtronx8** [adirh3/Fluent-Search#580]
Instantly search in file dialogs
Windows 10 21h2 - FS 0.9.91.65
#BUG

Instantly search in file dialogs not working in **xplorer2 & xyplorer**

**Comment by adirh3** [comment]
@mragtronx8 I can't repro this, can you write or record please what you're experiencing and what you're expecting?

Xyplorer and Xplorer2 are not file dialogs, to use instant search in them add them to this list -
<img width="571" alt="image" src="https://user-images.githubusercontent.com/27368554/167946622-6fcb21c0-c8b1-4d36-aca9-c52cfc48e79c.png">
