### ISSUE TITLE
Fluent Search File Indexing is taking too much cpu

### ISSUE THREAD

**Issue by kumar007git** [adirh3/Fluent-Search#583]
**Describe the bug**
Fluent search file indexing is always running at a minimum of 10% cpu in task manager. In fact, I see Fluent Search file indexing process running in task manager with high cpu even though I have not started Fluent Search application.

**To Reproduce**
1. Go to task manager
2. Search for Fluent Search File Indexer

**Expected behavior**
Fluent Search file indexer should be running only if Fluent Search app is started and running. Also, should not be constantly running at 10% cpu consumption in task manager.

 - Windows 10 Version: 21H2
 - Fluent Search Version 0.9.91.50

**Comment by adirh3** [comment]
@kumar007git thanks for the feedback.
Do you have some kind of background task that continously copies/generate/move files?

In general, the Fluent Search file indexer should not consume more than 1% CPU on normal usage.

To stop the indexer from running always, you can do the following -
1. Open Run, type `services.msc`
2. Find `FluentSearch.FileIndexer`, right click it -> properties
3. Change startup to `manual`.

Now the indexer will not start with Windows, but when Fluent Search client starts it will try start the indexer which will prompt a UAC (request for admin permission).

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.70                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by adirh3** [comment]
@kumar007git can you please let me know if this has been improved for you since recent nightly updates?
