### ISSUE TITLE
Everything Indexer [in-app search]

### ISSUE THREAD

**Issue by mragtronx8** [adirh3/Fluent-Search#587]
Everything indexer in-app search #Bug
Windows 10 21H2 - FS 0.9.91.69

for example, i have a folder or file called [ FLUENT SEARCH]

when using in-app search, if i type the first name [fluent] = fs finds it
but if i search [search] "the second word" = NOTHING TO SHOW {BUG}

![image](https://user-images.githubusercontent.com/62798102/168344839-2589feaa-0ad9-464d-ac71-c970d584cff8.png)
![image](https://user-images.githubusercontent.com/62798102/168344997-6b25f836-9a62-4a5e-83ee-bc257b41dedf.png)

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.70                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
