### ISSUE TITLE
make a parameter that gives the full path

### ISSUE THREAD

**Issue by H5820121** [adirh3/Fluent-Search#589]
Thanks for the amazing software!
Can you please make a parameter that gives the **full** path ,the %1 parameter   only gives the directory path.

**Comment by adirh3** [comment]
> Thanks for the amazing software! Can you please make a parameter that gives the **full** path ,the %1 parameter only gives the directory path.

Do you mean when using third party file manager? like opening files with it?

**Comment by H5820121** [comment]
Yes.

**Comment by adirh3** [comment]
@H5820121 this is possible through Tasks, currently I don't plan to add this as a dedicated feature inside FS.
To use Tasks, open the Tasks window using the system tray menu, then -
1. Create new Task project
2. Right click the canvas, Trigger -> Result selector
3. In result type set it to `File`, and save
4. Right click again, Search -> Custom operation, then name it `Open file in X`
5. Finally, add an open file operation, in file path put your custom file manager EXE, then in arguments you can pass the file path using `{searchResult.Context}`

**Comment by H5820121** [comment]
Thanks, it works well!
And thank you for the large investment for the benefit of the public, which is evident in every detail, and it is just a pity that there is no FS preview for the very useful DOCX files as well.

**Comment by adirh3** [comment]
> Thanks, it works well! And thank you for the large investment for the benefit of the public, which is evident in every detail, and it is just a pity that there is no FS preview for the very useful DOCX files as well.

Glad it helped, closing this :) 
Preview for docx might be added after I finish 0.9.91.x.
