### ISSUE TITLE
In-app Search "Speed / Results"

### ISSUE THREAD

**Issue by mragtronx8** [adirh3/Fluent-Search#590]
In-app Search "Speed / Results"
#BUG
windows 10 21h2 - fs 0.9.91.70

In-app Search **speed** [xplorer2 & xyplorer] is slow; in-comparison to windows explorer in-app search and fs normal search

also when searching [in-app file managers], **SCREEN** results is showing, but **FOLDER / FILE** is not always coming up in results
![image](https://user-images.githubusercontent.com/62798102/168463081-fae80142-b2fa-4da8-abec-951dfa7643a6.png)

**Comment by adirh3** [comment]
@mragtronx8 does it happen when using the FS file indexer? or only Everything?

**Comment by mragtronx8** [comment]
both fs & everything indexer

**Comment by mragtronx8** [comment]
it is sometimes happening "not always", 50/50
with both fs + everything indexers

**Comment by adirh3** [comment]
> it is sometimes happening "not always", 50/50 with both fs + everything indexers

Can you please disable Screen search app in settings and see if it's related
