### ISSUE TITLE
in-app search (FOCUS)

### ISSUE THREAD

**Issue by mragtronx8** [adirh3/Fluent-Search#591]
xplorer2 & xyplorer & windows explorer / opera / others (FOCUS)
#BUG
windows 10 21h2 
when searching in file managers / apps [xplorer2 / xyplorer / windows explorer / opera / others]; instant search is working,

search bar pops-up for search; but it losses focus; so when i type, nothing is being typed in the search bar.

**Comment by adirh3** [comment]
@mragtronx8 only on these file managers? On explorer it works 100% of the time?

**Comment by mragtronx8** [comment]
happening in all

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.76                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.77                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
