### ISSUE TITLE
File Dialog Change Folder

### ISSUE THREAD

**Issue by mragtronx8** [adirh3/Fluent-Search#593]
File Dialog Change Folder
#BUG

windows 10 21h2 - fs 0.9.91.70/71
https://drive.google.com/file/d/1YUtaQnCEwcSf7POHdgsZFHkcdQ_SbR8b/view?usp=sharing

it is not switching correctly to the target location/path 

note: **it is heading to the previous location, where the file/s were saved [BUG]**

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.72                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
