### ISSUE TITLE
[FR] markdown preview/render  using the FS previewer

### ISSUE THREAD

**Issue by cannibalox** [adirh3/Fluent-Search#596]
**Is your feature request related to a problem? Please describe.**

I really like to use FS to glimpse and quick-edit my markdown notes (stored in logseq / obsidian), I would love to have a render/preview of markdown files using the FS previewer in the fluent pane.(maybe wysiwig editing inside the code editor even ?)

**Describe the solution you'd like**

- the current FS works nicely to edit md files in the text editor, maybe add a button to switch to render view  ? (I know Quicklook preview is just a hotkey away, or I could just launch the file in a md editor, but there is a big appeal to have quick glimpse from within FS's internal preview pane). 

the way I envision it is, by default : preview rendered markdown, and enter edit mode with a hotkey or an button.

- or maybe go full wysiwyg editing ? (like Typora, Marktext https://github.com/marktext/marktext or vditor https://github.com/Vanessa219/vditor), or maybe not full wysiwyg, but showing the preview while the markup is visible like https://easy-markdown-editor.tk/  (which is a nice compromise imo).

**Describe alternatives you've considered**
- currently it is already possible to get a rendered preview using quicklook in a popup window, but wysiwyg markdown editing from the 'alt' preview pane would be the icing on the cake 
- for now I launch the md file in typora/marktext

**Additional context**
link to discord  convo: https://discord.com/channels/740636963396124714/826443172153786408/978345595284627597

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 1.0.0.11                                          . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by cannibalox** [comment]
Thank you @adirh3 !
markdown preview/edit works great, only nitpick : image links with relative paths are not rendered. eg: ![image.png](../assets/mypic.png) will render a not found icon even though the file exists in the relative path to the file. not sure if it's something you want to address though ? 
see the last line in th epic below pic below
![ss_20230828_FluentSearch_eWDiYZXJf9](https://github.com/adirh3/Fluent-Search/assets/4605693/b70e4732-77aa-495c-8714-b7b2576ab690)

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 1.0.0.12                                          . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by cannibalox** [comment]
tested and relative paths are working in 1.0.0.12, thank you !
closing this FR :)
