### ISSUE TITLE
Idk a black square border is there

### ISSUE THREAD

**Issue by Basic6969** [adirh3/Fluent-Search#597]
**Describe the bug**
A black square border is there screenshot attached

**To Reproduce**
Nothing when opened it shows that

**Expected behavior**
![image](https://user-images.githubusercontent.com/98833613/170758829-0d75491b-e79b-4d67-8b44-a02c9321643b.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/98833613/170758663-7d9ff62b-b8ea-4e72-94d8-003eb23426c6.png)

**Desktop (please complete the following information):**
 - Windows 11 Version: 22H2
 - Fluent Search Version: 0.9.90.0

**Additional context**
none

**Comment by PhoenixCODE2322** [comment]
@Basic6969  how did you fixed it , i just got the portable version and this is happening to me too.

**Comment by adirh3** [comment]
> @Basic6969 how did you fixed it , i just got the portable version and this is happening to me too.

Whats your Windows/Fluent-Search version?

**Comment by PhoenixCODE2322** [comment]
> > @Basic6969 how did you fixed it , i just got the portable version and this is happening to me too.
> 
> Whats your Windows/Fluent-Search version?

![image](https://user-images.githubusercontent.com/75798544/206538172-c7426857-49ce-4cda-bd8f-f5f95861925e.png)

**Comment by Basic6969** [comment]
> @Basic6969 how did you fixed it , i just got the portable version and this is happening to me too.

u using mica for everyone?

**Comment by PhoenixCODE2322** [comment]
> > @Basic6969 how did you fixed it , i just got the portable version and this is happening to me too.
> 
> u using mica for everyone?

yes yes

**Comment by PhoenixCODE2322** [comment]
> > @Basic6969 how did you fixed it , i just got the portable version and this is happening to me too.
> 
> u using mica for everyone?

it worked ... Added exception for Fluent Search . Thanks

**Comment by Basic6969** [comment]
> > > @Basic6969 how did you fixed it , i just got the portable version and this is happening to me too.
> > 
> > 
> > u using mica for everyone?
> 
> yes yes

in that go add the fluent search process

**Comment by Basic6969** [comment]
> > > @Basic6969 how did you fixed it , i just got the portable version and this is happening to me too.
> > 
> > 
> > u using mica for everyone?
> 
> it worked ... Added exception for Fluent Search . Thanks

nice :)
