### ISSUE TITLE
In chinese setting, system command don't work

### ISSUE THREAD

**Issue by fanhwid** [adirh3/Fluent-Search#598]
Setting the language to Chinese, the "shutdown" command can't show normal.
![image](https://user-images.githubusercontent.com/72638192/170900852-535397f2-6e4f-4072-a5e8-5e292308b5c1.png)
then I use chinese "关机“, It seems normal, but when I press Enter, it didn't work.
![image](https://user-images.githubusercontent.com/72638192/170901241-b25700a1-51a7-46b2-98a4-2e0019ceafa7.png)

Setting the language to English, the "shutdown" command becomes normal.
![image](https://user-images.githubusercontent.com/72638192/170900934-682b63fa-d7e9-4ee7-a3df-c2470c0362ef.png)

windows 10

**Comment by u-Sir** [comment]
我这边正常，同win11。你的图二默认选中了锁屏
![图片](https://user-images.githubusercontent.com/93647031/170904330-d9655c91-6224-4316-b8ca-cfc68139a649.png)

**Comment by fanhwid** [comment]
> 我这边正常，同win11。你的图二默认选中了锁屏 ![图片](https://user-images.githubusercontent.com/93647031/170904766-e16c44d2-a80c-414c-9f94-2450ab98c650.png)

锁屏也是没办法锁屏的。
不好意思，我是win10，前面写错了

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.79                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
