### ISSUE TITLE
Web search interface buggy

### ISSUE THREAD

**Issue by Metroid-Prime** [adirh3/Fluent-Search#6]
Web searches blank line doesn't show (sometimes?) when clicking + button. User must exit settings and re-enter or close/relaunch FS to see the blank lines

**Comment by mochigithub** [comment]
This is no longer happening after the latest version.

**Comment by mochigithub** [comment]
Apologies. This IS still happening even with new version.

**Comment by Metroid-Prime** [comment]
Closing this because it's covered under #450
