### ISSUE TITLE
no `files` results since 0.9.84.00

### ISSUE THREAD

**Issue by cannibalox** [adirh3/Fluent-Search#60]
**Describe the bug**
* since 0.9.84.00 I get no `Files` results during search, with and without the tag `Files` , **either with the FluentSearchIndexer or Everything**
* the only way I get results is by explicitly using an indexed folder path as a tag, eg: `c:\myfolder(tab)mysearch`
* the `files search` was working fine  for me in 0.9.82.40, the problem started with 0.9.84.00 onwards 
* I'm currently using FS 0.9.85.11 portable under windows 10 1809 ltsc x64. 
  *  same issue on 2 machines running win10 1809 ltsc 
    * nuc8 (Intel core i5-8259U 16GB + gtx970
    * amd ryzen 1700x 32GB + rtx2080

**Comment by adirh3** [comment]
body

**Comment by adirh3** [comment]
body

**Comment by adirh3** [comment]
test

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.85.20

**Comment by cannibalox** [comment]
confirmed working in 0.9.85.20, thank you for the fix ! 

closing

**Comment by Metroid-Prime** [comment]
From Changelog 0.9.85.20 - Fixed a bug that file search did not work when an index path setting was empty #60
