### ISSUE TITLE
When download file, FS don't integrate with dialog box well

### ISSUE THREAD

**Issue by fanhwid** [adirh3/Fluent-Search#600]
Bug discription:
step 1:
Download a file using chrome, the dialog box appears like below. 
![image](https://user-images.githubusercontent.com/72638192/171107361-78c2876a-4db9-4428-bfb6-5fedfb5d732f.png)
step 2:
Use FS to open the folder that i want to download into. In the picture the folder is "test folder"
![image](https://user-images.githubusercontent.com/72638192/171108015-f1af9051-6c7e-4186-b3f5-3eb9a8fc75bf.png)
step 3:
Select the FS search result "test folder", then press "Enter". The chrome download diagbox didn't change to the folder "test folder", it just downloaded the file into the original place.

**Comment by fanhwid** [comment]
> @fanhwid I can't repro this, does it happen only with specific apps? or specific folders? Are you on Windows 10?

Yes, I'm on Windows 10

**Comment by fanhwid** [comment]
> @fanhwid I can't repro this, does it happen only with specific apps? or specific folders? Are you on Windows 10?

@adirh3 I used a windows 11 computer, the problem still exist. If you need any log to debug, please tell me.

**Comment by fanhwid** [comment]
> 

I opened Paint, and save the pic to "test folder", 
![image](https://user-images.githubusercontent.com/72638192/171529029-90a89b0d-18cc-49ae-8618-7067b9a2dcb8.png)
Use "file-save as" to save it to "test folder"
![image](https://user-images.githubusercontent.com/72638192/171529328-2ef4794f-9c45-4437-8720-3d1f819a9877.png)
Use FS to search and select the folder and press Enter:
![image](https://user-images.githubusercontent.com/72638192/171529436-fd03e138-dfca-4f58-9384-1c21fdec8dc3.png)
But the pic didn't save to "test folder", it was saved to the default dir "desktop".
![image](https://user-images.githubusercontent.com/72638192/171529597-2775a89d-aeee-4973-b066-9644110bf277.png)

**Comment by adirh3** [comment]
@fanhwid do you have `Open folders in existing Explorer window` enabled?

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.83                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by fanhwid** [comment]
> This issue has been potentially fixed in version 0.9.91.83 . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

@adirh3 When using notepad, "save as" function work well, I could use FS to search the folder that i want to save to.
But,
1. when using chrome to download files, It still didn't work. 
2. when using Paint to save file, It still didn't work.

![image](https://user-images.githubusercontent.com/72638192/172032650-d6088647-98ee-4978-9da7-ae4eeebc085b.png)

![image](https://user-images.githubusercontent.com/72638192/172032655-04a15156-9c47-44a4-b57f-779c8edbcece.png)

![image](https://user-images.githubusercontent.com/72638192/172032692-694e80ca-a7dc-4307-ac32-2bfe439f9520.png)

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.84                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
