### ISSUE TITLE
In-app search don't clear the search tags

### ISSUE THREAD

**Issue by fanhwid** [adirh3/Fluent-Search#601]
FS setting, turn on "Always clear search tags" function.
![image](https://user-images.githubusercontent.com/72638192/171179552-aa946aa2-97c8-4bcd-8656-7dc4eac8b122.png)
![image](https://user-images.githubusercontent.com/72638192/171179632-46c0d70e-796a-4932-a010-782c781cbac8.png)

Bug discription:
step 1: use FS to search files like this, using the tag "file":
![image](https://user-images.githubusercontent.com/72638192/171179869-dded75b5-0223-4dd3-b706-98d7c56e5a34.png)
step 2: Using FS In-app search in Chrome to search the tabs, but the previous tag "file" didn't clear.
![image](https://user-images.githubusercontent.com/72638192/171180500-b3f9e202-f8e9-4641-9691-6639b060d224.png)
step 3: If the previous search didn't use tags, then the In-app search works normal:
![image](https://user-images.githubusercontent.com/72638192/171181090-70f10731-aec3-4bff-8b8d-b495da097def.png)

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.80                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
