### ISSUE TITLE
Hotkey not work in multi screen

### ISSUE THREAD

**Issue by 745245208** [adirh3/Fluent-Search#603]
**Describe the bug**
if enable "ignore hot key on full screen processes" and use multi screen,  hot key "ctrl+alt" not work

**To Reproduce**
1. enable "ignore hot key on full screen processes"
2. open mstsc to connect remote desktop and fullscreen to screen2
3. click task bar on screen1
4. click "ctrl+alt" ,not work

**Expected behavior**
ctrl+alt can open fluentsearch bar

**Desktop (please complete the following information):**
 - Windows 10 Version: [1909]
 - Fluent Search Version [0.9.91.71]

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.83                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
