### ISSUE TITLE
The FS UI become very wide, looks wired.

### ISSUE THREAD

**Issue by fanhwid** [adirh3/Fluent-Search#604]
in the recent version, the FS UI looks wired, the search box was so wide, and don't coordinate with the system
![image](https://user-images.githubusercontent.com/72638192/172033212-ccd715db-760d-4e3a-9ab7-21766d6092c2.png)
 
Version：0.9.91.83

**Comment by adirh3** [comment]
@fanhwid click on `Reset all window sizes to default` in Settings -> Appearance, and let me know if it happens again

**Comment by fanhwid** [comment]
> @fanhwid click on `Reset all window sizes to default` in Settings -> Appearance, and let me know if it happens again

It worked，Thanks
