### ISSUE TITLE
PARENT FOLDER [3rd Party File Managers]

### ISSUE THREAD

**Issue by mragtronx8** [adirh3/Fluent-Search#605]
**PARENT FOLDER [3rd Party File Managers] #BUG**

when am using Ctrl+2 with windows explorer,  it is working right.
but with xyplorer / xplorer2 it is not working as it should [it is jumping right into the folder, and not to the PARENT]

and if xyplorer/xplorer2 is open, ctrl+2 is not working. file manager must be closed / not in focus, for fs "ctrl+2" to open directory "wrong path and not parent, it is opening the folder itself"

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.88                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
