### ISSUE TITLE
Fluent Search getting auto killed

### ISSUE THREAD

**Issue by onlytanmoy** [adirh3/Fluent-Search#606]
Hiya, first things first, this is a fantastic app, so thank you for that, however I am not able to use it as it is getting auto killed, will appreciate your help to resolve it.

**To Reproduce**
I have Fluent Search installed from MS Store, it is set to start at start-up of my laptop, minimized to system tray
After some running of the laptop, when I hit the hotkey combination to launch search bar, nothing happens
If I then go to system tray, I can see Fluent Search icon present but when I try to click on it, it disappears

**Expected behavior**
The Fluent Search application should run in the background without getting killed

**Desktop (please complete the following information):**
 - Windows 11 Version: 21H2 (OS Build 22000.675)
 - Fluent Search Version 0.9.90.9999

**Comment by adirh3** [comment]
@onlytanmoy can you please try looking for crash errors -

1. Open Run 
2. Type `eventvwr` and run it
3. In the left panel go to Windows Logs -> Application
4. Right click Application -> Filter Current Log -> Check Error and press OK
5. Look for Fluent Search errors, the source should be FluentSearch.exe or .NET

Let me know if you find anything, if not it means that app exited normally.

**Comment by onlytanmoy** [comment]
Thanks for the detailed steps, very helpful to someone like me using Windows Event viewer for the first time.

I found two Errors at 09/06 with below details:-

1st one Source: Application Error
Faulting application name: fluentsearch.exe, version: 0.9.90.9999, time stamp: 0x61735063
Faulting module name: coreclr.dll, version: 6.0.21.52210, time stamp: 0x61734c6b
Exception code: 0xc0000005
Fault offset: 0x00000000001ccf41
Faulting process ID: 0x3b38
Faulting application start time: 0x01d87c3afd04fb24
Faulting application path: C:\Program Files\WindowsApps\21814BlastApps.BlastSearch_0.9.90.0_x64__pdn8zwjh47aq4\fluentsearch.exe
Faulting module path: C:\Program Files\WindowsApps\21814BlastApps.BlastSearch_0.9.90.0_x64__pdn8zwjh47aq4\coreclr.dll
Report ID: fa221333-14c0-4dea-bec8-e9c6bca3f753
Faulting package full name: 21814BlastApps.BlastSearch_0.9.90.0_x64__pdn8zwjh47aq4
Faulting package-relative application ID: FluentSearch

2nd one Source: .NET Runtime
Application: fluentsearch.exe
CoreCLR Version: 6.0.21.52210
.NET Version: 6.0.0
Description: The process was terminated due to an internal error in the .NET Runtime at IP 00007FFAA022CF41 (00007FFAA0060000) with exit code c0000005.

**Comment by adirh3** [comment]
@onlytanmoy when you open Fluent Search after it crashes, does it open normally? It crashes only in the background?

Would you mind trying to install Fluent Search using the EXE installer? 
There were few Microsoft Store users that experienced something similar and it was solved for them when installing through the EXE installer. You can find it here - https://www.fluentsearch.net/

**Comment by adirh3** [comment]
> Yes, opens normally after crash. I think it crashes for good as using the Ctrl+Alt hotkey combination doesn't trigger it.
> 
> Anyways I have uninstalled the program yesterday and installed it again via FluentSearch.appx downloaded from https://www.fluentsearch.net/ Also I did install some Windows 11 updates that came through now.
> 
> Let's keep it as watching brief for now and I will update again on this ticket if it still crashes and then would try the EXE installer.

Sounds good, keep me updated.
Forgot to mention, when your graphic's driver will update/restart Fluent Search may crash, writing here in case you restart it daily (someone else did).

**Comment by onlytanmoy** [comment]
Morning mate, I have started getting a pop-up of UAC for FluentSearch saying do you want to allow this app to make changes to your device? when I boot my windows, and then I need to hit Yes to continue, how do I disable this pop-up window? I don't want to set my UAC to Never Notify, just whitelist FluentSearch alone.

**Comment by adirh3** [comment]
> Morning mate, I have started getting a pop-up of UAC for FluentSearch saying do you want to allow this app to make changes to your device? when I boot my windows, and then I need to hit Yes to continue, how do I disable this pop-up window? I don't want to set my UAC to Never Notify, just whitelist FluentSearch alone.

Hey, do you have 2 versions of Fluent Search installed? It shouldn't notify you as long as the indexer is installed and set to run automatically.
To check if it's installed - 
1. Open Run and type Services.msc
2.  Search for FluentSearch.FileIndexer
3. Right click it properties
4. Change startup to automatic

**Comment by onlytanmoy** [comment]
Apologies for the delayed response, I was at work.
As I said before I have uninstalled the MS Store version and installed the appx package now, when I type in Windows search, it just shows Fluent Search beta, so I believe I just have one version installed.
Below is what it shows me, think I need to click Start and that should do?
![image](https://user-images.githubusercontent.com/48493659/173905854-bfff8c52-0857-4d5c-8bff-31f4e79693c9.png)

**Comment by adirh3** [comment]
> Apologies for the delayed response, I was at work. As I said before I have uninstalled the MS Store version and installed the appx package now, when I type in Windows search, it just shows Fluent Search beta, so I believe I just have one version installed. Below is what it shows me, think I need to click Start and that should do? ![image](https://user-images.githubusercontent.com/48493659/173905854-bfff8c52-0857-4d5c-8bff-31f4e79693c9.png)

I think the Microsoft Store did not fully uninstall the indexer service (it's not behaving well with services), lets try to reinstall the service -
In Fluent Search, open Settings -> Files -> File indexer -> Press "Uninstall Service", wait for it to finish then press "Install service".

**Comment by onlytanmoy** [comment]
Thanks for the guidance mate, I did that, status says running in services.msc, must be all good when I reboot my laptop next :)

**Comment by adirh3** [comment]
> Thanks for the guidance mate, I did that, status says running in services.msc, must be all good when I reboot my laptop next :)

Can you please confirm whether the original issue (crashing) was fixed?

**Comment by onlytanmoy** [comment]
Yes mate, I don't have the crash or auto-killed issue any more, happy to close this issue. Many thanks for your support.
