### ISSUE TITLE
Chinese version search file does not display

### ISSUE THREAD

**Issue by ttxhxz** [adirh3/Fluent-Search#608]
**Describe the bug**
Chinese version search file does not display

**To Reproduce**
1. outgoing software
2. Enter 2022-06.md
3. The result does not show the file

**Expected behavior**
When I search for "2022-06.md", the corresponding file should appear, but I don't see the corresponding result here

**Screenshots**
![image](https://user-images.githubusercontent.com/24288387/173511775-3baf58a0-c23e-4eb9-ab52-da01f32031a8.png)
![image](https://user-images.githubusercontent.com/24288387/173511865-8238ef16-2c61-4c75-b2cf-907eccea6ad9.png)
![1](https://user-images.githubusercontent.com/24288387/173512613-9f25e5f3-7276-46dc-84ca-69057748cc6b.gif)
![2](https://user-images.githubusercontent.com/24288387/173514612-954da1cb-be3a-4d3c-94c2-1970a066b6c1.gif)

**Desktop (please complete the following information):**
 - Windows 11 Version: [21H2 22000.675]
 - Fluent Search Version [0.9.91.85]

**Comment by ttxhxz** [comment]
![image](https://user-images.githubusercontent.com/24288387/173515129-0889612f-da1b-4f6d-b629-053a9ef4603f.png)

Whether I add this path or not, the corresponding file is not displayed
D:\火柴日报\

**Comment by adirh3** [comment]
@ttxhxz did you rebuild after adding D?
Is your D drive NTFS? You can check it by right clicking on it and then properties.

Does the 2022-05 file show in Fluent Search?

**Comment by ttxhxz** [comment]
![image](https://user-images.githubusercontent.com/24288387/173730590-2a18bd67-a0a3-482f-813d-6e855d95edcf.png)
yes it is NTFS
The D drive is added by default and cannot be deleted. At the same time, I have rebuilt the index many times, and nothing has changed.
This disk is a local disk, not a remote disk

**Comment by adirh3** [comment]
> ![image](https://user-images.githubusercontent.com/24288387/173730590-2a18bd67-a0a3-482f-813d-6e855d95edcf.png) yes it is NTFS The D drive is added by default and cannot be deleted. At the same time, I have rebuilt the index many times, and nothing has changed. This disk is a local disk, not a remote disk

When disabling Enable Chinese support in Settings -> Search, does it find the file?

**Comment by ttxhxz** [comment]
![image](https://user-images.githubusercontent.com/24288387/173999120-ea9808a6-f981-4804-9898-dcf374200a76.png)
@adirh3 
Yes, English is also not valid

**Comment by ttxhxz** [comment]
I have rebuilt the index after switching to English

**Comment by adirh3** [comment]
@ttxhxz I meant this setting -
![image](https://user-images.githubusercontent.com/27368554/174124201-1a98f49d-67c8-4d90-89c0-cb44a45b1979.png)
Do you have it enabled?

**Comment by ttxhxz** [comment]
![image](https://user-images.githubusercontent.com/24288387/174204962-8d4d8a06-2386-4d40-a007-338c0f207d8c.png)
No, I have turned it off after switching back to English, and re-indexed it again, the result is the same, but I still can't find the corresponding file

**Comment by ttxhxz** [comment]
Because it is a company computer, it is not convenient to use Discord to contact you.
After I reset all the settings of the software, the corresponding directory files can be searched normally.
I'm sure I'm not ignoring the files in that folder, and I've also found that most of the D drive files are not searchable. I feel that it is a bug that occurs when the indexer is added and deleted multiple times. After I restore the default and do not operate any settings, the text can be searched normally
Finally, thank you for your help~

**Comment by ttxhxz** [comment]
I reset the software and can't find the file again, it's too hard

**Comment by ttxhxz** [comment]
Now the software can't find the file after restoring the default settings.

**Comment by adirh3** [comment]
@ttxhxz can you please send me your settings folder as a zip file via mail or Discord when the issue occurs?
The settings are in `%appdata%\Blast\Settings`, they may contain personal data, so I suggest not sending them here.

Mail - support@fluentsearch.net
Discord - https://discord.gg/W2EuWvD6GD (contact me via private message)

**Comment by adirh3** [comment]
@ttxhxz thanks.
Can you try changing the setting `Max files to process` to `0` in Settings -> Files, and let me know if it finds the file?

**Comment by ttxhxz** [comment]
Oh! He succeeded! ! ! ! ! ! ! ! Excited! ! !

**Comment by ttxhxz** [comment]
It turns out that he is in the advanced settings. I can only find it by searching the settings. Why not set the number of index files to be unlimited by default?

**Comment by adirh3** [comment]
> It turns out that he is in the advanced settings. I can only find it by searching the settings. Why not set the number of index files to be unlimited by default? @adirh3

Thanks for the update, glad we figured it out :)
It used to be not ON by default since file search used to be slower, but that's not the case anymore, so I will change it.
