### ISSUE TITLE
Ctrl Trigger On Screen Search? 

### ISSUE THREAD

**Issue by nutnutwin** [adirh3/Fluent-Search#609]
**Describe the bug**
I recently updated from
0.9.91.64
to 0.9.91.87
anf found this bug

**To Reproduce**
- Bring Up the search window
- Press Ctrl

｢Search using Screen｣ is OFF
and ｢Search in-app using Screen hotkey｣ is set to ｢None｣

**Expected behavior**

**Screenshots**
If you need I can post a screenshot

**Desktop (please complete the following information):**
 - Windows 11 Version: 21H2
 - Fluent Search Version 0.9.91.87

**Additional context**
nothing extra

Thank you

**Comment by adirh3** [comment]
@nutnutwin this is due to new feature called Keyboard navigation in Settings -> System. 
It let's you navigate Fluent Search windows using screen search

**Comment by nutnutwin** [comment]
@adirh3 
Hi, thank you for your answer.
