### ISSUE TITLE
quicklook preview closes the FS window when `hide when losing focus` is on

### ISSUE THREAD

**Issue by cannibalox** [adirh3/Fluent-Search#61]
**Describe the bug**
when `Hide when losing focus` is on, and `quicklook` is set as the `file preview provider`, activating a preview (shift enter) will close the FS search window (whereas when using FluentSearch internal preview, the FS window stays open)

**Expected behavior**
there should be an exception for Quicklook, it should not cause the main windows to close

FS 0.9.85.20 win10 1809 ltsc

**Comment by ScarletKing-001** [comment]
Other FS windows (like settings) seem to overlap the Quicklook preview , irrespective of whether `Hide when losing focus` is turned on or off

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.85.50

**Comment by cannibalox** [comment]
fixed
