### ISSUE TITLE
PDF thumbnail previews

### ISSUE THREAD

**Issue by H5820121** [adirh3/Fluent-Search#611]
After I uninstalled 'Adobe Acrobat Pro DC (32-bit)'  and installed 'Adobe Acrobat Pro DC (**64-bit**)', FS do not show the PDF thumbnail previews, but the 'Flow Launcher' shows it well, so I think it's a bug of FS.
Thanks!
![image](https://user-images.githubusercontent.com/105562828/174535506-b2d05fe2-fc52-46d1-a261-d8ec176cd2f3.png)
![image](https://user-images.githubusercontent.com/105562828/174535407-def6935c-9f36-4ca1-a8e5-461b4df5d4e9.png)
![image](https://user-images.githubusercontent.com/105562828/174535699-c143162e-ec7f-46b4-8b3a-6afc40b51cb0.png)

**Comment by adirh3** [comment]
@H5820121 thanks for reporting this.
Was the issue persistent after a computer restart? 
Flow Launcher might've been keeping the thumbnails in memory after reinstalling the PDF reader.

**Comment by H5820121** [comment]
Yes, but now I checked and I see you're right the problem is also in Windows Explorer.
Can you help with that?
This happened after installation 'Adobe Acrobat Pro DC v2022.001.20142 x64'
thanks!

**Comment by adirh3** [comment]
@H5820121 sorry, missed your message.
Were you able to resolve that?
I believe rebuilding Windows thumbnail cache might work  - https://www.windowscentral.com/how-reset-thumbnail-cache-windows-10#:~:text=How%20to%20recreate%20the%20thumbnail%20cache%20using%20Disk,confirm%20and%20to%20complete%20the%20task.%20See%20More.

**Comment by H5820121** [comment]
Thanks!
