### ISSUE TITLE
The latest version， some apps can't be found some apps

### ISSUE THREAD

**Issue by fanhwid** [adirh3/Fluent-Search#614]
Version：0.9.91.94
In the latest version, some apps can not be found.
example: allegro
![image](https://user-images.githubusercontent.com/72638192/174931806-d2030518-fb89-43e5-ae47-60788a802e4b.png)
![image](https://user-images.githubusercontent.com/72638192/174931763-f1262367-9cc6-4580-9753-0cd3f36b5a4f.png)
example: 
![image](https://user-images.githubusercontent.com/72638192/174931930-0680076c-7f86-4358-a271-59d568027197.png)
![image](https://user-images.githubusercontent.com/72638192/174931972-23a2fe83-3af9-4c40-b0cf-ba3e05a05e4e.png)

**Comment by adirh3** [comment]
@fanhwid do you have any custom app locations?
Can you let me know what's the path of the lnk file for these apps? You can check in the start menu

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.95                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by adirh3** [comment]
@fanhwid I assumed this is fixed by the thumbsup, if not please reopen
