### ISSUE TITLE
Reorganization the Effects & Appearance tabs in settings

### ISSUE THREAD

**Issue by tomnapp2** [adirh3/Fluent-Search#621]
**Is your feature request related to a problem? Please describe.**
Fluent Search settings, at least when the "Advanced On" toggle is switched on, can be quite intimidating. An idea of mine to help make things more intuitive is to move most of the settings in "Effects" to "Appearance" and turn "Effects" into a dedicated group for animations.

**Describe the solution you'd like**
Move wallpaper background and transparency settings to Appearance group, leaving only the animations settings. Then rename the Effects group to Animations.

**Describe alternatives you've considered**
I'm not a designer, so I understand this might not make sense from a UI/UX point of view; its just the way I'd organize things if I had opportunity.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 1.0.0.11                                          . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
