### ISSUE TITLE
Bug in the FS preview of Hebrew .txt files in ANSI encoding

### ISSUE THREAD

**Issue by H5820121** [adirh3/Fluent-Search#623]
The preview of txt files in ANSI encoding does not display Hebrew correctly
![image](https://user-images.githubusercontent.com/105562828/177014822-b4f32e38-7609-4a07-bbdf-c28a606b89a1.png)

But in 'QuickLook' preview, it is displayed correctly.
![image](https://user-images.githubusercontent.com/105562828/177014922-50cf91d3-370e-4225-9531-9bd763916c78.png)

I use your wonderful software a lot!
Thanks!

**Comment by adirh3** [comment]
@H5820121 not sure how you saved txt file with Hebrew characters using ANSI, it shouldn't be supported.
Even in Windows notepad it won't work for me -
<img width="686" alt="image" src="https://user-images.githubusercontent.com/27368554/177015164-0ccc5e09-274a-4b13-bf60-559020ceba0e.png">

Previewing txt files with Hebrew text using UTF/Unicode should work in the latest nightly builds.

**Comment by H5820121** [comment]
Sorry, I do not understand what you mean. The files in the UTF Hebrew encoding in the FS preview are displayed correctly. The problem is only with the files in the ANSI encoding [and I have many of these], they are well presented only in the 'QuickLook' preview, as in the screenshot I attached above.
![image](https://user-images.githubusercontent.com/105562828/177015715-9b5c7fef-01c1-49a6-9e41-9a13420e6d44.png)
![image](https://user-images.githubusercontent.com/105562828/177015769-4d97a957-b618-44fe-9aff-21b82418e722.png)

Thanks!

**Comment by adirh3** [comment]
> Sorry, I do not understand what you mean. The files in the UTF Hebrew encoding in the FS preview are displayed correctly. The problem is only with the files in the ANSI encoding [and I have many of these], they are well presented only in the 'QuickLook' preview, as in the screenshot I attached above. ![image](https://user-images.githubusercontent.com/105562828/177015715-9b5c7fef-01c1-49a6-9e41-9a13420e6d44.png) ![image](https://user-images.githubusercontent.com/105562828/177015769-4d97a957-b618-44fe-9aff-21b82418e722.png)
> 
> Thanks!

I need to use other notepad app, Windows notepad won't let me save files with Hebrew text with ANSI encoding. 
Will try using some other apps

**Comment by H5820121** [comment]
Strange, I have no problem saving Hebrew text with ANSI encoding with Windows notepad.
![image](https://user-images.githubusercontent.com/105562828/177016018-d7286ceb-b011-4121-8d10-3cfc991592c5.png)
Maybe, because I had the Hebrew language kit installed on Windows.
![image](https://user-images.githubusercontent.com/105562828/177016090-0e7d85cc-ff5c-4bef-92d7-84355666ff82.png)

**Comment by H5820121** [comment]
[Example.txt](https://github.com/adirh3/Fluent-Search/files/9033778/Example.txt)
I have uploaded here the file in ANSI encoding, please try to open it in the FS preview, and in the 'QuickLook' preview.

**Comment by H5820121** [comment]
Have you succeeded now, to save files with Hebrew text with ANSI encoding?

**Comment by adirh3** [comment]
@H5820121 thanks for sharing the file, for some reason my notepad refuses to display or save Hebrew with ANSI encoding -
![image](https://user-images.githubusercontent.com/27368554/177052520-bc771888-f8a0-4d21-bf21-5a5642a3e4e0.png)

Maybe because I am using Windows 11.
Either way, I will add support for auto detecting the encoding in today's update, thanks!
![image](https://user-images.githubusercontent.com/27368554/177052530-c1ed7363-b81d-4527-8b80-52a4c92a7f53.png)

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.994                                        . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by H5820121** [comment]
Thank you!
I updated to the latest version, but I do not understand why, sometimes it worked, and sometimes not, but it's always fine in the 'QuickLook' preview as you can see in the screenshot.
![image](https://user-images.githubusercontent.com/105562828/177058565-432eb715-d23b-4253-9838-d1cca5552f60.png)

But I do not know if it is so important that it justifies bothering you so much with it.

And anyway, I do not think your problem is due to WIN11, I think that what I do not have the problem of saving Hebrew text in ANSI encoding is because I have the Hebrew language pack installed in Windows, so just as you have no problem displaying English text in ANSI encoding, so I have no problem displaying texts in Hebrew. And if you want, I would suggest installing a Hebrew language pack temporarily [then you can remove it], by pressing on the +
![image](https://user-images.githubusercontent.com/105562828/177058594-5429f198-68d4-4ff8-af77-4be5602bd832.png)

**Comment by adirh3** [comment]
> Thank you! I updated to the latest version, but I do not understand why, sometimes it worked, and sometimes not, but it's always fine in the 'QuickLook' preview as you can see in the screenshot. ![image](https://user-images.githubusercontent.com/105562828/177058565-432eb715-d23b-4253-9838-d1cca5552f60.png)
> 
> But I do not know if it is so important that it justifies bothering you so much with it.
> 
> And anyway, I do not think your problem is due to WIN11, I think that what I do not have the problem of saving Hebrew text in ANSI encoding is because I have the Hebrew language pack installed in Windows, so just as you have no problem displaying English text in ANSI encoding, so I have no problem displaying texts in Hebrew. And if you want, I would suggest installing a Hebrew language pack temporarily [then you can remove it], by pressing on the + ![image](https://user-images.githubusercontent.com/105562828/177058594-5429f198-68d4-4ff8-af77-4be5602bd832.png)

Can you please send me the file it's not working for.
Also, I got Hebrew language pack installed, i thinks it's issue with notepad, notepad++ works for me

**Comment by H5820121** [comment]
[נסיון0.txt](https://github.com/adirh3/Fluent-Search/files/9036688/0.txt)
Thanks!

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.995                                        . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by adirh3** [comment]
> Now, it's working fine. Thanks!
> 
> * Please, do not forget the FS preview for the popular office files.

There is a different issue for this, but won't happen in 0.9.91.x.
Closing
