### ISSUE TITLE
couldn't ignore 'recent file' path

### ISSUE THREAD

**Issue by theweeeknd** [adirh3/Fluent-Search#624]
too much **useless** / duplicated results from this path:
C:\Users\username\AppData\Roaming\Microsoft\Windows\Recent\

![image](https://user-images.githubusercontent.com/84619641/177018242-79f98940-6337-48cd-984f-1a0d0369c2b2.png)

but, failed to set it **ignored**, 'folder name invaild' in 'select folder' dialogue

![image](https://user-images.githubusercontent.com/84619641/177018341-026d206f-d868-400a-9e86-7fa5939c29f0.png)

i mean, why not we add a path to this 'ignored' list by just '**type** it' ? insted of trying '**select** it'

**Comment by adirh3** [comment]
@theweeeknd For some reason you can't select `recents` in any Windows dialog, I have no idea why.
You can add it by selecting it from the suggestions icon -
![image](https://user-images.githubusercontent.com/27368554/177030477-0bcfe3db-be27-461c-b17c-dae7c4755e07.png)

Or add a different folder and change its path in the table.

**Comment by theweeeknd** [comment]
> 

thx but in my case no 'recent' in this suggestion list

![image](https://user-images.githubusercontent.com/84619641/177060971-efd19f51-b0b4-4d87-9d22-86e9dbe451b5.png)

also fail to change path, select a path try to type sth but just … nothing happened 
![can't modify path](https://user-images.githubusercontent.com/84619641/177061126-50487528-2631-4722-8eb3-e91f3a6f3d93.gif)

**Comment by adirh3** [comment]
@theweeeknd sorry thought you were using the nightly version.
This is fixed in the nightly version, will be available as stable next week.

**Comment by theweeeknd** [comment]
> @theweeeknd sorry thought you were using the nightly version. This is fixed in the nightly version, will be available as stable next week.

thx very much
