### ISSUE TITLE
Support for other languages

### ISSUE THREAD

**Issue by KyroOW** [adirh3/Fluent-Search#626]
I would like Fluent Search to support more than just the english language, i was surprised by how customizable Fluent Search is despite having no other language than english.

**Comment by adirh3** [comment]
Thanks @KyroOW, Fluent Search is now fully translated to Spanish and Chinese in the nightly version.
If you'd like to help with the translation of a specific language, please let me know.

Translation will be ongoing based on volunteers from the community :)

**Comment by KyroOW** [comment]
I can help for French when i have extra time but since i'm not perfectly perfect in grammar i might do some mistakes until Molière's son shows up and fix it.

**Comment by adirh3** [comment]
> I can help for French when i have extra time but since i'm not perfectly perfect in grammar i might do some mistakes until Molière's son shows up and fix it.

If you'd like here is the link to the translation website (specifically for French) - https://app.tolgee.io/accept_invitation/cmTkhUwvKgdLKaPmSsHyAXAeVXHtrLmFGyJByBqADLIbTiIDCn

No worries if not, it's a lot of work.
Closing this.
