### ISSUE TITLE
I somehow invoked what appears to be a Task Switcher

### ISSUE THREAD

**Issue by KyroOW** [adirh3/Fluent-Search#627]
I was playing a game and got suddenly switched to Discord and noticed a white bar at the top of my screen that appeared for like a fraction of a second, so i took an Nvidia Shadowplay replay to see what it was and found this:

![image](https://user-images.githubusercontent.com/37251814/178063216-ea81b303-d15d-4350-8989-941f346900b7.png)

At the same time a Fluent Search icon was active on the Task Bar
![image](https://user-images.githubusercontent.com/37251814/178063206-d174599c-ce22-4bf9-9f00-93e348a86523.png)

I looked into the settings and unless it has a different name than what i was looking for, i wasn't able to find anything about a task switcher.

Judging by the video, at the time it happened, i was pressing the keys Z + CTRL and probably Q or D too (azerty keyboard)

**Comment by adirh3** [comment]
@KyroOW this is the process history window, you can disable it in Settings -> Processes -> Go to next/previous hotkeys.
I disabled it by default in the upcoming version.

**Comment by KyroOW** [comment]
Oh yes that was it ! Thank you.

**Comment by adirh3** [comment]
> Oh yes that was it ! Thank you.

Glad it helped, to reset simply select the hotkey and press Escape.
Closing :)
