### ISSUE TITLE
Use a black notification icon when task bar is in light mode

### ISSUE THREAD

**Issue by Jaap-van-Hengstum** [adirh3/Fluent-Search#63]
When the taskbar is put in light mode, the notification icon should switch to a black variant.

<img width="36" alt="fs-notification-icon-dark" src="https://user-images.githubusercontent.com/1670232/120974459-751c8500-c770-11eb-80c8-e36a73f3778f.png"> (dark mode)

<img width="38" alt="fs-notification-icon-light" src="https://user-images.githubusercontent.com/1670232/120974625-a5642380-c770-11eb-95c1-5a4da6b547f1.png"> (light mode)

On the left is the Docker icon shown for reference.

**Comment by Metroid-Prime** [comment]
Yes, I support this change. I think the logo needs a little bit of color and place  issue #24  asking for an outline on the logo. This is a major change as the logo should have to be changed everywhere that Fluent Launcher is present.
https://github.com/adirh3/Fluent-Search/issues/24

**Comment by adirh3** [comment]
@Jaap-van-Hengstum Actually it should change, are you using Appx or Exe?
Need to do something about the logo either way
