### ISSUE TITLE
How can I remove the right body of search result?

### ISSUE THREAD

**Issue by amm834** [adirh3/Fluent-Search#634]
![Screenshot (6)](https://user-images.githubusercontent.com/65492233/179543146-9df9df91-80a3-4252-b075-b38232bdb625.png)

I want to remove the right part of search menu for the minimalism.

**Comment by adirh3** [comment]
@amm834 right click empty space of it and press hide -
![image](https://user-images.githubusercontent.com/27368554/179543379-ca8aeafd-5f58-4398-b145-6e5770ded703.png)
