### ISSUE TITLE
BUG in FS 'Tasks'

### ISSUE THREAD

**Issue by H5820121** [adirh3/Fluent-Search#639]
I cannot change the settings in 'Tasks' that I created, 
For example, to change the settings in the 'Result selector',

![image](https://user-images.githubusercontent.com/105562828/181305582-330720cf-632f-4fa1-a1c8-b0e53eb76a84.png)

And in new Tasks I cannot make connections. For example, a connection between 'Custom operation' and 'Result selector'.
I have the latest nightly update installed.
In the past everything was fine, and I don't know when the problem occurred.
Thanks!

**Comment by adirh3** [comment]
@H5820121 is that on nightly?
If so it's known issue, for now you can use keyboard (right/left) to navigate and Enter to open.

**Comment by H5820121** [comment]
Thanks for the response,
As I mentioned I have the latest nightly update installed.
The  (right/left) navigate and Enter to open **helped**, 
But there is **still the problem. in new Tasks I cannot make connections**. For example, a connection between 'Custom operation' and 'Result selector'.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.92.25                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by H5820121** [comment]
Thanks, now it works properly!
By the way, is there any progress in fixing the bug #629 in FS Indexer?

**Comment by adirh3** [comment]
> Thanks, now it works properly! By the way, is there any progress in fixing the bug #629 in FS Indexer?

Not yet unfortunately, it's much more problematic than I originally thought.

**Comment by H5820121** [comment]
I wish you that you will soon succeed with this bug as well, for now I am using FS with everything indexer.
I ask out of curiosity, is this bug only in Hebrew (and Arabic) because they are RTL languages, or in all languages ​​other than English?
- I would like to take this opportunity to express my gratitude again for your wonderful application that is very useful to me, and for the great effort you invest in its development!
