### ISSUE TITLE
Context Prioritization Ignore not working

### ISSUE THREAD

**Issue by Mr-Frankenstein** [adirh3/Fluent-Search#64]
**Describe the bug**
When I add a folder path and set it to **Ignore** in **Context Prioritization**, it's still showing in search results.

**To Reproduce**
1. Go to 'Prioritizatation' (_Show Advanced_ should be turned on)
2. Add a folder path to 'Context Prioritization'
3. Set it to 'Ignore'
4. Search the folder

**Expected behavior**
The folder sets to ignore should not be showed in search results.

**Screenshots**
![image](https://user-images.githubusercontent.com/85425543/120983416-4ebe1000-c797-11eb-850a-c9613bec7383.png)
![image](https://user-images.githubusercontent.com/85425543/120983316-34843200-c797-11eb-8a4b-f89aa63a814a.png)

**Desktop (please complete the following information):**
 - Windows 10 Version: 20H2
 - Fluent Search Version 0.9.85.20

**Comment by Chance92** [comment]
I think I am having a similar problem with a .lnk file. I have set both the directory and .lnk file type to be ignored, but it is still showing up.

**Comment by Metroid-Prime** [comment]
I'm going with my gut and making this a high priority as the nature of the bug interferes with FS's core functionality of search.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.85.40

**Comment by Nomad-0** [comment]
closing the issue as the bug seems to be fixed, @Mr-Frankenstein please check if it's fixed on your end.

**Comment by Metroid-Prime** [comment]
I believe this might be fixed, but will wait for  @Mr-Frankenstein
