### ISSUE TITLE
[Feature] Nothing to show text background must be centered but it is overflowing to the right side of the panel

### ISSUE THREAD

**Issue by amm834** [adirh3/Fluent-Search#643]
![Screenshot (10)](https://user-images.githubusercontent.com/65492233/183118717-f9957642-3a34-4bf7-bace-a480f24b77af.png)

**Comment by adirh3** [comment]
@amm834 thanks, what version of Fluent Search do you use? (Can check in system-tray -> about)

**Comment by amm834** [comment]
I will send version soon bro

**Comment by adirh3** [comment]
@amm834 Can you try disabling `Remember windows size after restart` in Settings -> Appearance (advanced) and restarting Fluent Search?

**Comment by amm834** [comment]
I restarted but not working

**Comment by adirh3** [comment]
@amm834 in Settings -> Appearance can you click `Reset all windows sizes to default`

**Comment by amm834** [comment]
Now result reset is working properly when I use Search bar only.

**Comment by adirh3** [comment]
> Now result reset is working properly when I use Search bar only.

And when not using, does it still overflow?

**Comment by amm834** [comment]
On full window mode

**Comment by adirh3** [comment]
> On full window mode

Does it look the same as the search bar only? Can you please screenshot?

**Comment by amm834** [comment]
Currently 

![Screenshot (14)](https://user-images.githubusercontent.com/65492233/183142716-73319b43-c748-4b52-a211-3ad632f72e6b.png)

**Comment by amm834** [comment]
It is not overflow right now

**Comment by amm834** [comment]
https://github.com/adirh3/Fluent-Search/issues/643#issuecomment-1206653461

but third one is occurring on startup

**Comment by adirh3** [comment]
> [#643 (comment)](https://github.com/adirh3/Fluent-Search/issues/643#issuecomment-1206653461)
> 
> but third one is occurring on startup

When you open FS for the first time it has that weird padding at the bottom?
Even when disabling `Remember windows size after restart`?

**Comment by amm834** [comment]
Yes

**Comment by amm834** [comment]
But currently it is working as excepted. Let me show you.
![Screenshot (16)](https://user-images.githubusercontent.com/65492233/183143448-7ea87001-8984-44cf-a4d0-fe64d798b786.png)

**Comment by amm834** [comment]
[fs.zip](https://github.com/adirh3/Fluent-Search/files/9271051/fs.zip)
My setting to trace bug

**Comment by amm834** [comment]
I think, this issue is resolved but I also don't know why 🤣🤣🤣

**Comment by adirh3** [comment]
> I think, this issue is resolved but I also don't know why 🤣🤣🤣

Deleted settings as it may contain personal info (just in case :) )
So now you can't repro it? Did you change screen resolution or DPI when it happened?

**Comment by amm834** [comment]
Nah, I don't change the dpi and anything. I just change the setting of fs.

**Comment by amm834** [comment]
I cannot repro bug again. But i will open an issue when it is occurred to me again

**Comment by adirh3** [comment]
Ok I will try to repro it as well, please post here if you find how to repro it :)

**Comment by amm834** [comment]
I will

**Comment by adirh3** [comment]
This should be solved in the latest stable, feel free to reopen if not.
