### ISSUE TITLE
Processes display order doesn't follow history

### ISSUE THREAD

**Issue by rachedhedia** [adirh3/Fluent-Search#646]
**Is your feature request related to a problem? Please describe.**
When opening the search bar and filtering on process I'm ewpecting the process to be listed from the more recently opened to the older one. It's not the case and actually I don't understand how it's ordered.

**Describe the solution you'd like**
Have the processes list from the most recently focused to the last recently opened

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.92.30                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
