### ISSUE TITLE
Some UI Issues: Search Window, Tray Icon & Update Window

### ISSUE THREAD

**Issue by gman414** [adirh3/Fluent-Search#647]
Hi adirh3,

Describe the bug: 

i) There seem to be a problem with Search Window/Search Bar

Upon launching, only small section of the upper left corner area is visible.
This happens  on both Full Window & Search Bar mode.

![image](https://user-images.githubusercontent.com/110206456/183322961-d3bb7a99-3300-46a8-af59-f6e7b2a87f5a.png)

![image](https://user-images.githubusercontent.com/110206456/183323213-09953f21-fdeb-4e56-b739-0c04edf2fc89.png)

![image](https://user-images.githubusercontent.com/110206456/183322997-327f39fc-d45b-40d9-b299-f9c2ca4c80c2.png)

However toggling  Search Window Style in the settings  fixes issue temporarily.
But the Issues returns upon restart.

ii) The Tray Icon
Menu is not displayed when right clicked on the tray icon.

iii) The update pop-up windows is blank
When checking for updates, the pop-up windows is blank

![image](https://user-images.githubusercontent.com/110206456/183324501-34304555-c283-416e-8f4d-7e3eaa6de899.png)

Desktop
    Windows 10 Pro: 21H2
    Fluent Search Version: 0.9.92.27

Thank you.

**Comment by adirh3** [comment]
@gman414 does it still happen on latest version?

**Comment by gman414** [comment]
> @gman414 does it still happen on latest version?

@adirh3 . sorry for the delay. the issue was fixed in version 0.9.92.29.   No issues with the  latest, version 0.9.92.30 either. Thank you.
