### ISSUE TITLE
[Tasks] New Search Trigger is set to TextMatchType: Exact

### ISSUE THREAD

**Issue by BaalEvan** [adirh3/Fluent-Search#648]
**Describe the bug**
After creating new Search trigger searchText is set to match exact `''` instead of contains

**To Reproduce**
1. Create new Search trigger with random letter as prefix
2. Don't change anything beside prefix
3. Add custom result with {searchedText} in name
4. Add custom operation
5. Try to use it
6. You should see entry when there is no text but it stop working after adding any letter after space
Example
`prefix ` -> entry is visible
`prefix anything` -> no entry

**Expected behavior**
TextMatchType should be set to contains by default 

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 10 Version: not related
 - Fluent Search Version: 0.9.91.9994

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.92.30                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
