### ISSUE TITLE
Show bookmarks when using bookmark tag before typing.

### ISSUE THREAD

**Issue by Mr-Frankenstein** [adirh3/Fluent-Search#65]
Show bookmarks in search results even before you type anything when the bookmark tag is used.

**Comment by Nomad-0** [comment]
Sorry, got closed by mistake

**Comment by Metroid-Prime** [comment]
Can you mock this up for us please in a picture?

Basically what you want is when the bookmark plugin is triggered, to show a list of bookmarks (alphabetically?) in the result fields?

**Comment by adirh3** [comment]
This_issue_has_been_potentially_fixed_in_version_

**Comment by Nomad-0** [comment]
Issue fix confirmed. @Mr-Frankenstein Please check and let us know if you see anything contrary. 
Closing issue.
