### ISSUE TITLE
[Tasks] C# script node content isn't aligned to left

### ISSUE THREAD

**Issue by BaalEvan** [adirh3/Fluent-Search#650]
**Describe the bug**
First 5 characters typed inside content field in c# node are out of view

**To Reproduce**
1. Open Tasks
2. Add C# node
3. Try to write code in content field
4. First 5 characters are out of view

**Expected behavior**
All characters should be visible

**Screenshots**
![image](https://user-images.githubusercontent.com/1843494/183809476-01624a5b-64f1-442f-a772-2373ea81bd30.png)

**Desktop (please complete the following information):**
 - Windows 10 Version: 21H2
 - Fluent Search Version 0.9.91.9554

**Comment by adirh3** [comment]
Thanks @BaalEvan, does it happen consistently with any text?
Can you share what's your screen resolution and DPI please?

**Comment by BaalEvan** [comment]
Its happening on all (3) monitors
1680x1050
2560x1080
1200x1920 
100% scale

but it is happening only in PS,C# and json node (big textBox)

**Comment by BaalEvan** [comment]
Appearance settings

![image](https://user-images.githubusercontent.com/1843494/184019374-3c4b0f88-6980-4ad0-86f2-286a0013fa3c.png)

**Comment by adirh3** [comment]
@BaalEvan I believe this is fixed now, closing but feel free to reopen if its not fixed for you.
