### ISSUE TITLE
[Tasks] Global Variable List  

### ISSUE THREAD

**Issue by BaalEvan** [adirh3/Fluent-Search#651]
**Is your feature request related to a problem? Please describe.**
Accessing paths, API keys etc variables inside operation without comment isn't obvious and could be problematic for sharable tasks 

**Describe the solution you'd like**
Some variables related to the entire task but not specific operations could be exposed into settings or additional canvas blocks for easier access

**Describe alternatives you've considered**
Having a setting page with variables for tasks would be also great

**Additional context**
We discussed it on discord #suggestion channel

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.92.48                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
