### ISSUE TITLE
[Tasks] Context menu isn't attached to mouse position

### ISSUE THREAD

**Issue by BaalEvan** [adirh3/Fluent-Search#652]
**Describe the bug**
After moving mouse cursor from a different monitor (different resolution) and right clicking on TaskCanvas Context Menu is offsetted

**To Reproduce**
0. You need secondary monitor with different resolution (2560x1080 in my case)
1. Open TaskWindow on first monitor (1680x1050 in my case)
2. Move mouse to second monitor (for example during researching documentation or something)
3. Go back to 1st monitor and use Right mouse button to open Context Menu
4. Context menu isn't next to mouse cursor

**Expected behavior**
Context Menu should be next to Mouse cursor

**Screenshots**

https://user-images.githubusercontent.com/1843494/184018843-4d67f96e-c270-40b5-b531-a8b23ef1ad38.mp4

**Desktop (please complete the following information):**
 - Windows 10 Version: 21H2
 - Fluent Search Version alpha 0.9.92.29

**Comment by adirh3** [comment]
Thanks, this should be fixed on latest nightly, closing.
