### ISSUE TITLE
[QuickMenu] SubMenu background is transparent while main window and QuickMenu are not

### ISSUE THREAD

**Issue by BaalEvan** [adirh3/Fluent-Search#653]
**Describe the bug**
Text in QuickMenu SubMenu isn't readable on white/light background when app is in DarkMode (white text)

**Expected behavior**
Text should be readable 

**Screenshots**
![image](https://user-images.githubusercontent.com/1843494/184033692-4a2be48d-580d-471c-8ba8-bb31214c5fec.png)

**Desktop (please complete the following information):**
 - Windows 10 Version: 21H2
 - Fluent Search Version 0.9.92.29

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.92.31                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
