### ISSUE TITLE
Regular Search hotkey activates Quick Menu instead of regular Fluent Search window

### ISSUE THREAD

**Issue by tomnapp2** [adirh3/Fluent-Search#655]
**Describe the bug**
I activated the Quick Menu in all possible ways (i.e. I can access it through the left+right mouse click, a touchpad gesture [four-finger tap], and a keyboard shortcut [Win+Alt]). All of these methods activate the Quick Menu as expected. However, when I try to pull up the _regular_ Fluent Search window (i.e. the home screen) with the hotkey I had set long ago (Win), the Quick Menu is activated.
There are two important things to note here:
1. When pressing the regular Fluent Search hotkey, the regular Fluent Search window (i.e. the home screen) appears for a second before disappearing and being replaced by the Quick Menu.
2. When I click on a Task Bar shortcut I made to FluentSearch.exe, the regular Fluent Search window appears as expected.
3. Closing Fluent Search and restarting it does not seem to fix this.
 
**To Reproduce**
1. Set hotkey for Quick Menu
2. Activate Quick Menu with hotkey. Close Quick Menu
3. Press hotkey for regular Fluent Search search

**Expected behavior**
I expect the regular Fluent Search hotkey to activate the regular Fluent Search interface (i.e. the home screen)

**Desktop (please complete the following information):**
 - Windows 11 Version: 21H2
 - Fluent Search Version: 0.9.92.31

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.92.32                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by tomnapp2** [comment]
I updated and the problem does indeed seem to be fixed. Thank you!
