### ISSUE TITLE
Bug, The "window opacity" setting does not work in the submenus 

### ISSUE THREAD

**Issue by H5820121** [adirh3/Fluent-Search#656]
The window opacity setting
![image](https://user-images.githubusercontent.com/105562828/184548698-f4efaccb-64c9-42bf-92ba-e9ed136d309a.png)

 does not work in the submenus, as you can see in the screenshots.
![image](https://user-images.githubusercontent.com/105562828/184548786-b8b8bd29-7b8b-4596-983f-cb804d3e9267.png)
![image](https://user-images.githubusercontent.com/105562828/184548798-2c097285-7427-4b64-8bd3-fade0c810b07.png)

Thanks!

**Comment by H5820121** [comment]
![image](https://user-images.githubusercontent.com/105562828/184653857-bcc99530-e71c-4c0a-a6d9-03c1b75f4de6.png)

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.92.36                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
