### ISSUE TITLE
Development: "Search again" does not keep the window open

### ISSUE THREAD

**Issue by Sp1rit** [adirh3/Fluent-Search#658]
**Describe the bug**
I am handling the HandleSearchResult inside each operation (but also tried only in the App). Returning for example:
`new HandleResult(true, true) { SearchRequest = new SearchRequest("test", "", SearchType.SearchAll) };`

The new request is set, but the window closes. It seems to work for built in searches (like edit of chrome history item).

**Expected behavior**
The window should stay open to allow further search inside the previous result.

**Desktop (please complete the following information):**
 - Windows 11 Version: 21H2
 - Fluent Search Version: 0.9.91.9994

**Comment by adirh3** [comment]
@Sp1rit please set the `ISearchOperation`'s `HideMainWindow` to `False` to make it not hide the search window before running the operation.
If you'd like to hide the search window after running the operation, set the `ForceHideWindow` of `HandleResult` to `True`.
Hope this helps, also feel free to ping me in Discord for any questions - https://discord.gg/W2EuWvD6GD
