### ISSUE TITLE
[Tasks] Grouping isn't working

### ISSUE THREAD

**Issue by BaalEvan** [adirh3/Fluent-Search#659]
**Describe the bug**
Adding same string as a Group doesn't group entries

**To Reproduce**
1. Create new TaskProject
2. Add Search node
3. Add Custom Result with "example" as a Group
4. Add Second Custom Result with "example" as a Group
5. Try to call search 

**Expected behavior**
Entries should be grouped like when looking for app with active process

**Screenshots**
![BugReport-Grouping](https://user-images.githubusercontent.com/1843494/185054309-be41a638-6ea6-4525-a9e4-d3d3b361950e.png)

**Desktop (please complete the following information):**
 - Windows 10 Version: 21H2
 - Fluent Search Version Alpha 0.9.92.34

**Comment by adirh3** [comment]
@BaalEvan you need to enable `Group search results` in Settings -> Search

**Comment by BaalEvan** [comment]
I have it enabled and it is working for different kinds of search 
![image](https://user-images.githubusercontent.com/1843494/185182583-5e04b17d-13a3-4ace-bf90-00d8a3402cab.png)
![image](https://user-images.githubusercontent.com/1843494/185182635-6391e36c-c90f-411f-acda-ef54dd880185.png)

**Comment by BaalEvan** [comment]
But changing Smart into Type is kinda working but still Group field is ignored 
![image](https://user-images.githubusercontent.com/1843494/185184695-ef372355-9a51-404b-a00e-4b748c0b76b2.png)

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.92.35                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
