### ISSUE TITLE
Hotkeys for search results

### ISSUE THREAD

**Issue by Najah101** [adirh3/Fluent-Search#66]
Hotkeys for search results.
When hitting the hotkey it will select the search, then you can open the search result or use the shortcuts in the side panel.

Examples
![image](https://user-images.githubusercontent.com/85425543/120995568-24724f80-c7a3-11eb-85e2-a6446501ccca.png)
![image](https://user-images.githubusercontent.com/85425543/120995564-23412280-c7a3-11eb-9c51-265b1a4976c8.png)
![image](https://user-images.githubusercontent.com/85425543/120995573-25a37c80-c7a3-11eb-91e7-18098fd820bf.png)

Ctrl + numbers are already in use so maybe Alt + numbers

**Comment by Metroid-Prime** [comment]
I wonder if it's a better idea to allow the user to select (through a setting) the combo-button they would like to use for these quicklaunches.  That CTRL vs Command vs Alt.

What do you guys think?

**Comment by Nomad-0** [comment]
> I wonder if it's a better idea to allow the user to select (through a setting) the combo-button they would like to use for these quicklaunches. That CTRL vs Command vs Alt.
> 
> What do you guys think?

yes, I already have my `ctrl+number keys` open 
![image](https://user-images.githubusercontent.com/76395594/121060886-03cae980-c7e5-11eb-94dc-43386377699d.png)

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.82                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
