### ISSUE TITLE
[Tasks] Adding Information Elements causing Crash

### ISSUE THREAD

**Issue by BaalEvan** [adirh3/Fluent-Search#660]
**Describe the bug**
Clicking + button custom result settings window causes application crash

**To Reproduce**
1. Create TaskProject
2. Add CustomResult
3. Open settings for CustomResult
4. Click + button next to Information Elements
5. Application Crashed

**Expected behavior**
User should be able to add Information Elements

**Screenshots**
![image](https://user-images.githubusercontent.com/1843494/185185644-2967fb6a-d7dd-4eae-a9ac-dc6c470bdb6f.png)

**Desktop (please complete the following information):**
 - Windows 10 Version: 21H2
 - Fluent Search Version Alpha 0.9.92.33

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.92.35                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
