### ISSUE TITLE
[Tasks] Pinning Custom Result causes crash

### ISSUE THREAD

**Issue by BaalEvan** [adirh3/Fluent-Search#661]
**Describe the bug**
Pinning more than 1 Custom result causes application Crash

**To Reproduce**
1. Create new TaskProject
2. Add Search
3. Add Custom Result (Pin 1) with pinning enabled
4. Add Custom Result (Pin 2) with pinning enabled
5. Search
6. Pin "Pin 1"
7. Pin "Pin 2"
8. Crash

**Expected behavior**
Both results should be pinned without crash

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 10 Version: 21H2
 - Fluent Search Version alpha 0.9.92.33

**Additional context**
[ReproPin.yaml.txt](https://github.com/adirh3/Fluent-Search/files/9364411/ReproPin.yaml.txt)

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.92.35                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
