### ISSUE TITLE
[Tasks] Adding custom images to CustomResult doesn't work

### ISSUE THREAD

**Issue by BaalEvan** [adirh3/Fluent-Search#662]
**Describe the bug**
Adding customImage via Open window does nothing, adding via drag and drop causes app to hang

**To Reproduce**
https://user-images.githubusercontent.com/1843494/185187560-804e32ca-b7c3-4d67-827d-daeecc69b170.mp4

**Expected behavior**
User should be able to add image

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 10 Version: 21H2
 - Fluent Search Version alpha 0.9.92.33

**Comment by adirh3** [comment]
@BaalEvan thanks a lot for all the detailed feedback! it's much appreciated :)

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.92.35                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by adirh3** [comment]
@BaalEvan can you please go over the fixed issues and close them if they're fixed?
