### ISSUE TITLE
Edge extensions?

### ISSUE THREAD

**Issue by Rhizob** [adirh3/Fluent-Search#663]
Hi,

Is it currently possible to add (edge) extensions to the built-in browser (mobile view or otherwise)?
If not, I think this would be a great addition.

Thanks as always.

**Comment by adirh3** [comment]
@Rhizob unfortunately it's not supported yet by Edge web view.
Leaving here their issue for tracking - https://github.com/MicrosoftEdge/WebView2Feedback/issues/98

**Comment by Rhizob** [comment]
Got it. Thanks Adir. Hopefully they will change this soon.

**Comment by adirh3** [comment]
Closing it for now, tracking the Edge issue.
