### ISSUE TITLE
Web preview not working

### ISSUE THREAD

**Issue by opack** [adirh3/Fluent-Search#666]
**Describe the bug**
I cannot get the web preview to work: the preview panel remains empty and never shows the website result.

When contacted about this issue, @adirh3 suggested that I install [Microsoft WebView2](https://go.microsoft.com/fwlink/p/?LinkId=2124703), but this gave me the following error: _"Installation failed. Microsoft Edge Webview2 Runtime is already installed on your system"_
![image](https://user-images.githubusercontent.com/3687098/185768543-8b8851b0-cea6-40fe-94ac-091459e63691.png)

**To Reproduce**
1. Open Fluent Search Popup
2. Start a search or use any web-related keyword (`web`, `google`...)to search on the web
3. Results displayed suggest that a search on the web will be triggered
4. Press ALT key (or Shift+Enter) to display preview: the preview panel remains empty.

**Expected behavior**
The preview window shows the site similar to what I obtain when I trigger the "Search" (see below) action on a result, which opens the search in my browser.
![image](https://user-images.githubusercontent.com/3687098/185768481-92d4bc72-9291-4b15-b60c-e2e0d71392c2.png)
then I would expect to see the following in the preview panel
![image](https://user-images.githubusercontent.com/3687098/185768572-963a8092-8745-467e-b8e6-c8c35984af5b.png)

**Screenshots**
Fluent Search Settings > Web:
![image](https://user-images.githubusercontent.com/3687098/185768276-6c3c1396-910a-4834-9642-35b1a0529788.png)

Trying to search term "elephant" using default web search tag "google" and then using the ALT key to display preview:
![image](https://user-images.githubusercontent.com/3687098/185768255-ff004e99-cfeb-4818-82d2-3a454a818ffa.png)

**Desktop (please complete the following information):**
 - Windows 10 Version: Windows 10 Professionnel 21H2
 - Fluent Search Version 0.9.91.9995

**Additional context**

**Comment by adirh3** [comment]
@opack can you try uninstalling and reinstalling WebView2? It should show in Windows settings for removing apps

**Comment by opack** [comment]
Here was the current installed version:
![image](https://user-images.githubusercontent.com/3687098/185811704-54f68907-4ed7-48b0-b343-99a9c754a2df.png)
I uninstall it, as instructed.
Then reinstalled (using the link in my first message) and now I have the same version (but reinstalled):
![image](https://user-images.githubusercontent.com/3687098/185811731-f3707472-d352-4948-8ba1-50be82b6b10c.png)

Now, when I search something usin Google:
![image](https://user-images.githubusercontent.com/3687098/185811769-87cc9498-db8d-4f3f-95ee-d6ce58666d7a.png)
YEAH! It works 🥳

I'll reopen this issue if the problem appears again, but for now I'm closing it!

Many thanks @adirh3 , for the solution and even more for this wonderful tool 🤩
