### ISSUE TITLE
Bug in the tags in Settings for 'power users'

### ISSUE THREAD

**Issue by H5820121** [adirh3/Fluent-Search#667]
I noticed now, that in Settings for power users, even though **all the shortcuts for my tags work fine**, I don't see them in the settings view, and as you can see in the screenshot. In the past (I think two months ago) there was not this bug.

![image](https://user-images.githubusercontent.com/105562828/185787707-3c951e2c-83a3-4b5f-b708-258b6ce8e884.png)

My tags are one letter in **Hebrew**.
And **the more significant bug**, that when I define a new shortcut name for a new tag, the shortcut works temporarily, but it is not saved in the 'Power User.json' file, so when I restart the computer, it is not active and does not appear at all in the settings.
Thanks!

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.92.37                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
