### ISSUE TITLE
Search operation pane doesn't show complete file paths

### ISSUE THREAD

**Issue by Chance92** [adirh3/Fluent-Search#67]
**Describe the bug**
The search operation pane has difficulties in showing long file paths.

**To Reproduce**
1. Search for a file with long path
2. (optional) reduce the width of the search operation pane
3. See error

**Expected behavior**
The file path should be correctly wrapped based on the width of the pane. 

**Screenshots**
![image](https://user-images.githubusercontent.com/85488695/120998431-00514700-c780-11eb-9dc4-1835f40c3d3c.png)

**Desktop (please complete the following information):**
 - Windows 10 Version: 20H2
 - Fluent Search Version 0.9.85.20
**Additional context**

**Comment by adirh3** [comment]
This_issue_has_been_potentially_fixed_in_version_

**Comment by Chance92** [comment]
It's definitely improved, but the line break at the first line still looks weird and maybe a bit wasteful.
![image](https://user-images.githubusercontent.com/85488695/121100565-0f70dd00-c7f2-11eb-8236-a1b7c88e4a44.png)

**Comment by Metroid-Prime** [comment]
I'll keep this issue open so @adirh3  has a chance to address Chance92's latest comment.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.85.80

**Comment by Chance92** [comment]
It is fixed indeed. Thank you!
