### ISSUE TITLE
Impossible to add spaces in Arguments for "Default file manager"

### ISSUE THREAD

**Issue by opack** [adirh3/Fluent-Search#671]
**Describe the bug**
In order to add several arguments, I try to add a space after an argument in the input _Arguments_ of the section _Files > Default file manager_.
However, hitting space only shows/hides the section _Open folders in existing file manager window_.

**To Reproduce**
1. Go to _Files > Default file manager_
2. Try to add several arguments, separating them with a space
3. No space is inserted, and the _Open folders in existing file manager window_ section is shown/hidden on each space hit.

**Expected behavior**
A space is inserted in the field.

**Screenshots**
Here I tried to insert a space between `/T` and `"%1"`
![image](https://user-images.githubusercontent.com/3687098/186274568-108753ee-5aa7-4fe8-b132-2520962fde40.png)

**Desktop (please complete the following information):**
- Windows 10 Version: Windows 10 Professionnel 21H2
- Fluent Search Version 0.9.91.9995

**Additional context**
A simple workaround is available, so this is clearly not a critical bug: only edit the string elsewhere and paste it in the field.

_Please, don't hate me for all the issues I create these days 😥_

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.92.37                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by opack** [comment]
Perfect! It works fine, thank you very much! 👍 

However, it's not a big deal, but now I cannot move the Settings window anymore 😅 Do you want me to open another issue?

**Comment by adirh3** [comment]
> Perfect! It works fine, thank you very much! 👍
> 
> However, it's not a big deal, but now I cannot move the Settings window anymore 😅 Do you want me to open another issue?

No need, will be fixed in the next update.
Thanks :)
