### ISSUE TITLE
Text preview wrap does not adapt to pane size

### ISSUE THREAD

**Issue by wordpure** [adirh3/Fluent-Search#676]
**Describe the bug**
Even with word wrap turned on, the text in the preview pane does not automatically adjust to the maximum length of each line as the pane size changes.

**To Reproduce**
1. Turn on 'Setting - Preview - General - Word wrap'
2. Preview text file
3. Zoom out the preview pane
4. Text inside preview pane does not wrap properly

**Expected behavior**
Word wrap can adapt to changes in pane size.

**Screenshots**

![图片](https://user-images.githubusercontent.com/68013962/187640737-a0bd0b71-a439-4dc9-915c-b8c53ba49501.png)

![图片](https://user-images.githubusercontent.com/68013962/187640684-7e2f1944-24ff-4420-b43c-fe5071a9b2ba.png)

**Desktop (please complete the following information):**
 - Windows 11 Version: 21H2
 - Fluent Search Version: 0.9.92.43

**Additional context**

The distance between the text and the two ends of the pane is too tight. Maybe we can appropriately expand the white space on both sides (only the left side when word wrap is not turned on) to obtain a more comfortable reading experience?

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.92.47                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by wordpure** [comment]
Thanks for the fix.

> The distance between the text and the two ends of the pane is too tight. Maybe we can appropriately expand the white space on both sides (only the left side when word wrap is not turned on) to obtain a more comfortable reading experience?

I wonder if you could consider increasing the spacing on both sides of the text?

**Comment by adirh3** [comment]
> Thanks for the fix.
> 
> > The distance between the text and the two ends of the pane is too tight. Maybe we can appropriately expand the white space on both sides (only the left side when word wrap is not turned on) to obtain a more comfortable reading experience?
> 
> I wonder if you could consider increasing the spacing on both sides of the text?

Give horizontal padding? Wouldn't it reduce space for text to read?

**Comment by wordpure** [comment]
> Give horizontal padding? Wouldn't it reduce space for text to read?

What I'm thinking of is to add padding to the left and right sides of the text with a width of about two characters each, so that the text area is better separated from the line numbers or pane edges.

![图片](https://user-images.githubusercontent.com/68013962/192504221-fe983f40-9167-4700-bc31-f7bfb5314b8f.png)

This definitely reduces the readable area of the preview pane, but the size of the search window and preview pane is adjustable, so it doesn't have much of an impact and I think it's worth trading it for an improved reading experience.
