### ISSUE TITLE
Use single setting for theme selection

### ISSUE THREAD

**Issue by Jaap-van-Hengstum** [adirh3/Fluent-Search#68]
Instead of separate settings to select the dark/light theme or to use the system theme:

<img width="583" alt="system-theme" src="https://user-images.githubusercontent.com/1670232/121008478-55e31f00-c793-11eb-88ca-4a880aba9a31.png">

use a single setting "Selected theme" with the options:

- Light
- Dark
- Use system theme

**Comment by Metroid-Prime** [comment]
I understanding the request as the user experience as most apps (including mobile) do it this way and it's the standard. 

However, I could be wrong, but I _believe_ that the "Selected Theme" covers light & dark mode vs "Use System Theme" covers the _colors_ / highlighting of the app.  

Selected theme = light/dark mode
Use system theme = on = use the system's default color     off = trigger to choose a color.

**Comment by Nomad-0** [comment]
I think this one's fixed? @Jaap-van-Hengstum @Metroid-Prime

**Comment by Metroid-Prime** [comment]
@Jaap-van-Hengstum 
Here's what I see and I believe this fulfilled your request?  I am closing this, please validate when you're able
![image](https://user-images.githubusercontent.com/1836362/122631564-562bc600-d081-11eb-907e-3c7bc43424d4.png)
