### ISSUE TITLE
Fluent Search start on somewhere higher in first start

### ISSUE THREAD

**Issue by lvlzyro** [adirh3/Fluent-Search#681]
**Describe the bug**
In every first opening after boot in fluent search starts a little higher than usual.

**To Reproduce**
We figured out it's caused by "Adjust search window height based on the content" setting.

**Expected behavior**
It to open up in same position as usual in every time.

**Screenshots**

how it's supposed to be:
![correct](https://user-images.githubusercontent.com/45663782/190964851-6825cc7c-7154-463c-9902-5b3df609bf57.png)

how it goes:
![broken](https://user-images.githubusercontent.com/45663782/190964915-3a8d706e-efd6-4a73-a644-08e0c09610ee.png)

**Desktop (please complete the following information):**
 - Windows 11 Version: 22H2
 - Fluent Search Version: 0.9.91.9994

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.92.47                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
