### ISSUE TITLE
open powershell inside current folder

### ISSUE THREAD

**Issue by Dahlai** [adirh3/Fluent-Search#689]
I often would like to open a powershell (or command prompt) when navigating with windows explorer. 
Fluent Search has a nice feature to open up a powershell, but it is always in the user's root directory. Would be great if it started with the 'correct' directory being active.

**Comment by adirh3** [comment]
@Dahlai not sure I understand, when you search for any folder you will have an `Open Directory in Command Line`, does it not open the correct folder for you?

**Comment by Dahlai** [comment]
What you suggest works.

What I'd like to achieve, however, is that fluent search would detect that I'm using the file explorer and the current directory that I'm in and then have the option to open the powershell in that specific directory. I'm not sure if that would be within the scope of fluent search, but I hope this makes more sense, now.

**Comment by adirh3** [comment]
@Dahlai good idea, I created a Task (plugin) to do that using a hotkey -
https://raw.githubusercontent.com/adirh3/Fluent-Search-Tasks/main/Utilities/Open%20current%20path%20in%20WT/Open%20current%20folder%20in%20WT.yaml

To use it, download the file, then drag and drop it into the Tasks window (open from system tray).
Let me know what do you think.

**Comment by Dahlai** [comment]
@adirh3 
I tried it, but it doesn't work. For one, I think the `fileName: wt.exe` is likely wrong.
When I exchange it for the path to the powershell.exe it opens it up, but immediately closes it again.

Removing the `arguments: -d "{path}"` line resolves this issue, but then it just opens the powershell without changing to the current directory.

**Comment by Dahlai** [comment]
@adirh3 
thanks for the input, the following did the trick:
```
        fileName: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
        runAsAdmin: false
        arguments: -noexit -command "cd {path}"
```
