### ISSUE TITLE
Clipboard - Delete all entries except the saved ones

### ISSUE THREAD

**Issue by kwanice** [adirh3/Fluent-Search#69]

**Comment by MakeshVineeth** [comment]
Please elaborate the behavior you were expecting as well as provide screenshots if applicable.

**Comment by Metroid-Prime** [comment]
Hi @kwanice   We'll need a lot more details please about the request. Do you want an option for clearing the clipboard history? In the settings in the app itself?  A mockup of the request would be helpful too. Thank you!

**Comment by kwanice** [comment]
i dont need to explain a lot because @adirh3 already know about that

if u do a lot of copy/paste, your clipboard is full, and i dont want to restart FS just to erase all the entries :)

So in the clipboard plugin add a button to erase entries, except the saved one.

**Comment by Metroid-Prime** [comment]
Hi @kwanice , please do let us know the proposed design as there's a group of us tracking all of the issues and trying to help Adir focus his time on the development portion.   

I agree with you there should be a clear history option, but what was your (or Adir's) proposed design?

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.89.35
