### ISSUE TITLE
Search Window Size Isn't Remembered

### ISSUE THREAD

**Issue by Shikamaru30** [adirh3/Fluent-Search#692]
**Describe the bug**
The search window doesn't keep the size I specifically set for it, even though the setting for it to do so is turned on.

**To Reproduce**
1. Go to 'Settings'.
2. Click on 'Appearance'.
3. Scroll down to 'Remember Window Size After Restart'.
4. Restart Computer.
5. As you can see, the search window size wasn't remembered.

**Expected behavior**
I expected it to remember the search window size.

**Screenshots**
Do it for yourself, screenshots doesn't do the issue justice.

**Desktop (please complete the following information):**
 - Windows 11 Version: [e.g. 21H2]
 - Fluent Search Version [e.g. 0.9.92.54]

**Additional context**

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.92.56                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by Shikamaru30** [comment]
> This issue has been potentially fixed in version 0.9.92.56 . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

It works. Thank you.
