### ISSUE TITLE
remove previous tag watermark in search bar

### ISSUE THREAD

**Issue by u-Sir** [adirh3/Fluent-Search#694]
**Is your feature request related to a problem? Please describe.**
Now previous tag watermark will display in search bar, even `always clear tag` is enable. 

repo: 
1. type `image` and press `TAB` 
2. search anything and open it
3. launch FS again (tips shows)

this confused me. every time it shows, i used to wait it disappear and then I type something. 
yes, FS have settings about auto-clear searched tag, but the tips still there and ***distracted*** me.

And this sometimes will make the windows animation ***not smooth and counterintuitive***. 
 animation difference e.g.  
1. without tips:  search bar -> search bar with results
5. Now: search bar with results -> search bar -> type something -> search bar with results

**Describe the solution you'd like**
add an option to disable keeping the last search tag/text, or any option to make the search bar empty in every search, no delete animation, no residual watermark.

![图片](https://user-images.githubusercontent.com/93647031/200257971-c90ec1c9-f4e2-4526-b110-6aa661a15820.png)

https://user-images.githubusercontent.com/93647031/200262502-25ce3f65-ba3d-4741-be67-22c727af3bda.mp4

**Comment by adirh3** [comment]
@u-Sir sorry but I am confused what you mean by tips?
In the video I see the search tag is cleared and everything is back to normal after you opened Fluent Search for the second time.

**Comment by u-Sir** [comment]
> @u-Sir sorry but I am confused what you mean by tips? In the video I see the search tag is cleared and everything is back to normal after you opened Fluent Search for the second time.

you can see the pic. just something like `search in ....`

**Comment by adirh3** [comment]
> > @u-Sir sorry but I am confused what you mean by tips? In the video I see the search tag is cleared and everything is back to normal after you opened Fluent Search for the second time.
> 
> you can see the pic. just something like `search in ....`

In the picture you are using the tag, was it stuck after relaunching?

**Comment by u-Sir** [comment]
> > > @u-Sir sorry but I am confused what you mean by tips? In the video I see the search tag is cleared and everything is back to normal after you opened Fluent Search for the second time.
> > 
> > 
> > you can see the pic. just something like `search in ....`
> 
> In the picture you are using the tag, was it stuck after relaunching?

yes, it remains visible for a split second after relaunching

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.92.59                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
