### ISSUE TITLE
Indexed Paths not being honored.

### ISSUE THREAD

**Issue by Metroid-Prime** [adirh3/Fluent-Search#7]
This is a high priority issue unless I am missing something? 

![image](https://user-images.githubusercontent.com/1836362/120915745-6348be00-c65a-11eb-9d20-4c7b54f758c2.png)

I've got only 1 folder on indexed paths, but it's pulling other paths outside.
![image](https://user-images.githubusercontent.com/1836362/120915773-84a9aa00-c65a-11eb-93ce-ce3cd701f3fb.png)

**Comment by mochigithub** [comment]
I wonder if this is related to issue #53 ?   FS is saying root paths (e.g. C: & D:) are already indexed?  Why? That doesn't make any sense is the user doesn't explicitly tell FS to index them.   There shouldn't be any 'invisible indexing' happening.
![image](https://user-images.githubusercontent.com/1836362/120921107-f263cf00-c676-11eb-8f94-f3e75c3aa0d1.png)

**Comment by adirh3** [comment]
@Metroid-Prime This file is probably showing because you already opened it, it's not related to indexing.
I know this might be a bad UX, but usually a user won't get into this situation (this happened because of many updates)
You can confirm it by clearing your FS settings, and putting the index settings again, if the issue does not happen, change the priority of this please.

**Comment by Metroid-Prime** [comment]
> @Metroid-Prime This file is probably showing because you already opened it, it's not related to indexing.
> I know this might be a bad UX, but usually a user won't get into this situation (this happened because of many updates)
> You can confirm it by clearing your FS settings, and putting the index settings again, if the issue does not happen, change the priority of this please.

@adirh3  can you tell me precisely which FS setting I need to clear? Which file or folder?   I want to use a scalpel  rather than a sledgehammer lol

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.85.45

**Comment by Metroid-Prime** [comment]
@Nomad-0   Can you co-check with this me?  I believe this has been fixed so I'm closing it.
@adirh3  - I'll double check this with the example above on my other home computer as well when I return tonight.

**Comment by Nomad-0** [comment]
yes, I think it's fixed

**Comment by Metroid-Prime** [comment]
So far, so good on 2nd computer that had the issue.
