### ISSUE TITLE
Kill apps that are running as administrator

### ISSUE THREAD

**Issue by Nomad-0** [adirh3/Fluent-Search#70]
**Requested feature**
There are some apps that run as administrator which currently can't be killed with the `Kill Process` plugin. An option to kill those apps would be great.

**Comment by Metroid-Prime** [comment]
Yes, I agree with this.  What should happen I assume is that the system should trigger the UAC window and ask the user to get admin priv to kill the elevated process, but will defer to @adirh3

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.89.35

**Comment by Nomad-0** [comment]
yeah, it's working like a charm, Thank you.
