### ISSUE TITLE
`restart` not work

### ISSUE THREAD

**Issue by u-Sir** [adirh3/Fluent-Search#700]
**Describe the bug**
`restart` machine not work

**To Reproduce**
1. search `restart`  and press `enter`  and `ok` 

**Expected behavior**
restart 

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 11 Version: 22H2
 - Fluent Search Version 0.9.92.58

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.92.60                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
