### ISSUE TITLE
characterstandard form of Chinese is not correct

### ISSUE THREAD

**Issue by liuchanghuaX1** [adirh3/Fluent-Search#702]
The characterstandard form of Chinese is Janense，not Chinese.
![image](https://user-images.githubusercontent.com/40064819/202906723-dd96eaf6-de0b-4e8d-84cd-f1ee449a5267.png)

**Comment by u-Sir** [comment]
用的什么字体？我用的 `Microsoft Yahei UI` 正常
![图片](https://user-images.githubusercontent.com/93647031/202911111-9decaad1-b0cf-49e9-b1b0-96fb7d71ece0.png)

**Comment by liuchanghuaX1** [comment]
> 用的什么字体？我用的 `Microsoft Yahei UI` 正常 ![图片](https://user-images.githubusercontent.com/93647031/202911111-9decaad1-b0cf-49e9-b1b0-96fb7d71ece0.png)
![image](https://user-images.githubusercontent.com/40064819/202943463-cba920de-9792-484a-9cb3-a99f46aa187c.png)


我用的微软雅黑，字形有些简中有些日本字形。
