### ISSUE TITLE
Crash when searching for some specific keywords

### ISSUE THREAD

**Issue by NightWatch0** [adirh3/Fluent-Search#706]
If use everything as an indexer, it will crash when searching for specific keywords.

It crashed when I searched for a particular file, but not after replacing the indexer from everything to Windows or Fluent. Then I changed the indexer back to everything and tried some other keywords and it worked fine, but it crashed whenever I searched for that particular file name. After a while, it suddenly resumed working and stopped crashing. So I can't reproduce the problem consistently, only that the software may crash when searching for certain keywords if using everything as an indexer.

 - Windows 11 Version: [22H2 22621.819]
 - Fluent Search Version [e.g. 0.9.91.9994]

In addition, I found that I could not switch between English and Chinese input in the text box of the software (I am a Chinese user and use Shift to switch between English and Chinese input in the input method). If the settings page of FluentSearch is opened, the search box can only input English forever. Other times, I can only switch from English to Chinese by pressing the shortcut key (Alt+Space) to close the search box and pressing the shortcut key again to open the search box. There is also the problem of changing the font in the settings can not take effect on Chinese.

**Comment by adirh3** [comment]
@NightWatch0 when it crashes can you please open the Event Viewer, then go to Windows category and then Application and you will see two error logs for Fluent Search or ".NET" and send me these twos?

**Comment by NightWatch0** [comment]
[FluentSearch.zip](https://github.com/adirh3/Fluent-Search/files/10061707/FluentSearch.zip)
Here are all the error logs.

**Comment by adirh3** [comment]
@NightWatch0 did you install Fluent Search through the Microsoft Store?
If so, can you please try installing the nightly release from the installer and see if it still crashes - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by NightWatch0** [comment]
@adirh3 Yes, it is from the Microsoft Store. I tried the nightly version and it works fine. I think this bug can be considered solved, if it doesn't recur in the next period.
