### ISSUE TITLE
suggestion: improve indicator animations 

### ISSUE THREAD

**Issue by u-Sir** [adirh3/Fluent-Search#707]
Now fs has two sets of animations on up/down selecting. But display speed is not match, so that make it looks weird. what I suggest is just make it look like the Windows settings do
https://user-images.githubusercontent.com/93647031/202965058-5be0618e-60a0-447b-9167-3dbce23fdbd9.mp4
in this video, up/down only move the border, and the indicator before title only move when I press `enter` or click on it.

**Comment by adirh3** [comment]
@u-Sir you mean in Fluent Search settings or search window?

**Comment by u-Sir** [comment]
> @u-Sir you mean in Fluent Search settings or search window?
all FS windows. 😂
