### ISSUE TITLE
mouse double clicking

### ISSUE THREAD

**Issue by mragtronx8** [adirh3/Fluent-Search#708]
when i search in fs and double click mouse to run/open; double clicking is not working for folders or videos or files.
FS 0.9.92.60 - windows 10 22h2

**Comment by adirh3** [comment]
@mragtronx8 any chance these folders/files don't exist anymore? Does Fluent Search close when you double click?

**Comment by mragtronx8** [comment]
they exist.
No fs doesn't close.
