### ISSUE TITLE
`read file text` error

### ISSUE THREAD

**Issue by u-Sir** [adirh3/Fluent-Search#709]
**Describe the bug**
`read file text` error

**To Reproduce**
1. Go to `tasks`
2. create any trigger
3. create `read file text` block and copy any file path into textbox
4. connect them and trigger it

**Expected behavior**

**Screenshots**
![图片](https://user-images.githubusercontent.com/93647031/203108434-3b8fe942-eff7-4e7e-a915-db0e8349593f.png)

**Desktop (please complete the following information):**
 - Windows 11 Version: 22h2
 - Fluent Search Version 0.9.92.60

**Additional context**

**Comment by adirh3** [comment]
@u-Sir don't escape (the `""`) the path of the file and it should work
