### ISSUE TITLE
`Hotkey search tag mapping` can't select search tag

### ISSUE THREAD

**Issue by u-Sir** [adirh3/Fluent-Search#715]
**Describe the bug**
`Hotkey search tag mapping` can't select search tag

**To Reproduce**
1. go to `super user` -> `Hotkey search tag mapping`
2. click `+`
3. click on drop down button

**Screenshots**
![图片](https://user-images.githubusercontent.com/93647031/203802812-b1f910c7-ad57-4ee8-9bd7-76d1705560a1.png)

**Desktop (please complete the following information):**
 - Windows 11 Version: 22h2
 - Fluent Search Version 0.9.92.60

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.92.61                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
