### ISSUE TITLE
Progressbar causes ugly line

### ISSUE THREAD

**Issue by Jaap-van-Hengstum** [adirh3/Fluent-Search#72]
Turning off "Disable progressbar" in the settings causes an ugly line to appear in the search input:

<img width="662" alt="explorer_4VrPpTKOTy" src="https://user-images.githubusercontent.com/1670232/121050905-4676cc80-c7b9-11eb-9c02-a1aad30b1074.png">

I guess the progress bar background color causes this.

**Comment by adirh3** [comment]
This_issue_has_been_potentially_fixed_in_version_

**Comment by Metroid-Prime** [comment]
@Jaap-van-Hengstum  can you validate that this issue has been fixeD?

**Comment by Jaap-van-Hengstum** [comment]
This issue has been fixed.
