### ISSUE TITLE
can't drag to move in task

### ISSUE THREAD

**Issue by u-Sir** [adirh3/Fluent-Search#726]
**Describe the bug**

**To Reproduce**
1. Go to `tasks`
2. drag 

**Screenshots**
![图片](https://user-images.githubusercontent.com/93647031/205827344-38945c30-947f-4ac9-80b6-7c9e253817c5.png)

**Desktop (please complete the following information):**
 - Window 11 Version: 22h2
 - Fluent Search Version: 0.9.92.63
 - Installation source: Installer 

**Additional context**

**Comment by adirh3** [comment]
Should be fixed in 64

**Comment by u-Sir** [comment]
> Should be fixed in 64

tasks window no response on my side, i can't comfirm🤣
