### ISSUE TITLE
Enter Button [via keyboard] 

### ISSUE THREAD

**Issue by mragtronx8** [adirh3/Fluent-Search#727]
windows 10 22H2 - FS 0.9.92.64
Date: 07-Dec-2022 "updated"

Enter Button [via keyboard] in QM & Search Bar is not responding and not working. 
#BUG

**Comment by adirh3** [comment]
@mragtronx8 does it happen with default settings?
I can't repro this

**Comment by mragtronx8** [comment]
it is happening in my setting. Something is making a conflict.
Dont know what

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.92.66                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
