### ISSUE TITLE
double clicking on task custom result no response

### ISSUE THREAD

**Issue by u-Sir** [adirh3/Fluent-Search#728]
**Describe the bug**
double clicking on task result no response

**To Reproduce**
1. double clicking on task result

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Window 11 Version: 22h2
 - Fluent Search Version: 0.9.92.64
 - Installation source: Installe

**Additional context**

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.92.65                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
