### ISSUE TITLE
implement `Rename` action for files in the search window

### ISSUE THREAD

**Issue by Nomad-0** [adirh3/Fluent-Search#73]
**feature request** 
As we have almost all necessary context menu actions implemented on the FS search window, having an option to rename files among these will be great!

![image](https://user-images.githubusercontent.com/76395594/121063497-34f8e900-c7e8-11eb-89c9-024aaa59c2fc.png)

**Describe alternatives you've considered**
hotkey with `f2` button to rename

**Comment by Metroid-Prime** [comment]
Under issue #21  I also requested custom actions like Listary which would make this possible, but I agree and support this request that rename is a core windows function that's worth having it baked in

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.86.1

**Comment by Nomad-0** [comment]
If I select a file, press `f2` to rename and after renaming, press enter- the file gets deleted!!

**Comment by Nomad-0** [comment]
I found the bug. after renaming, I have to press f2 again. If I press anything else the file either gets opened or deleted. Is it by design?
