### ISSUE TITLE
Allow user to use their own original icons as display icons on Fluent Search

### ISSUE THREAD

**Issue by Shikamaru30** [adirh3/Fluent-Search#730]
**Is your feature request related to a problem? Please describe.**
Yes, I noticed that icons will be blurry or appear upside down when I'm using the app, and I also want Fluent Search to use the same original icons I'm using on my system.

**Describe the solution you'd like**
A setting that allows the user to change the search result icons to whatever we want, just as we can for the search icon.

**Describe alternatives you've considered**
No alternative that I can think of.

**Comment by adirh3** [comment]
What do you mean change icons?
Can you please give an example of a file/app that the icon is blurry or upside down?

**Comment by Shikamaru30** [comment]
> What do you mean change icons? Can you please give an example of a file/app that the icon is blurry or upside down?

![image](https://user-images.githubusercontent.com/82041382/206483839-7d1474ce-30b7-421d-b18c-0e4838b87a18.png)

**Comment by adirh3** [comment]
low res icons are due to browser, you can customize icons in the home screen (nightly) -
![image](https://user-images.githubusercontent.com/27368554/206484275-39cc25e2-bdf2-4db1-b91a-d165ce6df4c9.png)

Can you please send me one of the files with upside down icon?

**Comment by Shikamaru30** [comment]
[01. J Dilla - Donuts (Outro).zip](https://github.com/adirh3/Fluent-Search/files/10186795/01.J.Dilla.-.Donuts.Outro.zip)

**Comment by Shikamaru30** [comment]
> low res icons are due to browser, you can customize icons in the home screen (nightly) - ![image](https://user-images.githubusercontent.com/27368554/206484275-39cc25e2-bdf2-4db1-b91a-d165ce6df4c9.png)
> 
> Can you please send me one of the files with upside down icon?
[01. J Dilla - Donuts (Outro).zip](https://github.com/adirh3/Fluent-Search/files/10186795/01.J.Dilla.-.Donuts.Outro.zip)

**Comment by adirh3** [comment]
Are you using nightly? interestingly it's not upside down for me

**Comment by Shikamaru30** [comment]
> Are you using nightly? interestingly it's not upside down for me

No. I'll try it out.

**Comment by Shikamaru30** [comment]
> Are you using nightly? interestingly it's not upside down for me

Turns out I am using Nightly, yet I'm getting upside down icons for my audio files only.

**Comment by adirh3** [comment]
Can you try changing `Icon resolution` in file settings to High

**Comment by Shikamaru30** [comment]
> Can you try changing `Icon resolution` in file settings to High

It's already on high.

**Comment by adirh3** [comment]
> > Can you try changing `Icon resolution` in file settings to High
> 
> It's already on high.

Ok now I can repro as well lol.
Change to `Normal` and it will be fixed.
I will fix the `High`

**Comment by Shikamaru30** [comment]
> > > Can you try changing `Icon resolution` in file settings to High
> > 
> > 
> > It's already on high.
> 
> Ok now I can repro as well lol. Change to `Normal` and it will be fixed. I will fix the `High`

Ok, thank you. It displays properly again.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 1.0.0.11                                          . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
