### ISSUE TITLE
file manager icon in `processes` is not the same as the one displayed

### ISSUE THREAD

**Issue by u-Sir** [adirh3/Fluent-Search#731]
**Describe the bug**

**To Reproduce**
1. `win + e`
2. launch FS and jump to `processes` tag
3. see the icon

**Expected behavior**

**Screenshots**
![图片](https://user-images.githubusercontent.com/93647031/206626601-0d262456-f817-4100-9190-0aafc9e7b3eb.png)

**Desktop (please complete the following information):**
 - Window 11 Version: 22h2
 - Fluent Search Version: 0.9.92.64
 - Installation source: Installer
 - 
**Additional context**

**Comment by adirh3** [comment]
Can't repro, are you using Windows insider?

**Comment by u-Sir** [comment]
> Can't repro, are you using Windows insider?

no
![图片](https://user-images.githubusercontent.com/93647031/206698320-f34b798d-0bf6-4b4a-bfa8-2d8da94e1d61.png)
