### ISSUE TITLE
网页预览问题和一些其他bug

### ISSUE THREAD

**Issue by pzhren** [adirh3/Fluent-Search#735]
网络预览希望可以对网页版预览（非手机）模式也能进行点击操作，而不是直接打开浏览器。
其次，最好能调用自带浏览器中的插件，不然很多广告无法屏蔽

**Comment by pzhren** [comment]
word文档无法预览

**Comment by adirh3** [comment]
You can change web preview behavior in Settings -> Web.
<img width="538" alt="image" src="https://user-images.githubusercontent.com/27368554/207982423-0ffdfa3e-3aa2-48d8-b490-328e67d37222.png">

Office file preview is not supported yet.
Can you please explain more about what doesn't work with Chinese?

**Comment by pzhren** [comment]
> You can change web preview behavior in Settings -> Web. <img alt="image" width="538" src="https://user-images.githubusercontent.com/27368554/207982423-0ffdfa3e-3aa2-48d8-b490-328e67d37222.png">
> 
> Office file preview is not supported yet. Can you please explain more about what doesn't work with Chinese?
It is hoped that the webpage preview can be directly clicked in the preview window when using the non-mobile terminal mode, which will be very convenient.

Occasionally, you cannot switch to Chinese in the search input box using the built-in input method of windows.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.92.72                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
