### ISSUE TITLE
sometimes selecting animation stuck

### ISSUE THREAD

**Issue by u-Sir** [adirh3/Fluent-Search#736]
**Describe the bug**
sometimes animation stuck

**To Reproduce**
1. click on any result/item (more than 1 times)

here the video, if nothing shows up, please download to play.

https://user-images.githubusercontent.com/93647031/207802439-5da3e86d-b408-4653-ad8f-add33e3e9919.mp4

**Screenshots**
![image](https://user-images.githubusercontent.com/93647031/207801552-382b44a2-2552-499c-8ac5-abd7d816009e.png)

**Desktop (please complete the following information):**
 - Window 11 Version: 22h2
 - Fluent Search Version: 0.9.92.67
 - Installation source: Installer

**Additional context**

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.92.68                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by u-Sir** [comment]
> This issue has been potentially fixed in version 0.9.92.68 . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

still stuck
https://user-images.githubusercontent.com/93647031/208601919-88969663-2d7e-45d7-ab94-617f254ee76c.mp4
