### ISSUE TITLE
can't create/edit block in task

### ISSUE THREAD

**Issue by u-Sir** [adirh3/Fluent-Search#737]
**Describe the bug**
can't create/edit block in task

**To Reproduce**
1. Go to `tasks`
2.  create or edit block

**Desktop (please complete the following information):**
 - Window 11 Version: 22h2
 - Fluent Search Version: 0.9.92.67
 - Installation source: Installer

**Comment by adirh3** [comment]
@u-Sir can't repro this? Just opening any task operation?
