### ISSUE TITLE
switch IME not work in tasks window 

### ISSUE THREAD

**Issue by u-Sir** [adirh3/Fluent-Search#738]
**Describe the bug**
switch IME not work in tasks window , now i use `wubi`

**To Reproduce**
1. Go to `tasks`
2. switch to IME (wubi)
3. type anything by IME in any input box
4. still show in english

**Screenshots**

**Desktop (please complete the following information):**
 - Window 11 Version: 22h2
 - Fluent Search Version: 0.9.92.67
 - Installation source: Installer

**Additional context**

**Comment by adirh3** [comment]
In all text boxes in the Tasks window?
