### ISSUE TITLE
Settings & Taskbar Freezing

### ISSUE THREAD

**Issue by mragtronx8** [adirh3/Fluent-Search#739]
win 10 22h2 - fs .71
With reference to case #733 
settings & taskbar  are still freezing, when accessing settings couple of times and also when changing indexers.

#BUG

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.92.74                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.92.80                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by mragtronx8** [comment]
v.80 26Feb2023
issue still not fixed

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.92.81                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
