### ISSUE TITLE
suggestion: add option to `always clear last results`

### ISSUE THREAD

**Issue by u-Sir** [adirh3/Fluent-Search#749]
**Is your feature request related to a problem? Please describe.**
Now, FS will keep the last searched results, and it increase the unnecessary animation when I just launch FS to search other things.

**Describe the solution you'd like**
add option to `always clear last results`, clear search results after search window closed

**Describe alternatives you've considered**

**Additional context**

**Comment by mretier** [comment]
I would like to see this feature, too. With a recent update this has become especially pressing for me.
Now, when I search for a folder and open said folder through fluent search, the next time I open fluent search it is still stuck in that folder. In turn, I have to press escape, then select all text in the search box, and only then can I start a new search. 

Really not so fluent =/
