### ISSUE TITLE
Registering hotkey: alt key behaves differently from ctrl and shift keys

### ISSUE THREAD

**Issue by Jaap-van-Hengstum** [adirh3/Fluent-Search#75]
**Describe the bug**
When registering a hotkey, the `Alt` key behaves like a modifier key while the `Ctrl` and `Shift` keys do not. For example, you can register `Ctrl+Ctrl` as a hotkey but not `Alt+Alt`. Also when you want to register `Ctrl+Alt` you have to have to hold the `Alt` key while pressing `Ctrl` and it doesn't work the other way around.

**Expected behavior**
The `Alt` key behaving like `Ctrl` and `Shift` and not as a modifier key.

**Comment by adirh3** [comment]
Fixed on latest stable, feel free to reopen if it's still not working for you
