### ISSUE TITLE
FS indexer

### ISSUE THREAD

**Issue by mragtronx8** [adirh3/Fluent-Search#751]
win 10 22h2 - fs .71
- if fs indexer is in selection and i try to stop it. Fs is freezing and doesn't respond anymore.
- if fs indexer is indexing, fs is freezing by itself

The program FluentSearch.exe version 0.9.92.70 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.
 Process ID: 6384
 Start Time: 01d91a0c8a8d17de
 Termination Time: 1821
 Application Path: C:\Program Files\Fluent Search\FluentSearch.exe
 Report Id: eda160d9-801f-494f-83e0-20cec25522ec
 Faulting package full name: 
 Faulting package-relative application ID: 
 Hang type: Unknown

after that i have to kill fs in taskbar.
and sometimes when i reload fs, it hangs/freezes on startup, and i have to end it again in task manager.
#BUG

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.92.74                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by mragtronx8** [comment]
issue still not fixed 07Feb2023

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.92.80                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by mragtronx8** [comment]
v.80 26Feb2023
issue still not fixed

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.92.81                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
