### ISSUE TITLE
result type not work in English when language is Chinese

### ISSUE THREAD

**Issue by u-Sir** [adirh3/Fluent-Search#754]
**Describe the bug**
result type not work in English when language is Chinese. it caused some plugin not work properly in Chinese.
I thought it should be better to keep result types both in English and software language, e.g. `file` - `文件`   in Chinese.

**To Reproduce**
1. set FS language to Chinese
2. install plugin:  `open apps link path` or `open as admin`
3. search any `link` or `exe`
4. there is no operation in right panel

**Desktop (please complete the following information):**
 - Window 11 Version: 22h2
 - Fluent Search Version: 0.9.92.70
 - Installation source: Installer

**Additional context**

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.92.71                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
