### ISSUE TITLE
默认搜索怎么取消Google 没有VPN用不了Google

### ISSUE THREAD

**Issue by baldhead233** [adirh3/Fluent-Search#757]
默认网页搜索怎么取消Google 没有VPN用不了Google
不可能一直打开着VPN
还有调出fluent search 在任务栏还会显示应用图标 
结束之后就没有了
一般的快捷启动在任务栏 之类的几乎都是无痕的

**Comment by u-Sir** [comment]
按下图设置即可
![图片](https://user-images.githubusercontent.com/93647031/211183493-8e18da7a-b71b-4427-a434-31f247674240.png)
![图片](https://user-images.githubusercontent.com/93647031/211183543-6aa5cd37-5163-49b6-8647-acaa3fadc89e.png)

**Comment by baldhead233** [comment]
我翻遍了整个菜单找不到，感谢读者耐心回复
