### ISSUE TITLE
作者可以搞一个黑名单或者快捷键临时禁用启用的功能

### ISSUE THREAD

**Issue by baldhead233** [adirh3/Fluent-Search#759]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by u-Sir** [comment]
![图片](https://user-images.githubusercontent.com/93647031/211187808-6c2ab2fa-30cd-4f07-9817-fee45e8a2311.png)
老哥来 discord 问吧，更方便😉

**Comment by baldhead233** [comment]
好的 我没看到这个超级用户

**Comment by baldhead233** [comment]
这样子搞得我觉得我很呆一样{[(-_-)(-_-)]}zzz

**Comment by baldhead233** [comment]
其实我本来想用这个来替代火柴的,
之前没注意到有这些我的需求早都被实现了 
现在几乎可以替代火柴了(类似的软件)

**Comment by u-Sir** [comment]
> 这样子搞得我觉得我很呆一样{[(-_-)(-_-)]}zzz

啊这，这软件的设置太多了，上手是需要点时间。FS 其实可以直接搜索自己的设置项的，找不到可以先通过关键词搜索下
