### ISSUE TITLE
FS no response sometimes

### ISSUE THREAD

**Issue by u-Sir** [adirh3/Fluent-Search#761]
**Describe the bug**
It happens randomly,
![图片](https://user-images.githubusercontent.com/93647031/211814060-4426d147-7719-4c33-9eda-7215ea1ea815.png)

**Desktop (please complete the following information):**
 - Window 11 Version: 22h2
 - Fluent Search Version:  0.9.92.70
 - Installation source: Installer

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.92.74                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
