### ISSUE TITLE
A search bug

### ISSUE THREAD

**Issue by WilliamK7** [adirh3/Fluent-Search#764]
**Describe the bug**
When I type sth that is not the file name, FS still present some unrelated files or apps for me

**To Reproduce**
1. Type 'anything except the filename'
2. Wait a few seconds
3. See error

**Expected behavior**
FS doesn't present the files

**Screenshots**
https://user-images.githubusercontent.com/82304956/212450369-3de06dff-f9ae-49c4-935a-02c8c6bc05ac.mp4

**Desktop (please complete the following information):**
 - Windows 10 Version: [22H2]
 - Fluent Search Version: [e.g. 0.9.91.9994]
 - Installation source: Microsoft Store

**Additional context**
You can see that the final files that FS presents is the ones that show at the recommended page.
There maybe a relation between them.

This app is really great, it helps me a lot.
Hope to solve the problem soon, thanks.

**Comment by adirh3** [comment]
@WilliamK7 do you use `Zero latency mode` in Settings -> Search?
If so, does it happen if you disable it?

**Comment by WilliamK7** [comment]
I have just tried to disable it.
Unfortunately, it still happens😥

**Comment by adirh3** [comment]
@WilliamK7 can you please check if it happens with clean settings of Fluent Search?
You can check that in two ways by exporting your settings in Settings -> Sync -> Export, then press the Revert all to default button in the top left corner of the Settings window - 
![image](https://user-images.githubusercontent.com/27368554/212653536-83fe5b96-958c-4473-abc8-ad5b6e1eab32.png)

To restore your settings you can import them from Settings -> Sync -> Import.

**Comment by WilliamK7** [comment]
https://user-images.githubusercontent.com/82304956/212654992-ce0b69c9-7979-4764-b369-343d2b77ab51.mp4

This is with the clean settings.
I've only changed the indexer and the language.
BTW, I've been using everything as the indexer. Do I have to use FS's indexer? Anyway, the result looks good in everything.😂

**Comment by WilliamK7** [comment]
aha, I find that using the FS's indexer can solve the problem.😀
But there are a few more questions:
What are the differences between the two indexers?
Does the FS one use a lot of space?

**Comment by WilliamK7** [comment]
There's another small bug now😂

https://user-images.githubusercontent.com/82304956/212661925-31c5ad7c-774d-4ccb-8a7f-ca75dead6979.mp4

You can see that FS only shows the result after I type in the filename and its extension.
But it's not always like that, this bug only fits if the file is like "D:\a\a.txt", aka the filename is the same as its path name.

**Comment by adirh3** [comment]
@WilliamK7 seeing the video with empty settings, it's seems much better isn't it?
The Everything indexer will be less performant than Fluent Search one's, the main reason to pick it is if you're used to Everything's query language or Everything can index something you can't with Fluent Search.
In general, I would suggest using the Fluent Search indexer for better experience.

As for the bug with non-English letters, it should be solved in the Nightly release, you can check that by installing it from the links here - https://github.com/adirh3/fluent-search
The Nightly feed is not available when installed from the Microsoft Store.

**Comment by WilliamK7** [comment]
OK, thank you so much for the help. I really appreciate it.😄
I'll close the issue then.

**Comment by adirh3** [comment]
Feel free to reopen if you encounter this issue with the Nightly release.
