### ISSUE TITLE
Fluent Search (Beta) not responding immediately after installation

### ISSUE THREAD

**Issue by gman414** [adirh3/Fluent-Search#766]
1. Install Fluent Search
2. Upon installation completion, click "OK" on the language selection pop-up
3. A transparent Setup Wizard is presented
4. Setup Wizard becomes unresponsive & the setup cannot be completed ( fails to install indexer service)

Workaround:
5. FS task needs to be killed first from the Task Manager
6. Launch FS
7. Go to Settings and install Indexer( Service)
8.  After this FS is usable. 
 
Desktop Info :

    Window 10 Version: 21H2 (Build 19044.2486)
    Fluent Search Version: 0.9.92.71 Beta
    Installation source: Installer 

![FS01](https://user-images.githubusercontent.com/110206456/213070538-f823443c-524d-4422-a3e1-c3ecb9af6501.jpg)
![FS02](https://user-images.githubusercontent.com/110206456/213070667-8d0c168b-173e-45e9-a6df-8b4d5afcc5dd.jpg)
![FS03](https://user-images.githubusercontent.com/110206456/213070676-e5d1afd8-0ec0-47e1-83e4-5091008dfbdd.jpg)
![FS04](https://user-images.githubusercontent.com/110206456/213070684-b877ebc8-bba1-4932-985c-ac4497986ed3.jpg)
![FS05](https://user-images.githubusercontent.com/110206456/213070693-63f20ccb-20b0-45b1-a936-a2cb04ffe597.jpg)
![FS06](https://user-images.githubusercontent.com/110206456/213070704-89e4278e-1129-451c-a829-29eddc33ac40.jpg)

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.92.74                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
