### ISSUE TITLE
Drag and drop often shows restricted icon (🚫) 

### ISSUE THREAD

**Issue by Nomad-0** [adirh3/Fluent-Search#77]
**Describe the bug**
While trying to drag and drop a file, the cursor turns into a restricted icon inconsistently. Not consistent, but happens more times than a successful try. Confirmed by **Anas** on discord.

**To Reproduce**
try to drag and drop multiple times

**Expected behavior**
Easy drag and drop on a single try

**Screenshots**
![fs drag n drop mp4_snapshot_00 06_ 2021 06 08_08 44 25](https://user-images.githubusercontent.com/76395594/121115919-8f6d6600-c837-11eb-85a7-e11d3486d84b.jpg)
![fs drag n drop mp4_snapshot_00 06_ 2021 06 08_08 44 41](https://user-images.githubusercontent.com/76395594/121115923-92685680-c837-11eb-998e-b284c04279ea.jpg)

**Desktop (please complete the following information):**
 - Windows 10 Version: [21H1]
 - Fluent Search Version [0.9.85.30]

**Additional context**
[Video of the issue](https://discord.com/channels/740636963396124714/740636963836788818/851654045731258408)

**Comment by Metroid-Prime** [comment]
Can confirm.

**Comment by Nomad-0** [comment]
#88 has similar issue confirmed

**Comment by Nomad-0** [comment]
closing as the issue's been fixed.
