### ISSUE TITLE
Escape key should clear search text

### ISSUE THREAD

**Issue by AachoLoya** [adirh3/Fluent-Search#773]
**Is your feature request related to a problem? Please describe.**
There isn't a quick way to clear typed search text

**Describe the solution you'd like**
Pressing Escape key should clear search text and go back to initial screen

**Additional context**
Sometimes I just need to search for something else, but need to use backspace and delete all text manually. Escape key will make the process much faster

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.92.72                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by adirh3** [comment]
Hopefully by March-April.
