### ISSUE TITLE
search bar icon sometimes blank 

### ISSUE THREAD

**Issue by u-Sir** [adirh3/Fluent-Search#774]
**Describe the bug**
search bar icon sometimes blank 

**To Reproduce**
1. just search anything without `TAB`

**Screenshots**
![图片](https://user-images.githubusercontent.com/93647031/215653052-b4aeb877-4420-4d9d-9884-21fb1dfe915b.png)
![图片](https://user-images.githubusercontent.com/93647031/215653210-732dfdba-2095-4b7f-b942-759528bbe615.png)

**Desktop (please complete the following information):**
 - Window 11 Version: 22h2
 - Fluent Search Version: 0.9.92.72
 - Installation source: Installer

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.92.73                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
