### ISSUE TITLE
search item blank after selected

### ISSUE THREAD

**Issue by u-Sir** [adirh3/Fluent-Search#776]
**Describe the bug**
search item blank after selected

**To Reproduce**
1. search anything
2. Click on any results
3. Click on any other esults

**Expected behavior**

https://user-images.githubusercontent.com/93647031/215676819-feae43d7-72b7-4046-97b4-d51b32e06bdf.mp4

**Desktop (please complete the following information):**
 - Window 11 Version: 22h2
 - Fluent Search Version: 0.9.92.72
 - Installation source: Installer 

**Additional context**

**Comment by u-Sir** [comment]
is this the same issue?
![eSearch-2023-01-31-22-20-44-166](https://user-images.githubusercontent.com/93647031/215786138-f6054bec-734d-4462-9a42-4967169140fa.gif)

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.92.73                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
