### ISSUE TITLE
Integration with #ChatGPT 

### ISSUE THREAD

**Issue by hanneman123** [adirh3/Fluent-Search#778]
**Is your feature request related to a problem? Please describe.**
I want to use fluent search as a main search for local and web based queries and it's a hassle to do the same with ChatGPT queries. Having to switch context, open the app / website and then search in the ChatGPT textarea. 

**Describe the solution you'd like**
I would like to use a `#ChatGPT` tag like the other search engines and for it to take my prompt, paste it in the ChatGPT search area and submit. 
I've seen this done for a custom plugin to microsoft powertoys (can link if it's OK to link other projects etc) with a supporting browser extension.

**Describe alternatives you've considered**
I'm using powertoys for other stuff and the custom plugin mentioned above seems like the only option at this time.

**Additional context**
_EDIT:_
I've searched around a bit and it doesn't seem possible to engage with ChatGPT with only query-parameters, that would have been a plug-and-play solution, just adding the url and %s. But alas, it doesn't seem to work.

**Comment by adirh3** [comment]
Doesn't this work? `https://chat.openai.com/chat?PTquery=`? I have seen others do that but can't check since ChatGPT is down

**Comment by hanneman123** [comment]
> Doesn't this work? `https://chat.openai.com/chat?PTquery=`? I have seen others do that but can't check since ChatGPT is down

I cannot seem to get it to work, I tried with both sentences and only one word but nothing happens, I can write prompts in the text-area still and it's up and running for me. I'll look in to it a bit more as well, did not find that `PTQuery` name before so a new deep dive might yield results!

**Comment by adirh3** [comment]
@hanneman123 I made a simple integration with ChatGPT using user login in 0.9.92.91 (nightly) - 
![image](https://user-images.githubusercontent.com/27368554/233846270-8e89fb55-1891-4b9e-8f51-9d572acea862.png)
If you'd like try that out and let me know if you have any feedback.

**Comment by Rhizob** [comment]
> @hanneman123 I made a simple integration with ChatGPT using user login in 0.9.92.91 (nightly) - ![image](https://user-images.githubusercontent.com/27368554/233846270-8e89fb55-1891-4b9e-8f51-9d572acea862.png) If you'd like try that out and let me know if you have any feedback.

Hey Adir,

It kind of works on my end. I added the URL (https://chat.openai.com/chat?PTquery=) to fluent and it brings up gpt, but my search query in the fluent box won't automatically populate in gpt's chat/message box (based on your attached pic, seems like it's working on your end). Please see below:

![gpt](https://github.com/adirh3/Fluent-Search/assets/104737075/ed1f99d9-0e74-4735-b755-b98ccd521937)

Thanks!

**Comment by adirh3** [comment]
> > @hanneman123 I made a simple integration with ChatGPT using user login in 0.9.92.91 (nightly) - ![image](https://user-images.githubusercontent.com/27368554/233846270-8e89fb55-1891-4b9e-8f51-9d572acea862.png) If you'd like try that out and let me know if you have any feedback.
> 
> Hey Adir,
> 
> It kind of works on my end. I added the URL (https://chat.openai.com/chat?PTquery=) to fluent and it brings up gpt, but my search query in the fluent box won't automatically populate in gpt's chat/message box (based on your attached pic, seems like it's working on your end). Please see below:
> 
> ![gpt](https://user-images.githubusercontent.com/104737075/246261345-ed1f99d9-0e74-4735-b755-b98ccd521937.png)
> 
> Thanks!

Sorry somehow missed your message, you need to press enter to write in the chat (I changed that).
Feel free to reopen this if this still doesn't work for you.

**Comment by Michael679089** [comment]
How do you enable this in the stable version of fluent search?

**Comment by adirh3** [comment]
> How do you enable this in the stable version of fluent search?

Write chatgpt then press TAB
