### ISSUE TITLE
How can I build a settings panel like Fluent Search with AvaloniaUI

### ISSUE THREAD

**Issue by zjcscut** [adirh3/Fluent-Search#779]
![216501423-08578f93-dc6e-41a1-af92-aedc3792ad22](https://user-images.githubusercontent.com/13879735/216623800-2413982a-4ea9-4bc6-a6b8-0a00ede3a51a.png)

Is any demo code that could be a reference to create a settings panel like 'Fluent Search' app，or how to refresh the theme and styles immiediately when using AvaloniaUI. THX

**Comment by adirh3** [comment]
I suggest using FluentAvalonia - https://github.com/amwx/FluentAvalonia
The Settings controls in Fluent Search are custom, but FluentAvalonia has sometime similar.

**Comment by zjcscut** [comment]
@adirh3 THX, I will try it
