### ISSUE TITLE
display bug in search results

### ISSUE THREAD

**Issue by u-Sir** [adirh3/Fluent-Search#780]
**Describe the bug**
display bug in search results

**To Reproduce**
1. search anything
2. Scroll down 
3. See error
![图片](https://user-images.githubusercontent.com/93647031/216795587-de43947e-1962-4533-a48e-526ff3200ec4.png)

![eSearch-2023-02-05-08-37-09-276](https://user-images.githubusercontent.com/93647031/216795571-657254c3-b499-4b0d-b868-5527bdd04d0b.gif)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Window 11 Version: 22h2
 - Fluent Search Version: 0.9.92.73
 - Installation source: Installer  

**Additional context**

**Comment by u-Sir** [comment]
this may be the same issue, the last result show over the current
![图片](https://user-images.githubusercontent.com/93647031/216804081-f3742724-7871-4798-83c5-a6e7173aaef2.png)

**Comment by prakharb5** [comment]
Also facing this in nightly 0.9.92.78 😕

![image](https://user-images.githubusercontent.com/51435948/219959381-dd89a679-2f84-447d-b8b4-e86001080a4e.png)
