### ISSUE TITLE
suggestion url can't remove

### ISSUE THREAD

**Issue by u-Sir** [adirh3/Fluent-Search#782]
**Describe the bug**
the text can't delete

**To Reproduce**
settings -> web -> suggestion url

![图片](https://user-images.githubusercontent.com/93647031/216888291-06749079-72c8-4771-b757-9d8b457dfaaa.png)

**Desktop (please complete the following information):**
 - Window 11 Version: 22h2
 - Fluent Search Version: 0.9.92.74
 - Installation source: Installer

**Additional context**

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.92.80                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
