### ISSUE TITLE
recent file in QM not update after file deleted

### ISSUE THREAD

**Issue by u-Sir** [adirh3/Fluent-Search#783]
**Describe the bug**
by the way some translation still not apply in QM
**To Reproduce**
1. QM -> recent files -> delete any file
2. reopen QM -> recent files -> deleted file still show in list
Quick Menu:
![图片](https://user-images.githubusercontent.com/93647031/216891801-77cba5eb-f731-4453-8811-c37b54244fbc.png)
search via search window:
![图片](https://user-images.githubusercontent.com/93647031/216891773-fa29120c-42ff-46c8-96e0-47602ab8b286.png)

**Desktop (please complete the following information):**
 - Window 11 Version: 22h2
 - Installation source: Installer

**Comment by adirh3** [comment]
@u-Sir Windows most likely didn't clean up the recent link in `C:\Users\user_name\AppData\Roaming\Microsoft\Windows\Recent`.
Currently FS does not double check it since it would impact performance, let me know if you can confirm that's the lnk is still there.

**Comment by u-Sir** [comment]
> @u-Sir Windows most likely didn't clean up the recent link in `C:\Users\user_name\AppData\Roaming\Microsoft\Windows\Recent`. Currently FS does not double check it since it would impact performance, let me know if you can confirm that's the lnk is still there.

yeah, the link still there even file deleted.
