### ISSUE TITLE
`capslock + number` to select result

### ISSUE THREAD

**Issue by u-Sir** [adirh3/Fluent-Search#786]
**Is your feature request related to a problem? Please describe.**
when using keyboard navigation, Rectangles characters will change with every search, and it's looks not `Minimalistic` 😂

**Describe the solution you'd like**
`caps lock` is useless in search window so why not use `caps lock + number` to select result 1-10 and use `caps lock + shift  + number` to select result 20-30
for support more results, maybe should provide something like `Rectangles characters` to set custom characters, but the order should never change with every search
use `caps lock + n/p` for page next/previous
when search window is opening, block `Case switch` for `caps lock` key

**Describe alternatives you've considered**

**Additional context**

**Comment by j-maffe** [comment]
I've seen it used as ALT + Number in Flow Launcher and that makes much more sense. A lot of people, including me, have the caps lock mapped to a different key

**Comment by u-Sir** [comment]
> I've seen it used as ALT + Number in Flow Launcher and that makes much more sense. A lot of people, including me, have the caps lock mapped to a different key

it would be better to add option to custom modified key, and work as `custom key + number`
