### ISSUE TITLE
proxy info did not refresh after proxy closed 

### ISSUE THREAD

**Issue by u-Sir** [adirh3/Fluent-Search#787]
**Describe the bug**
proxy info did  not refresh after proxy closed

**To Reproduce**
1. run Fluent search
2. open proxy software( clash for windows), and enable `system proxy`
![图片](https://user-images.githubusercontent.com/93647031/216944854-4a1c8f3a-fbef-439e-ab42-fd405f2b4740.png)
3. restart PC
4. open proxy software( clash for windows) and `disable system proxy`
5. run fluent search 
6. use custom task request url (rss task [rss.zip](https://github.com/adirh3/Fluent-Search/files/10661956/rss.zip))
7. type `verge` and press `TAB` in search windows
8. see error in tasks window. kill fluentsearch.exe and relaunch FS will fix this
![图片](https://user-images.githubusercontent.com/93647031/216943878-4385158c-cd12-46be-be53-1d5d4e1f61a9.png)

**Desktop (please complete the following information):**
 - Window  11 Version: 22h2
 - Fluent Search Version: 0.9.92.74
 - Installation source: Installer

**Additional context**

**Comment by adirh3** [comment]
I believe this is due to XmlDocument using old `WebRequest` class, you will need to refresh manually in your code -
```
WebRequest.DefaultCachePolicy = new RequestCachePolicy(RequestCacheLevel.NoCacheNoStore)
```
Or something like this, I haven't tried it

**Comment by u-Sir** [comment]
> I believe this is due to XmlDocument using old `WebRequest` class, you will need to refresh manually in your code -
> 
> ```
> WebRequest.DefaultCachePolicy = new RequestCachePolicy(RequestCacheLevel.NoCacheNoStore)
> ```
> 
> Or something like this, I haven't tried it

how about use `HTTP Action` to loading first,  then use XmlDocument to pharse?
