### ISSUE TITLE
tasks drawboard keep moving with cursor

### ISSUE THREAD

**Issue by u-Sir** [adirh3/Fluent-Search#788]
**Describe the bug**
tasks drawboard keep moving with cursor

**To Reproduce**
click any block in tasks
![eSearch-2023-02-06-20-07-01-189](https://user-images.githubusercontent.com/93647031/216967785-b7a8ae18-5c7b-42b5-b54e-9d31d91c322e.gif)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Window 11 Version: 22h2
 - Fluent Search Version: 0.9.92.74
 - Installation source: Installer

**Additional context**

**Comment by adirh3** [comment]
@u-Sir I believe this is fixed on >.78, please re-open if not
