### ISSUE TITLE
search bar icon displary wrong

### ISSUE THREAD

**Issue by ltu00** [adirh3/Fluent-Search#79]
**Describe the bug**
search bar icon displary wrong

**To Reproduce**
1. open search bar without type 

**Screenshots**
![image](https://user-images.githubusercontent.com/50564608/121155733-a97c6800-c87a-11eb-8f1f-28ebde30eab0.png)

**Desktop (please complete the following information):**
 - Windows 10 Version: [20H1]
 - Fluent Search Version [0.9.85.30]

**Comment by Nomad-0** [comment]
closing and merging the issue being supposedly duplicate with #78 . Please comment if you think there has been any mistake
