### ISSUE TITLE
App icons are not aligned properly in Home Screen

### ISSUE THREAD

**Issue by prakharb5** [adirh3/Fluent-Search#791]
**Describe the bug**
The icons of pinned apps in home screen are not aligned correctly. This makes it look unpolished and a little messy.

**To Reproduce**
1. Pin some apps
2. See the home screen.

**Expected behavior**
The icons should be vertically centered to look uniform.

**Screenshots**

![image](https://user-images.githubusercontent.com/51435948/217870867-d26d8215-eff2-4cd3-b176-592298083322.png)

**Desktop (please complete the following information):**
 - Window 11 22H2
 - Fluent Search Version: 0.9.91.9994
 - Installation source: Microsoft Store

**Additional context**
-

**Comment by adirh3** [comment]
Thanks @prakharb5 this is fixed in 0.9.92 nightly

**Comment by prakharb5** [comment]
I tried it out, and it already is a lot better! Thanks!
