### ISSUE TITLE
Add option to reset search after a fixed amount of time

### ISSUE THREAD

**Issue by prakharb5** [adirh3/Fluent-Search#792]
**Is your feature request related to a problem? Please describe.**
Currently, you can either choose to keep the search results when closing and opening, or remove them instantly after closing. I want to request an additional option, to reset the results after a fixed time (user-configurable).

**Describe the solution you'd like**
An additional option to choose this setting, and a textbox to enter the amount of time (in seconds)

**Describe alternatives you've considered**
There is no alternative for this currently

**Additional context**

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.92.78                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
