### ISSUE TITLE
FluentSearchV3.db too large

### ISSUE THREAD

**Issue by azhe403** [adirh3/Fluent-Search#793]
**Describe the bug**
.db file very large

**Expected behavior**
keep .db file in healthy size.

**Screenshots**
![image](https://user-images.githubusercontent.com/17938038/218317837-7138a7d5-45a8-470d-8579-fb36267cebab.png)
![image](https://user-images.githubusercontent.com/17938038/218317934-8b08b9a1-2722-49fe-ab96-77931ccb7de1.png)

**Desktop (please complete the following information):**
 - Window 10/11 Version: Windows 11 22H2
 - Fluent Search Version: 0.9.92.73
 - Installation source: Portable

**Additional context**

**Comment by adirh3** [comment]
Can you please screenshot your file settings?
Do you index file content? If so is it filtered to specific files or all files?

**Comment by azhe403** [comment]
oh yes, after disable that, the .db file size back to reasonable size!

![image](https://user-images.githubusercontent.com/17938038/218347695-933f1afe-15f7-40c6-887e-5109c27a1e8c.png)
![image](https://user-images.githubusercontent.com/17938038/218347795-781f4a49-5acd-48f4-af80-8f5de26c36c4.png)

thanks for support sir, I'll close this.
