### ISSUE TITLE
Multiplication not showing properly for RTL languages

### ISSUE THREAD

**Issue by Tamnac** [adirh3/Fluent-Search#794]
**Describe the bug**
Multiplication doesn't display properly for RTL languages. The operator which should be after the asterisk is before.

![image](https://user-images.githubusercontent.com/49466795/219271583-3841f331-8ada-492b-9de1-ccd895abbc87.png)

**To Reproduce**
1. Type in a multiplication problem, like 12*2

**Expected behavior**
Shows up properly, like english 
![image](https://user-images.githubusercontent.com/49466795/219271467-a4a26d86-0b96-405c-906d-77e8ae773827.png)

**Desktop (please complete the following information):**
 - Windows 10 22H2 
 - Fluent Search Version: 0.9.91.9994
 - Installation source: Store

**Additional context**
I tested using Urdu

**Comment by adirh3** [comment]
Thanks @Tamnac, this will be fixed in 0.9.92 (already in the Nightly feed)
