### ISSUE TITLE
screen seach unusable 

### ISSUE THREAD

**Issue by minhe7735** [adirh3/Fluent-Search#798]
**Describe the bug**
double letter tags starts with letters that's already used in single letter tags. So if you try to type the double letter, the single letter one will be clicked.

**To Reproduce**
1. Activate screen search it hotkey

**Screenshots**
![image](https://user-images.githubusercontent.com/61667570/220484598-f69b6b1c-0fd4-4840-85fe-e64427915b67.png)

**Desktop (please complete the following information):**
 - Window 11 Version: [e.g. 20H1]
 - Fluent Search Version: 0.9.92.78

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.92.79                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
