### ISSUE TITLE
When the mouse is set to right-click mode, the screen search function will become right-click when clicked. 鼠标设置成向右键模式时，屏幕搜索功能单击会变成右击

### ISSUE THREAD

**Issue by xaoyao** [adirh3/Fluent-Search#799]
When the mouse is set to right-click mode, the screen search function will become right-click when clicked.
windows鼠标设置成左手模式，屏幕搜索功能的左右键点击会变成相反的
![image](https://user-images.githubusercontent.com/12218604/220865052-5457f411-646d-4aff-b64d-543feef842d3.png)
![screen](https://user-images.githubusercontent.com/12218604/220865109-fedf6c1b-3670-487a-bc4c-6f6afc9ffb5d.gif)

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.92.80                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by Temozly** [comment]
我按下ctrl+m之后，再按4，并没有出现鼠标右键的效果，这个是要怎么设置才会生效的，win11系统
