### ISSUE TITLE
Web Entries disappearing 

### ISSUE THREAD

**Issue by Metroid-Prime** [adirh3/Fluent-Search#8]
***I am still investigating this issue***

Since we've spoke Adir I have repeatedly lost Web entries. This is definitely an issue and is happening repeatedly but not reproducibly.

Web Search entries have been disappearing on Metroid's computer.  Entire "T" section disappeared. 

EDIT: 6/4/21 - now my entire section of ***META*** (4 of them) web searches have disappeared.

**Comment by mochigithub** [comment]
@adirh3  I plan to re-add all of my results, confirm I have them all one by one, back up my web settings and then wait for them to disappear.  I will then copy the corrupted settings and compare them using Beyond Compare and see what the difference is.

**Comment by Metroid-Prime** [comment]
@adirh3  I am closing this temporarily so it doesn't clutter up the open tickets while I investigate which may take 1-2 weeks.

If anyone else is seeing this behavior, please post.
