### ISSUE TITLE
Indexer on network Folder, not working

### ISSUE THREAD

**Issue by kwanice** [adirh3/Fluent-Search#80]
**Describe the bug**
\\xxxxx\xxxx\Videos is not indexed properly, sometimes it's work..sometimes no, very difficult to reproduce exactly 

**Desktop (please complete the following information):**
Win 10 Pro
Build 21390.1

**Comment by adirh3** [comment]
Duplicate with #9

**Comment by Nomad-0** [comment]
closing this as being duplicate with #9 .
