### ISSUE TITLE
Why is there a superposition problem?

### ISSUE THREAD

**Issue by zhl111** [adirh3/Fluent-Search#801]
I turned off transparent mode. Why is this still happening?
![image](https://user-images.githubusercontent.com/29135984/221344159-1b2be8c6-701b-4600-9e9a-3e456bd3f5b3.png)

**Comment by adirh3** [comment]
This is a bug in the nightly version that will be fixed soon

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.92.86                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
