### ISSUE TITLE
set pic as icon not work 

### ISSUE THREAD

**Issue by u-Sir** [adirh3/Fluent-Search#802]
**Describe the bug**
set pic as an icon not work 

**To Reproduce**
if see nothing, please download to play

https://user-images.githubusercontent.com/93647031/221410801-793dceab-1f37-4c81-b71d-8dbe5c860aae.mp4

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Window 11 Version: 22h2
 - Fluent Search Version: 0.9.92.80
 - Installation source: Portable

**Additional context**

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.92.82                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.92.83                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
