### ISSUE TITLE
[Bug] Dark mode has some black text

### ISSUE THREAD

**Issue by ThePython10110** [adirh3/Fluent-Search#803]
**Describe the bug**
In the latest nightly version, in dark mode, some text is black instead of white.

**To Reproduce**
1. Turn on dark mode
2. Several things (including the 2-character window shortcuts and Settings category headings) are black, not white.

**Expected behavior**
All text should change to white, not just some.

**Screenshots**
![image](https://user-images.githubusercontent.com/87204246/222823264-59fca1a4-b7e8-47ec-b9a6-f4bd026151c9.png)
![image](https://user-images.githubusercontent.com/87204246/222823305-4466eea7-0ae3-49bd-b495-e47184ca329d.png)
![image](https://user-images.githubusercontent.com/87204246/222823401-fce59286-9795-4785-ab01-0fbf6db08998.png)
![image](https://user-images.githubusercontent.com/87204246/222823715-cb3052af-3cd1-43b1-96eb-3730f94d148e.png)

**Desktop (please complete the following information):**
 - Windows 10 Pro 22H2
 - Fluent Search Version: 0.9.92.80
 - Installation source: `winget install BlastApps.FluentSearch`, then an upgrade to the latest nightly version

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.92.81                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
