### ISSUE TITLE
Screen search issue with multiple monitors

### ISSUE THREAD

**Issue by YangHanlin** [adirh3/Fluent-Search#804]
**Describe the bug**
In a multi-monitor setup, labels in the screen search feature pointing to UI elements on a screen are incorrectly located on another screen under some circumstances.

**To Reproduce**
1. Set up multiple monitors;
2. Open Fluent Search settings, and ensure `Screen > Search using Screen` is enabled and `Screen > Search using Screen hotkey` is set;
3. Press the hotkey to trigger the screen search feature.
4. As is shown in the screenshot below, labels pointing to UI elements on the first screen wrongly appear on the second screen, and no label appears on the first screen.

**Expected behavior**
Labels pointing to UI elements on each screen are placed correctly next to the UI elements being pointed to.

**Screenshots**

![Screenshot of the 2nd screen, showing some labels are pointing to the 1st screen](https://user-images.githubusercontent.com/8692892/223734512-cfeedd71-2268-4d0e-bd51-11fce6913b55.png)

**Desktop (please complete the following information):**
 - Windows 10/11 Version: Windows 11 22H2 (Build 22621.1344)
 - Fluent Search Version: 0.9.92.49
 - Installation source: Installer, stable channel

**Additional context**
There are currently 2 monitors in my setup, respectively with

- resolution 2500x1600 and a scale of 150%;
- resolution 1920x1080.

The layout of the screens is as follows (if it helps):

![image](https://user-images.githubusercontent.com/8692892/223737843-87769ba3-4224-4c24-85c9-dab20006c02d.png)

**Comment by adirh3** [comment]
That version seems to be old nightly, can you try downloading thr latest nightly and try again?
You can update by changing the release feed to Nightly in Settings or downloading manually from the links in the GitHub read me.

**Comment by YangHanlin** [comment]
> That version seems to be old nightly, can you try downloading thr latest nightly and try again? You can update by changing the release feed to Nightly in Settings or downloading manually from the links in the GitHub read me.

@adirh3 Thanks for your reply! I have downloaded and tried the latest nightly version, and this issue has gone.

However, the labels now show up only on the screen with the active window, and no label appears on the other screen. Is this intentional?

**Comment by adirh3** [comment]
> > That version seems to be old nightly, can you try downloading thr latest nightly and try again? You can update by changing the release feed to Nightly in Settings or downloading manually from the links in the GitHub read me.
> 
> @adirh3 Thanks for your reply! I have downloaded and tried the latest nightly version, and this issue has gone.
> 
> However, the labels now show up only on the screen with the active window, and no label appears on the other screen. Is this intentional?

Glad it was solved, currently screen search is limited to one display due to technical issues.
You can invoke it on the entire screen by setting the `Search using Screen hotkey` in Settings.
