### ISSUE TITLE
[0.9.85.30] `Preview>Toggle preview key>semicolon` doesn't work in French Azerty

### ISSUE THREAD

**Issue by cannibalox** [adirh3/Fluent-Search#81]
**Describe the bug**

[0.9.85.30] `Preview>Toggle preview key>Semicolon` doesn't work with a French Azerty keyboard layout (and probably other non- ansi US layouts)
 `;`  doesn't trigger preview but add a semicolon to the searchterm
![FluentSearch_Fluent_Search_20210608_470_QQyDfIdIK5](https://user-images.githubusercontent.com/4605693/121226210-970a2a80-c88a-11eb-8238-7a7c8a19fa2f.png)

- my physical keyboard is in French ISO layout : 
  - `;` doesn't trigger preview when my keyboard layout is set to FR in windows (also doesn't work with the on-screen keyboard) 
  - it works as expected when I switch to US Qwerty keyboard

**Comment by LarsJandel** [comment]
Ya, tried it on a German keyboard as well with  no success, but the semicolon isn't a good key anyway as it is trigered by `Shift`+`,` [comma]. 
![image](https://user-images.githubusercontent.com/32457827/121230120-20236080-c88f-11eb-8314-a6ae307e0c99.png)

**Comment by Metroid-Prime** [comment]
*please ignore the link to issue eighty-two in the post above.  There is no relation.

**Comment by adirh3** [comment]
@cannibalox since the support for semicolon is removed, I suggest you close this issue for now.
