### ISSUE TITLE
The right panel will still appear after each reboot.

### ISSUE THREAD

**Issue by Tspm1eca** [adirh3/Fluent-Search#819]
**Describe the bug**
After I hide the right panel, it still appears after every reboot.

**To Reproduce**
hide the right panel

**Expected behavior**
Auto hide the right panel every reboot.

**Desktop (please complete the following information):**
 - Window 10 Version: [22H2]
 - Fluent Search Version: [0.9.91.9995]
 - Installation source: Installer

**Comment by adirh3** [comment]
Do you have `Remember window size after restart` enabled?

**Comment by turkishfilms** [comment]
When I hit hide right side panel it just gets little but doesnt go away. I just want it gone so its only a search bar and like 5 results. do i need to enable home?
