### ISSUE TITLE
Link Issue # to GitHub post

### ISSUE THREAD

**Issue by Metroid-Prime** [adirh3/Fluent-Search#82]
Not sure if this can be somehow automated, but it would be great to be able to make the "# number" listed in the changelog a hyperlink that opens to the Github page of that specific issue. 

It would be https://github.com/adirh3/Fluent-Search/issues/** where the ** is the issue number.

For example, the changelog could look like this. The user should be able to click on the number which would load that Github page.   A small gesture, but a big impact for those of us passionately testing FS

Fixed a bug that the search window layout could arrange weirdly [#82](https://github.com/adirh3/Fluent-Search/issues/81)

**Comment by adirh3** [comment]
Update already make my user write that this issue is potentially fixed in the version.
It's not me typing manually.
For last update it I disabled it.

**Comment by Metroid-Prime** [comment]
@adirh3  the way I understand your post. It's already implemented via automated mechanism but was disabled temporarily in the last version?

**Comment by adirh3** [comment]
> @adirh3 If I I understand your post correctly, it's already implemented via automated mechanism but was disabled temporarily in the last version?
> 
> Let me know if that's the case so I can close this ticket.

Yes you can close it

**Comment by Metroid-Prime** [comment]
Closing.  FYI @adirh3  if it's supposed to be in the latest update it wasn't.  If that's expected, no problem.

**Comment by adirh3** [comment]
@Metroid-Prime I think I misunderstood, I meant that new versions will notify all fixed issues that they are potentially fixed.
I will add links to changelogs as well.

**Comment by Metroid-Prime** [comment]
Whoops, I forgot to close this!
