### ISSUE TITLE
QUICK MENU "Firefox BROWSER"

### ISSUE THREAD

**Issue by mragtronx8** [adirh3/Fluent-Search#824]
FS 0.9.92.88 - WIN 10 22H2
# BUG

quick menu list showing unwanted/un-selected files in "firefox" [highlight in red rectangle below]

![image](https://user-images.githubusercontent.com/62798102/228309586-abb1c652-6d86-4d9b-bcb6-95266d1e2f9e.png)

**Comment by adirh3** [comment]
@mragtronx8 I think you have `Search in al results` disabled again in Settings
