### ISSUE TITLE
Having Fluent Search running in the background causes framerate issues with Counter-Strike: Global Offensive

### ISSUE THREAD

**Issue by emilnymann** [adirh3/Fluent-Search#828]
**Describe the bug**
While Fluent Search is running in the background, Counter-Strike: Global Offensive becomes unplayable since it stutters heavily and the framerate drops to 30 every time you move around in the game.

**To Reproduce**
1. Launch Fluent Search
2. Let it run in the background (minimize to tray)
3. Launch Counter-Strike: Global Offensive
4. Join a game
5. Framerate drops with any movement input (WASD) but not with mouse input.

**Expected behavior**
Fluent Search does not affect CS:GO

**Desktop (please complete the following information):**
 - Window 11 Version: 22H2
 - Fluent Search Version: 0.9.91.9994
 - Installation source: Microsoft Store

**Comment by adirh3** [comment]
Hey can you try either and let me know if it helped - 

1. Add CSGO to ignored processes in Settings -> Processes -> `Ignore these processes for in-app content search`
2. Completely disable process search/in-app content search if you're not using it
3. Enable gaming mode from the system tray menu before entering the game

**Comment by vvirtues** [comment]
Can confirm this while playing Apex Legends as well

**Comment by vvirtues** [comment]
can also confirm that pressing the WASD keys while in main menu (CSGO) has a noticable stutter when interacting with animated menu elements

**Comment by vvirtues** [comment]
> Hey can you try either and let me know if it helped -
> 
> 1. Add CSGO to ignored processes in Settings -> Processes -> `Ignore these processes for in-app content search`
> 2. Completely disable process search/in-app content search if you're not using it
> 3. Enable gaming mode from the system tray menu before entering the game

Enabling gaming mode seems to fix it, every other method does not

**Comment by vvirtues** [comment]
![FluentSearch_lk9PokJT0t](https://github.com/adirh3/Fluent-Search/assets/81705406/bc1d844a-d253-4fff-a660-6e4e5d06efed)

**Comment by vvirtues** [comment]
Nightly/gaming mode does the trick, cant wait for it to be pushed

**Comment by adirh3** [comment]
This is now in the stable build, closing.
Feel free to reopen if you're still experiencing this issue when enabling `Ignore hotkey on full screen processes`.
