### ISSUE TITLE
Search shows on the left monitor instean of the main monitor

### ISSUE THREAD

**Issue by Pietro228** [adirh3/Fluent-Search#830]
**Describe the bug**
My monitors turned themselves off (power saving - PC is running and after 15 minutes the monitors turn off). When I came back to my PC and my monitros turned on I wanted to search something but the window for search is not on the main screen, but it's on the left monitor. I have to restart the app to make it appear on the main monitor.

**To Reproduce**
1. Turn off monitors
2. Turn on monitors
3. Try to search something
4. Window is displayed on a wrong monitor

**Expected behavior**
Search window should open on the main monitor as expected. The search window should set it's position everytime before it's shown, not only on startup.

**Screenshots**
![obrazek](https://user-images.githubusercontent.com/53868994/230792948-254a67a5-8cf7-4e49-a9ae-639485d0a7f0.png)
After restarting the app:
![obrazek](https://user-images.githubusercontent.com/53868994/230792994-fdee248b-b9ba-4a68-8122-750b7aaad52d.png)

**Desktop (please complete the following information):**
 - Window 11 Version: 22H2 22621
 - Fluent Search Version: 09.91.9994
 - Installation source: Microsoft Store

**Additional context**
None.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.92.997                                        . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
