### ISSUE TITLE
quicklook support

### ISSUE THREAD

**Issue by Raynbda** [adirh3/Fluent-Search#832]
id like quick look support for fluent search i know it already has a preview feature but the preview is too small

**Comment by adirh3** [comment]
Quick Look is already supported, you can use it by changing `Preview provider` to `Quick Look` in Settings -> Preview

**Comment by Raynbda** [comment]
am i supposed to press the space bar on a fluent search result and it pops up because if that's the case when i press the spacebar it registers in the searchbar
