### ISSUE TITLE
FS's window does not contract when text is deleted (minimal interface)

### ISSUE THREAD

**Issue by Metroid-Prime** [adirh3/Fluent-Search#84]
v0.9.85.35 

When I type text, and then delete it, I see this:
![image](https://user-images.githubusercontent.com/1836362/121296239-2b818680-c8a5-11eb-8b2d-ea8be7c35103.png)

What should happen is window should contract  back to minimal bar interface

**Comment by Metroid-Prime** [comment]
This issue has been confirmed.  Deleting text after searching for something shows "Nothing to show" in the result bar

**Comment by adirh3** [comment]
@Metroid-Prime This has been fixed in 0.9.40.0

**Comment by Nomad-0** [comment]
yes, fixed on my end

**Comment by Metroid-Prime** [comment]
> @Metroid-Prime This has been fixed in 0.9.85.40

Confirming fix & closing. TY!
