### ISSUE TITLE
click custom color caused FS crash

### ISSUE THREAD

**Issue by u-Sir** [adirh3/Fluent-Search#841]
![image](https://github.com/adirh3/Fluent-Search/assets/93647031/70700d17-c5da-4725-a878-a599c989ad54)
![image](https://github.com/adirh3/Fluent-Search/assets/93647031/51e76791-2360-42e4-8ffb-ee9f60b469fb)

**Desktop (please complete the following information):**
 - Window 11 Version: 22h2
 - Fluent Search Version: 0.9.92.95
 - Installation source: Installer

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.92.97                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
