### ISSUE TITLE
Allow for C-n C-p

### ISSUE THREAD

**Issue by mohamed-aziz** [adirh3/Fluent-Search#843]
Hi there,
I want to be able to move between items in the menu using Control-n and Control-p.
I'm sure alot of people want this feature, it's default readline keycombo, also default for emacs users.

Cheers,
Aziz

**Comment by adirh3** [comment]
You can set that in Settings -> Search 
![image](https://github.com/adirh3/Fluent-Search/assets/27368554/86dd933c-2cc1-4cf0-be0c-5a4773916942)


If you use Process Search, it has default shortcut for opening new instance as `Ctrl+N` so you might want to disable it -
![image](https://github.com/adirh3/Fluent-Search/assets/27368554/21f3c836-e28e-4828-b4bf-ffaef7f86450)

**Comment by deadcombo** [comment]
These are my bindings, they work fine.
