### ISSUE TITLE
When using Fluent Search, edge is often unresponsive

### ISSUE THREAD

**Issue by chenmodcm** [adirh3/Fluent-Search#848]
**Describe the bug**
Edge is often unresponsive when the Fluent Search application is opened, and edge is normal when the Fluent Search application is closed

**To Reproduce**
1. open edge
2. Open Fluent Search
3. to operate the edge
4. edge not responding
5. Close Fluent Search
6. edge no longer appears unresponsive

**Expected behavior**
Edge no longer becomes unresponsive when using Fluent Search

**Screenshots**
![image](https://github.com/adirh3/Fluent-Search/assets/104850646/f5241b02-0835-4017-96c2-4acb8df9696c)

**Desktop (please complete the following information):**
 - Window 10 Version: 22H2
 - Fluent Search Version: 0.9.92.99
 - Installation source: Installer

**Comment by never-for-ever** [comment]
Fluent Search will also affect the operation of Tekla. When Fluent Search is running, Tekla 2017 is particularly prone to crashes and shows an impact on mshtml.dll in the windows system event manager.

Window 10 Version: 22H2
Fluent Search Version: 0.9.92.99 
Installation source: Installer

**Comment by adirh3** [comment]
@never-for-ever @chenmodcm can you please try disabling in app content search in Settings -> Processes, or add these apps to the ignore list below it?
(Disabling Process Search should also work)

**Comment by chenmodcm** [comment]
I turned off the content search and edge is no longer unresponsive, thanks
