### ISSUE TITLE
Expand search settings function to include names of setting panes/plugins

### ISSUE THREAD

**Issue by Metroid-Prime** [adirh3/Fluent-Search#85]
![image](https://user-images.githubusercontent.com/1836362/121298603-02fb8b80-c8a9-11eb-9341-5124d63f390f.png)

**Comment by Metroid-Prime** [comment]
@Nomad-0  @adirh3  I guess a general question I should pose out there is _how_ aggressive do we want Fluent Search's settings to be?

1. Should it search alt text?
2.  Should it search the name of the panes
3. Should it search in plugin section?

**Comment by Nomad-0** [comment]
I think we should focus on this After Adir improves the texts and names of the settings as I guess he plans to do so

**Comment by Metroid-Prime** [comment]
> I think we should focus on this After Adir improves the texts and names of the settings as I guess he plans to do so

Excellent point.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.85.45

**Comment by Metroid-Prime** [comment]
> This issue has been potentially fixed in version 0.9.85.45

Feature confirmed in x.45 version. Closing
