### ISSUE TITLE
Fluent Search does not remember network drive indexing setting

### ISSUE THREAD

**Issue by Drakemoor** [adirh3/Fluent-Search#854]
**Describe the bug**
Starting/restarting Fluent Search resets the network drive indexing setting.

In `Settings → Files` under `Paths and indexing → Indexed paths`, the indexing of my mounted network drives is turned off. I turn it on every time, but if I close FS and restart it, the toggle is off again. So, FS has to reindex them again.
The drives are mounted and have their own letters.
This issue always occurs, not only after system restart, meaning it happens even if I restart FS in a middle of a working session. 

**To Reproduce**
1. Start FS as usual
2. Go to `Settings → Files` under `Paths and indexing → Indexed paths` and make sure the network drives indexing is on
3. Wait until the drives indexing finish
4. Exit FS
5. Start FS again
6. Go to the same setting
7. The network drives indexing toggle is off

**Expected behavior**
I expect the indexing feature to stay on after I turn it on. I expect it to be turned off only when I explicitly turn it off.

**Screenshots**
![Clipboard Image](https://github.com/adirh3/Fluent-Search/assets/93224920/c789402e-9022-4bd1-93ec-033ae31785db)

**Desktop (please complete the following information):**
 - Window 10 Home Version: 22H2
 - Fluent Search Version: 0.9.91.9995
 - Installation source: Installer

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.92.997                                        . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
