### ISSUE TITLE
setup guide auto detect supported language  and hidpi support 

### ISSUE THREAD

**Issue by u-Sir** [adirh3/Fluent-Search#855]
setup guide auto detect supported language  and add hi-dpi support 
![image](https://github.com/adirh3/Fluent-Search/assets/93647031/95aeb173-d998-4185-820b-788bca4dcfd0)

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.92.991                                        . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
