### ISSUE TITLE
TortoiseGit unresponsive while FluentSearch is running

### ISSUE THREAD

**Issue by JVimes** [adirh3/Fluent-Search#857]
**Describe the bug**

While FluentSearch is running, [TortoiseGit ](https://tortoisegit.org/) takes around 3-10 sec to become responsive when doing certain operations (often opening or closing a window).

**To Reproduce**

1. Install TortoiseGit
2. In Windows Explorer, right click a repo folder > TortoiseGit > Git Show log
3. Try any of: 
    - Click the branch name in the upper left
    - Close log window
    - Other things, often involving opening/closing TortoiseGit windows

**Expected behavior**
TortoiseGit is not unresponsive while FluentSearch is running.

**Desktop (please complete the following information):**
 - Window 10/11 Version: Windows 10 22H2 (OS Build 19045.3155)
 - Fluent Search Version: 0.9.91.0
 - Installation source: Microsoft Store

**Comment by JVimes** [comment]
The repro seems to happen more on some repos and not others. I wish I could post the repo I have that shows it the most (lags the most), but it's for work.

**Comment by adirh3** [comment]
@JVimes please try disabling process search or in app content search in Settings -> Processes, or if you use these add this app to the ignore list.

**Comment by JVimes** [comment]
Thank you much. Adding `TortoiseGitProc` to the ignore list fixed it.

Do some apps just not play well with process search?

**Comment by adirh3** [comment]
> Thank you much. Adding `TortoiseGitProc` to the ignore list fixed it.
> 
> Do some apps just not play well with process search?

Glad it helped.
Yes Fluent Search uses Windows accessibility feature to do in app content search and some apps do not have good accessibility support.

**Comment by JVimes** [comment]
Maybe a timeout would work as a failsafe? I'm assuming my unresponsive app caused an API call to not return for a long time since my window was totally frozen.

**Comment by adirh3** [comment]
> Maybe a timeout would work as a failsafe? I'm assuming my unresponsive app caused an API call to not return for a long time since my window was totally frozen.

I wish I could detect it, it's not even about timeout it's just Fluent Search call the accessibility api once, and since the software implementation does not handle it efficiently it may stuck in some cases.
If I was able to detect it I would've ignored the software automatically.

**Comment by JVimes** [comment]
Ah, gotcha. I think TortoiseGitProc is a safe candidate for default exclusion in the app, should you decide. Thank you again!
