### ISSUE TITLE
The input method cannot be switched from English to Chinese within the input box of FS（在FS的输入框内无法将输入法从英文切换为中文）

### ISSUE THREAD

**Issue by Elisise** [adirh3/Fluent-Search#858]
**Describe the bug**
When I use the shortcut key to invoke the search box of Fluent Search (FS), my input method is in English mode. Then I press the Shift key to switch the input method to Chinese mode, but pressing the Shift key does not work, and the input method remains in English mode.

This issue sometimes occurs and sometimes does not.

I am using the default input method software provided by the Windows operating system.

**Desktop**:
- Windows 11 Professional 22H2
- Fluent Search Version: 0.9.91.9995
- Installation source: Portable / Microsoft Store (I have installed and used both versions of the software, and the issue exists in both versions.)

**Comment by adirh3** [comment]
@Elisise can you please update to 0.9.92 (just released0 and see if it still happens?
