### ISSUE TITLE
Can't set acrylic correctly.

### ISSUE THREAD

**Issue by cccpism** [adirh3/Fluent-Search#859]
**Describe the bug**
When I set the transparency effect to Alex and restart, it will become transparent again.

**To Reproduce**
1. set transparency effect as “acrylic”
2. restart

**Desktop (please complete the following information):**
 - Window 11 Version: 23H2 22631.2048
 - Fluent Search Version:  0.9.92.996
 - Installation source: Installer

**Comment by adirh3** [comment]
Do you have Use GPU enabled in Settings -> System?

**Comment by cccpism** [comment]
> Do you have Use GPU enabled in Settings -> System?
you mean in fluent search settings? if so, I have

**Comment by nevara** [comment]
Can confirm on at least 2 of my machines

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.92.997                                        . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
