### ISSUE TITLE
Show most recent used files/folder when main search wiindows of fluent search is invoked

### ISSUE THREAD

**Issue by edenexposito** [adirh3/Fluent-Search#86]
One of the most interesting utilities for a file browser is always to quickly display what the user will need. In fact you search because you need to find .... and what you are most likely to want to use is the last thing the user has used...
It would be great if when you invoke "Fluent Search" the result window, before starting to search for anything, would already show a list of the last files and folders that the user has modified.

**Comment by Metroid-Prime** [comment]
We don't want this in **minimal mode**

**Comment by Nomad-0** [comment]
Agree with Metroid Prime. When the search window was an actual window, we literally demanded from the dev to give a "Search bar only" view.

**Comment by Metroid-Prime** [comment]
> Agree with Metroid Prime. When the search window was an actual window, we literally demanded from the dev to give a "Search bar only" view.

Yep.  The idea is that we want to make Fluent Search a power user's tool, but not to alienate the basic user as well. That's where minimal mode comes in. Alfred is masterful at doing this -- easy for general user, but very powerful when configured especially with workflows.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.92.23                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.92.24                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
