### ISSUE TITLE
Quick menu bug: Freeze when hover to "Customize result"

### ISSUE THREAD

**Issue by khanhtoan529** [adirh3/Fluent-Search#861]
**Describe the bug**
As the title

**To Reproduce**
1. Open Quick Menu
2. Right-click on any result under 'Recent Files' and 'Recent Processes'
3. Hover to 'Customize result'
4. See error: FS freeze for a while

**Expected behavior**
Be able to customize the result

**Screenshots**
<img width="321" alt="image" src="https://github.com/adirh3/Fluent-Search/assets/94975142/cc96215d-52dc-4b9b-803a-32245bc6e739">

**Desktop (please complete the following information):**
 - Window 11 Version: 22H2
 - Fluent Search Version: 0.9.92.996
 - Installation source: Appx

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.92.997                                        . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
