### ISSUE TITLE
UAC prompt on windows start-up

### ISSUE THREAD

**Issue by onlytanmoy** [adirh3/Fluent-Search#862]
Hi @adirh3 hope you are doing well.
This is not a bug really but more of an usability issue.
I have set Fluent Search to start automatically on my windows boot, but recently started getting the pesky UAC pop-up on every boot (attached image) where I have to press Yes.
I am using the latest version of Fluent in my Win 11 machine.
FluentSearch.FileIndexer in services.msc is setup as start type=automatic
Please let me know how to get rid of this without having to change my current UAC setting?
![image](https://github.com/adirh3/Fluent-Search/assets/48493659/5dd32900-c765-4bfe-82b3-9917f3c37e39)

**Comment by adirh3** [comment]
@onlytanmoy can you open Services and right click FluentSearch.FileIndexer -> Properties, and check if startup is set to Auto?

**Comment by onlytanmoy** [comment]
Yes, it is as I already mentioned in my initial post
> FluentSearch.FileIndexer in services.msc is setup as start type=automatic

**Comment by adirh3** [comment]
Sorry missed it, can you screenshot the properties of the FluentSearch.FileIndexer service?
Specifically the full path

**Comment by onlytanmoy** [comment]
Here you go mate
![image](https://github.com/adirh3/Fluent-Search/assets/48493659/89f8be4e-26ea-476e-a53c-62168c33a87e)
Path to executable: C:\ProgramData\Fluent Search\IndexerData\Blast.Service.exe --indexer --run "C:\ProgramData\Fluent Search\IndexerData" "Appx"

**Comment by adirh3** [comment]
@onlytanmoy thanks! Will fix that in an update tomorrow

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.92.997                                        . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by onlytanmoy** [comment]
Thanks, I will wait for this version to be made available in MS Store and then update from there, no rush.

**Comment by adirh3** [comment]
> Thanks, I will wait for this version to be made available in MS Store and then update from there, no rush.

Weren't you using the APPX version?

**Comment by onlytanmoy** [comment]
Yeah so it seems since when I search for the app in MS Store I can see 'Install' button enabled :)
If I install this new exe will it update my existing version and retain the settings?
![image](https://github.com/adirh3/Fluent-Search/assets/48493659/7b54cd3b-e3aa-45e2-8c57-bae4d34e2794)

**Comment by adirh3** [comment]
> Yeah so it seems since when I search for the app in MS Store I can see 'Install' button enabled :) If I install this new exe will it update my existing version and retain the settings? ![image](https://user-images.githubusercontent.com/48493659/255675003-7b54cd3b-e3aa-45e2-8c57-bae4d34e2794.png)

You didn't receive an update? Try clicking check for updates in the system tray menu

**Comment by onlytanmoy** [comment]
No, I am still on v 0.9.92.996, I am getting below message when checked for updates
![image](https://github.com/adirh3/Fluent-Search/assets/48493659/b88e6575-91e6-4605-a2b6-315fbd2851f7)

**Comment by adirh3** [comment]
> No, I am still on v 0.9.92.996, I am getting below message when checked for updates ![image](https://user-images.githubusercontent.com/48493659/255686366-b88e6575-91e6-4605-a2b6-315fbd2851f7.png)

Something is wrong with Appx updater.
I suggest you to install the EXE version from https://fluentsearch.net as I plan to stop updating the Appx.
You can export and import settings from Settings -> Sync.

**Comment by onlytanmoy** [comment]
Many thanks mate, I am now on the latest v0.9.92.998 after installing the exe and more importantly no longer getting that nagging UAC pop up following the reboot of my laptop :)
