### ISSUE TITLE
Run apps elevated with Ctrl+Shift+Enter

### ISSUE THREAD

**Issue by JVimes** [adirh3/Fluent-Search#863]
**Describe the solution you'd like**

Ctrl+Shift+Enter launches currently highlighted app as Elevated in Start search. Suggest doing that in Fluent Search, too.

**Comment by adirh3** [comment]
Hey you can change the shortcut for opening as admin in Settings (Toggle advanced) -> Apps -> Open as admin key gesture.
I will also change the default to Ctrl+Shift+Enter if it's not already is.

**Comment by JVimes** [comment]
Sweet 🙂 It worked. I think it'll be a good default. Thank you!
