### ISSUE TITLE
Default folder icon changes

### ISSUE THREAD

**Issue by displayerror** [adirh3/Fluent-Search#865]
Hello,
All my Default folder icons are changing randomly.
I pinned a bunch of folders to my Home Screen (from the suggestions box) and all the folders contain a desktop.ini with assigned icon e.g.
```
[.ShellClassInfo]
IconResource=C:\folder\name.ico,0
```
But all appeared as the OS Default yellow folder (the exception being the shell Music folder, it appeared with the FS Music note icon).

So I decided to add all the folder icons manually via FS Customize Result. 
That's when I noticed that on restarts the Default folder icon would shift around. Any non-assigned folders would randomly inherit custom icons:
![230729_FluentSearch_97ed3](https://github.com/adirh3/Fluent-Search/assets/7947310/ee480c8b-9fb3-4705-8884-48976ab73926)

With every restart of FS the Default folder changes. Could be Blue, next time Orange, ColorWheel... I can't see a pattern to it: 
![230729_fliuentsearch](https://github.com/adirh3/Fluent-Search/assets/7947310/2be7730f-f34d-4951-b692-fc70eaf9f205)

After a few restarts FS will decide to 'lock in' an icon and will always use that as the Default folder even after restarts:
I tried 'flushing' the problem icon by changing it (the ColorWheel) to a Smiley icon, and restarting FS but it's still somehow reading/using the ColorWheel for Default folders:
![230729_FluentSearch_85b49](https://github.com/adirh3/Fluent-Search/assets/7947310/6fb29b05-5270-473d-befd-63c83f824c99)

![230729_FluentSearch_5c406](https://github.com/adirh3/Fluent-Search/assets/7947310/87698b89-b2b5-454a-a159-5befbf1e747a)

I've cleared Windows Thumbnail Cache and Refreshed Icons, rebooted... and it's not helped it. One time I disabled the 'Show Home screen' toggle, and the Default folders returned to OS default! But next restart it stopped working and chose another random icon.
The only thing that seems to restore it is deleting System.json.

I've repeated this process a few times now from a blank config and it seems to break whenever I start adding icons with Customize Result.
Not sure what else to try!
Thanks for any suggestions

- Window 10x64 [21H2]
- Fluent Search Version: [0.9.92.998]
- Installation source: Installer

**Comment by adirh3** [comment]
@displayerror thank you for the detailed issue.
There is a bug that for folders specifically Fluent Search will use the first icon it loaded from Windows, this was due to performance consideration (as loading icon is pricey and most folders have the same icon).
I will change that in an upcoming version and will update here.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 1.0.0.11                                          . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
