### ISSUE TITLE
Add support for custom Everything instances (File Search)

### ISSUE THREAD

**Issue by vvirtues** [adirh3/Fluent-Search#866]
**Is your feature request related to a problem? Please describe.**
I use Everything Alpha (1.5a) but FS does not recognize it as an indexer. I realized that this is because it uses its own instance name to differentiate from another instance (instance name `1.5a`). If you add support for custom instances, not only can users use a custom everything instance for FS but also add support for 1.5a, since FS doesnt detect the alpha

**Describe the solution you'd like**
Add support for custom instances/instance names for FS when using `Everything` as the file indexer

**Describe alternatives you've considered**
Switching to normal Everything installation 

**Additional context**
At first I had no idea how to solve the problem of incompatibility with everything-alpha, but I noticed this line in a different program's README (https://github.com/srwi/EverythingToolbar) that mentioned that if you were using the alpha, you had to set a custom instance name for the toolbar to work

**Comment by vvirtues** [comment]
![msedge_dk6mzYNOSA](https://github.com/adirh3/Fluent-Search/assets/81705406/35e6f225-0d12-4ea5-9369-1dadcef96eff)

**Comment by adirh3** [comment]
To use Everything 1.5 with Fluent Search do the following -

1. Completely exit Everything (File -> Exit) and Fluent Search
2 .Open your Everything.ini in the same location as your Everything.exe
3. Change the following line:
alpha_instance=1
to:
alpha_instance=0
4, Save changes and restart Everything

**Comment by vvirtues** [comment]
> To use Everything 1.5 with Fluent Search do the following -
> 
> 1. Completely exit Everything (File -> Exit) and Fluent Search
>    2 .Open your Everything.ini in the same location as your Everything.exe
> 2. Change the following line:
>    alpha_instance=1
>    to:
>    alpha_instance=0
>    4, Save changes and restart Everything

Thank you, but the `Everything.ini` file is actually supposed to be `Everything-1.5a.ini`

**Comment by pzhren** [comment]
Use everything as the index, but the search results are inconsistent with everything, what if some of them are not searched.
