### ISSUE TITLE
Web search on multiple URLs at once

### ISSUE THREAD

**Issue by DRYN07** [adirh3/Fluent-Search#869]
Is it possible to search on multiple URLs at once with the Web search tags (or a plugin)?

I would like to add multiple websites to search the same query or just open their homepages

In Keypirinha Launcher, it looks like this:

[site/My Multi Search]
url = 
    https://www.google.com/search?q=%s
    https://duckduckgo.com/?q=%s
    https://www.startpage.com/sp/search?query=%s

[site/My Search on News Sites]
url = 
    https://www.news_1.com/search?q=%s
    https://news_2.com/?q=%s
    https://www.news_3.com/search?query=%s

So when I trigger the "My Multi Search" + "my keyword", it opens up every defined site with my search query. If a keyword (%s) is not specified, it opens the homepage.

**Comment by adirh3** [comment]
Hey, you can do that by specifying all URLs separated by space -
![image](https://github.com/adirh3/Fluent-Search/assets/27368554/491587b6-e87f-452b-9eda-2375334192aa)

**Comment by DRYN07** [comment]
Hmmm then maybe I am doing something wrong or just a misunderstanding.

There is for example this. If I understand correctly, it should open google and bing search too, right? 
![image](https://github.com/adirh3/Fluent-Search/assets/29770761/73cffef5-1236-48e3-86cb-a97603166d57)

But for me, it just pastes the second URL in the first URL's search bar :/ 
![image](https://github.com/adirh3/Fluent-Search/assets/29770761/d825cd30-746d-4142-bb6c-e308e0318b25)

**Comment by adirh3** [comment]
@DRYN07 sorry for the delay, can you please double check there is no extra space between the URLs?
If it still happens, can you check if it happens for you in 1.0.x (beta)?

**Comment by DRYN07** [comment]
I use the beta and it is working well now :))
