### ISSUE TITLE
Change screen search methods from hotkey

### ISSUE THREAD

**Issue by Frederik-Frydenberg** [adirh3/Fluent-Search#872]
**Is your feature request related to a problem? Please describe.**
Sometimes the screen search image recognition fails to pick up items. Changing it to use UI search items will often pick them off. 

**Describe the solution you'd like**
A method for swapping, or combining, the two search engines, without having to open the fluent search settings. Could be a hotkey that swaps engine while screen search overlay is active. 

Example:
This is a github issue with two links to other issue.
![image](https://github.com/adirh3/Fluent-Search/assets/67787560/629b4bcf-f780-4da1-bc92-4d6ae6fd97d0)

Fluent search screen search image recognition fails to pick up the issue link that is not at the start of the text:
![image](https://github.com/adirh3/Fluent-Search/assets/67787560/4f645ee8-3a29-43cb-aa5b-0bdb49dd728b)

Using the Search UI engine works:
![image](https://github.com/adirh3/Fluent-Search/assets/67787560/2cdd0b43-2681-4db3-a10c-dea6efaa7e80)

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 1.0.0.11                                          . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
