### ISSUE TITLE
Child settings hide on mouse click without any indication of it being hidden afterwards

### ISSUE THREAD

**Issue by dg-wfk** [adirh3/Fluent-Search#873]
When I click on a child setting like "Automatically learn file extension usage" of the parent setting "Prioritized file extensions" in the settings category "Files" it disappears with no sign of it whatsoever.

1. Go to the settings category "Files" 
2. Click on the  setting "Prioritized file extensions"
3. The setting "Automatically learn file extension usage" disappears

Expected behavior
1) A indicator should be shown when hidden as it is at the subcategory heading like "Application" in the category "Files". It is either a pointy bracket pointing up or down on mouse hover according to the collapsed status.

OR

2) Nothing should happen at all if you click on a setting.

Screenshots
![image](https://github.com/adirh3/Fluent-Search/assets/10115038/c6f8b7ed-950d-4ccf-afe5-456a7d71c861)
![image](https://github.com/adirh3/Fluent-Search/assets/10115038/6d6bf5ba-fe86-4d60-a898-e537a077a0c9)

Desktop
 - Window 10 Version: 22H2
 - Fluent Search Version: 0.9.92.998
 - Installation source: Installer (downloaded 4 hours ago)

Comments
Because the usefulness of the hiding feature of child settings is questionable, I would propose to disable it.

If it stays enabled, I would recommend additionally to showing an indicator to save the hidden/non-hidden state, which is now not implemented. Right now, if you change the settings category or close the settings, the next time you go back all child settings are visible regardless of whether they were hidden or not unlike the collapsed state of subcategories, which is actually saved.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 1.0.0.11                                          . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
