### ISSUE TITLE
Use file picker instead of folder picker in settings for default file manager

### ISSUE THREAD

**Issue by dg-wfk** [adirh3/Fluent-Search#874]
When I click on the button at the end of the text filed "File path" in the settings for "Default file manager" (category "Files", subcategory "Files") a folder picker is launched with which I cannot choose the file path of the executable file of the desired application but only the folder path to it.

1. Go to the settings for "Default file manager" (category "Files", subcategory "Files").
2. Click on the button at the end of the text filed "File path".
3. Folder picker is launched.

Expected behavior
Launching a file picker to get the file path of the executable file of the desired application.

Screenshots
![image](https://github.com/adirh3/Fluent-Search/assets/10115038/cf3051b7-8755-4704-8b4a-7adc7c8aad8e)

Desktop
 - Window 10 Version: 22H2
 - Fluent Search Version: 0.9.92.998
 - Installation source: Installer (downloaded 4 hours ago)

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 1.0.0.11                                          . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
