### ISSUE TITLE
search bar position

### ISSUE THREAD

**Issue by mragtronx8** [adirh3/Fluent-Search#879]
windows 10 22h2 - fs 1.0.0.12
search bar position #BUG

when triggering in-app search, fs is not sticking to the set option "my case LAST POSITION"
it is opening search bar on the top right windows corner
![image](https://github.com/adirh3/Fluent-Search/assets/62798102/3a408f39-e20c-497b-b551-0e36b771e426)

this is happeningg when using in-app search

**Comment by adirh3** [comment]
How do you trigger in-window search? Using hotkey or using instant search?

**Comment by mragtronx8** [comment]
instant

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
