### ISSUE TITLE
[Feature Request] Integrate into/replace Powertoys (Run)

### ISSUE THREAD

**Issue by ThaDaVos** [adirh3/Fluent-Search#883]
**Is your feature request related to a problem? Please describe.**

Just really curious, as you state to be a Microsoft Software Engineer, why isn't this implemented as PowerToys Run? Your UI is so amazing! And feels smoother too - so why not integrate it into PowerToys or offer it as replacement/upgrade for PowerToys Run itself?

**Describe the solution you'd like**

Nothing - just stating an idea - would be great if it was implemented though

**Describe alternatives you've considered**

Running FluentSearch separately next to PowerToys Run to test it out of course!

**Additional context**

**Comment by adirh3** [comment]
Hey @ThaDaVos, glad to hear you liked the UI in Fluent Search!
I am indeed working at Microsoft currently, but Fluent Search is a hobby project of mine, and it isn't related to Microsoft in any way.
Hope this answers your question, feel free to share any other feedback regarding to Fluent Search here :)
