### ISSUE TITLE
video keep playing after preview is off

### ISSUE THREAD

**Issue by u-Sir** [adirh3/Fluent-Search#885]
**Describe the bug**
video keep playing after preview is off

**To Reproduce**
1. search any video , `*.mp4` 
2. press `alt` to preview
3. press `alt` close the preview
4. video still playing in background

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Window 11 Version: 22H2
 - Fluent Search Version: 1.0.0.14 beta
 - Installation source: Installer

**Additional context**

**Comment by adirh3** [comment]
@u-Sir I can't repro this, does it happen with any video?
