### ISSUE TITLE
Screen Search/Search in-window problem

### ISSUE THREAD

**Issue by DRYN07** [adirh3/Fluent-Search#886]
If I use CTRL+M, my screen looks like the image below, a grey overlay hides my screen. This happens with stable and beta apps too. Any idea what should cause this?

![image](https://github.com/adirh3/Fluent-Search/assets/29770761/5a98b54c-8306-4604-8a34-0c61fa5bff10)

**Comment by adirh3** [comment]
@DRYN07 are you using MicaForEveryone? If so add FS to the ignore list of it

**Comment by DRYN07** [comment]
Oh yes, that was the issue, thank you.
