### ISSUE TITLE
Disable Auto Play in Preview

### ISSUE THREAD

**Issue by DRYN07** [adirh3/Fluent-Search#888]
Every media file automatically starts playing when I just want to search for something. It would be nice to have an option to disable this.

**Comment by adirh3** [comment]
@DRYN07 you can disable auto preview of Audio in Settings -> Preview

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 1.0.0.15                                          . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
