### ISSUE TITLE
 Is it possible to hide the taskbar icon when the window is active?

### ISSUE THREAD

**Issue by zhj9709** [adirh3/Fluent-Search#889]
Use Ctrl+Alt to activate the window
![image](https://github.com/adirh3/Fluent-Search/assets/13991774/5777ea22-1b39-45fa-b3f8-56ed255867ef)

Like Wox、Flow Launcher
![image](https://github.com/adirh3/Fluent-Search/assets/13991774/4ad40dae-ab82-4096-b1ec-348909cf9829)

**Comment by adirh3** [comment]
Yes, disable `Show in taskbar` in Settings -> Appearance

**Comment by zhj9709** [comment]
> Yes, disable `Show in taskbar` in Settings -> Appearance

Thank you very much, I saw it with the Advanced On option turned on
