### ISSUE TITLE
Multi-level path matching

### ISSUE THREAD

**Issue by Chance92** [adirh3/Fluent-Search#89]
**Is your feature request related to a problem? Please describe.**
I find it difficult to find the exact file I want when there are multiple files with the same name. For example, I have 20 project folders, and there's a "procurement" folder under each of the project folders. Currently it can be difficult and time consuming to find the exact procurement folder I want.

**Describe the solution you'd like**
I hope FS can match file path at different levels. For example, if I am looking for: 
`    E:\Documents\Work\Projects\project1_1\Procurement`
I can enter:
`    project1_1\procurement`
or even
    1_1\procure
and FS would try to find/prioritise items with "project1_1" or "1_1" in their paths, and "procurement" or "procure" in their names.
Ideally I hope the function can be extended to multiple levels, so I can use terms like:
`    work\1_1\procure`
or
`    E:\doc\1_1\proc`
and FS can search/prioritise based on multiple levels.
It would be even better if I could enter the file paths at the end of the search term. For example, I first enter:
`    procure`
but FS finds too many matches. Then I keep entering:
`    procure \\1_1`
or even
`    procure \\1_1\\work`
or a combination like
`    procure \\work\1_1`
so in this case I can keep narrowing down the results without re-entering from scratch.

**Describe alternatives you've considered**
I am still thinking.

**Comment by adirh3** [comment]
@Chance92 searching project1_1\procurement does not work for you? When using backslash Fluent Search will search in the path, you can even use space to make separate search.

For example, path - C:/a/b/c/d/file.txt
Search- b/c file or a/b c file.txt should work as well

**Comment by Chance92** [comment]
@adirh3 I have tried project1_1\procurement once or twice before and it didn't work, so I thought it wasn't implemented yet. I have tried again just now and it seems to work occasionally, but most times it doesn't, especially in OneDrive. Should I raise this as a bug?

**Comment by Metroid-Prime** [comment]
Wait, you mentioned OneDrive.  Is this a network path or a local path?

**Comment by Chance92** [comment]
@Metroid-Prime I believe the path is local. It's like E:\OneDrive\xxxxx

**Comment by adirh3** [comment]
@Chance92 please make sure the files your'e not finding are not found because of path searching or because FS didn't index them at all.
If it's the later, then close this issue and open a new one, thanks.

**Comment by Chance92** [comment]
> @Chance92 please make sure the files your'e not finding are not found because of path searching or because FS didn't index them at all.
> If it's the later, then close this issue and open a new one, thanks.

I am suppose to enter file paths in a consecutive order, right? For example, if I want to find
`E:\Documents\Work\Projects\project1_1\Procurement`
I must enter something like
`project1_1\Procurement`
or
`1_1\Procure`
But not something like
`Documents\Procurement`
or
`project\procurement`
Is this how it is supposed to work? I have been trying to use the last two methods, which did not work, and now I see why. The first two methods works fine, but they can be less convenient especially when I can't remember the exact name of the folders or the order of the file path.

**Comment by adirh3** [comment]
> > @Chance92 please make sure the files your'e not finding are not found because of path searching or because FS didn't index them at all.
> > If it's the later, then close this issue and open a new one, thanks.
> 
> I am suppose to enter file paths in a consecutive order, right? For example, if I want to find
> `E:\Documents\Work\Projects\project1_1\Procurement`
> I must enter something like
> `project1_1\Procurement`
> or
> `1_1\Procure`
> But not something like
> `Documents\Procurement`
> or
> `project\procurement`
> Is this how it is supposed to work? I have been trying to use the last two methods, which did not work, and now I see why. The first two methods works fine, but they can be less convenient especially when I can't remember the exact name of the folders or the order of the file path.

Using space in the middle of the search acts as `OR`, so you can search `project\ procurement` or `Documents\ Procurement` to make it work. Without using space, it will search for the exact term.
Let me know if it works for you.

**Comment by Chance92** [comment]
@adirh3 Thanks. I think it is working. I will close this one now.

**Comment by Chance92** [comment]
Sorry to reopen this one. It seems the function stopped working in 0.9.85.65

**Comment by adirh3** [comment]
> Sorry to reopen this one. It seems the function stopped working in 0.9.85.65

Can you share info/screenshot of scenario it's not working?

**Comment by Chance92** [comment]
Here are some screen shots.
![Snipaste_2021-06-17_11-05-01](https://user-images.githubusercontent.com/85488695/122376414-0acbc780-cf5c-11eb-9945-df9a803db824.png)
![Snipaste_2021-06-17_11-04-37](https://user-images.githubusercontent.com/85488695/122376428-0d2e2180-cf5c-11eb-9ef6-be78864426ff.png)

**Comment by adirh3** [comment]
> Here are some screen shots.
> ![Snipaste_2021-06-17_11-05-01](https://user-images.githubusercontent.com/85488695/122376414-0acbc780-cf5c-11eb-9945-df9a803db824.png)
> ![Snipaste_2021-06-17_11-04-37](https://user-images.githubusercontent.com/85488695/122376428-0d2e2180-cf5c-11eb-9ef6-be78864426ff.png)

Just making sure - does it find the required file or directory when you don't use partly path searching?

**Comment by Chance92** [comment]
No. FS can't find anything today. It seems the FS service can't install for some reason.

**Comment by Chance92** [comment]
It works fine with exe version. I am closing this one, hopefully for the last time. Thank you!
