### ISSUE TITLE
Always prioritize folders in results

### ISSUE THREAD

**Issue by DRYN07** [adirh3/Fluent-Search#898]
Option for prioritizing folders in the search results. When the search results number is less than the actual files/folders number, it only shows the files and removes the folders. It would be nice to have an option to show folders always on top.

Example (max results number: 15)
- FOLDER (30 files + 10 folders)

It will show only 15 files, never folders.

The new feature "order by type" in the search results would be excellent for this, but it only affects the 15 results and not every file/folder.

I know there is a "folder" tag for this, but I would still appreciate a separate option.

**Comment by adirh3** [comment]
Currently Fluent Search does not prioritize files higher vs folders, they both are treated the same by the algorithm.
If you've found a scenario that you think folders are showing below please share here the searched text and the results please.

For now, I suggest you increasing the max search results to higher number so you get most results. (BTW the 15 number was increased by default)

**Comment by DRYN07** [comment]
Yup, just did that :)) 

If the mentioned scenario happens, I will take some screenshots. However, it works fine if the max number is bigger.
