### ISSUE TITLE
Network files not being found

### ISSUE THREAD

**Issue by Metroid-Prime** [adirh3/Fluent-Search#9]
Everything app is separately finding files in networked locations when FS is not.

Some more specifics:
1. Mac Mini network share files & folders using SMB 
2. network folder is mapped to O:\ drive
3. Adding O:\ drive or manual \\ path  doesn't pull all of the files
4. Some of the files show, some don't.
5. I have permissions for read/write to all of the files.
6. Listary and flow launcher can access all of the files.

**Comment by Metroid-Prime** [comment]
Can anyone replicate this?  @Nomad-0

**Comment by Nomad-0** [comment]
sorry, I don’t have network drives

**Comment by Metroid-Prime** [comment]
Can confirm this is still active in latest build

**Comment by kwanice** [comment]
yes, still very buggy... @Metroid-Prime 
sometimes i can access some files, sometimes not, sometimes i have to wait 5 seconds or more for one result, 
or i have to add a new character, or remove one to display some result..quite weird behavior :p

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.85.45

**Comment by Metroid-Prime** [comment]
Can confirm broken in 0.9.85.45.  Many network files not found

**Comment by adirh3** [comment]
> Still broken in 0.9.85.45. Many network files not found
> 
> EDIT: Fresh copy of FS, can confirm definitely broken with O:\ or \192.168.1.29\Documents in the index path

I need more information, does it happen for all network drives? Files not found are in a specific directory or all files not found? Once network drive configured and you rebuild index, do you progress ring in Fluent Search?

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.85.50

**Comment by Metroid-Prime** [comment]
Hi @adirh3 
Apologies for the late reply.  I will validate this tonight when I get back on my home computer!

**Comment by Metroid-Prime** [comment]
> > Still broken in 0.9.85.45. Many network files not found
> > EDIT: Fresh copy of FS, can confirm definitely broken with O:\ or \192.168.1.29\Documents in the index path
> 
> I need more information, does it happen for all network drives? Files not found are in a specific directory or all files not found? Once network drive configured and you rebuild index, do you progress ring in Fluent Search?

It's completely random, but I have a folder called /Documents.   I tried adding both the network mapped drive O:\  and then also tried the manual network address \\192.168.1.25\*dirname*   and rebuilt the index in FS.  Tried exiting and re-opening and files aren't found.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.85.55

**Comment by Metroid-Prime** [comment]
> This issue has been potentially fixed in version 0.9.85.55

Congrats! This was a longstanding issue and OMG I think you did it @adirh3 !!!

**Comment by nataloko** [comment]
New user here.
Finding this same problem on a brand new installation (0.9.90)

**Comment by adirh3** [comment]
> New user here. Finding this same problem on a brand new installation (0.9.90)

This should be working in 0.9.90, what kind of network drive do you have? 
Not all drives are supported in 0.9.90, but in 0.9.91 all should work, you can try it out by changing the release feed in Settings -> System

**Comment by nataloko** [comment]
> > New user here. Finding this same problem on a brand new installation (0.9.90)
> 
> This should be working in 0.9.90, what kind of network drive do you have? Not all drives are supported in 0.9.90, but in 0.9.91 all should work, you can try it out by changing the release feed to nightly in Settings -> System (note - it's less stable than 9.90)

Hi. As far as I know is a standard Windows "shared folder". I tried both a mapped drive and direct access (\\shared\folder\), with the same result.

I've now updated to nightly release and seems to work ok :)

**Comment by brian6932** [comment]
@adirh3 I have this same issue with a mounted sshfs network drive, on 0.9.91.9995
