### ISSUE TITLE
Need a more simplified preview pane and an adaptive search box.

### ISSUE THREAD

**Issue by cccpism** [adirh3/Fluent-Search#902]
In the previous official version, when dragging the right side of the search preview box to the right edge, the preview pane would simplify into a few action buttons. I hope this feature can be restored in the current version. Also, I hope the search box can automatically change its length according to the length of the search results.

**Comment by adirh3** [comment]
Hey, which version of Fluent Search are you using?

This feature still works in both 0.9.92.x and 1.0.x (beta). 
You can make the search window height adjust automatically by enabling `Adjust search window height based on content`.

**Comment by cccpism** [comment]
According to your suggestion,I've solved this issue.Thanks
________________________________
发件人: ***@***.*** ***@***.***> 代表 Lighto ***@***.***>
发送时间: 2023年10月10日 02:13
收件人: adirh3/Fluent-Search ***@***.***>
抄送: cccpism ***@***.***>; Author ***@***.***>
主题: Re: [adirh3/Fluent-Search] Need a more simplified preview pane and an adaptive search box. (Issue #902)


Hey, which version of Fluent Search are you using?

This feature still works in both 0.9.92.x and 1.0.x (beta).
You can make the search window height adjust automatically by enabling Adjust search window height based on content.

―
