### ISSUE TITLE
Invisible window persists and blocks all interactions with other programs/desktop in v 1.0.0.20

### ISSUE THREAD

**Issue by Gahwa-Gahwa** [adirh3/Fluent-Search#903]
After updating to version 1.0.0.20 the app now blocks all interactions with desktop and other programs. There is an invisible window from Fluent Search that cannot be removed even if the app is minimized to tray. 
After closing the app things get back to normal.

This issue starts right after starting the app, even before calling FS.

I had the same issue on both Windows 10 & 11.

**Comment by adirh3** [comment]
Thanks for reporting it!

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 1.0.0.21                                          . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by Gahwa-Gahwa** [comment]
Thanks for quick fix! works well now 👍
