### ISSUE TITLE
Screen search rectangle opacity is forgotten upon restart

### ISSUE THREAD

**Issue by deadcombo** [adirh3/Fluent-Search#904]
**Describe the bug**
Screen search letter rectangles become opaque after restarting,, when they were made translucent the previous session. The alpha bar is reset to maximum.

**To Reproduce**
1. Go to 'Screen' settings
2. Click on 'Custom rectangle background'
3. Decrease alpha value
4. Restart Fluent

**Expected behavior**
The alpha setting is remembered and applied.

**Desktop (please complete the following information):**
 - Window 10 Version: Version 10.0.19045 Build 19045
 - Fluent Search Version: 1.0.0.21 Installer (Nightly)
 - Installation source: Installer

**Additional context**
https://github.com/adirh3/Fluent-Search/issues/350 might be related.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 1.0.0.22                                          . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by deadcombo** [comment]
Yep, seems okay now. Thank you 👍
