### ISSUE TITLE
Please show the thumbnail for pictures

### ISSUE THREAD

**Issue by ligq** [adirh3/Fluent-Search#905]
Could you please add the function to show the thumbnails for pictures?
It would be easier for us to find the target pictures.

Pdf, pptx, docx already show the thumbnails, why not for the pictures?

Besides, I hope to have an option to change the size of the thumbnails on the right panel.

**Comment by adirh3** [comment]
Thumbnail should load for pictures, can you see thumbnail for these pictures in Explorer?

Also you can preview pictures by pressing Alt, which then you will see the picture on the right-side pane and be able to zoom in.

**Comment by ligq** [comment]
> Thumbnail should load for pictures, can you see thumbnail for these pictures in Explorer?
> 
> Also you can preview pictures by pressing Alt, which then you will see the picture on the right-side pane and be able to zoom in.

Yes, I can see the thumbnails for those pictures in Explorer. I am running the latest version 1.0.0.21 on Win11 RP version 22631.2361. Other file types (pdf, pptx, docx) work well on my computer. Only pictures do not work.

And the preview works well for any file types. I did not know I can zoom them.

**Comment by adirh3** [comment]
Which type of files you don't see thumbnail for? Also can you screenshot the icons you get instead of the thumbnail

**Comment by ligq** [comment]
> Which type of files you don't see thumbnail for? Also can you screenshot the icons you get instead of the thumbnail

I cannot see the thumbnails of all types of pictures, jpg, png, gif.  Also, I found the djvu file did not work. I have installed the djvu extension, and I can see the thumbnail and preview in the Explorer.

Here is the screenshot of the jpg file
![image](https://github.com/adirh3/Fluent-Search/assets/1676652/b83eb922-5ed3-4f47-acc1-7dc44e0864dc)

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 1.0.0.31                                          . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by ligq** [comment]
Great. Thank you so much.

**Comment by kwanice** [comment]
![image](https://github.com/adirh3/Fluent-Search/assets/14847187/425c2565-fade-44ec-90bb-183fb8eeb48d)

still nothing for me ? should i see a thumbnail here?

**Comment by adirh3** [comment]
@kwanice isn't that a thumbnail? the red cat thing

**Comment by kwanice** [comment]
> @kwanice isn't that a thumbnail? the red cat thing

no its the logo of irfanview 🤭 lol
