### ISSUE TITLE
default file manager box keep one line

### ISSUE THREAD

**Issue by kwanice** [adirh3/Fluent-Search#91]
**Describe the bug**
The box to specify the file manager keep only one line, and cant be adapted to the lenght of the full path

![image](https://user-images.githubusercontent.com/14847187/121490830-af3a9080-c9d5-11eb-9924-25c41bf888b3.png)

**Expected behavior**
The box should be adapted to the lenght of the path

**Desktop (please complete the following information):**
 - Windows 10 Version: 21390.1000
 - Fluent Search Version: 0.9.85.35

**Comment by Metroid-Prime** [comment]
Can confirm, but want to clarify @kwanice  that what you're saying is that the "Path" box in your picture doesn't adjust to the full length of the path?  I noticed this as well.

**Comment by kwanice** [comment]
@Metroid-Prime yes exactly...sorry my English is bad to explain technical problem 😂

**Comment by adirh3** [comment]
This issue has been potentially fixed in version

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.85.40

**Comment by Metroid-Prime** [comment]
I can confirm this is fixed.  The box expands much more than better but obviously to a limit. It can't expand forever as there's limited space.

@kwanice  closing, but please confirm

**Comment by kwanice** [comment]
@adirh3 @Metroid-Prime 
Yes its much more better, still feel something is missing, like a scroll bar? or maybe expand the box vertically ? 
because we have to use arrow or mouse to scroll inside this box .

but its good.
thanks :)

**Comment by Metroid-Prime** [comment]
I would put in an UX/UI enhancement for that. I agree scroll bar is appropriate and standard user interface when something runs over
