### ISSUE TITLE
Zoom not allowed when opening PDF in Edge

### ISSUE THREAD

**Issue by SaarthakSinghal** [adirh3/Fluent-Search#913]
**Describe the bug**
A few days back, when the version was 1.0.15, whenever I used to open my PDF, I was allowed to zoom in the PDF in the preview pane. But now in 1.0.21, I am not allowed to zoom the PDF.

**To Reproduce**
1. Search any PDF
2. Go to the Preview Pane on the right.
3. The error is that I am not able to zoom the PDF.

**Expected behavior**
I thought I could zoom in the PDF as I did before when the version was around 1.0.15, but now I can't.

**Screenshots**

**Desktop (please complete the following information):**
 - Window 11 Home Version - 22H2 
 - Fluent Search Version: 1.0.21
 - Installation source: Installer

**Additional context**

**Comment by adirh3** [comment]
Can you please check with 1.0.22

**Comment by SaarthakSinghal** [comment]
> Can you please check with 1.0.22

Yes, now I can. 
Thanks.
