### ISSUE TITLE
Behavior on selected line from result

### ISSUE THREAD

**Issue by kwanice** [adirh3/Fluent-Search#92]
**Describe the bug**
not easy to explain
When u make a search on FS, u have for example 30 results, when u go down the highlighted line go down to the bottom of the windows but when u reached the bottom, the highlighted line stuck on the bottom of the windows => the behavior expected is the line should go up even if it reach the bottom of the windows

2nd : when u switch from left side to right side, its very difficult to see the highlight between left panel to right panel, we can only see the line is darker on the right panel => behavior expected : we should see the line highlighted on the left panel, with a darker color, like on the right panel.

sorry for the bad explanation^^
hope u will see on the video : first i go down, reach the bottom, and go up, but the line is stuck at the bottom and finally go up after the scroll bar reach the top
after u can see the right panel blinking, because i use the left and right arrow

**Screenshots**
![2816A534-196A-4520-98F0-CA6C4C77D1C8](https://user-images.githubusercontent.com/14847187/121492167-ed847f80-c9d6-11eb-8016-cbb0bc4336ba.GIF)

 - Windows 10 Version: 21390.1000
 - Fluent Search Version: 0.9.85.35

**Comment by Nomad-0** [comment]
@Metroid-Prime Please have a look and assign the priority here as I didn't quite understand the bug 😶

**Comment by adirh3** [comment]
This issue has been potentially fixed in version

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.85.40

**Comment by Metroid-Prime** [comment]
@kwanice  please comment whether it's been fixed.

**Comment by kwanice** [comment]
YES !
Great :) work fine! @Metroid-Prime @adirh3
