### ISSUE TITLE
Executables launch with Fluent Search directory as CWD

### ISSUE THREAD

**Issue by itaiferber** [adirh3/Fluent-Search#923]
**Describe the bug**

It appears that in very recent versions of Fluent Search (including the latest nightly build, 1.0.0.23), Fluent Search launches executables with their CWD set to its own containing directory instead of theirs (e.g., `%LOCALAPPDATA%\Programs\Fluent Search`). (Similar to #246, except not System32).

**To Reproduce**

1. Enable the "Apps" plugin to search for and launch executables
2. Search for an executable and launch it

**Expected behavior**

The executable should launch with its CWD set its parent directory on disk, the same as launching it from a shortcut, the task bar, or File Explorer; this is necessary for executables which expect their CWD to be their containing dir, and search it for assets or config files.

**Screenshots**

A screenshot from Process Explorer of an executable launched via Fluent Search:

![ProcessCWD](https://github.com/adirh3/Fluent-Search/assets/33716/ad725c8a-86bd-4830-90b7-e7b544d287d5)

**Desktop (please complete the following information):**
 - Window 10 Version: 22H2
 - Fluent Search Version: 1.0.0.23 (I was previously on the latest stable version, but don't remember the exact version number)
 - Installation source: Installer

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 1.0.0.24                                          . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by itaiferber** [comment]
Wow, incredible turnaround time, @adirh3! Can confirm this is resolved in 1.0.0.24 😄
Thanks so much!
