### ISSUE TITLE
Quick Menu Recent Browser [BUG]

### ISSUE THREAD

**Issue by mragtronx8** [adirh3/Fluent-Search#924]
Windows 10 22H2 - Fluent Search 1.0.0.24
12Nov2023

quick menu recent browser is not working properly when using firefox only
#bug

it is not showing the proper recent history. It picks random addresses [which even are not used long time ago].

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 1.0.0.33                                          . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
