### ISSUE TITLE
Can't install Fluent search file indexer service

### ISSUE THREAD

**Issue by mretier** [adirh3/Fluent-Search#926]
**Describe the bug**
I installed the latest FS version from the Windows Store (0.0.92.998).
When attempting to install the FS file indexer, I'm prompted for admin privileges.
After providing the login, I get the following error message:

`The application was unable to start correctly (0x0000142). Click OK to close the application.`
 
**Desktop (please complete the following information):**
 - Window 11
 - Fluent Search Version: 0.0.92.998
 - Installation source: Microsoft Store

Any idea what may resolves this issue?

Thanks,
Michael

**Comment by mretier** [comment]
When I open `services.msc` there is no `FluentSearch.FileIndexer`. The is no service with FluentSearch in its name.

**Comment by adirh3** [comment]
When does it show the error you mentioned? after you allow admin permissions?
Any chance your user does not have permissions to the ProgramData folder?

**Comment by mretier** [comment]
After entering the admin login. I can create folders and files within `C:\ProgramData`

**Comment by adirh3** [comment]
@mretier why do you need to enter admin login? Is your user not admin?
Can you try installing Fluent Search using the EXE installer? you can find link here - https://fluentsearch.net

**Comment by mretier** [comment]
@adirh3 thanks for your feedback. I reinstalled fluent search using the EXE installer and it seems to work now
