### ISSUE TITLE
Search tag only feature for web search URLs

### ISSUE THREAD

**Issue by Mr-Frankenstein** [adirh3/Fluent-Search#93]
Search tag only feature for each web search URLs.

When there are a lot of web search URLs the search result will get messy. FS has a Search Tag Only feature but it applies to every Web search URL. 

![unknown](https://user-images.githubusercontent.com/85425543/121505040-19682b00-ca00-11eb-804d-88e7d3cd30bc.png)

**Comment by Metroid-Prime** [comment]
@Mr-Frankenstein  sorry to hijack this thread, but what is the intention of this new checkbox?   I ask as an avid user of the web URL section.

**Comment by Mr-Frankenstein** [comment]
> @Mr-Frankenstein sorry to hijack this thread, but what is the intention of this new checkbox? I ask as an avid user of the web URL section.

When there are a lot of web search URLs, the search results will start to get messy. I could make Web search 'Search Tag Only' but then I can't just type and search in google. So when there is 'Search Tag Only' for each web search URLs, I can make the most used ones to always show in the search results and less used ones can be used by their own tags.

**Only implement this feature if others want this too.**

**Comment by Metroid-Prime** [comment]
Oh I see so you're talking about in the results column when you're initiating a web search right?

**Comment by adirh3** [comment]
This issue has been potentially fixed in version

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.85.40

**Comment by Nomad-0** [comment]
Closing the issue as the feature has been implemented.
