### ISSUE TITLE
Hide icon in taskbar

### ISSUE THREAD

**Issue by Aradig26** [adirh3/Fluent-Search#930]
**Is your feature request related to a problem? Please describe.**
It looks weird when the search bar ipens an icon on the taskbar. 
**Describe the solution you'd like**
There should be an option to hide it
**Describe alternatives you've considered**
None
**Additional context**
This could be similar to powertoys run

**Comment by adirh3** [comment]
@Aradig26 disable `Show in taskbar` to hide the icon in Settings
