### ISSUE TITLE
Is "file V3" supported as 3rd-party file manager?

### ISSUE THREAD

**Issue by christubuntu** [adirh3/Fluent-Search#936]
I'm trying to register Files v3 (https://github.com/files-community/Files) as 3rd-party file manager. I'm entering it's path on my system (C:\Users\User\AppData\Local\Files\Files.App.Launcher.exe)
Beforehand, I set it as Default file manager (Settings, Advanced).
1. If in FS, I leave Arguments field as empty, if I Open any folder in FS, Files v3 will open a new "Home" page
2.  If I input "%1 as argument, nothing happens.

Is there something I can do to make it work, or it's just not supported, so  nothing can be done. 
thx.

**Comment by adirh3** [comment]
Did you try setting it using the suggestions icon?
![image](https://github.com/adirh3/Fluent-Search/assets/27368554/0d06e8a8-10f8-4021-bfe6-403311ff0a6b)

Should look like this after clicking -
![image](https://github.com/adirh3/Fluent-Search/assets/27368554/ef45be05-6cc8-4602-9042-c94dbed1064c)

**Comment by christubuntu** [comment]
works like a charm. thx.
