### ISSUE TITLE
the FS menu is behind the hidden icon on the taskbar 

### ISSUE THREAD

**Issue by kwanice** [adirh3/Fluent-Search#94]
**Describe the bug**
please see the picture to understand ^^ LOL

**Screenshots**
![image](https://user-images.githubusercontent.com/14847187/121511428-e6666d00-c9e8-11eb-8af6-81e9bd84d874.png)

**Desktop (please complete the following information):**
 - Windows 10 Version: 21390.1000
 - Fluent Search Version: 0.9.85.35

**Comment by Metroid-Prime** [comment]
This might be a regressed bug as I thought it was fixed in an earlier version a few weeks ago. .

**Comment by Metroid-Prime** [comment]
@Nomad-0 @MakeshVineeth 
Can anyone reproduce this? I believe I put in a bug report a long time ago about something similar, but Adir fixed it.  My right click menu is displaying properly.
![image](https://user-images.githubusercontent.com/1836362/121965052-4d559000-cd21-11eb-92cf-de5e57d785db.png)

**Comment by MakeshVineeth** [comment]
Interesting, thought this was fixed already. I'm unable to reproduce this bug from my end.

**Comment by Nomad-0** [comment]
can't reproduce this. It wasn't constant tho

**Comment by Metroid-Prime** [comment]
@kwanice   can you reproduce this still in the latest version as of 6/14/21. If not, let us know if it's OK to close.

**Comment by kwanice** [comment]
@Metroid-Prime yes for me it seems to be ok now. :)

**Comment by Nomad-0** [comment]
closing it then

**Comment by kwanice** [comment]
@Nomad-0 hey, on the last build .75 the problem came back...

can you check for u ?
![image](https://user-images.githubusercontent.com/14847187/122635667-96249480-d0e5-11eb-90b6-d2a218616ede.png)

**Comment by Nomad-0** [comment]
ok here 
![image](https://user-images.githubusercontent.com/76395594/122635808-b5ccb480-d107-11eb-9244-a6692102a073.png)

**Comment by Metroid-Prime** [comment]
Works for me too
![image](https://user-images.githubusercontent.com/1836362/122663548-0e27a480-d150-11eb-9e04-7c67c7b116d7.png)

**Comment by kwanice** [comment]
yes now on last uptate its working again :)
thanks

**Comment by MakeshVineeth** [comment]
Reopening the issue as @Nomad-0 seem to face it again.
![image](https://user-images.githubusercontent.com/19371684/125314256-a8e06100-e353-11eb-83f5-1a5bda9a8b5b.png)

**Comment by adirh3** [comment]
Should be fixed on latest stable version
