### ISSUE TITLE
Launch a URL directly (to go to a direct link or website by typing/pasting the URL)

### ISSUE THREAD

**Issue by Nomad-0** [adirh3/Fluent-Search#95]
**Is your feature request related to a problem? Please describe.**
Sometimes I have URLs copied and I want to launch them in the browser. But if I use _Web Search_ for this I get the results are given below and no option to launch the URL directly (to go to the link/website). 

![image](https://user-images.githubusercontent.com/76395594/121528954-c1402180-ca1d-11eb-89f2-395c10ca9059.png)

However, I can launch some URLs through Chromium but only if they are in my bookmarks or history and not if they're something new.

**Describe the solution you'd like**
An option in _Web search_ or _Chromium Search_ to directly launch a URL entered or copied from clipboard would be great to have. (I think Keypirinha has a feature similar to this)

**Comment by Metroid-Prime** [comment]
I support this request. I believe Alfred has this feature.

**Comment by adirh3** [comment]
You can launch URLs as long as they're with HTTP prefix, will add it to work without as well

**Comment by adirh3** [comment]
This issue has been potentially fixed in version

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.85.40

**Comment by Nomad-0** [comment]
@adirh3 The result is appearing but pressing `return` doesn't do anything. @Metroid-Prime can you please check if you can go to an Url.

![image](https://user-images.githubusercontent.com/76395594/121762357-32372480-cb57-11eb-90ad-102901df19f1.png)

**Comment by Metroid-Prime** [comment]
> @adirh3 The result is appearing but pressing `return` doesn't do anything. @Metroid-Prime can you please check if you can go to an Url.
> 
> ![image](https://user-images.githubusercontent.com/76395594/121762357-32372480-cb57-11eb-90ad-102901df19f1.png)

Can confirm. Result appears but nothing happens when you press Enter

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.85.45

**Comment by Metroid-Prime** [comment]
Not working in  0.9.85.45.  Typing in fluentsearch.net and hitting enter does nothing

**Comment by Nomad-0** [comment]
> Not working in 0.9.85.45. Typing in fluentsearch.net and hitting enter does nothing

It's working on my end. Did you use _web_ tag before entering the URL?

**Comment by Metroid-Prime** [comment]
> > Not working in 0.9.85.45. Typing in fluentsearch.net and hitting enter does nothing
> 
> @Metroid-Prime It's working on my end. Did you use the _web_ tag before entering the URL?

Yes it works, apologies. Space has been removed from triggering searches so I didn't realize that at the time.
