### ISSUE TITLE
Unit Converter & Currency Converter does not work

### ISSUE THREAD

**Issue by DRYN07** [adirh3/Fluent-Search#959]
Yes, it is enabled in the settings :D

https://github.com/adirh3/Fluent-Search/assets/29770761/2beba3a2-38eb-45ff-8f28-3dc64fbb6a95

**Comment by eikaramba** [comment]
For me it works. Did you set an api key? normally it should use the default one, but maybe the field is blank for you. in that case create one and put it there.
![grafik](https://github.com/adirh3/Fluent-Search/assets/1320525/ad2f1954-e4de-4484-b6e7-2cb56df6f67d)

**Comment by DRYN07** [comment]
Yes I have an API key there, I suppose the default one (ME7...)

I checked apilayer.com but I am not sure how to make my own API. I tried others from the marketplace (EXCHANGE RATES DATA API), but doesn't do anything either. Could some options be conflicting in fluent search?

**Comment by adirh3** [comment]
@DRYN07 unit converter does not need API, that's currency converter.
Can you please make sure you don't have `Search tag only` enabled for it?
![image](https://github.com/adirh3/Fluent-Search/assets/27368554/954bc2ee-7d21-444f-872e-fa0b628ae970)

**Comment by DRYN07** [comment]
Yes, I mixed them by mistake because none of them works :D

Here is a video about both of them and their settings. In the past I tried to reinstall the app and the plugins but after a while this always happens :/


https://github.com/adirh3/Fluent-Search/assets/29770761/560e3424-df1f-4577-b211-50a139a5277a

**Comment by vector2927** [comment]
I am still having that problem. as he showed in the video. it is not working, both currency and unit converter. I have tried using own api as well, but did not work.

**Comment by eikaramba** [comment]
for me it still works, i wrote that currency converter task back in the day. still working so far. it is best that you have a look at the task yourself an debug to find out why it is not working for yourself
