### ISSUE TITLE
Occasionally some of the settings in Fluent Search are not persistent between system reboots.

### ISSUE THREAD

**Issue by MakeshVineeth** [adirh3/Fluent-Search#97]
**Bug Description:**
As the title says: Some of the Settings in Fluent Search are not persistent between system reboots and they always get reset on next launch. Settings that I've faced issues with are `Release feed` & `Start minimized` in Fluent Search Settings > System.

**Steps To Reproduce:**
1. Go to Fluent Search Settings.
2. Navigate to System related settings.
3. Enable Start minimized.
4. Change Release feed to Nightly.
5. Restart the System.
6. Those settings will be reset to default after system restart!

**Expected behavior:**
The settings preference should persist between every system reboot.

**Desktop Information:**
 - Windows 10 Version: 21H1
 - Fluent Search Version: 0.9.85.35

**Comment by Metroid-Prime** [comment]
@MakeshVineeth  are you on the discord channel? You may want to zip your settings folder ( "\Fluent Search\Blast\Settings\"  in portable version) and **send it to Adir via PM** in the  Discord channel.

I had this issue with just the main FS trigger hotkey a while back but I haven't seen it in a while.

**Comment by adirh3** [comment]
This will happen if FS couldn't close properly (like crash, force restart of Windows, BSOD, etc.).
Can you check if it happens for you when you close FS safely? (Through system tray)

**Comment by MakeshVineeth** [comment]
It happens regardless of crashes/force restarts etc. On the previous day, I did try to close FS safely and restarted the PC, the settings still have been reset. But as I mentioned in the title, it happens occasionally and so it is not reproducible at the moment.

**Comment by MakeshVineeth** [comment]
Closing my issue as it is no longer reproducible. Will reopen if I face it again in the future.
