### ISSUE TITLE
How do I add to the Home Screen, the "Pinned" section?

### ISSUE THREAD

**Issue by classicrocker883** [adirh3/Fluent-Search#972]
**Is your feature request related to a problem? Please describe.**

If the ability to add to the Home Screen does not exist, then it should

**Describe the solution you'd like**

Drag and drop, or add through the menu settings

**Describe alternatives you've considered**

I would like to add to the "Pinned" section with rows and columns, but how? I see "show suggested", "show pinned" but nothing about adding to it. I can add a folder, but how do I add other apps or files?

**Additional context**

There are way too many Settings and they are all over the place.

ps. use `<!--` **words text** `-->` if you do not want the text to be seen, but the user can while writing the edit.
ex.
```html
**Additional context**
<!-- Add any other context or screenshots about the feature request here. -->
```

**Comment by adirh3** [comment]
You can add results to home screen by pinning them through search window.
To do so simply search for the desired result and then either -
1. Press the pin icon at the top right
2. Press Alt+P shortcut to pin a result
3. Right click the result pane (right-side) and click pin result

**Comment by kwanice** [comment]
Not working anymore...
