### ISSUE TITLE
FP on Kaspersky and Windows

### ISSUE THREAD

**Issue by Rhizob** [adirh3/Fluent-Search#973]
Hello,

Just wanted to let you know that Kaspersky AV is picking up the beta/nightly exe file as a threat and quarantining it. It's labeled as 'PDM:Trojan.Win32.Generic' and windows itself warns user from installing the beta. I'm sure it's just Kaspersky/Windows acting up since the stable version of the exe doesn't cause any issues. 

Thanks for all the hard work!

**Comment by adirh3** [comment]
Thanks! I will take care of it.
