### ISSUE TITLE
Machine learning sensitivity option displays Revert button even at it's default value. 

### ISSUE THREAD

**Issue by MakeshVineeth** [adirh3/Fluent-Search#98]
**Bug Description:**
The `Machine learning sensitivity` option in Fluent Search Settings > Search displays a Revert button even if it's default value (which is 500%)

**Steps To Reproduce:**
1. Go to Fluent Search Settings
2. Go to Search related settings
3. Scroll down to Machine learning sensitivity option and try to change the value to default 500%
4. The Revert button is always displayed.

**Expected behavior:**
Inline with the other settings of the Fluent Search, the Revert should only show up when the settings have been changed to custom values.

**Screenshot:**
![2021-06-11](https://user-images.githubusercontent.com/19371684/121597684-a2ae4a80-ca5e-11eb-84bf-19aeff366895.png)

**Desktop Information:**
 - Windows 10 Version: 21H1
 - Fluent Search Version: 0.9.85.35

**Comment by adirh3** [comment]
This issue has been potentially fixed in version

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.85.40

**Comment by Metroid-Prime** [comment]
@MakeshVineeth   please confirm issue has been fixed

**Comment by MakeshVineeth** [comment]
Yes, this issue has been fixed in the latest build. Thanks and closing this issue.
