### ISSUE TITLE
Results list overlaid

### ISSUE THREAD

**Issue by ligq** [adirh3/Fluent-Search#981]
Sometimes the result list is overlaid, for version 1.0.0.33 and 1.0.0.34. After restarting FS the issue disappears.
My windows version is Win11 23H2 22631.3155

<img width="295" alt="image" src="https://github.com/adirh3/Fluent-Search/assets/1676652/263dfa40-d0a2-49cb-bab1-f3bec90e8467">

**Comment by ligq** [comment]
It seems the overlap appears after I switch displays. I have an external display for my laptop, and they have different dpi. After restarting FS the overlap disappears.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 1.0.0.37                                          . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by ligq** [comment]
That's great. Thank you so much.

**Comment by ligq** [comment]
That's great. Thank you so much.
