### ISSUE TITLE
Intuitive tag behaviour (erase/insert/replace tag)

### ISSUE THREAD

**Issue by venturqx** [adirh3/Fluent-Search#984]
### Erase tag
![Capture d'écran 2024-03-11 211507](https://github.com/adirh3/Fluent-Search/assets/114839780/0b4cba2e-fadd-4370-996c-47155d4e9c25)

**Problem :** It is not possible to erase a tag (using backspace) when something is written after the cursor.
Therefore it is impossible to remplace a tag.
**Expected behaviour :** Backspace = Erase tag before

### Insert tag
![Capture d'écran 2024-03-11 211636](https://github.com/adirh3/Fluent-Search/assets/114839780/31374cc7-b1bc-4ebc-9351-712e85d9a9b8)

**Problem :** It is not possible to insert a tag (using tab) from what's written before after the cursor, when something is written after the cursor.
Therefore it is impossible to replace a tag.
**Expected behaviour :** Tab = Insert tab based on what is present before the cursor

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 1.0.0.36                                          . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by venturqx** [comment]
Yes, good job!

However, pressing "Tab" insert the tag, and move the cursor right (after the first f in the following image), instead of just inserting the tag.
![Capture d'écran 2024-03-11 211636](https://github.com/adirh3/Fluent-Search/assets/114839780/31374cc7-b1bc-4ebc-9351-712e85d9a9b8)

**Comment by adirh3** [comment]
@venturqx not sure I understand, are you saying inserting the tag doesn't work for you in this scenario?

**Comment by venturqx** [comment]
If I press "Tab" in this situation :
![Capture d'écran 2024-03-11 211636](https://github.com/adirh3/Fluent-Search/assets/114839780/31374cc7-b1bc-4ebc-9351-712e85d9a9b8)

It inserts the tag and move the cursor right n time, where n is the length of the tag :
![image](https://github.com/adirh3/Fluent-Search/assets/114839780/988a43f1-d2cd-4707-8861-4b3388e7366b)

Instead of simply inserting the tag and not moving the cursor :
![image](https://github.com/adirh3/Fluent-Search/assets/114839780/5f6f17bc-c548-4b48-83f6-aa466aa5eab9)

**Comment by adirh3** [comment]
@venturqx got it, but wouldn't it make sense to move the curosr to the end?

**Comment by venturqx** [comment]
@adirh3 It hadn't crossed my mind, but it does seem like a better idea

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 1.0.0.37                                          . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
