### ISSUE TITLE
Extra Border space showing up for window

### ISSUE THREAD

**Issue by A16D** [adirh3/Fluent-Search#986]
Whenever I open the launcher or setting window and extra border space is showing up. What is the fix ? 
Win 11
Launcher- latest Github release
![Snipaste_2024-03-23_10-36-30](https://github.com/adirh3/Fluent-Search/assets/103478102/80570ccb-716e-4efb-a6f1-c71c2b723164)

**Comment by adirh3** [comment]
Are you using MicaForEveryone? If so please add Fluent Search to the ignore list
