### ISSUE TITLE
a weird black box around the whole fluent search windows

### ISSUE THREAD

**Issue by Only-Moon** [adirh3/Fluent-Search#989]
**Describe the bug**
a black box appeared around Fluent Search, no idea what caused it but it's there and doesn't go away.

**To Reproduce**
no idea

**Expected behavior**
Not have that black box.

**Screenshots**
![Screenshot 2024-03-30 222707](https://github.com/adirh3/Fluent-Search/assets/75924613/40a90130-ead6-4b1c-9788-a4ef5fbca83a)

**Desktop (please complete the following information):**
 - Window 11 Version: 22H2
 - Fluent Search Version: 1.0.0.37 Nightly
 - Installation source: Installer 
**Additional context**

**Comment by adirh3** [comment]
@Xx-Mohit-xX do you use MicaForEveryone? If so please add Fluent Search to it's ignore list

**Comment by Xx-Mohit-xX** [comment]
> @Xx-Mohit-xX do you use MicaForEveryone? If so please add Fluent Search to it's ignore list

No I don't. I don't use anything for transparency

**Comment by adirh3** [comment]
@Xx-Mohit-xX do you have `Use GPU` enabled in Settings -> System -> Performance? If so, please enable it

**Comment by Xx-Mohit-xX** [comment]
> @Xx-Mohit-xX do you have `Use GPU` enabled in Settings -> System -> Performance? If so, please enable it

It's gone now
