### ISSUE TITLE
on "save as" dialog box, if we look for folder, settings open

### ISSUE THREAD

**Issue by kwanice** [adirh3/Fluent-Search#99]
**Describe the bug**
on a dialog box "save as", if we open FS to search for a folder, by selecting up and down, the folder is selected, but if we pressed enter, the settings windows open

**Expected behavior**
if we press enter, the selected folder should be opened

**Desktop (please complete the following information):**
 - Windows 10 Version: 21390.1000
 - Fluent Search Version: 0.9.85.35

**Comment by kwanice** [comment]
i tried now, and i cant reproduced...:/

**Comment by Nomad-0** [comment]
Set it to _Low priority_ as you can't reproduce

**Comment by Metroid-Prime** [comment]
@kwanice  if you can't reproduce, I suggest we close this. You can always re-open easily if needed.

**Comment by Metroid-Prime** [comment]
Closing this. @kwanice please reopen if you see it again or if you disagree

**Comment by kwanice** [comment]
ok i tried to reproduced on the new version i cant anymore...let's see @Metroid-Prime
