### ISSUE TITLE
Stupid softwear

### ISSUE THREAD

**Issue by bigQY** [adirh3/Fluent-Search#990]
**Describe the bug**
On April Fool's Day, I was using Fluentsearch and the software automatically opened a prank website. I am very upset by this and consider this practice to be stupid and unprofessional. I spent a long time trying to figure out what program opened the page. I eventually found out it was this programme, and this complete lack of prompting to the user is disgusting, and I will never use this stupid software again!

**Comment by Nadim147c** [comment]
I agree it was very frustrating. I thought some malware attack had happened to my system or fluent search had been compromised.

**Comment by adirh3** [comment]
@bigQY I'd like to apologize for the inconvenience this caused you and others.
I have no excuses, this is something I programmed into Fluent Search in its early builds and even I forgot it exists.
I understand how unprofessional and umpromoting this is, and removed it from the next builds of the app.

My goal is to make Fluent Search feel as native and professional as possible so I will make sure to not miss things like this in the future.
Thanks!
