### ISSUE TITLE
Reset Search not working

### ISSUE THREAD

**Issue by henechen** [adirh3/Fluent-Search#998]
1. Reset search when opening: reset search to empty text when opening the search window.

https://github.com/adirh3/Fluent-Search/assets/23579978/bac31fb3-4018-4fbb-ac47-569a70d0ffb4

 - Window 11 Version: 23H2
 - Fluent Search Version: 0.9.92.998
 - Installation source: Installer

**Comment by adirh3** [comment]
@henechen please click on the text "Reset search when opening" twice, it should open a setting below to indicate how long should Fluent Search wait before resetting search.
The setting is not properly visible for you due to a visual glitch that is fixed in version >1.0.0

**Comment by henechen** [comment]
> @henechen please click on the text "Reset search when opening" twice, it should open a setting below to indicate how long should Fluent Search wait before resetting search. The setting is not properly visible for you due to a visual glitch that is fixed in version >1.0.0


Clicked twice, nothing happened. But, I had to turn on "advanced mode" so I could actually see the setting when clicking once on the text, then, a submenu showed up with the mentioned setting.

I believe this issue can be closed now. Thanks!
![image](https://github.com/adirh3/Fluent-Search/assets/23579978/8be0d72c-0915-40e3-a334-1ef95344cf3d)
